### ISSUE TITLE
no such column: userfields

### ISSUE THREAD

**Issue by donk7413** [grocy/grocy#1021]
I want use a userfiled on Ingredient in recipes : 
measurement unit (like "kg","g","a spoon of")

i have created the userfiled on the web interface : 
```
{
    "id": "8",
    "entity": "recipes_pos",
    "name": "grammage",
    "caption": "Grammage",
    "type": "text-single-line",
    "show_as_column_in_tables": "1",
    "row_created_timestamp": "2020-09-30 14:19:24",
    "config": "",
    "userfields": null
  }
```
When i try to post a new recipe_pos, i have this error : 
```
{
  "error_message": "SQLSTATE[HY000]: General error: 1 table recipes_pos has no column named userfields_id"
}
```

This is my posted JSON : 

```
{
    "id": "8",
    "recipe_id": "1",
    "product_id": "60",
    "amount": "1.0",
    "note": "",
    "qu_id": "2",
    "only_check_single_unit_in_stock": "0",
    "ingredient_group": "",
    "not_check_stock_fulfillment": "0",
    "row_created_timestamp": "2020-09-30 14:28:56",
    "variable_amount": "",
    "price_factor": "1.0",
    "userfields": 
    {
         "grammage" : "kg"
    }
  }
```

the product_id, recipe_id exist
the id is not used (max : 6)

**Comment by berrnd** [comment]
That's intentional because userfields cannot be set through the ["Generic entity interactions" endpoints](https://demo.grocy.info/api#/Generic%20entity%20interactions), they have their own endpoint:
[`PUT /userfields/{entity}/{objectId}`](https://demo.grocy.info/api#/Generic%20entity%20interactions/put_userfields__entity___objectId_)
