### ISSUE TITLE
Add missing items to shopping list inconsistency with open items

### ISSUE THREAD

**Issue by D3v01dZA** [grocy/grocy#1032]
When using minimum desired stock in tandem with opening items I'm seeing some (what I consider to be) strange behavior.

If I have an item with a minimum stock of 1 and I have 1 open item in stock and go to the shopping list to add missing items, nothing gets added (I expect this behavior).

If I have an item with a minimum stock of 2 and I have 2 items in stock, one of which is open, and go to the shopping list to add missing items, 2 items get added (I expect only 1 item to get added so that it is consistent with the above behavior).

**Comment by berrnd** [comment]
That was already reported/fixed in #855 (not yet released).

I just tried that with the current master ([pre-release demo](https://demo-prerelease.grocy.info/stockoverview)) and it works as you would have expected it (when `FEATURE_SETTING_STOCK_COUNT_OPENED_PRODUCTS_AGAINST_MINIMUM_STOCK_AMOUNT` is set to `true`, which is the default).

**Comment by D3v01dZA** [comment]
Thank you for the info! I tried to find a duplicate but obviously didn't do a very good job (sorry :))
