### ISSUE TITLE
Impossible to open less than 1 item quantity

### ISSUE THREAD

**Issue by Musickiller** [grocy/grocy#1046]
It is currently possible to consume or purchase less than 1 item, however, it's not possible to open it.

For example, I buy cheese in packs, and each pack is 0.25 kg. It would actually be better if the cheese would be stored in packs before I open it, and change to kg when I open a pack. But as far as I understand, current implementation of units does not allow it. As an option, an "open" button should open 1 pack (which is defined as 0.25 kg in my product).

So if you want I can also open an issue (feature request) to make it possible to combine different unit types, like "2 packs and 0.1 kg unpacked".

I use grocy-desktop 1.7.0.0
If you need any additional info, let me know!

**Comment by berrnd** [comment]
You can open partial amounts on the consume page - just use the button "Mark as opened" instead of "OK".
The product option `Allow partial units in stock` needs to be enabled.

To be able to use any product related quantity unit at any place is already tracked in #1015.

The consume/open buttons on the stock overview page are currently fixed to `1` QU, but it's already tracked in #613 to make this configurable per product.

Also related to #729.
