### ISSUE TITLE
Allow decimals in quantity units for recipe ingredients

### ISSUE THREAD

**Issue by SxthGear** [grocy/grocy#105]
Current ingredient implementation does not allow for sub values of quantity units. It is necessary to use decimals specifically when using non-metric amounts. 

For example, a recipe requires 1/4 cup of water and the input field does not accept a decimal value between 0 and 1 (in this case it should be 0.25 for a quarter cup). Instead of accepting the decimal, an error of "This cannot be negative" appears and locks the form.

![image](https://user-images.githubusercontent.com/959706/47822420-1a0d9080-dd32-11e8-9c10-9ea17570675e.png)

**Comment by berrnd** [comment]
In general I wanted to keep it as simple as possible, that's why in stock only integral numbers for the amount are allowed (see https://github.com/grocy/grocy/issues/32#issuecomment-408946222).

For a recipe ingredient when "Only check if a single unit is in stock" is checked, this doesn't matter (because it's checked against an amount of "one in product stock unit" - so will change this, that decimal numbers can be used when that flag is checked.

Also a maybe special recipe ingredient here: I don't think you have (tap) water as cups in stock - so maybe we should also add a checkbox to don't check the stock amount at all for that ingredient - otherwise you always have to have at least one cup water in stock to see the ingredient requirement fulfilled...

**Comment by BlizzWave** [comment]
I have just solved this by adding 1/4 cup and so on in quantity units.

**Comment by Braintelligence** [comment]
@BlizzWave So the solution is to keep adding 1/2, 1/4, 1/8 and so on to measurements, because we can't have decimals there? Obviously there is a demand for fractures of a unit but for some reason it is deemed a solution and "simpler" to create a new unit for every fraction. This is awful from a UI/UX perspective.

**Comment by matejdro** [comment]
I have to agree with @Braintelligence here. It would be nice if some other solution could be thought out.

For example, a pack of flour can contain 1kg of flour. If recipe needs 200g of flour, that means that whole pack is enough for 5 meals. So, just marking a pack is not sufficient.

I could track flour in grams for example, adding 200x 1g of flour, but I feel that breaks many other features (such as consume one, or price of one unit).

Maybe good idea would be to give product separate amounts for shopping and for consuming? For example Flour could have 1 pack like currently, but it would also have 1kg attached to the pack. That way, grocy would know exactly how much is available.

**Comment by berrnd** [comment]
Products can now be partially consumend (not yet released) - see #123 and https://github.com/grocy/grocy/commit/dfc05e0bec2c524dc2f35a833f8fff6435f63a46.
