### ISSUE TITLE
How can I add more than image to the product?

### ISSUE THREAD

**Issue by scottydelta** [grocy/grocy#1054]
is there a way to add more than 1 pic to a product? Right now addition of new pic replaces the old pic.

thanks

**Comment by berrnd** [comment]
The next version will include a new Userfield type "File", so you can add a Userfield of that type to products and your second picture there. See #977.

**Comment by scottydelta** [comment]
I can see this feature on the pre-release demo, is it stable enough for me to use it or do you suggest that I wait for the next release?

**Comment by berrnd** [comment]
Because a lot has changed since the last release, there some things here and there which do not work - at least the reported ["bug"](https://github.com/grocy/grocy/issues?q=is%3Aopen+is%3Aissue+label%3Abug) und ["ui-bug"](https://github.com/grocy/grocy/issues?q=is%3Aopen+is%3Aissue+label%3Aui-bug) issues here, probably more.

I also don't care that database migrations work between every commit, just between each release - so you would maybe need to take care of them manually...
