### ISSUE TITLE
Show time on Stock entries page

### ISSUE THREAD

**Issue by white-gecko** [grocy/grocy#1063]
It would be good to not only display year-month-day on the stock entries page, but also hour and minute.
Maybe this should be configurable, people might also want to have the seconds (?)

**Comment by kriddles** [comment]
Hi, purchased date and best before date are both stored as year-month-day so would need to change to include a timestamp. 
What is your reason to be so granular with time for this request?

**Comment by white-gecko** [comment]
If I perform several transactions at a day I still want to be able to identify all of the product that I purchased at once in the shop so I can group them or go through them and add the prices from the receipt. (See #1061)

**Comment by berrnd** [comment]
The purchased-date can't be extended for that since that's also one of the "stock row identifiers" (ref #1343).

Technically, each table in the database already has a column `row_created_timestamp` which contains exactly what the name implies - I'm going to add this column (hidden by default) on the stock entries tables, hope that helps for what you've thought of for this.
