### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by cr0ssmind** [grocy/grocy#1071]
Hello,

It is very nice project. Do you plan to support PostgreSQL database server?

Thanks!

**Comment by berrnd** [comment]
Merged into #89.

From my side, unless there are problems with SQLite, no.
And that's still the case.

Do you have any SQLite related problems with grocy?

**Comment by cr0ssmind** [comment]
From the point of Docker deployment, it is easier to maintain/backup persited data independently in PostgreSQL. Especially for longer time. SQLite is nice for desktop application because of embedded nature (fire and forget), but server side needs a little bit robust solution. :-)

**Comment by berrnd** [comment]
I have not so much experience with Docker, but if your PostgreSQL can have a persistent volume, why not that one which contains the `grocy.db` database file?

> but server side needs a little bit robust solution

I don't know how often I heard that, not only for grocy.
SQLite is great, not for a huge amount of data or a huge amount of (concurrent) users.
Both has the average grocy installation, not.

The big advantage is (at least for me): No additional server/service needed.

So immediately after there are real world issues with SQLite in grocy, I personally will work on that (but of course anyone can catch up on that, however, grocy uses a little amount of SQLite specific SQL things currently, so a solution/migration for that would be needed).

Some real world numbers (personally like them more than generic assumptions that something is not so "robust"):

My personal grocy instance, running since grocy v0.1.0:
- 539 products
- 44 chores
- 64 batteries
- 10911 stock transactions
- 637 tracked chore executions
- 462 tracked battery charge cycles
- => ~1.77 MB database file size
- => 0 times that I had a corrupt database

The demo instances
- ~ 2000 visitors with ~20000 page views per month on average
- Highest peak (March this year) ~18000 visitors with ~190000 page views
- => 0 database related problems so far
- => Everything runs in a (Debian 10 LXC) container with limited resources and never uses more than ~400 MB RAM and is reasonable fast

**Comment by rkj** [comment]
I've run into issues with SQLite on other docker containers: https://stackoverflow.com/a/9962003

**Comment by berrnd** [comment]
> on other docker containers

Unrelated to Grocy. Sounds like if using NFS you're exactly looking for problems - congrats on that.
