### ISSUE TITLE
Be able to translate all the user-input text in Grocy to other  languages 

### ISSUE THREAD

**Issue by Juansero29** [grocy/grocy#1073]
I have started using Grocy this week-end and made the rough process of going through my pantries and scanning/adding each product to Grocy one by one. Took my two whole days of doing nothing but adding products, prices, and recipes manually. 

Since I live in France I currently use Grocy in French since it simplifies going shopping and having straight out of the shopping list the correct product name in the language the shop sells it. 

My issue is: Every once in a while, I go live to a Spanish speaking country for a couple of months every year. And there again, I would need to create a new instance of Grocy to manage my household in Spanish.

Plus, at somepoint, I expect to change the country where I live from time to time (every 4 ~ 5 years or so). So I don't like thinking that I will have to start and administrate a new instance of Grocy every time I change countries. That would mean recreating all my 300 hundred products, my 60 recipes manually, just to translate the text inside it. And that's just the products I have now, imagine what I will have in a couple of years! 

So... Wouldn't it be nice to have a feature where one could add the default language (locale) for all the text items the user adds in the database (products, recipes, locations, etc...) and from the Grocy options be able to change this default language to a new one? 
Then I can imagine using some external web service of translation which magically will go search every line of Text and translate it accordingly to the new language.

Maybe it won't be perfect, but at least it would avoid having to recreate all my Grocy data every time I change the country where I live and the language shops and people around me speak.

**Comment by berrnd** [comment]
The interface language can be different per user since #976 (not yet released).
This still doesn't apply to user input text.

Is this really needed? I understand it for products, but do you also "think" chores and the rest in a different language just because you live in another country after time?

So for products, you could just use the description field (which would not be searchable in product pickers, but if you use barcodes this maybe doesn't really matter).

Another option: "Product aliases", already requested in #1066.

Another option: Do the translation manually / directly in the database, it's just the `name` field of the `products` table...
