### ISSUE TITLE
Feature request:  Meal plan API, dynamic meal plan

### ISSUE THREAD

**Issue by vring0** [grocy/grocy#1082]
Please add the ability to create a meal plan through the API. I want to make a dynamic meal plan, it will change according to the availability of the necessary products in the refrigerator.

**Comment by berrnd** [comment]
Everything what's possible via the UI, is possible via the API because uses nothing else to trigger actions.

So a simple way to check how it's done is just using the browser developer tools and look at the requests made.

Check the ["Generic entity interactions" endpoints](https://demo.grocy.info/api#/Generic%20entity%20interactions) and see https://github.com/grocy/grocy/issues/777#issuecomment-616797264 for exactly an example for how to add something to the meal plan.
