### ISSUE TITLE
UI change idea

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1089]
just an idea for after V3 but how does the dev team feel about replacing the shopping list "Add Item" button with a search bar or drop down of products and then one of those small pop ups with the amount and notes.

when adding multiple items to a shopping list, the back and forth between pages (with all due respect) sucks.

**Comment by berrnd** [comment]
Thanks for the idea.

Using dialogs everywhere instead of jumping between pages (like for example when adding an ingredient to a recipe) is a good idea and should be already tracked anywhere here.

A shopping list item is either a product or a note or both, when `FEATURE_FLAG_STOCK` is disabled only a note - so only a product picker would not be enough...

However, you can make more or less everything possible by using [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) or just edit the code directly to fit exactly your needs.

**Comment by berrnd** [comment]
> Using dialogs everywhere instead of jumping between pages (like for example when adding an ingredient to a recipe) is a good idea and should be already tracked anywhere here.

Have not found the issue I had in mind, so created #1091 to track this, should be also pretty easy to do, so a thing for the next release.
