### ISSUE TITLE
Log File

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1090]
a grocy specific log file in the data folder.

a log file that includes things like log in activity, db changes, specific info on errors, request.remote_addr from api requests and such. 

possibly a config entry on the types of logs, like ERROR, INFO, WARNING.

**Comment by Festeazy** [comment]
depending on how much work it would be, you could just had basic info in it at first and then build on it in future updates.

**Comment by berrnd** [comment]
Activity = the journals.

Errors are displayed and logged in the default PHP log file you have configured (because everything is just a regular PHP exception/error).

Requests are logged in your default webserver access logged, if configured accordingly.

So what would be the real benefit? To have a "own" log file?

**Comment by Festeazy** [comment]
I think a dedicated log file for grocy could include information from the setup, install, migration, and update process, this log file could then be provided on Reddit/GitHub for support.
The errors would be more readable for non-programmer users.

Activity being included wouldn't be a necessity, I agree with you there but could be could be a nice touch if set to include it.
