### ISSUE TITLE
Prerelease: User permissions not saved and/or displayed

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1099]
It's not possible to change the Userrights once is touched.

The Serverlogs say this:
`PHP Warning: Invalid argument supplied for foreach() in /opt/grocy/controllers/UsersApiController.php on line 163`

Seems, that something depends on the php-code...

```
Ubuntu 20.04
Apache 2.4
php 7.4.3
SQLite Version 3.31.1
and on all out-of-the-box installation config
```

**Comment by berrnd** [comment]
> once is touched

What does that mean?
Please provide the steps how this is reproducible.

**Comment by berrnd** [comment]
Was able to reproduce that:
The inital state of the checkboxes is wrong: If you have the `ADMIN` permission ("All permissions" checkbox) all checkbox below (so all) should be disabled since the `ADMIN` permission indirectly means you have all permissions.
Workaround click the "All permissions" checkbox twice first (uncheck/check), then the disabled state of the other checkboxes is correct.

**=> So the initial state is the problem.**

> Muss man das in Englisch diskutieren?... Ist doch eh ein Deutsches Projekt und naja, mein Englisch ist eher was für Hunde

Laut Web-Stats der Website und Demos, sind gerade mal um die 13 % deutschsprachig und bei Englisch kann halt einfach immer jeder einfacher mitlesen, deswegen ist das doch gscheiter, finde ich...

**Comment by sleeplessnight2** [comment]
I think, you misunderstand me.

I create now a new user. This User have admin rights. (all are checked).
Now you deactivate one these checkboxes and press "save".

Then click any Menü Button to leave this page. After that, the User loose all rights and can do nothing more. It's unable to give this User Admin with a another Admin his rights back or make him as admin again.

**Comment by berrnd** [comment]
Two things:

- As mentioned above: If the user has ADMIN permissions, all other checkboxes should be greyed out, currently that's not the case, the end result when you uncheck any of the checkboxes is undefined _<== this is the base problem (as already mentioned)_
- If you remove permissions from the currently logged on user, of course this will have immediately an corresponding effect - when the last user with ADMIN permissions is removed, there is also an warning

**Comment by sleeplessnight2** [comment]
It's not solved. Sorry - i can't give a user any special Rights. Only admin or nothing. (i used now a fresh created database)

Look at the video... it give me the confirmation "Permissions saved" - but after a site recall nothing is saved.

[https://www.dropbox.com/s/a33jp8s25xmffqa/Bildschirmvideo%20aufnehmen%202020-11-01%20um%2021.22.39.mov?dl=0](https://www.dropbox.com/s/a33jp8s25xmffqa/Bildschirmvideo%20aufnehmen%202020-11-01%20um%2021.22.39.mov?dl=0)
