### ISSUE TITLE
Feature request: Development setup documentation / Devcontainer

### ISSUE THREAD

**Issue by edenhaus** [grocy/grocy#1114]
Hi,

first nice work :smile: 

I think we should add a documentation about how to setup up a development environment. I am planning to contribute to this project, but I never have setup a php project. It would be great to have a tutorial similar to Home Assistant (https://developers.home-assistant.io/docs/development_environment)
Also I think it's a great idea to use a devcontainer, so nobody must think about the dependencies and also nothing has to be installed on the dev machine except of docker and visual studio code. HA also use it (https://github.com/home-assistant/core/tree/dev/.devcontainer)

Thanks in advance,
Robert

**Comment by berrnd** [comment]
We had that before.

https://github.com/grocy/grocy/issues/863#issuecomment-631298442
#904
#811

My opinion about that is still the same: How to do development heavily depends on personal preferences.
We have a lot of ideas/examples how some of us like it around here, I think that's enough.
In general, grocy is a pretty normal/basic PHP application, so nothing special needed, any tutorial on how to setup a PHP dev environment would basically fit...

**Comment by berrnd** [comment]
This specific error was reported multiple times lately, only happens when using the master branch, it's about the new setting `DEFAULT_LOCALE` and the [`LocaleMiddleware`](https://github.com/grocy/grocy/blob/master/middleware/LocaleMiddleware.php), haven't had that personally but also haven't looked into it so far more detailed - so seems to be something broken currently, that can also happen anytime in the master branch...

**Comment by edenhaus** [comment]
thanks for you help :)
