### ISSUE TITLE
Bug: Don't apply unit conversion for "Only check if a single unit is in stock" recipe ingredients

### ISSUE THREAD

**Issue by AllesMeins** [grocy/grocy#1120]
Adding QU-Conversions leads to rounding-errors when editing recipies.

How to reproduce:

1. Add a QU-Conversion to an existing product (preferably with some crooked numbers) For example: 1 Bottle = 34 Tablespoons
2. Create a new recipe
3. Add 1 Tablespoon of the product to the Ingredients list
4. Save

This leads to something like 0,987 Tablespoons being displayed on the recipe.

**Comment by AllesMeins** [comment]
Just found a related problem. Setup Steps 1 + 2 as above

3. Add 1 Tablespoon of ingedient but check the "Only check if a single unit is in stock" box above
4. Save

This leads to "34 Tablespoons" in the recipe

**Comment by berrnd** [comment]
This is not solvable unless calculating with an infinte number of decimal places or using something like proposed in #389 - or you have another idea.

The next version will provide a configuration option for how much decimal places should be used for displaying amounts, maybe a kind of workaround....

**Comment by berrnd** [comment]
> Just found a related problem. Setup Steps 1 + 2 as above
>
> 3. Add 1 Tablespoon of ingedient but check the "Only check if a single unit is in stock" box above
> 4. Save
> 
> This leads to "34 Tablespoons" in the recipe

This is most probably already fixed (can't find/remeember the issue), or please try to reproduce it on the [pre-release demo](https://demo-prerelease.grocy.info).

**Comment by AllesMeins** [comment]
> The next version will provide a configuration option for how much decimal places should be used for displaying amounts

My math is a bit rusty but yes I think this would fix it if you calculate with enough precision/decimal places internaly.

> This is most probably already fixed (can't find/remember the issue), or please try to reproduce it on the pre-release demo.

Unfortunately not... I reproduced it in the pre-release demo (See recipe for Chocolate sauce). That has now 34 Bunch of cheese, but I added only 1

**Comment by berrnd** [comment]
> I think this would fix it if you calculate with enough precision/decimal places internaly.

This would never fix it, it's just a workaround.
The only fix would be to use real fractions, which is a whole different approach about how to enter, store, display and calculate with numbers (already tracked in #389).

For the next version (pre-release demo) all explicit roundings on any calculation are already removed, so it's only limited by the new setting (for display) and the database engine (SQLite, don't know what the default precision for the data type `REAL` is) and/or PHP (datatype `float`) for calculation.

> Unfortunately not... I reproduced it in the pre-release demo (See recipe for Chocolate sauce). That has now 34 Bunch of cheese, but I added only 1

**TODO for this issue**
Ok, so let's track that here - the problem is that when `Only check if a single unit is in stock (a different quantity can then be used above)` is checked no unit conversions should be applied (as the label says).
