### ISSUE TITLE
Feature request: Product image upload via rest API

### ISSUE THREAD

**Issue by cr0ssmind** [grocy/grocy#1140]
It would be great if the API could handle images - because of the REST nature base64 encoded binary can be considered.

The **properties** obejct CRUD has to expand with:

```
{
.....
image: "iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAAGElEQVQIW2P4DwcMDAxAfBvMAhEQMYgcACEHG8ELxtbPAAAAAElFTkSuQmCC"
image_mime: "image/png"
.....
}
```

**Comment by berrnd** [comment]
The API can handle files, have a look at the [File endpoints](https://demo.grocy.info/api#/Files).

For uploading files this currently just takes the file "as is" in the request body (`application/octet-stream`).
Encoding files BASE64 adds IMHO uneccessary overhead.

So is there a problem with the current endpoints?
The UI uses them for all file operations without known problems...

**Comment by berrnd** [comment]
Closing this for now, if you have problems by using the API, feel free to reopen it.

If you meant by that request to extend the POST `/objects/{entity}` endpoint (here for entity `products`) by that two fields: That does currently not really fit, just because the "Generic entity interactions" endpoints are pretty much a direct interface to the corresponding database tables - not entity specific and files are not stored in the database.
