### ISSUE TITLE
Feature request: Deletable Products - a suggestion

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1145]
I've decided to fork your great project and make some personal changes in it.

But I would like to give back a little as thanks for your work and bring in an idea of how such a deletability of products could look without losing the active / inactive feature...

Here is the process as a video (saves me dozens of lines of explanation...):
https://www.dropbox.com/s/x5zhsaoda7jcusu/2020-11-27_17-10-54.mp4?dl=0

If it's not the way you like just close this case.

**Comment by berrnd** [comment]
Thanks, but I won't rebuild this by a video - a pull requests with the changes, if this should be somehow included, would be the easiest thing.

I'm also not happy with the new active flag.

In my opinion deleting a product should delete everything, so also all journal data, from all recipes, and so on - because you want to delete it.

#906 is about to hide products on stock overview (and other places) - so some checkboxes for where to show a product, if you want to only hide, but not delete it.
