### ISSUE TITLE
Bug: Amount shopping and storing not used correctly 

### ISSUE THREAD

**Issue by masterdot** [grocy/grocy#1161]
I did enter the product, bought in a 5 kg pack to be stored as 5kg.
But if I stock it, it's just 1kg instead of 5 kg as intended. 

Looks like a bug to me. 

![Screenshot_20201207_114148_com android chrome_1](https://user-images.githubusercontent.com/493105/101341653-b5fb1600-3881-11eb-87cf-2cb37a5d70cd.jpg)
![Screenshot_20201207_114212_com android chrome_1](https://user-images.githubusercontent.com/493105/101341849-fc507500-3881-11eb-8ff3-1a328f038b94.jpg)

**Comment by berrnd** [comment]
What do you mean by _"if I stock it"_?

When I reproduce this:
When using the [/purchase page](https://demo.grocy.info/purchase) and adding 1 (Packung) => 5 kg are added to stock (because for purchase the purchase unit is used)
When using the [/inventory page](https://demo.grocy.info/inventory) and adding 1 (kg) => 1 kg is added to stock (because for the inventory page the stock unit is used)

In the next version on any place/page the unit to use can be selected, have a look at the [pre-release demo](https://demo-prerelease.grocy.info/).

**Comment by masterdot** [comment]
It seems to have been I issue with the inventory option. When I do stock via inventory I add 1 teabag instead of 1 pack containing 20 bags. If I do stock vio buy its OK.

I'm pretty new to grocy, 2nd day now and figuring out how it works, sorry :)
