### ISSUE TITLE
Feature request: show date/time at login screen

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1178]
Please describe what you would find useful and please also check (by searching open requests here) if that was maybe already requested.

(cant tell if this is already able in v3 demos due to not being able to log out)

show date/time at login screen if activated in config for having it in the title

**Comment by berrnd** [comment]
Doesn't really fit because that's a user setting and no user context is available before login.
The default settings configured in `config.php `are just defaults, those and the one the user configures are matched together and exposed/used (not only) in the JS variable `Grocy.UserSettings`, which is therefore empty on the login page.

I also think it's better to keep the login screen as clean as possible, both UI wise and also technically, as this is the only publicly (means unauthenticated) exposed page.
