### ISSUE TITLE
Question: Script loading

### ISSUE THREAD

**Issue by edenhaus** [grocy/grocy#1192]
Hi @berrnd,

giving a try in https://datatables.net/extensions/buttons/ I realized that all our scripts are placed at the end of the body. Unfortunately the extension buttons need jquery and some datatable libs to be in the header...

I came across with the script attribute `defer`, which is better explained in https://flaviocopes.com/javascript-async-defer/
What do you think? Should we add all script with the `defer` attribute and place it in the header?
I can open a PR if you agree.

Cheers

**Comment by berrnd** [comment]
From what I know about this, it doesn't make that much difference regarding performance.
But I think with `defer` the order how the scripts get loaded is not defined, so that's maybe a problem with scripts that depend on a script loaded before...

When it's only about a single page which needs this, there is also the section `pageStyles` in [layout.default](https://github.com/grocy/grocy/blob/master/views/layout/default.blade.php) which, despite the naming, can be used in views to put anything in the head.

**Comment by berrnd** [comment]
So if it is needed for something, feel free to change what's ever needed to get it working... 🙂
