### ISSUE TITLE
Feature request: QU Conversion Overrides in API

### ISSUE THREAD

**Issue by Gerw88** [grocy/grocy#1194]
"QU Conversion Overrides" are not mentioned/do not exist in the API.
I'd set QU overrides for many of my products through the web interface, and had been using the API recently, just noticed there was no way to query these fields.

Could be nested in `GET` requests to `/objects/products/{id}` perhaps? Or called as objects of their own?

**Comment by berrnd** [comment]
> "QU Conversion Overrides" are not mentioned/do not exist in the API.

Wrong, everything what the UI does is possible via the API, because the UI uses the API.

The easiest thing is to just check what the UI does for example via the Browser Developer Tools.

Most objects are exposed via the ["Generic entity interactions" endpoints](https://demo.grocy.info/api#/Generic%20entity%20interactions).

To create a QU specific for a product (so an override) is basically this example request:
`POST /objects/quantity_unit_conversions`
```
{
   "product_id": 15,
   "to_qu_id": 10,
   "factor": 123,
   "from_qu_id": 2
}
```

The only difference between "standard" conversions and product overrides is that product overrides have a `product_id`, the standard conversion have just `null` there.

**Comment by Gerw88** [comment]
Thanks @berrnd - have applied this to my script and all is good again!
