### ISSUE TITLE
Feature request: Merge "Add" buttons in the shopping list to reduce real estate usage

### ISSUE THREAD

**Issue by DanielNautre** [grocy/grocy#1198]
I would like to suggest merging the "add buttons on the shopping list as they take up a lot of space. This is is especially trueon mobile and with some languages that need more words/characters than english. e.g.:
![image](https://user-images.githubusercontent.com/2039600/102698754-038f5f80-4240-11eb-9df0-9bb01cba3091.png)

One idea would be to take cues from the meal plan interface hiding the less used option in a dropdown:

![image](https://user-images.githubusercontent.com/2039600/102698770-32a5d100-4240-11eb-9c51-6b0d27f82e87.png)

**Comment by berrnd** [comment]
Do you mean the buttons in the head

![grafik](https://user-images.githubusercontent.com/2161815/102699356-5b2fca00-4244-11eb-9fac-1e70b5f6f3f3.png)

or the buttons per row on the table?

For the buttons per row on the table: Maybe makes not so much sense, I personally for example use all of them frequently also on mobile during shopping (and they have no text, only icons).

For the head buttons: That's why the collapsing for small screens was introduced (not yet released, so you probably use the master branch when you already have this).
They are already hidden by default behind the ellipsis menu button, so don't see why we should add another drodpown menu after expanding...

**Comment by DanielNautre** [comment]
I was talking about the head buttons, though the buttons per row do also take up a bit too much space in my opinion but that's off topic and less of a problem.

I understand your point about the ellipsis, but it does feel like sweeping everything under a rug rather than putting some order there. I will give it more thought, I might be able to come up with something cleaner.

**Comment by berrnd** [comment]
It's basically the same behaviour as on all pages - collapse head button and filter row on `sm` screen size...

For this example page, this would mean a dropdow with 5 lines/menu items (because there are 5 buttons) which most probably would at least take the same space/height, when not more, because currently in your example screenshot two buttons fit in one line.

However, if you want improve that, feel free to do so, everything is always appreciated - but then please for all pages, different behaviour on different pages is IMHO the worse option...
