### ISSUE TITLE
Feature Request: Speed improvement/ optimizing of tables

### ISSUE THREAD

**Issue by BlizzWave** [grocy/grocy#120]
Don't know if this is actually possible. 
But when you start to run alot of items in Grocy it starts slowing down.
I have about 160+ products in my installation and it takes about 3 seconds to reload and the page becomes responsive again. 
3 seconds is not that much, but when you are going back and forth between pages it becomes annoying.

**Comment by BlizzWave** [comment]
Yeah, my kitchen tablet is struggeling now actually.

**Comment by BlizzWave** [comment]
Bernd, have you given this more thought?

**Comment by berrnd** [comment]
Not in detail yet, but I'll try to do something this weekend...

**Comment by berrnd** [comment]
Hm, to really use the above mentioned (better) dynamic loading of data the whole page(s) need to to be rewritten because currently there are heavy dependencies between the server side rendering and the JS part...

I tried a simple workaround (hiding the table during the inital rendering), this improved the loading time of the stock overview page in my test case with about 145 products from 1700 ms to 1000 ms.

Maybe you could test this in your environment, if this is an adequate workaround for now.
You just need to replace the two files attached in your grocy directory.
[grocy_patch_120.zip](https://github.com/grocy/grocy/files/2729535/grocy_patch_120.zip)

... my dream is still to have a modern JS only frontend (React, Angular, or something) at some time in the future...

**Comment by BlizzWave** [comment]
Tried it now. It indeed speeds things up, but it removes all the buttons in both my computer (chrome) and windows tablet (chrome)

![capture](https://user-images.githubusercontent.com/6298655/50725763-ea4c8180-1102-11e9-98b6-84df9e337baa.PNG)

**Comment by berrnd** [comment]
Sorry, that was accidentally hidden - I fixed the file, you can take it from [here](https://raw.githubusercontent.com/grocy/grocy/2e265ac70ab9e2d4edd9e8436240dd9503239c7b/public/viewjs/stockoverview.js), needs to be replaced in `public/viewjs` - if this does not help you mabye need to delete the local storage data, can be done in Chrome under `chrome://settings/siteData`.

For me the speed is ok for now, also depends on the client performance, so maybe we let this is a workaround for now for the stock overview page, will also add it for the journal pages and products master data page - all other pages with tables contain typically not that much data, I think.
