### ISSUE TITLE
Shopping list item form validation - product or note should be required

### ISSUE THREAD

**Issue by kk7ds** [grocy/grocy#1226]
Confirmed on the demo-prerelease site.

1. Go to Shopping List
2. Click Add Item
3. In product field, type "asdf" (or some other string that doesn't match a product) and hit enter
4. Observe a flash of a dialog that looks like the "Add new product, add barcode to existing product" box that disappears immediately
5. You're taken back to the shopping list and now there is a blank item in the list (not even containing "asdf")

I assume the expected workflow is to prompt the user to add a new product (which is what I was hoping for when I clicked enter)?

**Comment by berrnd** [comment]
In dialogs, `ENTER` is used to to submit/close the dialog, so use `TAB` here instead (which is also the common key to jump between / leave input fields).

**Comment by kk7ds** [comment]
So the expected behavior is to add an empty item (with quantity 1) to the shopping list?

![image](https://user-images.githubusercontent.com/3046399/103297494-47efcd80-49ad-11eb-9193-6a0fae8b56ba.png)

That doesn't make sense to me, because it also means that if I scan a non-existent barcode to add it to my list, it won't ask me to add the product first. For example, in inventory, if I scan a non-existent item, it asks me to add it, it does not just add inventory of zero of a blank product. It seems to me that the UI expects to ask me to add, because the add dialog appears and then immediately disappears before the empty item is added to the list.

If you really expect enter to close the add item dialog without prompting me to add a non-existent product, surely it shouldn't add a blank item that I have to then to edit/delete right?

**Comment by berrnd** [comment]
`TAB` is the common key to leave / jump to the next input field.
`ENTER` was added especially for the product dropdown (#889), it's still not a common key for that action.
`ENTER` is the common key to close/submit dialogs.

So what's the simple problem about using `TAB`?
I want to avoid adding special handling above all the default/common (in browsers or third party components built-in) behavior, because when things work the same in general, it's IMHO better - means I would rather remove the special `ENTER` handling for the product picker (#889) again.

A shopping list item currently enforces no mandatory fields, maybe you just want to add a note - so a blank item is not disallowed.
There is #586 about adding configurable mandataory fields, for example if you want to enforce that a product needs to be selected for shopping list items.

> For example, in inventory, if I scan a non-existent item, it asks me to add it, it does not just add inventory of zero of a blank product.

Wrong comparison. Inventory doesn't use a dialog.
It's simply about common keys for dialogs - "use a dialog for everything" was also just added in v3.0.0 because of user requests, because it "looks so much nicer" - I personally don't really care, but seems that "looks nicer" is not always "works better" (however, still doesn't bother me personally because I simply use `TAB` to leave fields everywhere and always...).

**Comment by kk7ds** [comment]
Using tab is not a problem, it's just the UI inconsistency (at least as perceived by me) that seems to be the problem to me.

I didn't realize grocery items could have a blank product. That seems counter-intuitive to me, but if that's the behavior you want, then I understand. I still don't think that the user expects to get a _completely_ empty grocery item if they hit enter (i.e. no note or product). Further, the "add new item or add barcode to existing item" displaying and exiting immediately makes the user think that they were supposed to get an option to create it, but missed that opportunity.

Adding a completely blank list item seems pointless to me, and I can't imagine any user ever intentionally doing this (i.e. why is "Save" sensitive when none of the fields in the dialog have been changed?). Here's another scenario where I think the user is surprised:

1. Click add item
2. Type (incorrectly) an item quickly and hit enter
3. Get a completely blank grocery item that I have to clean up, potentially not even understanding why, since I don't realize I typo'd the product name.

I would expect to get no item or a warning. If I typed nothing in the product field, but something in the note field, then that makes more sense, but that's not the scenario above. The completely empty item is *never* what I want, so it seems like bad UX to do that in this case. I'm an engineer and can map quirky behavior in my head easily. I want my family to use this, so any surprising or confusing behavior like this makes it difficult to drive adoption amongst the non-engineer members of the family.

Anyway, just MHO, I'll drop it.

**Comment by berrnd** [comment]
> why is "Save" sensitive when none of the fields in the dialog have been changed?

Simply because none of the fields are mandatory = form is always valid.

Then let's track here that for shopping list items either a product or a note is mandatory, probably this solves are your mentioned problems here - will change the title accordingly.

However, "either field" is not a standard HTML5 form validation option, so needs to be somehow hand crafted.

> I want my family to use this, so any surprising or confusing behavior like this makes it difficult to drive adoption amongst the non-engineer members of the family.

You should start thinking on regex patterns for the note field then, "asdf" there would make the form valid, but is it valid? ;D

**Comment by berrnd** [comment]
TODO for this issue:
For shopping list items either a product or a note should be mandatory ("either field" form validation).

**Comment by kk7ds** [comment]
Tested just now on the demo site and the new behavior is massively better, IMHO. Thanks!
