### ISSUE TITLE
Regression: "Add as new product and prefill barcode" doesnt work after upgrade to 3.0.0

### ISSUE THREAD

**Issue by Dinth** [grocy/grocy#1227]
"Add as new product and prefill barcode" doesnt work after upgrade to 3.0.0.

How to reproduce:
1. Click "Purchase"
2. Scan a new product or enter a random number in "Product" field.
3. "Create or assign product" pop-up will show up. click "Add as new product and prefil barcode"
4. "Create product" page will open. "Barcode" field is nowhere to be seen. 
5. Fill in product details and click "Save & Continue".
6. The product is added, but without a barcode. Scanning same product again in "Purchase" window will not recognize the product and "Create or assign product" pop-up will show again. 
7. Your missus will make a huge drama about it ;)

**Comment by berrnd** [comment]
Have you tried it till the end (so posting the purchase transaction) or do you just assume it doesn't work because you don't see a barcode field on the create-product-page?

Because it works.

Here is how the workflow is handled now: https://github.com/grocy/grocy/issues/1221#issuecomment-751511756

Here is a video about it: 

https://user-images.githubusercontent.com/2161815/103284008-50aac880-49da-11eb-963c-738853463261.mp4

**Comment by berrnd** [comment]
> 6. The product is added, but without a barcode. Scanning same product again in "Purchase" window will not recognize the product and "Create or assign product" pop-up will show again.

This part is a duplicate of #839.

However, I use that workflow personally a lot and practically had never the need to scan the same product immediately again...

**Comment by Dinth** [comment]
@berrnd thanks for your clear answer. I have tried it now and indeed it work, although the procedure i have used is no different to the workflow I'm using after our weekly shopping and I'm sure that more than few products were added without barcodes over our last two shopping. I will try again after our next shopping and i will gather some evidence if i will replicate the problem
