### ISSUE TITLE
Allow decimal units for products

### ISSUE THREAD

**Issue by Braintelligence** [grocy/grocy#123]
Hi there,

I want to be able to add "2.5kg" of something so it can be converted to "2500g" in stock.

I can't input any decimal numbers, though. It says it shouldn't be less than 0. Only integer numbers are allowed.

The use-case here is to not type in 4 digits where three or even one symbol(s) would suffice.

**Comment by berrnd** [comment]
Thanks for the suggestion. We had this point in [some other issues](https://github.com/grocy/grocy/issues?q=decimal) too. My base idea was to keep it simpel. There is only one single quantity unit per product, only for purchasing there can be a different one and it is converted to the stock unit directly on booking the purchase. Stock amount can also only be an integral number (no decimals), as this would lead to rounding problems at some point.

When decimals are allowed, how to handle when you consume 0.33 kg (a third) of something 3 times?

Other organizational suggestions for this:
- Different quantity units
- Different products with the unit size in the name

I for myself just don't need this detail in most cases, for example potatoes, which I buy in different unit sizes, I only have one product in grocy with quantity unit "Pack"...

**Comment by Braintelligence** [comment]
If you buy potatoes with different unit sizes and the quantity unit is "pack", how can you tell when your potato stock is gone?
Do you have one product type for each type of pack that has a different sizing factor?

**Comment by berrnd** [comment]
>  Do you have one product type for each type of pack that has a different sizing factor?

That's one option, I personally don't track every potatoe, just "consume" the pack when it's empty.
For apples for example I just have it in stock as "piece" and track every single apple.

With the example of 0.01 left I just wanted to point out that exactly this is often a problem in stock management systems in general which I wanted to prevent initially, because I thought for home use it should be simple - and that you don't have to workaround such leftovers at the end...

I see your point, but in general I think I want to keep in the current way by default.
So I think of an option per product "Allow partial units in stock", which is not set by default, and when set enables decimal amounts for that product in purchase/consume/inventory/recipes, otherwise only integral numbers as of now.
Would that work for you?

**Comment by Braintelligence** [comment]
That would be an acceptable solution!
I don't know how you can cope without decimals if you're using the recipe function extensively :/

**Comment by Braintelligence** [comment]
No problem, your app inspires me. It's good to start things yourself if it helps you with your everyday life.

**Comment by berrnd** [comment]
This is now done, if you want you can play around a little bit in the already updated [pre-release demo](https://demo-prerelease.grocy.info) to check if this works for you. :)
