### ISSUE TITLE
Bug: Stock overview is sorted by product ID

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#1235]
The stock overview page has the products sorted by product ID instead of best before date or name. Also the sorting by ID is not in numerical order but by comparing strings (eg. 1,10,100,101 instead of 1,2,3...).

Clicking on the "Next due date" row header sorts the entries, but it has to be done every time loading the page.

**Comment by berrnd** [comment]
Initial sorting is based on the "Value" column ascending - not the best default, will be improved:
https://github.com/grocy/grocy/blob/200964edff92648408f479ffd8fed199e9494e17/public/viewjs/stockoverview.js#L2

Sorting numeric columns works since https://github.com/grocy/grocy/commit/b5fc64cf5d14db12b197071cff5be7ed3c4d79b3#diff-97bfd032f2462795959d97922f7cb270b7d12d5e97d2965c8e725ce0b4fc3104.

> Clicking on the "Next due date" row header sorts the entries, but it has to be done every time loading the page.

Cannot reproduce that. (?)
DataTables states are saved server side as a user setting since https://github.com/grocy/grocy/commit/dd8fa5ff66a3533dba00a191d299564f9c35d6db#diff-971c04bb34ea5a124ad687ea4eb7a88e1fd7dc89cb670f692fd3e3d7436a72a0.

**Comment by Forceu** [comment]
Hm after clicking on the column row header again, it seems to be working now. Very strange, because it did not save it before... I keep it in mind though and report back if it happens again.

**Comment by Forceu** [comment]
When I opened Grocy today, it reverted back to sorting by id, so it did not store the sorting I selected earlier. Has that been fixed by the commit as well?

**Comment by berrnd** [comment]
DataTables state loading happens here:
https://github.com/grocy/grocy/blob/5cd3fb092a145b1f94de22cecf65758a229d735b/public/js/grocy.js#L754-L766

(`Grocy.UserSetting` contains all user settings, [populated here](https://github.com/grocy/grocy/blob/5cd3fb092a145b1f94de22cecf65758a229d735b/controllers/BaseController.php#L184).)

So there must be some error there (maybe try to check the JS console at the time when this is happening), haven't had that myself so far.

**Comment by Forceu** [comment]
I am not on the dev version, but the current release. Today I had the same problem again, with no errors in the console.

**Comment by berrnd** [comment]
Sorry, I really don't know what to do about that unless it's reproducible, I also only ever use the current release on my private instance and still haven't experienced that myself...
