### ISSUE TITLE
Use barcode amount also for Consume (and Inventory and Transfer)

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#1254]
_Originally posted by @sleeplessnight2 in https://github.com/grocy/grocy/issues/1253#issuecomment-753939237_

I was just about to write something similar.

But I expand this:
The quantity stored in the barcode is not used at all when consuming.
Here simply the two values are taken (Quick-Consume or default value from the user settings).

My suggestion: Per barcode another "Quick-Consume-Amount" possibility - then you don't need to change too much in the code.

**Comment by berrnd** [comment]
Of course we can extend that the barcode amount get also used/prefilled on Consume (and Inventory, and Transfer).

> My suggestion: Per barcode another "Quick-Consume-Amount" possibility - then you don't need to change too much in the code.

Why should a barcode have a different amount for purchase and consume?
A barcode is attached to a pack of 10, or of 20...

**Comment by sleeplessnight2** [comment]
> Why should a barcode have a different amount for purchase and consume?
> A barcode is attached to a pack of 10, or of 20...

Yes, that is exactly what I am trying to get the message across all the time. Because that doesn't make sense - but is currently the case.

As an example:
I have 100 products migrated from 2.7.x. All these barcodes have NO amount stored in them.
So when consuming through a barcode, the system takes a different amount - the quick consume or the default amount.
...
So how do you want to get a handle on this?
According to this, the quantity from the barcode would have to be prioritized before the other actions.
And this should also theoretically appear correctly in the "Amount" field immediately after scanning.

Exactly this question is the issue since the whole " drama about the consuming quantity " of me... See 1149...
... and exactly THAT'S why I'm still of the opinion, that a standard-consume-quantity doesn't make sense when using a barcode -> Because as mentioned by you: Why should a barcode have a different amount for purchase and consume?

But nice that the grievance is finally noticed :D
And if now the amount of a barcode becomes the same, which is also consumed, I'm overjoyed and celebrate the day, because I can finally remove my self-modified code lines :)

**Comment by berrnd** [comment]
My question was not about that this makes no sense, it was just about why a DIFFERENT (means second) amount for a barcode is needed (instead of using the amount currently only used on purchase, as this new feature was clearly done for purchase so far) - that you haven't answered.

No second amount field for barcodes will be added, but, as the title says, the barcode amount will be used on consume/inventory/transfer - anytime soon, like all the other open enhancements.

I personally have no problem (since we have Scan Mode), I like it simple, so my stock QU is always the QU I normally (means always) consume products. I scan one time to remove 1. I scan 2 times to remove 2. ...
