### ISSUE TITLE
Feature request: REST API CRUD for Recipes

### ISSUE THREAD

**Issue by RafalDadas** [grocy/grocy#1255]
Is there any chance that there will be an API endpoint for creating, reading, updating & deleting recipes? I'm working on Android & iOS app for grocy and this feature would be awesome! :wink:

**Comment by berrnd** [comment]
Of course, everything what the UI does is possible via the API, because the UI uses the API.

Check the ["Generic entity interactions" endpoints](https://demo.grocy.info/api#/Generic%20entity%20interactions) endpoints.

Another good thing is always to just check what the UI does for example via the Browser Developer Tools.

See also: https://github.com/grocy/grocy/issues/983#issuecomment-684749371
