### ISSUE TITLE
Feature request: filter showing only what is actually on stock

### ISSUE THREAD

**Issue by liffez** [grocy/grocy#1263]
will it be possible to make a status filter option in the stockoverview that just shows the items actually on stock.
With the amount > 0

**Comment by berrnd** [comment]
The stock overview page only shows currently in-stock products (so intentionally those are all with an amount > 0).

And all not-in-stock products but which are currently below their min. defined stock amount.
So you want to hide them?

**Comment by liffez** [comment]
Yes it was to hide the ones that has a defined min. stocka value but currently are not in stock.

**Comment by Festeazy** [comment]
I agree with this a little bit too, i only want to see whats below my min stock when i actually have any of that product avialable

maybe could be done in a stock setting?

**Comment by berrnd** [comment]
> maybe could be done in a stock setting?

Of course it can be done, wherever and however, I would prefer a generic approach, as most of the time, like for the new table options - so maybe extending this by a "table filter".

Because lately there have been a lot requests about detail-things, which is not a problem, but adding an option for every little thing is IMHO not the solution...

It's also always possible to modify pretty much everything yourself, without maintaining your complete own fork ([README ref](: https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself)).

Here is a snippet for `data\custom_js.html` which hides all rows with an amount of 0 on the stock overview page:
```html
<script>
	if (Grocy.ActiveNav == "stockoverview")
	{
		$("td[data-order='0']").closest("tr").addClass("d-none");
	}
</script>
```

**Comment by liffez** [comment]
the original suggestion was also just to extend the "table filter" (or  "status filter" as i called it) with one more option, that showed only the items currently in stock.

I totally agree that focus has to be on the general structure of the project and then tweak in the small things.
And a general structure that by the way is made really nice :-)

thanks for the snippet - i have not thought about using it this way.

**Comment by Uatschitchun** [comment]
> the original suggestion was also just to extend the "table filter" (or "status filter" as i called it) with one more option, that showed only the items currently in stock.

I'd totally second that request, which should be the standard view, imho. A product out of stock isn't in stock.
All other views, like also those incl. below min amount, etc should be "status filters" then.

**Comment by berrnd** [comment]
@Uatschitchun on the one hand you say it's so unbelievably wrong to show something _not_ in stock on the [/stockoverview](https://demo.grocy.info/stockoverview) page and at the same you say you want to show _not in stock but below min. stock amount products_ there? Please really come on... 🙄

> Using the snippet above isn't a solution as all other filters don't work anymore when using it! Ex. being able to show products below min. amount

Products below min. stock amount are highlighted in blue on the stock overview page and of course that filter still works for all products _in stock and at the same time below min stock amount_, since you want to only see _in stock_ products there. May I suggest (again) to try things before commenting.

_This references https://www.reddit.com/r/grocy/comments/mh5bf9._

**Comment by Uatschitchun** [comment]
@berrnd 
I sure have tried the snippet and it doesn't allow to show products with amount "0" that are below min amount anymore! As the snippet is global, how you'd show products that aren't in stock after using the snippet?
Ok, wasn't precise enough. A global filter filtering all with amount "0" forever isn't what was asked and isn't what I seconded!

No ERP is going to show what's out of stock when opening the stock overview. No media player is showing media not present by default.
Imho stock overview should at first always show what's **in stock**. It could be a new status, as requested, although I think it should be the default.

**Comment by berrnd** [comment]
> As the snippet is global

It's not, it only runs on the /stockoverview page, any other page is not affected and will still show any product - great again that you claim something just wrong which only proofs that you haven't even tried it despite saying you had - let's end this here.

This here is about that displaying _currently not in stock but below min. stock amount products_ should be optionally / configurable somehow - which is still a valid feature request and will be done at any point.

**Comment by berrnd** [comment]
There is now a new status filter on the stock overview page: 

![grafik](https://user-images.githubusercontent.com/2161815/125319885-76c30500-e33b-11eb-9b06-b7f7b058941c.png)

**Comment by berrnd** [comment]
Yeah, finally - there are definitely too few releases since the beginning of 2020 compared to the time before, needs to be changed... :) 

All open known bugs are fixed, so just trying to do some other smaller requested things and thinking about dropping a new release at the end of next week or so...

**Comment by liffez** [comment]
Great job anyway 👍
And you know - everything takes time 😊
