### ISSUE TITLE
Rounding error results in rice always having a cost of 0.00/g

### ISSUE THREAD

**Issue by vorkuta** [grocy/grocy#1270]
When purchasing rice on Grocy, it results in a 0 cost due to rounding errors (as far as I can tell).

Example:

Purchase 1000g of rice, this costs around £1.00 = £0.001/g

As this has three decimal places I cannot enter the value, so I try total price instead.

When entering a total price of 1, Grocy shows that this ‘means 0.00 per gram’, and when purchased the price stays at 0.00.

I could set the base unit for rice to be 10g, but it doesn’t feel like the right way of doing things.

If I am missing something here please let me know.

**Comment by berrnd** [comment]
Since v3.0.0 it's possible to configure the decimal places for all amount and price inputs, if you set that reasonablehigh, it works accordingly. If you leave this by 2 decimal places, it's correct since `0.001` rounded to two decimal places is simply `0.00`.

[Changelog](https://grocy.info/changelog#v3.0.0) excerpt:
> The decimal places for all amount and price inputs can now be configured (stock settings / top right corner settings menu, default for amounts is `4`, for prices `2`)

Demo (recipe) with exactly your example:
https://test-bom9bkdcrqw2tzy801v51n.demo.grocy.info/recipes?recipe=7

**Comment by vorkuta** [comment]
Thanks.
