### ISSUE TITLE
Consume parent product: Wrong amount validation when QU conversion is involved

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#1306]
_Originally reported here: https://www.reddit.com/r/grocy/comments/lfnx83_

> 1) Create parent product - Coca Cola
> - Units purchase/stock: millilitres
> 
> 2) Create child product - Coca Cola 1.5L
> - Units purchase/stock: bottle
> - Set products QU conversions: 1 bottle = 1500ml (and the reverse)
> 
> 3) Purchased 3 bottles of Coca Cola 1.5L
> 
> 4) Now the parent Coca Cola shows 4500ml is in stock, which is correct.
> 
> 5) I go to consume, select the parent Coca Cola, asks how much to consume in millilitres and now there is the problem.
> 
> It only lets me put in the number from 0.0001 to 3ml - as I bought 3 bottles, instead of letting me put in 4500ml.

Private demo instance with that example: https://test-zw74j72c3f7foocdy0f4k.demo-prerelease.grocy.info

**Comment by InToSSH** [comment]
Thank you for creating the issue.
Here are some screenshots to clarify the consume problem of product [Coca Cola](https://test-zw74j72c3f7foocdy0f4k.demo-prerelease.grocy.info/product/27) from the example instance:

![2021-02-09_12-11-09](https://user-images.githubusercontent.com/6452373/107355702-24ea2a80-6ad0-11eb-846e-4a085206b339.png)

Consume page only allows to consume 7ml - because the stock comes from a child product [Coca Cola 1.5L](https://test-zw74j72c3f7foocdy0f4k.demo-prerelease.grocy.info/product/28) - which has 7 bottles in stock - units are not converted to ml.
![2021-02-09_12-11-41](https://user-images.githubusercontent.com/6452373/107355706-261b5780-6ad0-11eb-96b7-c0dc9990fdc0.png)

**Comment by cavazosomar** [comment]
Is this bug back? The same thing is happening to me on v3.3.1

**Comment by berrnd** [comment]
> Is this bug back?

What's reported for this above including the there [mentioned private demo instance](https://test-zw74j72c3f7foocdy0f4k.demo-prerelease.grocy.info) with the particular example can still be used to easily verfiy that - and based on that the answer is: No.

So please open a separate issue and describe there how the reproduce the problem by providing an example on a private demo instance as mentioned on the issue template.

**Comment by cavazosomar** [comment]
Actually I just tested that private demo instance with that same product and the issue is there

Reproduce step 5 in the original post:
simply go to the consume page and select Coca Cola as the product
Input any value above 3 milliliters and the error appears

**Comment by berrnd** [comment]
Ok, but that's a totally other problem / error message - this here was about input validation problems, not about anything else. You can input any number, but the consume transaction is declined by the API with the message `Amount to be consumed cannot be > current stock amount (if supplied, at the desired location)`. I only test things related to the issue topic.

Moved to #1949, since tracking unrelated things in a 1.5 years old issue is untrackable.
