### ISSUE TITLE
Feature request: Disable expiration tracking per product group

### ISSUE THREAD

**Issue by Ape** [grocy/grocy#1317]
I'd like to have expiration tracking for some product groups (food stuff), but have it disabled for others (non-food).

**Comment by berrnd** [comment]
Beside that grocy is not supposed for non-food, it's not needed, since you can just set the product default to `-1` which means it never expires. I personally simply use it like that.

Product defaults are prefilled at any place you need to enter a due date, means when the product has a default set, you never need to enter it for that product manually.

**Comment by Ape** [comment]
Could I then have default product settings for product groups? That would really speed up adding new products and I think there are other fields besides the expiration that would be relevant.

**Comment by berrnd** [comment]
> Could I then have default product settings for product groups? That would really speed up adding new products and I think there are other fields besides the expiration that would be relevant.

Duplicate of #603.
