### ISSUE TITLE
Feature request: Add ability to skip chores

### ISSUE THREAD

**Issue by RubenKelevra** [grocy/grocy#1322]
Currently, there's no way to tell Grocy that a chore which it thinks is 'overdue' is in reality not necessary and should be skipped.

Say you create a chore for the dishwasher - which needs to be emptied daily, which means it gets overdue after a day.

But there are days where the dishwasher is half-full and haven't yet run - so it would be nice to be able to push the chores due date forward in custom amounts of time per chore. In my example for the dishwasher, it would be nice to have something like 'in 3 hours' when you turn it on, or 'tomorrow' when it's still half full.

**Comment by berrnd** [comment]
Already possible, check the chore option "Due date rollover":

![grafik](https://user-images.githubusercontent.com/2161815/107845051-f70b2b80-6dd8-11eb-8460-7669a2d9bf94.png)

**Comment by RubenKelevra** [comment]
Hey @berrnd,

yeah but that's not what I want (I think).

Sometimes chores are just overdue, since some family member has its turn and misses to do it. Then it should be shown as overdue. This way either a different member can do it, say bring the trash out or can remind him/her on the task which is overdue. 

Using this option would just skip them all the time.

I think what we need is a manual option to skip it x days, so just it's overdue gets pushed forwards. So one has already checked that the trash and it's not full - so it's just moved forwards one day.

That would be great!

Thanks for considering!

**Comment by berrnd** [comment]
Of course we could add a "skip" option which would be technically the same as when the chore was done, with the difference that it's not tracked as "done" - feel free to add that as a separate request if that's what you want.

Don't really get what you want since you say that you want to show a chore as overdue, so that someone else can pick it up and at the same time you want to skip it.

When my chore "Clean the kitchen" is due and the kitchen is not dirty, I maybe doesn't clean it but track the chore as "done" - the next execution is scheduled by the chores period type (same as "skip", if that would be already there).

If I want to clean the kitchen then maybe tomorrow, I would not track the chore as done and enable "Due date rollover", so it will be also due tomorrow (not overdue) to maybe check if it's dirty enough to clean it then.

If the kitchen should be cleaned exactly at the due date, I would not enable "Due date rollover" to highlight it explicitly to be overdue when missed.

**Comment by RubenKelevra** [comment]
Alright, I'll open a new ticket and try to explain it a bit better why this is needed for us :)

Sorry for the confusion, English isn't my native language and I sometimes hit some corner cases where I'm not sure how to express myself properly.
