### ISSUE TITLE
Bug: UI: amount entry on purchase shows only 1 digit on browser width >1200

### ISSUE THREAD

**Issue by schlamar** [grocy/grocy#1328]
At browser width 1200 the purchase page switches to a 3 column layout but the third column is empty. This results in the amount entry shrunk down to 1 digit which makes purchases for products requiring big amounts (e.g. with gram unit) really tedious.

![image](https://user-images.githubusercontent.com/238652/107843622-10a67600-6dcd-11eb-82b5-0926c9c22476.png)

Edit: I have a High-DPI Full HD display with DPI Scaling 150%. So the 1200 width is actually 1800 on the display. Maybe that's relevant here.

**Comment by berrnd** [comment]
Mabye simply collapse the sidebar will help.

Or use [custom CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to make everything fit your needs.

It's hard to support any screen width with any DPI scaling pixel perfect..

Default [Bootstrap breakpoints](https://getbootstrap.com/docs/4.6/layout/overview/#responsive-breakpoints) are used:
- The sidebar is hidden/collapsed below `lg` (992px width)
- The "right part" (product overview card here) is hidden/collapsed below `md` (768px width)

**Comment by schlamar** [comment]
Well, in my case there is a third breakpoint placing an empty column right
of the product overview (see screenshot above) and I would say that's a bug!

Bernd Bestel <notifications@github.com> schrieb am Sa., 13. Feb. 2021,
09:24:

**Comment by berrnd** [comment]
> third breakpoint placing an empty column right

Yes, on `xl` (so > 1200px) there are 3 columns, otherwise  the form and the product card would be so so wide that it just looks ugly, of course that's maybe not perfect for 1201px, but as I said, making it pixel perfect for any screen width with any DPI scaling is hard (and I will personally not do it, unless it doesn't work on "standard" screen sizes/resolutions).

Code ref for the purchase page (similar to any other page with the same layout):
https://github.com/grocy/grocy/blob/a455a012045e4f505859f2a05651d72741bcde02/views/purchase.blade.php#L19
https://github.com/grocy/grocy/blob/a455a012045e4f505859f2a05651d72741bcde02/views/purchase.blade.php#L157

So feel free to improve it while not breaking anything else and provide a pull request for it.

**Comment by berrnd** [comment]
Or simply just collapse the sidebar, as already suggested, and get ~200px more width...

![grafik](https://user-images.githubusercontent.com/2161815/107846772-a39fda00-6de6-11eb-9924-e08b8282db1e.png)
