### ISSUE TITLE
Feature request: More concise calendar event titles

### ISSUE THREAD

**Issue by Ape** [grocy/grocy#1329]
Currently calendar event titles are formatted like 'Product due: Tomato Sauce'. I'd like to change it to 'Tomato Sauce is due'. This change could be done similarly to other event types.

This issue arised when my (external) mobile calendar overview could only show  'Product du...' for all the related events so I couldn't see which products are expiring without opening the events. With the new format it would show up as something like 'Tomato Sau...' which immediately gives me the main information even if it cannot fit the whole title.

**Comment by berrnd** [comment]
> even if it cannot fit the whole title

So there is never a real solution for your problem...

Also possible to solve using [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself).

For me it makes more sense to prefix the events by "topic/category" (since we not only have expiring products, also due chores and so on).
