### ISSUE TITLE
Feature Request: Location API / Product API

### ISSUE THREAD

**Issue by horphi0815** [grocy/grocy#1340]
Would be great to get a location API, to create and manage the locations and products. :-)

Best regards,

Phil

**Comment by berrnd** [comment]
Already possible - everything what the UI does is possible via the API, because the UI uses the API.

Check the ["Generic entity interactions" endpoints](https://demo.grocy.info/api#/Generic%20entity%20interactions).

Another good thing is always to just check what the UI does for example via the Browser Developer Tools.

Get all locations: [`/objects/locations`](https://demo.grocy.info/api/objects/locations)

Get a specific location (by id): [`/objects/locations/2`](https://demo.grocy.info/api/objects/locations/2)

Get a specific location (by name): [`/objects/locations?query%5B%5D=name%3DFridge`](https://demo.grocy.info/api/objects/locations?query%5B%5D=name%3DFridge)

Add a location: `POST /objects/locations`
```
{
  "name": "Fridge2",
  "description": "xy"
}
```

Update a location: `PUT /objects/locations/2`
```
{
  "description": "New description..."
}
```

Delete a location: `DELETE /objects/locations/2`

**Comment by berrnd** [comment]
Searching through the requests here is also always an option - related questions: #885, #1255, #1194, #1140, #1082, #1021, #983, #777, #544, #311

**Comment by horphi0815** [comment]
Damned, shame on me....:-/
Thanks for your fast response. I put a monthly donation for you in place. :-)

Please keep go on this project.

BR

Phil
