### ISSUE TITLE
Feature Request: Product location on demand

### ISSUE THREAD

**Issue by horphi0815** [grocy/grocy#1349]
Hi @berrnd ,

 to manage my stuff  @home, it would be great to pick the item via barcode and couple it with a second scan to a storage rack, locker, etc...

If i buy my stuff and bring it @ home, i would like to put it in a storage compartment and scan the storage compartment to actualize the default location in the product, to ensure the right location.

Is this possible, or did i missed something?

Best regards,

Phil

**Comment by berrnd** [comment]
Currently each product has a default location which is prefilled on the /purchase page. That product default location is not changed when using another one on a purchase transaction, since it's a _default_.

Of course this can be technically done, also via [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) (simply update the product location on submit of the purchase form).

**Comment by Saturo78** [comment]
Could you provide a example how this can be done via custom JS? I´m interested in that but not talented enough to do this on my own.

**Comment by berrnd** [comment]
Here is a snippet for `data/custom_js.html` which does that (_update the product location on submit of the purchase form_);

```html
<script>
if (Grocy.ActiveNav == "purchase")
{
	$("#save-purchase-button").on("click", function(e)
	{
		var productId = $("#product_id").val();
		var locationId = $("#location_id").val();

		Grocy.Api.Put('objects/products/' + productId, { "location_id": locationId },
			function(result)
			{ },
			function(xhr)
			{ }
		);
	});
}
</script>

```

**Comment by berrnd** [comment]
Products have a default location (which is prefilled on the /purchase page).

Products now also have a default consume location (which is prefilled on the /consume page, ref https://github.com/grocy/grocy/issues/1365#issuecomment-1086931240).

Updating the products _default location_ on each purchase IMHO doesn't make so much sense in reality and if really needed anyways, it can be achieved by the custom JS example provided above.
