### ISSUE TITLE
Bug: changes on table options not saved

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1366]
After some time all changes made in the table options are set back to standard. Not sure if this is related to my browser?

**Comment by berrnd** [comment]
I'm still sorry, but I still have no clue how to help for reports like "something doesn't work sometimes"...

So please report things only if you have something reproducible, specific error logs or anything else mentioned on the issue template.

**Comment by Saturo78** [comment]
¡Hola Señor Berrnd!

To reproduce the behavier, click on the eye button on the stock overview page.
Select for example product group, last purchased ore something else not shown.
Click the okay button.
Go to the stock overview page.
Change the order of the tabs in the stock overview.

Close the browser window.
Restart the browser.
Go to the stock overview page.
The selections you made in the previous step are all gone.
Just product, amount and next due date are selected.

Are these settings not saved beyond the active session?
If this is the case, please accept my apologies for reporting this behaviour as an issue.

Te aplicación me gusta mucho y me gustaría utilizarla!

¡Muchas gracias!


Am 20. Februar 2021 18:03:59 MEZ schrieb Bernd Bestel <notifications@github.com>:

**Comment by berrnd** [comment]
> Are these settings not saved beyond the active session?

Since v3.0.0 it's saved as a user setting (as mentioned on the changelog), so persistent, before it was saved in browser `localStorage`, so not bound to any session, but at some point your browser may clear the `localStorage` - code ref:
https://github.com/grocy/grocy/blob/3d82c9abbd4f17d130c39a5774c26f109584dec8/public/js/grocy.js#L741-L766

Any time something is reported without reproducible steps, I start guessing some and try to reproduce it.
Now I did exactly what you described and still everything works as expected, at least here (recent Firefox, no single addon, default [demo-prerelease](https://demo-prerelease.grocy.info/) instance):

https://user-images.githubusercontent.com/2161815/108605600-4e029900-73b5-11eb-89ec-3dee3d6c81df.mp4

So I just can further guess:
- If it works not on your installation, it's maybe something about browser or your installation
- If it does not work for you also on the demo, it's something about your browser

At any point the mentioned user setting need to be reset if that happens, or the previous state was never saved - both can be investigated using the browser developer tools, maybe try to check the requests made to the API endpoint `/user/settings/{settingKey}`...

Unless something is reproducible, it's not worth to report or track it as a bug since how should anyone fix something not reproducible without any errors...

**Comment by hermann-san** [comment]
I've the same problem and it for me it's not browser related.  
Once I've changed the columns, it is saved, but only for a certain time period. 
so I can change it on my PC (Firefox) and I can see the changes on my mobile phone too (Android Firefox). However, a few hours later (or a day later) I've checked again, and the changes are gone. Back to default.  I've did it on the product page (default store column).
The same thing happened on the demo page

**Comment by berrnd** [comment]
Someone needs to provide a reproducible way if this should be fixed.

I also use grocy daily and also on Firefox Desktop + Android and never had that problem.

The only known problem related to that is, that column settings can be messed up after updating grocy when default columns were changed on the corresponding table (because technically everything is based on the column index).

&nbsp;
>  The same thing happened on the demo page

The demo page is unfortunately not a good reference for user setting problems, since that's used by many people in the context of the very same grocy user. And the (public) demo instances get reseted multiple times a day.

**Comment by hermann-san** [comment]
@berrnd   this is what I do.
1. go to "products"
2. Table Option - view columns,  checkmark "Default shop"  + click OK
3. close the Grocy browser  tab.
4. after 3 hours check the table again. Default shop should be gone.

I'm using Grccy 3.3.1 on Yunohost

**Comment by berrnd** [comment]
Nothing is saved in the browser (cookies, local storage, whatever) and nothing is done on a time schedule - so can't be reproducible by that. I can't say if Yunohot does anything special, since I don't know a tiny bit of that.

**Comment by hermann-san** [comment]
@berrnd  
For me it's reproducible. Every time  I change the table option, changes are gone after 1-2 hours. I've tried in different browsers several dozens times. Same result, every time.
I would be surprised if Yunohost would play a role in the process, but I can open an issue with them and see what they say.  Thanks for now.

**Comment by berrnd** [comment]
Sorry, I can only fix things reproducible in a reproducible way - having a problem only in one/your environment is not that...

**Comment by hermann-san** [comment]
So yesterday I did a fresh install of Grocy with Docker on Linux. That was quick and easy for me and on Day 1 I did change the table options for "Products". On the next day ("Day 2")  I did check the options and the setting were gone. The settings do seem to stick for a short while, but (as mentioned above), they are gone after that short period.
The same happens on Windows with the Desktop app.
Important is to really only check again after a few hours or the next day. Else it looks like the change is persistent, but in fact it isn't ( in my tests).
So from my tests, the issue is not only related to Yunohost with Grocy.

![grafik](https://user-images.githubusercontent.com/7679654/192302458-efe2f612-2418-421d-9f72-ec18f572aa67.png)

**Comment by pascallj** [comment]
I can confirm this bug is still present. It can also easily be confirmed in the demo.

I created a new private demo yesterday, opened this in Firefox, added the 'value' column to the filter options and closed it. Opened it today and the filter option was gone. My Firefox is set to clear cookies on exit, but that cannot be it because it works fine in private mode or Chrome afterwards.

How unlikely you might think it is, it really seems to be 'after some time'.

**Comment by berrnd** [comment]
> How unlikely you might think it is, it really seems to be 'after some time'.

This is not about faith, it's software - so simply provide that 100 % reproducible example in a clear and concise new report and I will maybe have a look - better than spamming year old threads.

How unlikely you might think that I'm not a Grocy user myself - I am, daily, multiple times and never had that problem. Maybe simply triple check that not random Browser add-ons are the bad guy here, wouldn't be the first time.

**Comment by berrnd** [comment]
3 years, nobody of you (of which it seems at some point this was an important thing) was willing to dig into this, e.g. by reading documentation and finding [this](https://datatables.net/reference/option/stateDuration) - thanks so far and it's my pleasure to provide Grocy to you all.

**Comment by berrnd** [comment]
Fixed by / merged into #2494.
