### ISSUE TITLE
Bug: Consume page: "Use a specific stock item": Potentially duplicate items shown

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1368]
Demo preview version

Purchase 1 bottle of milk to the fridge
Purchase 1 bottle of milk to the pantry
Go to the consume dialog
Select Milk (don't change location)
Use a specific stock item
1 Entry for one bottle of milk is shown ->thats correct

Change Location to pantry
Use a specific stock item
the stock entry for the one bottle of milk in the pantry is shown twice.

![grafik](https://user-images.githubusercontent.com/71584438/108607717-64632180-73c2-11eb-9401-ebe44386a256.png)

Change Locaton to pantry
Use a specific stock item
now the Entry for the one bottle in the fridge also is shown two times.

On stock there are only two bottles, one in the fridge an one in the pantry:
![grafik](https://user-images.githubusercontent.com/71584438/108607811-f1a67600-73c2-11eb-8399-c7da6471482e.png)

**Comment by berrnd** [comment]
Just a timing problem, the `Use a specific stock item` dropdown is initialised, async `onchange` of the location dropdown - means this happens when you change the location dropdown "fast" (means faster than your browser finished populating the dropdown from the change before), not depending on if the selected product has stock in multiple locations or not.

Code ref:
https://github.com/grocy/grocy/blob/3d82c9abbd4f17d130c39a5774c26f109584dec8/public/viewjs/consume.js#L210-L280

Of course a bug, but I doubt this really happens when using grocy in real world use cases - I personally consume products by using "Use a specific stock entry" on my personal instance often and never saw that happen...
