### ISSUE TITLE
'/stock/volatile' API doesn't list "due_type = Expiration date" products

### ISSUE THREAD

**Issue by Ape** [grocy/grocy#1372]
The `/stock/volatile` API endpoint correctly list products that are due, overdue, or expired, but doesn't list any expiring products.

Do you think we should add `expiring_products` category to the JSON response or just list expiring products in the `due_products` list (it already has the `due_type` field)?

**Comment by berrnd** [comment]
There was a naming change in v3.0.0, there are no "expiring" products since then - [changelog](https://grocy.info/changelog#v3.0.0) excerpt:

>  - Endpoint `/stock/volatile`
>     - The query parameter `expiring_days` was renamed to `due_soon_days`
>     - The field `expiring_products` was renamed to `due_products`
>     - The field `expired_products` now only contains expired products (so them with `Due date type = Expiration date`)
>     - The new field `overdue_products` contains only overdue products (so them with `Due date type = Best before date`)

Products are "due soon" regardless of the `due_type`, both types are highlighted in yellow on the stock overview page.

But true, products which are due soon and `due_type` = `Expiration date` are currently missing in `due_products` of the API response.
