### ISSUE TITLE
Feature request: API for product info by name

### ISSUE THREAD

**Issue by Ape** [grocy/grocy#1374]
I'd like to have an API endpoint for getting product info by product name. This would be similar to `GET /stock/prodcuts/{productId}` and `GET /stock/products/by-barcode/{barcode}`.

**Comment by berrnd** [comment]
1. Lookup the product id by using the generic filters available for the `GET ​/objects​/{entity}` endpoint:
https://demo.grocy.info/api/objects/products?query[]=name=Paprika

2. Take the id and use the `GET /stock/products/{productId}` endpoint:
https://demo.grocy.info/api/stock/products/12

(The "by-barcode" endpoints were created before the generic filters were available, so we could even remove them all now - or otherwise provide a separate endpoint for more or less any field products can have...)
