### ISSUE TITLE
Bug:  vsprintf(): Argument #2 ($values) must be of type array, null given

### ISSUE THREAD

**Issue by Juansero29** [grocy/grocy#1401]
Getting this error on a fresh Grocy install with nginx. Seems to come from LocalizationService, even though grocy is in English.

vsprintf(): Argument #2 ($values) must be of type array, null given

Error source:
E:\WebServer\grocy\services\LocalizationService.php:89

Error message:
```
vsprintf(): Argument #2 ($values) must be of type array, null given
```

Stack trace:
```

#0 E:\WebServer\grocy\services\LocalizationService.php(89): vsprintf()
#1 E:\WebServer\grocy\services\DemoDataGeneratorService.php(383): Grocy\Services\LocalizationService->__t()
#2 E:\WebServer\grocy\services\DemoDataGeneratorService.php(29): Grocy\Services\DemoDataGeneratorService->__t_sql()
#3 E:\WebServer\grocy\controllers\SystemController.php(32): Grocy\Services\DemoDataGeneratorService->PopulateDemoData()
#4 E:\WebServer\grocy\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(43): Grocy\Controllers\SystemController->Root()
#5 E:\WebServer\grocy\vendor\slim\slim\Slim\Routing\Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 E:\WebServer\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#7 E:\WebServer\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#8 E:\WebServer\grocy\vendor\slim\slim\Slim\Routing\Route.php(341): Slim\MiddlewareDispatcher->handle()
#9 E:\WebServer\grocy\vendor\slim\slim\Slim\Routing\RouteRunner.php(84): Slim\Routing\Route->run()
#10 E:\WebServer\grocy\middleware\LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#11 E:\WebServer\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#12 E:\WebServer\grocy\middleware\AuthMiddleware.php(31): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 E:\WebServer\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#14 E:\WebServer\grocy\vendor\slim\slim\Slim\Middleware\RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 E:\WebServer\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#16 E:\WebServer\grocy\vendor\slim\slim\Slim\Middleware\ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 E:\WebServer\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#18 E:\WebServer\grocy\middleware\CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 E:\WebServer\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#20 E:\WebServer\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 E:\WebServer\grocy\vendor\slim\slim\Slim\App.php(215): Slim\MiddlewareDispatcher->handle()
#22 E:\WebServer\grocy\vendor\slim\slim\Slim\App.php(199): Slim\App->handle()
#23 E:\WebServer\grocy\app.php(94): Slim\App->run()
#24 E:\WebServer\grocy\public\index.php(45): require_once('...')
#25 {main}
```

**Comment by berrnd** [comment]
Since demo data data is being populated, you don't run with `MODE` = `production` - anything happening in `demo` or `dev` mode is really not considered to be a bug...

Beyond that I have also really no clue how to help by only having the stack trace - it works here and on the demo instances...
- Double check that the files in the `localization` directory are valid
- Double check that all your quantity units properly contain a `name` and a `name_plural`

**Comment by Juansero29** [comment]
Oops, this bug was supposed to be in a draft, but it was actually posted. That's why it has like no context at all and no info, I'm sorry for that.

I actually could repair the app by following some instructions in #649 and also downloading PHP 7.4. (I was using PHP 8) 

However, I'm seeing this on top of recipes:

![image](https://user-images.githubusercontent.com/19156405/110249550-d9b02400-7f76-11eb-8bfc-995652649a76.png)

Is that supposed to be an icon?

**Comment by berrnd** [comment]
This still looks like you use demo data most probably because `MODE` is not `production`, if this is not a development environment, I don't know why you should want that...

The recipe picture is missing, demo data pictures are tried to be downloaded while populating demo data [here](https://github.com/grocy/grocy/blob/c483c345981be5c49353c50cea6befffe3d66e2e/services/DemoDataGeneratorService.php#L326-L331), maybe your `data/storage` directory is not writable. Add your own image to any recipe and this will not happen. The same recipe on the stable demo instance: https://demo.grocy.info/recipes?recipe=5

And just again: Demo data and dev things are out of scope of bug reporting. Please use the [subreddit](https://www.reddit.com/r/grocy) for general help as already [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).
