### ISSUE TITLE
Bug: Parent product put to shopping list despite child products above min stock amount

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1409]
Joghurt is parent product
Joghurt 0,1% and Joghurt 3,5% are child products

Min stock amount:
Joghurt = 0 (Accumulate sub products min. stock amount activated)
Joghurt 0,1% =2
Joghurt 3,5% =0

![grafik](https://user-images.githubusercontent.com/71584438/111000593-97c21c00-8382-11eb-8277-26e190c58597.png)
Despite the accumulated min. stock amount of Joghurt is fullfilled, another one is put on the shopping list.

When i set the min stock amount like
Joghurt 0,1% =1
Joghurt 3,5% =1
it works correct.

Do i have to set the parent product to 2 and the childs to 0 if it doesn't matter which child is bought?

**Comment by berrnd** [comment]
First: Here is a private demo instance with your example - as always, much easier to check it instead of only having screenshots: https://test-4dvk4e7jvwpptu5dsgayp.demo-prerelease.grocy.info

Should work like that, seems to be only a problem when the parent product has exactly the accumulated min. stock amount currently in stock (so here 2, works when 3 are in stock).

> Do i have to set the parent product to 2 and the childs to 0 if it doesn't matter which child is bought?

Should be no difference when `Accumulate sub products min. stock amount` on the parent is set.

**Comment by berrnd** [comment]
Turns out that I was wrong and the original idea (and how it's currently built) works like you said:

> Do i have to set the parent product to 2 and the childs to 0 if it doesn't matter which child is bought?

This works, I've tried to make this clearer in https://github.com/grocy/grocy/commit/0dc37fb361b8b2918eb2554812fa6fdfb6851003 by disabling the "Minimum stock amount" input field of child products when the parent has "Accumulate sub products min. stock amount" set.
