### ISSUE TITLE
Format des ingrédients

### ISSUE THREAD

**Issue by undergroundoyo** [grocy/grocy#1413]
Bonjour,

Je pense qu'il serait intéressant d'avoir le moyen de préciser pour certain produit comme la faine, le sucre, le riz, son kg/m3.  Grace a cela dans la liste des ingrédient on pourrait soit définir un poid ou un volume.  Et si on choisi dans la liste des ingrédient un volume le logiciel pourrait décompté dans les stocks le poid utilisé.

Merci

**Comment by berrnd** [comment]
Please use English here, thanks.

**Comment by undergroundoyo** [comment]
Hello,

I think it would be interesting (when we add product in the database for products such the flour, the sugar or more) to be able to specify the kg/m3. Thanks to that when we creat a recipe with a an ingredient list we will be able to define a weight unit or volume unit define in the format list. And if a volume unit was chosen from the ingredients list, the software could be count the weight used in the stocks.

Thank you

**Comment by berrnd** [comment]
I don't if I understand what you mean, but when it's about defining a product density: Already possible: Simply also create the density unit as a (product specific) quantity unit conversion. Any unit, directly or indirectly to a product, can be used at any place, so also for recipe ingredients.

**Comment by undergroundoyo** [comment]
yes but we will be obliged to define for each product a conversion density to weight and density to volume. lot lines....But if we will be able to define in the case the density we can be just get the weight.

An exemble we want add the flour.

1) i creat in the database product the flour with define in the case the density (just for for exemple 380kg/m3).
2) i add in the stock the flour and define the weigt (for exemple 200g)
3) i creat a g format and a l format and i define juste the conversion unit whit the kg = 1000g and m3=4226 cup

when in a recipe I need 1cup of flour the software took of automaticly 200g (volume * densité)

**Comment by berrnd** [comment]
The density/volume is always a thing to be defined per product, so the only benefit I see is that the indirect conversion (here cups) could take the volume information (kg/m³) instead of being directly defined for the specific product.

Makes things a lot more complex, I try to keep it simple (and already partly failed) since we still manage a fridge, not a business, so I think grocy doesn't need this at least because this is already possible by using existing product specific unit conversions and once set up, I don't think product density change often (like most other product properties)...

**Comment by undergroundoyo** [comment]
OK. Thank you for taking some of your time to analyze my request. I congratulate you on this beautiful project which contributes to the end of waste

**Comment by undergroundoyo** [comment]
Sorry i will be boring. But when i add a product whit g format. It is possible in the ingredient list to use a other format in the format list ? exemple à tsp ?because a see that is locked

**Comment by ABBiABBi** [comment]
Thanks



Sent from my Galaxy



-------- Original message --------
From: undergroundoyo ***@***.***>
Date: 14/03/2021 23:21 (GMT+03:30)
To: grocy/grocy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [grocy/grocy] Format des ingrédients (#1413)


Sorry i will be boring. But when i add a product whit g format. It is possible in the ingredient list to use a other format in the format list ? exemple à tsp ?because a see that is locked

**Comment by berrnd** [comment]
> But when i add a product whit g format. It is possible in the ingredient list to use a other format in the format list ?

Any directly or indirectly linked unit (by conversions) is possible to be selected anywhere (as said). Default conversions are limit to 1 level (#1360) and there is #1264 which affects the latest release.
