### ISSUE TITLE
Feature request: Add additional labels to github issues.

### ISSUE THREAD

**Issue by Uatschitchun** [grocy/grocy#1426]
Searching the issues is a valuable resource for looking up questions, bugs or requests prior to posting something.
Would it be an idea to add additional labels for to be able to filter the issues by topics. Labels could be in regards to parts of Grocy (like recipes, meal planning, barcodes, etc).
As far as I can see there now are only 2 labels: bug & enhancement. 
The "vNext" milestone could also be a label so the users are able to easier see if an enhancement or bug is planned for next release.

**Comment by berrnd** [comment]
This only adds more time-effort (would be me, I guess) for IMHO little value since the GitHub search is in general already powerful enough to find what you search for.

Currently only the GitHub default labels are used to classify issues which is still enough in my opinion.

Some time ago I started adding version-milestones (`vNEXT` will be renamed to the version once it's released), however, there is no plan about anything like [mentioned in README](https://github.com/grocy/grocy#roadmap) (so far, each release always contained all since then reported bugs fixed).

> The "vNext" milestone could also be a label so the users are able to easier see if an enhancement or bug is planned for next release.

Filtering by milestones is also possible, doubling the same information into a label adds nothing but clutter...
