### ISSUE TITLE
[Feature request] Replace dollars with appropriate currency for other countries

### ISSUE THREAD

**Issue by lucanomax** [grocy/grocy#1449]
A simple replacement of currency based on the country set, not a big change but It could improve appearence.

**Comment by berrnd** [comment]
Of course already possible - check the `data/config.php` option `CURRENCY`:
https://github.com/grocy/grocy/blob/d23fda245e7a1974c354213f9a228995f2fd583f/config-dist.php#L33-L37

**Comment by lucanomax** [comment]
@berrnd I searched in web UI settings. Why not adding a toggle instead of keeping it "hide" in config files? For people in their first approach of the app isn't so clear.

**Comment by berrnd** [comment]
The `data/config.php` file is there since ever, the GUI setting pages came later, that's all.

It's already tracked in #575 to migrate everything (possible) to UI, feel free to contribute that, any help is appreciated.

**Comment by darrena092** [comment]
@berrnd would you be open to a PR that adds the ability to change settings via environment variables in addition to the current system of using text files? I'm sure a lot of people running this in Docker would appreciate it as it's likely the path of least resistance for them.

**Comment by berrnd** [comment]
> the ability to change settings via environment variables
> I'm sure a lot of people running this in Docker would appreciate it

Personally not using anything Docker, but I also appreciate that and that's why this is already possible since [v1.24.0](https://grocy.info/changelog#v1.24.0), so since a little more than 5 years and that's even also mentioned at the exact same place where the rest about that is mentioned:

https://github.com/grocy/grocy/blob/6602c76005bfdb436681d976e130407650719a4a/config-dist.php#L3-L14

Please be so kind and do a little research beforehand next time and use the [r/grocy subreddit](https://www.reddit.com/r/grocy) ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests)) for general usage questions instead of spamming random threads here. This approach is even already widely used, e.g. in [grocy-docker](https://github.com/grocy/grocy-docker), [linuxserver/docker-grocy](https://github.com/linuxserver/docker-grocy) or in the [HA Add-on](https://github.com/hassio-addons/addon-grocy) - so you obviously really haven't had just a little look and what you mentioned yourself about the possible use case.
