### ISSUE TITLE
Support Arabic language

### ISSUE THREAD

**Issue by mnayef95** [grocy/grocy#1450]
## Expected behavior
It would be nice if the addon support the Arabic language

## Actual behavior
Currently, the Arabic language is not supported

## Proposed changes
If someone adds steps in the comments about how to translate the addon because I checked the transifex and found Arabic language exists there but it's not available when you set language to `ar`

**Comment by berrnd** [comment]
> checked the transifex and found Arabic language exists there but it's not available when you set language to `ar`

Any language which reached a completion level of 70 % will be provided with a pre-release demo instance and will also be included in releases (that's also [mentioned in README](https://github.com/grocy/grocy#localization)).

`ar` has currently a completion level of 36 %: https://www.transifex.com/grocy/grocy/language/ar/
Feel free to help translating grocy, much appreciated.

Like also noted in README, RTL support is currently missing, so that's another problem for `ar`, but already tracked in #984.
