### ISSUE TITLE
Optimize grocy.openapi.json to support nswag (and Microsoft's OpenAPI implementation)

### ISSUE THREAD

**Issue by PhilippCh** [grocy/grocy#1457]
# Issue
It seems like the following lines in the `grocy.openapi.json` file are not recognized by nswag or Microsoft's OpenAPI implementation (OpenApiDocument classes), thus making generation of C# client code impossible without manually modifying the JSON document.

```
"$ref": "#/components/internalSchemas/ExposedEntity_NotIncludingNotListable"
```

# Workaround
You can manually move all nodes under 'internalSchemes' to 'schemes' and update all lines containing references to 'internalSchemes'. This seems to at least generate some client code. I have yet to check whether the generated code has any issues.

**Comment by berrnd** [comment]
`internalSchemas` instead of just `schemas` was only used to hide some schemas on [/api](https://demo.grocy.info/api) - Swagger UI seems to not have a problem with that, but of course we can put everything into `#/components/schemas`...

The "raw" file also contains placeholders, it's served on [`/api/openapi/specification`](https://demo.grocy.info/api/openapi/specification) to feed the integrated Swagger UI instance (and was, at least from my side, not supposed for anything else so far).

Maybe see also #1218 and #1451.

**Comment by PhilippCh** [comment]
No worries, I was using the specification available at /api/openapi/specification.

I can whip up something tomorrow, moving the definitions to ‘schemas’ should be an easy task.
