### ISSUE TITLE
[Feature Request] Meal planning

### ISSUE THREAD

**Issue by shadowtor** [grocy/grocy#146]
It would be great to be able to schedule/plan recipes (in a way a meal plan) for times/days and adding that to the grocery listing so can pre-plan what is needed to be bought (after taking away from what is currently in stock)

**Comment by matejdro** [comment]
I've been thinking about that:

1. Ability to assign every recipe a set of tags (for example Pasta, Rice, Chicken, Eggs etc.)
2. A button that would generate meal plan for next X days. To preserve variety, meal picker would pick based on weighted random distribution, where tags that have been eaten recently would have lower change of getting picked. That way you would not eat pasta every day, for example.
2. Generated plan should be somehow editable by user
3. I think ingredients should not be consumed when creating plan, but marked with something like "planned to consume". After all this is only a plan and plans change.
4. There should be option for both "Generate plan for all ingredients" (with indicator of what needs to be bought like OP mentioned) and "Generate plan for ingredients I have"

I might be able to start working on something like that in the following months and submit pull request, if author of the grocy agrees.

**Comment by matejdro** [comment]
I would also argue that unit situation needs to be resolved before this feature can be properly implemented (e.g. if you have 2 packs of unopened flour and another pack of opened flour, grocy has no way of knowing for how much meals this would suffice).

**Comment by berrnd** [comment]
Thanks for your input/ideas! :)

I would be very happy when you start working on this - feel free to do so, maybe just add a little note here when you have started or create a "[WIP]" prefixed pull request.

> I would also argue that unit situation needs to be resolved before this feature can be properly implemented

What do you mean by that? The only issue I see for this is #123 which is already done (but not yet part of a release)...

**Comment by matejdro** [comment]
Yes I meant #123. Awesome.

**Comment by HydrelioxGitHub** [comment]
I'm very interesting in this feature too. I've just discovered Grocy and all the features I need is covered by the software except this one. I'm not a skilled developer so I don't think I can help with this but I hope this feature will be implemented soon.

**Comment by d4kn** [comment]
I'd like a "Schedule Recipe" date box on  each recipe page which places an event on the calendar for that recipe. Once all items in that recipe are within the range of "Default Best Before Days" add necessary items to a shopping list automatically.

**Comment by MakiG0** [comment]
this is the only one feature i missed in grocy. There are any progress here? I think, the date box on each recipe will be a great idea, @d4kn, but my devolopement skills aren't great...

**Comment by berrnd** [comment]
There is a lot of progress in grocy, I would say, but not about meal planning so far, if there is progress, you could read it here...

grocy is only my hobby, one I like, but not the only one, and because of that, there are no release dates, it's done when it's done, maybe tomorrow, maybe tomorrow next year, everyone is invited to contribute, I appreciate all ideas and contributions.

**Comment by berrnd** [comment]
And depends on what you want in detail, but recipes can include recipes, which maybe can also be used to define meals - e. g. create a recipe called "Next week" and reference all planned recipes for that week in this recipe, you could then even put everything needed and missing for the whole week on the shopping list...

**Comment by MakiG0** [comment]
@berrnd: Thanks for you quick reply.
i was looking for a food planer and finally i found your tool grocy. Im really glad about that. you did a nice job, btw ;-)  
i think its just simple but I don't know, if you understand what i meant in detail.
I organise my recipes in grocy and with a date field i could plan the food for the whole week.
For example:
Monday - Pizza
Tuesday - Spaghetti
Wednesday - Toast Hawai
...
The calendar show me and my family finally, what i'm going to cook for the week. This is "all" what i depends ;-)

**Comment by berrnd** [comment]
Ok, so then let's start simple: A week view where you can add recipes for each day

And because there are only two options
> it's done when it's done, maybe tomorrow, maybe tomorrow next year

let's take tomorrow, and because tomorrow is today - just have a look at http://demo-prerelease.grocy.info/mealplan if this is what you thought of and helps to start with. (?)
:D

(Maybe we close this here for now and move any further ideas/wanted functionality for this to separate issues for a better overview...)

**Comment by HydrelioxGitHub** [comment]
Wow... Your post is my new definition of efficiency !

I've only seen this view on mobile and this seems great to me. 

Thanks for your work !

**Comment by MakiG0** [comment]
OMG...you got it. this is exactly what am i looking for. I totally agree with HydrelioxGitHub, thats a new definition of efficiency!
Thanks a lot for this solution, great job!!!

**Comment by berrnd** [comment]
Thanks - you're welcome. :)

So of course this is a good start, but a little boring - at least it should be possible to see if anything is missing per day/week and also maybe display the costs per day/week, and when it's just because we can, or not? :D

I had an idea how to do this easily:
Just create a (internal) recipe per day/week which includes all recipes for that day/week - for recipes we already have the rest of the functionality.

So if you want, have another look at http://demo-prerelease.grocy.info/mealplan if you miss anything else for a first version of meal planning.
(If you find any issues, `include-internal` can be passed as a query parameter to `/recipes` to also show the for the meal plan generated internal recipes: https://demo-prerelease.grocy.info/recipes?include-internal)

@matejdro
Could you please move your further ideas about generating meal plans, etc. from above to separate issues, then this can be tracked there - thank you. And if you still want to start working on it yourself - much appreciated. :)

**Comment by MakiG0** [comment]
At the moment, i did not miss anything. All i want is just the possibility, to add recipe to a week planner ;-) 
I did not understand, what you meant with 

> just create a (internal) recipe per day/week which includes all recipes for that day/week - for recipes we already have the rest of the functionality.

> 
Issue: 
i cannot delete a recipe on a day or add the ingredients to shopping list, for example Chocolate Sauce on 7/5.

**Comment by berrnd** [comment]
I just meant with that that I use _internally_ nested recipes per day and week to do the "put everyhting on the shopping list" and the cost calculation easily by reusing existing functionality.

> i cannot delete a recipe on a day or add the ingredients to shopping list, for example Chocolate Sauce on 7/5.

The recipes are not intended to be displayed normally, not needed. They are also automatically regenerated on any change of the meal plan. The shopping list button(s) on the meal plan are disabled when the corresponding products are already on the shopping list (like on the recipes pages).

**Comment by MakiG0** [comment]
ah, okay. now i got it ;-)
i use grocy as a docker of linuxserver.io. when is the meal plan in the stable version?!

**Comment by berrnd** [comment]
Let's prepare a release the coming weekend...

**Comment by d4kn** [comment]
This is awesome, thanks!

**Comment by matejdro** [comment]
Wow this looks awesome. Yes, I still plan on working on this myself eventually, but I'm unfortunately a bit busy.
