### ISSUE TITLE
Bug: stock

### ISSUE THREAD

**Issue by undergroundoyo** [grocy/grocy#1463]
Hello

I don't know if it's really a bug but I couldn't find anything in the github that would match. 

I create 3 formats : pack, unit and g.

Then I create a product with the 1 pack format. In the "UQ" section, I create an entry 1 pack = 6 units and another entry 1 unit = 50g. 

I go into the purchase 1 pack of the product.

Then create a recipe indicating that I needed, for example, 100g. When I ask to withdraw from the stock there is no effect. There is always 1 pack in stock. Otherwise it should indicate either 4 units or 200g

Thank you

**Comment by berrnd** [comment]
Indirect unit conversions are currently somehow broken, see #1264 - so maybe related to that.

If not, please reproduce your example on a private/persistent demo instance (like also mentioned on the issue template), most of the time there are more things (product/QU/etc. properties) to consider like you mentioned and it's hard to guess that all...

**Comment by undergroundoyo** [comment]
Ok thank you 

I think I saw my error to your examples. I simply recreated my product by filling in the sections Quantity unit stock = pieces, Default quantity unit purchase = pack , factor purchase to stock quantity unit = 6 and UQ 1 pieces = 50g. 

Now when I create my recipe with 60g it counts down the number of pieces in the stocks.
Thanks for this example. Is the link for the example still valid over time (to inspire me) or will it disappear?

**Comment by berrnd** [comment]
I took the time to create an example by what you mentioned:
Product: https://test-g4sjo273blbvl76qwy10xn.demo-prerelease.grocy.info/product/27
Recipe: https://test-g4sjo273blbvl76qwy10xn.demo-prerelease.grocy.info/recipe/7

=> The recipes ingredient list shows 60 Grams (because the product was added to the recipe in that unit)
=> The hint "This equals 1.2 Pieces" on the ingredient edit form **is a just a hint** (like on all pages to check the amount converted into the products QU stock, use for example [custom CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) if you don't want to see that)
=> 60 Grams * the defined factor of 0.02 = 1.2 Pieces
==> Conclusion: I can't see a problem... (?)

In stock everything is related to the products stock QU but you can use any other related QU everywhere (as said, currently unfortunately at least broken for indirect conversions like tracked in #1264) - so I would personally set the products stock QU to that unit in which I store/use the product in my kitchen at most.

> Thanks for this example. Is the link for the example still valid over time (to inspire me) or will it disappear?

They are not deleted over time, otherwise this would be of course mentioned at the place where you create such an instance...

![grafik](https://user-images.githubusercontent.com/2161815/116806030-b8a92100-ab2a-11eb-999e-ff0d4e340458.png)
