### ISSUE TITLE
Bug: consumption order works only in default location

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1481]
The consumption order open, due, fifo is applied to the default storage location. An open stock in another storage location is not consumed first.

**Comment by berrnd** [comment]
I'm unable to reproduce that:
- Works on the stock overview page
- On the /consume page you always selected a location (defaults to the products default location), this is used

Here is a private demo instance: https://test-2actr7sua569j4zq83yso.demo-prerelease.grocy.info

![grafik](https://user-images.githubusercontent.com/2161815/118352227-8d79f500-b560-11eb-8409-2d561372a63c.png)

The highlighted stock item is not in the default location, but opened and expires later than the others, but it is picked when consuming form the stock overview page and also when using the /consume page and selecting the "Candy cupboard" location.

So if this is reproducible, please provide the steps - always hard and takes a lot of time to guess everything...

**Comment by Saturo78** [comment]
You ´re right.
But wouldn´t it be good if Grocy picks the location with the oldest stock entry automaticly?
I often store products in different locations so it would be really helpful to know from which location/stock entry i have to consume next.

**Comment by berrnd** [comment]
Then maybe better an item `<Auto>` (or empty, or something similar) in the location dropdown of the /consume page which would then do the same (picking the next one from any location) at the end as when consuming the product from /stockoverview (which I personally always do since I always follow the default rule "Opened first, then FIFO").

(That you currently can't see all the locations where a product is currently stored on the /stockoverview page is already tracked in many other requests.)

When I consume a product I first pick it physically, then track it in grocy. When I always use opened products first, I could blindly use the stock overview page to consume and it will pick that. When I don't use the opened one or maybe have opened items in different locations, then there is IMHO never an other option than to use the /consume page and pick the location (and maybe the exact stock entry, or maybe go via the /stockentries page) unless grocy learns to guess which item you have in your hand or just eaten...
