### ISSUE TITLE
Feature request: Chore "due soon days": Option for "today"

### ISSUE THREAD

**Issue by RubenKelevra** [grocy/grocy#1485]
It would be nice if we could define a cutoff time what is considered 'today', instead of assuming 24 hours forward. 

So if someone defines 1 day he means that this needs to be done until midnight:

![Screenshot_20210523-194057560](https://user-images.githubusercontent.com/614929/119270862-1fd46580-bbff-11eb-8f7a-72d50f169b9d.jpg)

**Comment by karifritsch** [comment]
+1 for this feature

One quick option before a full today feature is implemented could be setting the due date for 11:59pm instead of 12am.
That way if I want to do the chore on Sunday, it will be yellow on Sunday rather than red. If set at 1 day, yellow chores effectively become "due today" with 11:59pm as time due.

**Comment by berrnd** [comment]
Chores (and tasks/batteries) due today have now a separate highlighting + status filter, see https://github.com/grocy/grocy/issues/1740#issuecomment-1019522579.

Additionally, "due soon days" of chores/tasks/batteries can now be disabled:

![grafik](https://user-images.githubusercontent.com/2161815/150692406-15fc251e-bd80-4ba3-afc5-a52610b6430a.png)

When doing that, you have essentially only a status filter / highlighting for upcoming chores of today, hope that fits.
