### ISSUE TITLE
Bug: QU conversions section of Products shows spurious error

### ISSUE THREAD

**Issue by dmbreakey** [grocy/grocy#1498]
Specifically, two of the QU conversion rows show:

**Notice:** Trying to get property 'name' of non-object in  **<vhost-root>/data/viewcache/9eaf17cc040b2f466ea356b19e24bf182960056f.php on line 610**

This appears to be _similar_ to the error reported on the subreddit [here](https://www.reddit.com/r/grocy/comments/hninc4/products_page_giving_502_error/), but this is being reported directly in the UI.

I've checked my web-server logs to see if something similar is happening; I don't see the error it indicates, so I assume the suggested fix won't address it.

I'm running Grocy standalone behind an Apache 2.4 server on a _vhost_ config, running PHP 7.3.28.

I've looked at the relevant code, and as best I can tell, this is happening because I've deleted two _Quantity Units_ that I no longer need/use, but I assume the DB is still referencing them (both rows have replaced QU's that I've deleted).

It's not causing any other issues I can see, so the only problem for me is the (minor) annoyance of a messed-up layout for the **QU Conversions** section for those products that end up using those conversions.

Deleting and re-creating the product doesn't fix it, either.

I have done some minor tightening up of server security, by making everything **but** the _data_ folder read-only to the server process; I also set the _config.php_ file as read-only.

**Comment by berrnd** [comment]
Handling of deleted referenced objects is currently unfortunately not handled on any place, so that's the (known) problem in general. Doing this maybe requires a general rewrite of how grocy currently accesses the database / handles objects.

This is only a notice, the default `php.ini` value for `error_reporting` is set to not show them - so normally this won't be noticed and also should be not really a problem (beside unreferenced/missing data).

So the only way to resolve this is to manually cleanup your database for unreferenced QU conversions (and delete them) and missing QUs which are referenced by any product (and re-assign an existing one):
```sql
-- Delete product specific QU conversions of deleted products
DELETE FROM quantity_unit_conversions
WHERE product_id NOT IN (SELECT id FROM products)

-- Re-assign a valid QU purchase for any product which has an invalid one assigned
UPDATE products
SET qu_id_purchase = (SELECT MIN(id) FROM quantity_units)
WHERE qu_id_purchase NOT IN (SELECT id FROM quantity_units)

-- Re-assign a valid QU stock for any product which has an invalid one assigned
UPDATE products
SET qu_id_stock = (SELECT MIN(id) FROM quantity_units)
WHERE qu_id_stock NOT IN (SELECT id FROM quantity_units)

-- Delete any QU conversion for not longer existing QUs
DELETE FROM quantity_unit_conversions
WHERE from_qu_id NOT IN (SELECT id FROM quantity_units)
	OR to_qu_id NOT IN (SELECT id FROM quantity_units)
```

> I have done some minor tightening up of server security, by making everything but the data folder read-only to the server process; I also set the config.php file as read-only.

Beside that of course you shouldn't expose the `data` directory (only the `public` directory like also [mentioned in README](https://github.com/grocy/grocy#how-to-install)) I don't get what's the point about that for this particular problem...
