### ISSUE TITLE
Clean up resized images (`*downscaledto*`) when deleting an image

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1499]
I have the feeling that recipe images are still present on the server after deleting and saving.

Steps to reproduce:

Go to a recipe
Press delete in the foto section
Click save recipe

Check the recipe picture folder via ftp.

**Comment by berrnd** [comment]
Thanks, since I find facts better than feelings: Deleting pictures works (happens [here](https://github.com/grocy/grocy/blob/d23fda245e7a1974c354213f9a228995f2fd583f/public/viewjs/recipeform.js#L49-L64)), but the resized pictures (those with `downscaledto` in the filename are not cleaned up) - shouldn't hurt anyone, you can delete them all anytime since they are regenerated when needed.

Can be of course improved.
