### ISSUE TITLE
Feature Request: Hide UI elements without permission instead of disabling them

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#1505]
If I remove access for my account to use calendar it still shows up but the link is just marked as `disabled`.
Removing access should hide it in the UI, this is why I've opened this as a bug.

<img width="247" alt="Screen Shot 2021-06-15 at 9 58 15 am" src="https://user-images.githubusercontent.com/6525926/121975210-3a45cd00-cdc0-11eb-9e1b-8cc1eaf0c414.png">

**Comment by berrnd** [comment]
That was the design decision - everything you don't have permission for is disabled, not only sidebar menu items.

If you think removing instead of disabling items without permission is better, than this is clearly not a bug, more an enhancement request.

**Comment by berrnd** [comment]
As mentioned above, it was a design decision to disable elements you don't have permission for, instead of hiding them.

If you think hiding those elements instead makes more sense, you can achieve this by simply using [custom CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself).

Here is a snippet (for `data/custom_css.html`) which does that:
```html
<style>
.not-allowed {
	display: none !important;
}
</style>
```
