### ISSUE TITLE
Bug: Dirty forms aren't being detected

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#1506]
Multiple times today while having "Auto reload on external changes" enabled my page was reloaded and I lost my form details. I'm mainly seeing this while using the Home Assistant add-on in the iframe. If I goto the iframe's source directly it doesn't seem to be an issue.

https://github.com/grocy/grocy/issues/265 seems related.

Should I close this and reopen it on the Home Assistant Grocy add-on repo?

**Comment by berrnd** [comment]
The reload doesn't happen when there is a dirty form and only when idling for at least 50 seconds ([code ref](https://github.com/grocy/grocy/blob/d23fda245e7a1974c354213f9a228995f2fd583f/public/js/grocy_dbchangedhandling.js#L15-L42)) - please provide the exact steps to reproduce this if you think it doesn't work.

IMHO you only need [Auto reload on external changes](url) for example for "terminals" which are always on and should reload when something has changed (I use it in my kitchen) or when you _really_ use grocy with _multiple users at the same time_, otherwise I don't see any benefit.

**Comment by OmgImAlexis** [comment]
> The reload doesn't happen when there is a dirty form and only when idling for at least 50 seconds (code ref) - please provide the exact steps to reproduce this if you think it doesn't work.

I opened the new product page and started filling it out, my partner changed some stuff on their machine and while looking at their screen mine refreshed with the form still having my data. After the refresh the data was gone. Ideally this should at least provide an alert like most sites do stating the form has unsaved data before the page refreshes. 


> MHO you only need Auto reload on external changes for example for "terminals" which are always on and should reload when something has changed (I use it in my kitchen) or when you really use grocy with multiple users at the same time, otherwise I don't see any benefit.

It's on by default. Maybe this should be changed then?

**Comment by OmgImAlexis** [comment]
I'd be more than happy to share a screencast of this happening. As I stated it only happens in the HA iframe so maybe that's. causing the issue here?

**Comment by berrnd** [comment]
> Ideally this should at least provide an alert like most sites do stating the form has unsaved data before the page refreshes.

It should not refresh, at least that's what the code referenced above does (or should do)...

To have it reproducible on the demo instance would be best (like also mentioned on the issue template), everything else is guessing - don't know what HA does around an embedded webapp...
