### ISSUE TITLE
Bug: API endpoint /stock doesn't return the stock row id in the response

### ISSUE THREAD

**Issue by DeepCoreSystem** [grocy/grocy#1507]
When calling the API endpoint /stock, the returned response doesn't contain the stock row id that is needed if we want to fetch the details of a given stock via the endpoint /stock/entry/"row id"

![grafik](https://user-images.githubusercontent.com/3703938/122031041-9adc0680-cdce-11eb-957a-7de4b95d742d.png)

**Comment by berrnd** [comment]
`/stock` returns one object per product, behind each product can be `n` "stock rows".

Use `/stock/products/{productId}/entries` to get all the "raw" stock entries per product.
Example: https://demo.grocy.info/api/stock/products/12/entries

(I'm open for anything and appreciate every bug report and also happy to help for any questions that come up, but I'm really allergic to declaring something as a bug without asking first if that's maybe intentional...)

Technical background / how stock is currently organized in the database:
- Each stock entry (table `stock`), has an `stock_id`, this id is generated when the entry was first added (normally via purchase)
- Stock entries can get split, this `stock_id` remains the same and groups rows in the `stock` table together
- Stock journal entries (table `stock_log`) have also that `stock_id` and
  - a column `transaction_id` to group all used stock entries by one transaction together (e. g. when you consume an amount of 5 and this transaction used 5 different rows/entries of the `stock` table)
  - a column `correlation_id` to group journal entries together which are dependent on each other (currently for eample used when editing stock entries, there is one journal entry for the values before and one for the values after the edit action)
