### ISSUE TITLE
Feature Request: Barcode scanning

### ISSUE THREAD

**Issue by generalsnipe** [grocy/grocy#153]
Use a barcode (UPC) of the product to quickly add or subtract one unit when scanned. 

The barcode scanner I have is just a HID device that will enter the barcode data, then then press the enter key. My ideal is that when you got grocery shopping, you can scan the item in, and have it add to the inventory. When you use an item, like milk, and the bottle is empty, you scan the bottle before throwing it out, and have it subtract from the current inventory.

**Comment by berrnd** [comment]
Exactly this is possible since grocy was born - a product can have one or multiple barcodes attached, on each product-dropdown a entered barcode is resolved to the corresponding product when leaving the field (which is implicitly done when your scanner sends an `ENTER` or `TAB` after the barcode - I use this multiple times per week).

See also: https://github.com/grocy/grocy#barcode-readers
(And the screenshots at the bottom of README.)
