### ISSUE TITLE
Bug: Tables group by column results (sometimes) in duplicated groups

### ISSUE THREAD

**Issue by wrybind** [grocy/grocy#1534]
Grouping stock entries does not work. Not all items of one category are grouped together. The same category appears multiple times for different entries.

#1419 (solved) listed this bug for sorting by purchase date. 

However, in the current demo the bug exists for all possible groupings. Examples for grouping by purchase date ("2021-07-08" appears two times) and by product group (multiple mentions of "Refrigerated products" and "Sweets"):

![2021-07-18 12_24_32-Window](https://user-images.githubusercontent.com/79023505/126063911-a997cfe1-90ab-493f-90fe-c3f8819e04b2.png)
![2021-07-18 12_24_09-Window](https://user-images.githubusercontent.com/79023505/126063913-d018c6bb-a5f8-4fd7-b4d6-d24bd2654c1f.png)

**Comment by berrnd** [comment]
The mentioned fix was only about the "Last purchased" column, maybe every column needs "special grouping handling", or we need another way in general about that (the [DataTables RowGroup](https://datatables.net/extensions/rowgroup/) extension is used for that), and not every column makes sense to be used as a grouping column...

The purchased date duplication is not reproducible and the [pre-release demo](https://demo-prerelease.grocy.info/stockoverview), nothing has changed since then, so even more strange...

![grafik](https://user-images.githubusercontent.com/2161815/126064507-a0c115de-fa50-4210-8302-d10eee4c9174.png)

**Comment by tjhowse** [comment]
![grocy_product_group_bug](https://user-images.githubusercontent.com/1008081/127600890-a079c10e-7b57-48c6-bc2a-b65e4770aa44.gif)
I came here to report this bug, and found someone had beaten me to it! Here's a gif demonstrating the problem, if that helps.

**Comment by crazyelectron-io** [comment]
An it is not just the grouping, but also the order of the groups (introduced with the 3.1.0 release). We use this grouping in the Shopping list to walk through the Shop while crossing off the items in the correct order.

**Comment by berrnd** [comment]
> but also the order of the groups (introduced with the 3.1.0 release)

There was a fixed order (ascending) for the grouped column applied before, now that's customizable (by clicking the column header, like for any other column). See #1402.

Works from what I can test. Otherwise please describe a reproducible example in a separate issue. This here is about duplicated groups.

**Comment by crazyelectron-io** [comment]
Unfortunately, there is no option in the UI to sort on the **group** column:
![image](https://user-images.githubusercontent.com/58385194/127851405-a5ab108b-400a-4a53-a4be-c82225e0647c.png)
only the other columns. As a result, it is no longer possible to have a shopping list ordered on groups.

**Comment by berrnd** [comment]
Still not the topic here, but as already mentioned above:

> (by clicking the column header, like for any other column)

Show "Product group" column, use the column header to sort it, works.

**Comment by tjhowse** [comment]
Yes, I think that would be a reasonable approach: Sorting for the grouping column should be force-enabled.

**Comment by berrnd** [comment]
> Sorting for the grouping column should be force-enabled.

We had that before, was removed for #1402 - turns out that this was needed for keeping the grouped rows together (which sounds logical, but I haven't had in mind or noticed in https://github.com/grocy/grocy/issues/1402#issuecomment-879276949, sorry). So I simply restored the old behaviour.

**Comment by RobBie1221** [comment]
@berrnd This does not fully fix it for me. I'm seeing issues in the shopping list. I can see here:
https://github.com/grocy/grocy/commit/91d8eaeb7433c0817abf332c1a81dc4a4b9bdc53
That also in `shoppinglist.js` and many more files tags like `orderFixed` has been removed (and not just in `grocy.js`. Placing it back in `shoppinglist.js` fixes it for me on the shopping list page.
