### ISSUE TITLE
Bug: Release notes have incorrect statement on PHP version

### ISSUE THREAD

**Issue by frenck** [grocy/grocy#1537]
The release notes provide an incorrect statement:

![image](https://user-images.githubusercontent.com/195327/126146110-9b82c435-4bc8-42ec-bffd-93ca4c3e8d53.png)

However, the root composer file specifies that it requires PHP 8, see:

https://github.com/grocy/grocy/blob/d871ed7b53bd9fafa1ecc9846b14569bf04d15d8/composer.json#L3

![image](https://user-images.githubusercontent.com/195327/126146228-260804cf-6a5c-4188-bbc2-9a9fde98073f.png)

This means: Either the release notes are incorrect, or the `composer.json` has been accidentally set too strict.

**Comment by frenck** [comment]
This is not a question @berrnd, as I don't need an answer.
Please resolve the wrong labeling for this case.

**Comment by berrnd** [comment]
That's just like before, there we had [`>=7.4` in `composer.json`](https://github.com/grocy/grocy/blob/4a4d9c451f3092fa33104401d69233f5f73d3234/composer.json#L3) and [README mentioned that PHP 7.2 _should_ also be ok](https://github.com/grocy/grocy/tree/v3.0.1#how-to-install).

Was not and is not enforced because of [`"platform-check": false`](https://github.com/grocy/grocy/blob/edfa404ed6b5da4609eee6a664fb5ab54c0e5aa2/composer.json#L31) ([doc ref](https://getcomposer.org/doc/06-config.md#platform-check)).

Means like what's mentioned in README and on the changelog: Feel free to run with whichever runtime you prefer and it works, I personally don't see a point why using old stuff anywhere should be the way to go and only care that it works with PHP 8 from this release on. (However, I can also say that PHP 7.4 is definitely still fine for v3.1.0 since I also tested that.)

> as I don't need an answer.

Sorry for answering then.

**Comment by frenck** [comment]
In that case, it is not working as intended. Just set up a quick test to verify:

```yaml
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires php >=8.0 but your php version (7.4.21) does not satisfy that requirement.
  Problem 2
    - mike42/escpos-php is locked to version v3.0 and an update of this package was not requested.
    - mike42/escpos-php v3.0 requires ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.

```

Thus IMHO still a valid bug report. The release notes state support for PHP8, while currently it is set to be required in the composer.json, thus a bug or incorrect release notes. (As shown with the test above).

**Comment by frenck** [comment]
Whoa, that is composer being false about its problem reporting when multiple problems are present.

So, it reports problem 1 because of problem 2. However, problem 1 is invalid reported.

I'll report this bug upstream with composer 👍

**Comment by berrnd** [comment]
Ok. 👍

`"platform-check": false` is the check when running the app, if you install the dependencies manually (the [release ZIP](https://releases.grocy.info/latest) includes them so no need to run `composer` (and `yarn`) at all when using that) you have to use [` --ignore-platform-req=php`](https://getcomposer.org/doc/03-cli.md#install-i) to ignore that the same way.

If not impossible (for me not a problem on any platform), I would highly recommend using PHP 8 (makes some pages also noticable faster).

**Comment by frenck** [comment]
- I don't want to use the release zip, as there is no guarantee of the contents match the actual tag in the GitHub repository, additionally, the requirements in that package do not have to match or fit my environment, so that is dangerous.
- `--ignore-platform-req=php`: No thanks, IMHO that is bad practice and should not be used.
