### ISSUE TITLE
Unable to run grocy: PHP module 'intl' not installed, but required.

### ISSUE THREAD

**Issue by tfont** [grocy/grocy#1543]
Happened after updating.

**Comment by berrnd** [comment]
Yes, this PHP extension is required, so no real suprise that it doesn't work without that.

Also already answered in https://github.com/grocy/grocy/issues/1539#issuecomment-883397281 - would be great if you check existing issues here (or simply the changelog) first before reporting.

This here is the issue tracker for reproducible problems, please use the [subreddit](https://www.reddit.com/r/grocy) for general help like also mentioned on the issue template and in README.

You also posted this in grocy/grocy-desktop#29 (the purpose of cross posting "issues" without further details/references is maybe beyond my understanding, but ok) - so have you grocy installed manually or do you run it by using grocy-desktop? In grocy-desktop a accordingly configured PHP runtime, including the `intl` extension, is definitely included.

**Comment by tfont** [comment]
This is a poor response and is indeed a bug.

I will update this in the 'desktop' repo as the error takes place from the desktop version.

**Comment by berrnd** [comment]
> the error takes place from the desktop version.

Then this is simply the wrong repo.

> This is a poor response and is indeed a bug.

Sorry for answering, will consider not answering at all to such reports (with missing details / reproducibility) in the future. mainly echoing the same amount of effort you bring into it.

This is most likely not something broken or missing in grocy-desktop, since the `intl` extension is definitely included and enabled (check the included PHP runtime; where to find it is noted in README) - more a specific problem with your installation/environment. I'm most of the time happy to help for that as well, but not in this way in this here is the wrong place.

Proof/source: Many users that already updated successfully without problems.
