### ISSUE TITLE
Bug: Barcodes are returned as integers in API call

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#1564]
By running GET `api/objects/product_barcodes`, the barcode values are returned as int. In previous versions it was a string however, which is a breaking change. The output will be a string, if any non numeric characters are included in the barcode, which is unpredictable behaviour for an API call.

This also means that barcodes with leading zeros will be incorrectly transmitted by the API call: The barcode `000123` would be correctly displayed in the Grocy menu, but the API call would return `123`.

**Comment by berrnd** [comment]
That numbers are now returned as numbers was noted in the [v3.1.0 changelog](https://grocy.info/changelog#v3.1.0):

> ### API improvements/fixes
> > ❗ Numbers are now returned as numbers (so technically without quotes around them, were strings for nearly all endpoints before - should practically be no real difference)

Was generically done by [`json_encode`'s `JSON_NUMERIC_JSON`](https://www.php.net/manual/de/json.constants.php#constant.json-numeric-check), of course that doesn't fit for barcodes...

**Comment by MrJohnZoidberg** [comment]
Maybe undo this step and perform numeric conversions for each wanted key in a response would be the best way to solve the issue?

I can't find any workaround which would work with the JSON_NUMERIC_CHECK together in this case, because you use the json_encode in a very general method (I think it is ApiResponse).

And below [this comment](https://stackoverflow.com/a/6608413) and in the [php user contributed notes here](https://www.php.net/manual/en/function.json-encode.php#106641) people recommend to not use the way to convert all things which look like numbers to numbers.

But I know that doing the conversion manually for every number (without barcodes) would be hard work...

**Comment by berrnd** [comment]
I've tried some approaches to solve this (for example having a list of numeric field names + generically iterating over the API response and setting the type based on that) without success so far.

So definitely was not a good idea to do this that way and probably needs to be undone for now. Shit happens.

That everything retrieved from the database is neither SQLite's fault, nor one of the ORM used ([LessQL](https://github.com/morris/lessql)) - it's PDO.

And it seems that just that was now finally implemented (15 year old feature request) for PHP 8.1 (haven't tested it so far):
https://bugs.php.net/bug.php?id=38334
https://github.com/php/php-src/commit/438b025a28cda2935613af412fc13702883dd3a2

<details>
<summary>Off-topic:</summary>
What me brought to doing this was just the moaning of someone that grocy is so fkn bad in any kind, and one of the "arguments" was that a not strictly typed API is the worst thing you could have.
JSON_NUMERIC_CHECK looked at a first glance to exactly "fix" that.
I have personally absolutely no problem (for this project) about being lazy about data types, it's sometimes even fun.
So I need to learn to ignore those type of people better (unfortunately this seem to get more the bigger the community around grocy gets, but that's the world I think), since that even reduces my desire and fun to work on this project at all lately - so sorry for that.
</details>

**Comment by berrnd** [comment]
//CC @supergeorg, since I think you've changed some or a lot things in [Grocy-SwiftUI](https://github.com/supergeorg/Grocy-SwiftUI) related to API field type changes introduced in v3.1.0 (this change has been reverted due to the problem described above, any field is technically a string now again, just like before - sorry for the inconvenience).

**Comment by supergeorg** [comment]
> //CC @supergeorg, since I think you've changed some or a lot things in [Grocy-SwiftUI](https://github.com/supergeorg/Grocy-SwiftUI) related to API field type changes introduced in v3.1.0 (this change has been reverted due to the problem described above, any field is technically a string now again, just like before - sorry for the inconvenience).

Personally, I like the right data type for returns (e.g. int for int values etc) better. I will probably add a parsing for the values, since using the right data types really simplifies the code (no conversions are needed when processing data). It would be nice if a properly working solution with the correct data types instead of strings will be released sometimes, but for now it is ok. I will release an update in time with the new Grocy Version.

PS: the most tricky part was that empty fields didn't display null as they should, but rather an empty string, while the expected data type was a number.

**Comment by berrnd** [comment]
A quick heads up on this:

As mentioned above, PHP 8.1 now finally provides returning native data types in PDO SQLite.

The next release will be a major version bump and will then (again) contain this (and at least one more breaking API change and will require PHP 8.1 - see the [preview changelog](https://grocy.info/changelog#preview)).
