### ISSUE TITLE
Bug: iCal Calendar not working -> GET /calendar/ical returns error 500

### ISSUE THREAD

**Issue by superbreadi** [grocy/grocy#1569]
Error when opening iCal: https://en.demo.grocy.info/api/calendar/ical?secret=TJ7htk891LJaELxKrLqkKgzQPtwIOLWqALMrQ3CJRfbzOLob8Y

This only happens since grocy 3.1.0 when chores with interval have the option "**Track date only**" set to true.

`{"error_message":"Eluceo\\iCal\\Domain\\ValueObject\\PointInTime::__construct(): Argument #1 ($dateTime) must be of type ?DateTimeInterface, bool given, called in \/var\/www\/demo.grocy.info\/controllers\/CalendarApiController.php on line 33","error_details":{"stack_trace":"#0 \/var\/www\/demo.grocy.info\/controllers\/CalendarApiController.php(33): Eluceo\\iCal\\Domain\\ValueObject\\PointInTime->__construct()\n#1 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(43): Grocy\\Controllers\\CalendarApiController->Ical()\n#2 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(384): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#3 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Slim\\Routing\\Route->handle()\n#4 \/var\/www\/demo.grocy.info\/middleware\/JsonMiddleware.php(13): Slim\\MiddlewareDispatcher->handle()\n#5 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(209): Grocy\\Middleware\\JsonMiddleware->__invoke()\n#6 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#7 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(341): Slim\\MiddlewareDispatcher->handle()\n#8 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Routing\/RouteRunner.php(84): Slim\\Routing\\Route->run()\n#9 \/var\/www\/demo.grocy.info\/middleware\/AuthMiddleware.php(48): Slim\\Routing\\RouteRunner->handle()\n#10 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\AuthMiddleware->__invoke()\n#11 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php(59): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#12 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\RoutingMiddleware->process()\n#13 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php(107): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#14 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process()\n#15 \/var\/www\/demo.grocy.info\/middleware\/CorsMiddleware.php(30): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#16 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\CorsMiddleware->__invoke()\n#17 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#18 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/App.php(215): Slim\\MiddlewareDispatcher->handle()\n#19 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/App.php(199): Slim\\App->handle()\n#20 \/var\/www\/demo.grocy.info\/app.php(106): Slim\\App->run()\n#21 \/var\/www\/demo.grocy.info\/public\/index.php(45): require_once('...')\n#22 {main}","file":"\/var\/www\/demo.grocy.info\/vendor\/eluceo\/ical\/src\/Domain\/ValueObject\/PointInTime.php","line":26}}`

**Comment by berrnd** [comment]
That's already reported in #1547, also already fixed, but not yet released.

Can also be easily verified by trying it on the [pre-release demo](https://demo-prerelease.grocy.info/), like mentioned on the issue template, or checking the [preview-changelog](https://grocy.info/changelog#preview).

**Comment by akoshpinter** [comment]
Hi,

I hope it is not a problem that I write on this closed issue, but I get a very similar error (also reproducible on demo instance), when I create a Task without a due date. 

`{"error_message":"Eluceo\\iCal\\Domain\\ValueObject\\PointInTime::__construct(): Argument #1 ($dateTime) must be of type ?DateTimeInterface, bool given, called in \/var\/www\/demo.grocy.info\/controllers\/CalendarApiController.php on line 43","error_details":{"stack_trace":"#0 \/var\/www\/demo.grocy.info\/controllers\/CalendarApiController.php(43): Eluceo\\iCal\\Domain\\ValueObject\\PointInTime->__construct()\n#1 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(43): Grocy\\Controllers\\CalendarApiController->Ical()\n#2 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(384): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#3 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Slim\\Routing\\Route->handle()\n#4 \/var\/www\/demo.grocy.info\/middleware\/JsonMiddleware.php(13): Slim\\MiddlewareDispatcher->handle()\n#5 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(209): Grocy\\Middleware\\JsonMiddleware->__invoke()\n#6 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#7 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(341): Slim\\MiddlewareDispatcher->handle()\n#8 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Routing\/RouteRunner.php(84): Slim\\Routing\\Route->run()\n#9 \/var\/www\/demo.grocy.info\/middleware\/AuthMiddleware.php(48): Slim\\Routing\\RouteRunner->handle()\n#10 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\AuthMiddleware->__invoke()\n#11 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php(59): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#12 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\RoutingMiddleware->process()\n#13 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php(107): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#14 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process()\n#15 \/var\/www\/demo.grocy.info\/middleware\/CorsMiddleware.php(30): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#16 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\CorsMiddleware->__invoke()\n#17 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#18 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/App.php(215): Slim\\MiddlewareDispatcher->handle()\n#19 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/App.php(199): Slim\\App->handle()\n#20 \/var\/www\/demo.grocy.info\/app.php(106): Slim\\App->run()\n#21 \/var\/www\/demo.grocy.info\/public\/index.php(45): require_once('...')\n#22 {main}","file":"\/var\/www\/demo.grocy.info\/vendor\/eluceo\/ical\/src\/Domain\/ValueObject\/PointInTime.php","line":26}}`

I had problems on my local instance also with Batteries without a next date and stock best before expiration date, but I am unable to reproduce it on the demo server. 

I fixed it locally for the Batteries and Stock by adding the following lines in the CalendarService.php to not include those in the export because I figured out that the entries are not null and the null check in CalendarApiController.php:29 does not work:
`  if (str_starts_with($currentStockEntry->best_before_date, "2999-12-31"))
    {
      continue;
    }
`
I know this is not the ideal solution, so I didn't create a PR. But I hope it is helping to debug the problem. And this is the error message for them:
`{"error_message":"Epoch doesn't fit in a PHP integer","error_details":{"stack_trace":"#0 \/app\/grocy\/vendor\/eluceo\/ical\/src\/Domain\/Entity\/TimeZone.php(46): DateTimeImmutable->getTimestamp()\n#1 \/app\/grocy\/controllers\/CalendarApiController.php(77): Eluceo\\iCal\\Domain\\Entity\\TimeZone::createFromPhpDateTimeZone()\n#2 \/app\/grocy\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(43): Grocy\\Controllers\\CalendarApiController->Ical()\n#3 \/app\/grocy\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(384): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#4 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Slim\\Routing\\Route->handle()\n#5 \/app\/grocy\/middleware\/JsonMiddleware.php(13): Slim\\MiddlewareDispatcher->handle()\n#6 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(209): Grocy\\Middleware\\JsonMiddleware->__invoke()\n#7 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#8 \/app\/grocy\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(341): Slim\\MiddlewareDispatcher->handle()\n#9 \/app\/grocy\/vendor\/slim\/slim\/Slim\/Routing\/RouteRunner.php(84): Slim\\Routing\\Route->run()\n#10 \/app\/grocy\/middleware\/LocaleMiddleware.php(16): Slim\\Routing\\RouteRunner->handle()\n#11 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\LocaleMiddleware->__invoke()\n#12 \/app\/grocy\/middleware\/AuthMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#13 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\AuthMiddleware->__invoke()\n#14 \/app\/grocy\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php(59): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#15 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\RoutingMiddleware->process()\n#16 \/app\/grocy\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php(107): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#17 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process()\n#18 \/app\/grocy\/middleware\/CorsMiddleware.php(30): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#19 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\CorsMiddleware->__invoke()\n#20 \/app\/grocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#21 \/app\/grocy\/vendor\/slim\/slim\/Slim\/App.php(215): Slim\\MiddlewareDispatcher->handle()\n#22 \/app\/grocy\/vendor\/slim\/slim\/Slim\/App.php(199): Slim\\App->handle()\n#23 \/app\/grocy\/app.php(106): Slim\\App->run()\n#24 \/app\/grocy\/public\/index.php(45): require_once('...')\n#25 {main}","file":"\/app\/grocy\/vendor\/eluceo\/ical\/src\/Domain\/Entity\/TimeZone.php","line":46}}`

**Comment by berrnd** [comment]
> I hope it is not a problem that I write on this closed issue, but I get a very similar error (also reproducible on a [demo instance](https://test-ssrdgi8ee9r4tlmfnhl8n.demo.grocy.info/api/calendar/ical?secret=ltZnk6wuIpFL4MniGaS3RimdCwwVMCMd7pk2jjzwgiMQf8cTF6)), when I create a Task without a due date. I am using latest release 3.1.3 in docker.
>...

Moved to #1745.
