### ISSUE TITLE
Bug: logic flaw

### ISSUE THREAD

**Issue by Shredder5262** [grocy/grocy#1570]
So, Lets say, for example, I have 2 "containers" of orange juice. one is opened and half empty , the other is unopened and full. 

I've added a product for the orange juice container the quantity unit stock is Fl Oz, the default quantity unit purchase is "container, the factor purchase to stock quantity unit is 59...because the container size when purchased is 59 Fl Oz. 

If I add the first container (59 fl oz) and enter it as 1 - Container = 59 Fl Oz  then consume 30 fl oz of that  I'm left with 29 Fl Oz...then I mark those 29 Fl Oz as opened. Working so far. 

NOW, I have a second container that is unopened that i want to add to my inventory, so naturally i would add it in the same way
I go to inventory (because the product already exists) , select the product, enter a new stock amount of 1 container (which is 59 Fl Oz . If i choose 1 container I get a message saying that 30 fl oz's will be added to stock....this is wrong. If the default purchase size is 59 fl OZ and I'm adding a new container to my existing inventory of 29 Fl Oz.  It should add another 59 fl oz giving me a total stock of 88 Fl Oz....not equal a total of 59 Fl Oz. So then when i consume, and select the stock amount, I would subtract the consumption from a specific stock and subtract it from the already opened container. 
In it's current state this does not add up and you would never be able to input more than one quantity of a product.

**Comment by berrnd** [comment]
First: "Opened" is tracked by the products QU stock, so if you want to track opened containers, the only way to do this is to have Orange Juice in stock by containers.

Second: Very hard to read, a practical example makes it so much easier to understand - I took the time and created a demo instance (like also mentioned on the issue template):
Product: https://test-j930vx1t3ucq794x8fiyyl.demo-prerelease.grocy.info/product/27

> so naturally i would add it in the same way I go to inventory

Since I don't know what nature has thought for stock management, let's clarify what grocy has for it:

- [/purchase](https://test-j930vx1t3ucq794x8fiyyl.demo-prerelease.grocy.info/purchase) is to add things, the amount entered there is added to stock
- [/consume](https://test-j930vx1t3ucq794x8fiyyl.demo-prerelease.grocy.info/consume) is to remove things, the amount there is removed from stock
- [/inventory](https://test-j930vx1t3ucq794x8fiyyl.demo-prerelease.grocy.info/inventory) is to add or remove things, you enter the current amount you have in stock (so used to check/correct the current stock amount if it's wrong)

Based on that and currently having `29 Fl Oz` of `Orange Juice` in stock by the example above:

> select the product, enter a new stock amount of 1 container (which is 59 Fl Oz . If i choose 1 container I get a message saying that 30 fl oz's will be added to stock....this is wrong

29 Fl Oz are in stock, you say 1 container (which equals 59 Fl Oz should be now in stock in reality), means 30 (59 minus 29) Fl Oz need to be added to fulfill that. My math confirms that.

> It should add another 59 fl oz giving me a total stock of 88 Fl Oz

If you use /purchase instead of /inventory then it surprisingly exactly does that.

Like [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), the better place for general questions is the [subreddit](https://www.reddit.com/r/grocy).

I'm most of the time more than happy to help for anything, but I'm really allergic to declaring something as a bug before simply trying things and not asking.
