### ISSUE TITLE
be able to see products with zero minimum stock

### ISSUE THREAD

**Issue by nuovo10** [grocy/grocy#1576]
enable in the option "shopping list", to be able to filter by product group to see which products I have with a minimum of zero stock (products that are purchased sporadically) and to be able to add them to the shopping list.

Another option would be within "manage product data" - >> "products", to be able to add them to the shopping list.

**Comment by berrnd** [comment]
All products with a min. stock amount > 0 and currently not in stock products are shown additionally on the stock overview.

All products below the defined min. stock amount can be added to the shopping list with one click ("Add products that are below defined min. stock amount"-button on the shopping lists page).

So showing all products on the stock overview page or adding all out-of-stock ones to the shopping list would basically make the min. stock amount obsolete, so what's the point? You can already manually add things to the shopping list.

**Comment by berrnd** [comment]
> The products with a min. stock amount = 0 are not seen anywhere. 

You answered that yourself, the complete list is the master data list.
The stock overview page only lists what's in-stock or missing, otherwise the better name would be "products overview page" and we could simply use the master data list since there is then no real difference at the end.
Has been already discussed on many places.

> Note. It closes the questions very soon, it seems that it is not open to new suggestions

We have 170 open and 318 already implemented suggestions as of today. So I see, I'm definitely not open to suggestions, thanks for pointing that, would have missed that otherwise.

However, some things are basic design decisions and won't be changed.
What fits you maybe doesn't fit anybody else. This is Open Source, change anything for yourself however it fits best.

**Comment by nuovo10** [comment]
Thanks, I just wanted to propose ideas that I think would improve the application

Unfortunately I don't know how to program

Again thanks. It will be the application that I will use from now on
