### ISSUE TITLE
Feature request: Tooltip / Popup Management

### ISSUE THREAD

**Issue by fnordson** [grocy/grocy#1577]
Could we have a way to turn off popups/tooltips altogether please? 
![tt](https://user-images.githubusercontent.com/5624605/129292079-eb7a0de2-0e1d-4277-8346-1c1325bf5bf5.png)

Those stay just too long, same goes for the confirmation bubbles making mobile use difficult.  
And yeah, they sometimes get stuck up there as seen in screenshot.

After using grocy for longer now, we don't need them at all so a on/off switch would be enough.  
Alternatively: I'm looking for a way to do it myself through code if you could help me out where.

**Comment by berrnd** [comment]
That's known, the root problem is the component used ([Bootstrap](https://getbootstrap.com/docs/4.6/components/tooltips/) / [Popper.js](https://popper.js.org/)).

Tooltips were hidden on touch devices before v3.1.0, since it's even worse there, however, there were a lot requests to show them also there - so I think we never find a conclusion for that topic...

> Alternatively: I'm looking for a way to do it myself through code if you could help me out where.

Easy: Use [custom CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself): Create the file `data/custom_css.html` with the following content:
```html
<style>
.tooltip {
  display: none;
}
</style>
```

**Comment by fnordson** [comment]
Awesome. 
Danke Bernd
