### ISSUE TITLE
Bug: ios app grocy mobile error when connecting to local instance

### ISSUE THREAD

**Issue by herrtschaefer** [grocy/grocy#1593]
I recently installed grocy on my home assistant instance on a linux pc. I created an api key and scanned the QR code with the grocy app. i instantly get an error as seen in the image. I think the same issue came up with the pantry party app.
![grocy_error](https://user-images.githubusercontent.com/23578813/131218953-c28f8e6d-93c4-4656-9ae5-44ba8f6ef6fa.jpeg)

App version
1.1.3 on ios 14.7.1 iphone 12 pro max and on iphone 6s+

grocy instance
Version 3.1.0
Veröffentlicht am 2021-07-16 vor etwa einem Monat

PHP Version 8.0.8
SQLite Version 3.35.5

Home assistant
Core
Version
core-2021.8.8
Neueste Version
core-2021.8.8

Supervisor
Version
supervisor-2021.06.8
Neueste Version
supervisor-2021.06.8
Kanal
stable

**Comment by berrnd** [comment]
This is the repo of grocy itself ("the server" / web app).

So you're totally wrong here.
Grocy Mobile: https://github.com/supergeorg/Grocy-SwiftUI
Home Assistant Add-on: https://github.com/hassio-addons/addon-grocy

Personally not using any of this, but a simple search turns out that external access (I think they call it "Ingress") is currently broken:
hassio-addons/addon-grocy#208
hassio-addons/addon-grocy#209
(But only guessing that this also is the root problem for this here.)

However, definitely not a problem of grocy, interesting how you came to the conclusion to report this as a bug here...

**Comment by herrtschaefer** [comment]
because i thought it might be related to the fact that i cannot see api tokens when logging in via the http://homeassistant_ip:configured_port instead of within Homeassistants sidebar.

**Comment by berrnd** [comment]
> because i thought it might be related to the fact that i cannot see api tokens when logging in via the http://homeassistant_ip:configured_port instead of within Homeassistants sidebar.

And exactly that is mentioned in the two Home Assistant Add-on issues above and additionally also in  hassio-addons/addon-grocy#212.
