### ISSUE TITLE
API: /stock/products/by-barcode does not follow quantity unit sizes

### ISSUE THREAD

**Issue by potatothesparky** [grocy/grocy#1604]
I've been testing out Grocy for implementation at home, but it needs to be easy for the wife acceptance factor.
So I've been testing it out using Barcode Buddy as a way to easily scan products in and out of Grocy.

when scanning items with Barcode Buddy it only adds/consumes the base unit of the product rather than the quantity unit amount that is setup in the barcode.

For example, Milk, with a base unit of 1L, and two barcodes units for 2L bottle and 3L bottle, each scan of either will add/consume 1L and not the amount that was set in the barcode.

Using the Grocy webpage when scanning the barcode the correct amount is added/consumed as expected and this is unique only to the API.

**Comment by berrnd** [comment]
In general the API requires the amount to be posted in the products stock quantity unit (on all endpoints).

A barcode is used to lookup a product, when the barcode also has an amount attached, this is used on the frontend to prefill the corresponding fields. However, you can add any amount using any barcode. That's why the API endpoint `/stock/products/by-barcode/{barcode}/add` also requires an amount (just like `/stock/products/{productId}/add`) - check the example on [`/api`](https://demo.grocy.info/api#/Stock%20%22by-barcode%22/post_stock_products_by_barcode__barcode__add):

![grafik](https://user-images.githubusercontent.com/2161815/132292868-8af5e08b-35d2-4f3f-9a3d-f1ce5f33291d.png)

The "Stock by-barcode" endpoints are basically the same as the "normal" stock endpoints, they just directly take a barcode instead of a product id.

The frontend uses the API for everything and can be used as a reference implementation if there are questions how things are done.
