### ISSUE TITLE
Bug: browser refresh required to show new products

### ISSUE THREAD

**Issue by jon-daemon** [grocy/grocy#1605]
I installed grocy on a webserver that I don't have root access. It's used to serve my websites.
I just downloaded grocy_3.1.1.zip and extracted it on the root folder of a subdomain. I used these settings:
```
Setting('BASE_PATH', '/public/index.php');
Setting('BASE_URL', 'https://mydomain/public');
Setting('DISABLE_URL_REWRITING', true);
```
I couldn't make it to work with enabled URL rewriting. I don't use a subdirectory and I followed the instructions in config.php but it wasn't working with empty BASE_PATH and just a "/" in BASE_URL.

I created an index.php in the root of my subdomain which redirects to /public/index.php. I get a message saying "This page does not exist" and 5 seconds later I get redirected on ```https://mydomain/public/index.php/login``` which is working fine.

The about page gives me these info:
```
Version 3.1.1
Released on 2021-08-21 20 days ago
PHP Version 7.3.30
SQLite Version 3.26.0
```
The problem is that I don't see the changes/additions I make right after I make them. I add a product and I have to refresh the browser to see the new product in the products list.
The most frustrating is that I don't see the newly added products when I try to add them in the shopping list. I can see them if I connect in incognito/private mode. For new products I have to close the browser tab and login again from another incognito/private tab.
Could this be a permissions issue? The data folder has permissions 755 and the grocy.db file has 644.
Is this a cache issue? Is this related to the browser or the server side? How could I fix that?

**Comment by berrnd** [comment]
This is the wrong place for help requests, that's also [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) and on the issue template - obviously you have ignored both.

Help requests go to the [subreddit](https://www.reddit.com/r/grocy), this here is the issue tracker for reproducible problems or feature requests.

If the entered data / new product is saved, then logically it can't be a file permission problem related to the database file, since saving would then never work.

So I guess something about caching, but without some reproducible example I really don't know how to help for anything...
