### ISSUE TITLE
Bug: Wrong price if 'Add decimal separator automatically for price inputs' is activated

### ISSUE THREAD

**Issue by b1n4ryj4n** [grocy/grocy#1608]
Demo: https://test-0gm1r5qocl6j3i7yrgh84g3.demo-prerelease.grocy.info

if 'Add decimal separator automatically for price inputs' is activated the price input act wrong. 
If it is not enabled it works fine.

steps to reproduce:
1. goto Stock settings
2. activate **Add decimal separator automatically for price inputs** and save
3. goto Purchase
4. Select for example **Toast** add an amount and try to add an price with a decimal separator like **1,19** it will change to **1,00**.

expected: price input stays at **1,19**

**Comment by berrnd** [comment]
Sorry, but have you even checked the explanation of the option where exactly that - that the **decimal separator is automatically added** and **you always have to enter the value without it** - is explained?

![grafik](https://user-images.githubusercontent.com/2161815/132867365-44adef0b-6930-427a-828b-176807906d74.png)

If you don't need this / enter the separator manually, I don't know why you should enable this...

And I also don't get how you come to the conclusion that this is a bug, if you maybe think of that this should not add the decimal places automatically if the value already has one, then it would be an enhancement / feature request, but definetly not a bug since it works like it's described.

**Comment by berrnd** [comment]
Was introduced in #1345 (there are also more examples of how it's supposed to be used).

**Comment by b1n4ryj4n** [comment]
Ah ok, then I misunderstood the function and the tooltip. Sry
