### ISSUE TITLE
Feature request: Option to manually set date for first chore due date

### ISSUE THREAD

**Issue by karifritsch** [grocy/grocy#1612]
I lost my database with a HD failure so I'm having to recreate everything.

I have pay rent set for 25th. When I created this chore, it expects the next tracking to be for October, not September.
I also have a chore for washing my sheets every two weeks on Sundays. But, I can't tell it to start on the date where I do laundry. It's currently on the wrong week. 

Seems like chores will only start counting after the initial trigger event happens. Like Sept 25th triggers it to work for October or an upcoming Sunday will start the 2 week timer.

I essentially have to always use dynamic regular to control chores, even if I want it to be weekly. Even without without due date rollover being checked, it doesn't show the chore as overdue on the 26th, it just sets the due date for next month and never becomes red.

**Comment by berrnd** [comment]
> Seems like chores will only start counting after the initial trigger event happens

Correct - what's the problem about simply tracking the chore once "dummy wise" in the past?

Example:
1. New chore to be done on bi-weekly on sundays
  => currently the next estimated tracking time will be 2021-09-26 (in two weeks from today)
2. Track the last execution manually to be done on 2021-09-05 (last week)
  => next estimated tracking will be 2021-09-19 (next week)

**Comment by karifritsch** [comment]
Just tried 2 out and that allowed me to have the weeks set correctly.
I could do this as well for paying rent on the 25th, but it seems like an awkward workaround (and not intuitive to a regular user) when it should know that Sept 25 is an upcoming due date because it fulfills the criteria. But it takes that first trigger as the date to start counting for next estimated tracking rather than as the first due date itself.

**Comment by berrnd** [comment]
Definitely also works (since it's technically not different) for "monthly on 25h"-chores - example:
https://test-52rkhc6w04tp3dq5c0pk4r.demo.grocy.info/choresoverview

> but it seems like an awkward workaround

However you call it - it works, never behaved differently and is only a one time thing per chore - so of course a reasonable  feature request, but very very low priority for me...

**Comment by karifritsch** [comment]
I think biggest request would be for grocy to make weekly/monthly items set
first instance in the future as due date, especially for monthly. That
would solve the problem.
It would set the due date when most users would expect it to. If it sets
due date to this Friday and I really want it next Friday, I know how to
correct it. I don't have to think about it.
That's why I wanted the manual control. Because as it is right now, I
didn't feel like I could control when it would set the first due date.
After all, why wouldn't it set Sept 25 as the next due date?

**Comment by berrnd** [comment]
> After all, why wouldn't it set Sept 25 as the next due date?

Because the current simple rule is:
The next estimated tracking time is based on the last tracking time *and use `today` as the last tracking time, if the chore was never tracked before* ([code ref](https://github.com/grocy/grocy/blob/616e1dd5d7c4539a6a6dd52a825780ac376f92bc/migrations/0124.sql#L36-L60)).

> That's why I wanted the manual control.

You have that already by, I repeat myself, simply tracking the chore once for a past date - maybe not so intuitive (for you), but works.

**Comment by berrnd** [comment]
There is now a new chore option "Start date" which is then used as a schedule starting point when the chore was never tracked before:

![grafik](https://user-images.githubusercontent.com/2161815/153062583-fc1960b8-2f58-4769-bbbe-82e830e81747.png)
