### ISSUE TITLE
Bug: In EUR, value after komma isn't counted 

### ISSUE THREAD

**Issue by KingMark66** [grocy/grocy#1613]
When inserting a purchase in grocy and filling in the price. for example 1.65. The price after the komma isn't included or shown in grocy. 
With 2 pieces in stock, stockvalue is €2, last bought €1,.... The '0.65' isn't shown anywhere.

Any solutions?

**Comment by b1n4ryj4n** [comment]
Look here: https://github.com/grocy/grocy/issues/1608 or here https://github.com/grocy/grocy/issues/1345 it's not a bug its a feature ^^

**Comment by berrnd** [comment]
Correct, double check your [stock settings](https://demo-prerelease.grocy.info/stocksettings) `Decimal places allowed for prices` and `Add decimal separator automatically for price inputs`. The decimal separator itself is based on your browsers locale settings.

Like [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), this is the issue tracker, so for reproducible bugs, this here is more than obviously not a bug (since a [quick look on the demo](https://demo-prerelease.grocy.info/stockentries) shows that each and every stock item has a price with decimals there), so the better place for general questions is the [subreddit](https://www.reddit.com/r/grocy).

**Comment by KingMark66** [comment]
Dear,
Thnx for the reply, but i've tried everything. Automatic on/off, putting ',' or '.'. I either get a 1€ or unknown. On mobile, scanning the barcode and putting in the price there. It's the same. Putting in the price on 'add-on' on HA. It's the same.

**Comment by KingMark66** [comment]
After more testing. The problem is with the mobile app. If I put 'automatic off'. I can fill in the prices as intentend on my PC(HA add-on). But on mobile app it says onknown. Are there settings on the app, i should change? App is in English, add-on in Dutch

**Comment by berrnd** [comment]
There are multiple apps, would be great if you mention which one you're referring to - I personally have no experience with any of them.

> But on mobile app it says onknown

I further guess that this means barcode scanning, just a quick search on [their repo](https://github.com/hassio-addons/addon-grocy) shows that the Add-on still uses grocy v3.1.0 which is affected by #1564 which exactly is about broken barcode lookups.

Still not the right place for help requests...

Simply try to recreate the problem on the demo instance, make a screenvideo or something to make things clear and I'm happy to help (when it's about grocy itself).
