### ISSUE TITLE
Default quantity unit purchase

### ISSUE THREAD

**Issue by grossier** [grocy/grocy#1615]
Hi, I'm quite new to Grocy so maybe there is somewhere this mechanism.
If in the recipe there is, lets say, one egg (which _Default quantity unit purchase_ is pack=12 pieces) and I add it to my shopping list via _Put missing product on shopping list_ then why on my shopping list isn't it one pack of eggs instead of one piece of egg?
Also, is there any way that it will not add 1/12th of a package (because I can't buy 1/12th of a pack), but will round up?

**Comment by berrnd** [comment]
> I'm quite new to Grocy

Then please also have a look at [README which mentions](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) that this is the issue tracker and therefore definitely the wrong place for general help requests (=> [ /r/grocy subreddit](https://www.reddit.com/r/grocy)).

> If in the recipe there is, lets say, one egg (which Default quantity unit purchase is pack=12 pieces) and I add it to my shopping list via Put missing product on shopping list then why on my shopping list isn't it one pack of eggs instead of one piece of egg?  Also, is there any way that it will not add 1/12th of a package (because I can't buy 1/12th of a pack), but will round up?

Because that's simply not done yet (tracked in #1355).

Practical example from my personal real live experience of using grocy:
There are 2 eggs on the grocy shopping list, the store only has packs of 6 or 10: I hardly scratch my head and, after a lot of time but before the store closes, come to the conclusion to pick the pack of 6.
🤪
