### ISSUE TITLE
Bug: Cal Calendar not working - chore -> Dynamic regular or Weekly 

### ISSUE THREAD

**Issue by hanspeter1** [grocy/grocy#1625]
## Expected Behavior
iCal Link is working -> https://< domain >/api/calendar/ical?secret=< secret >

## Current Behavior
Error: "Eluceo\\iCal\\Domain\\ValueObject\\PointInTime::__construct(): Argument #1 ($dateTime) must be of type ?DateTimeInterface, bool given, called in /app/grocy/controllers/CalendarApiController.php on line 33"

## Steps to Reproduce

1. iCal Link is working (No error)
2. Set new chore -> Period type = Dynamic regular or Weekly (if a Day of a Week is not selected) -> Save
3. iCal Link is not working (see Current Behavior)
4. Delete chore -> iCal Link is working

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**Installed:**
On Portainer 2.6.3 with https://github.com/linuxserver/docker-grocy#docker-compose-recommended-click-here-for-more-info

**Comment by berrnd** [comment]
Related to #1547.

Persistent demo instance to reproduce that: https://test-57vvmhiz5472gz7qxo0ewq.demo-prerelease.grocy.info/api/calendar/ical

&nbsp;
> Weekly (if a Day of a Week is not selected)

That's another problem - saving should not not be possible in that case, since "weekly and _no_ day of week" is nonsense and also fails to calculate the next estimated tracking time.
