### ISSUE TITLE
Feature request: Change the Purchase date when entering a purchase

### ISSUE THREAD

**Issue by thesatman** [grocy/grocy#1631]
when registering a purchase the system date is used, and the stock entry can be edited to change the date once the initial purchase is entered. Sometimes yesterdays grocery shopping receipts just have to wait to be registered in Grocy. Maybe for a day or two. It would be helpful if the purchase screen had a purchase date field that can be edited, so you don't have to do in in the Stock entries edit modus.

**Comment by berrnd** [comment]
Already possible, check the stock setting `Show purchased date on purchase and inventory page (otherwise the purchased date defaults to today)`:

https://demo.grocy.info/stocksettings#show_purchased_date_on_purchase

![grafik](https://user-images.githubusercontent.com/2161815/135244031-3e9ad727-58e2-4b8b-ba92-a7d6a586bedd.png)
