### ISSUE TITLE
Bug: Issue scanning barcodes

### ISSUE THREAD

**Issue by StevenJonSmith** [grocy/grocy#1634]
Hi,
Today I configured Grocy via the Linux Server docker image behind a Reverse Proxy with SSL.

When I try to scan a barcode on my Galaxy 20+, via Chrome, the camera opens and it turns on the flash. The icon to control the flash vanishes and the barcode can never be read, no matter what product I test on. I think this is due to the inability to focus the image due to the light reflection I can't disable.

Sometimes it shows a yellow detection square but this doesn't coincide with a read.

**Comment by berrnd** [comment]
Tested it, works here - and that's more than obviously not a bug, more a help/support request for which we have the [subreddit](https://www.reddit.com/r/grocy) (that's also [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) and on the issue template - seem that you successfully missed both).

There is also the setting `FEATURE_FLAG_AUTO_TORCH_ON_WITH_CAMERA` to disable auto enabling of flash light:
https://github.com/grocy/grocy/blob/282168f92ca2980f70e3248d789c3d08f3a4e5ea/config-dist.php#L222

Camera barcode scanning is provided by an external component [ericblade/quagga2](https://github.com/ericblade/quagga2).

In reality, this can't be working that fast compared to a laser barcode scanner (due to focus, lighting, angle, and the rest) and I'm personally 1000 % faster by simply typing/searching for the product on my smartphone...
