### ISSUE TITLE
Bug: Cannot choose desired parent product

### ISSUE THREAD

**Issue by HiranChaudhuri** [grocy/grocy#1640]
I am using Grocy 3.1.2 (dockerized ghcr.io/linuxserver/grocy:latest).

There is a product called "Obst".
There is a product called "Äpfel" with parent "Obst"
There is a product called "Tafeläpfel" with parent "Obst".

I am trying to configure "Tafeläpfel" to have parent "Äpfel", however the dropdown field for parent products never lists that word.
What should be the reason for a product to not be offered as a parent?

**Comment by berrnd** [comment]
Would be great if you can check / provide your example on a private demo instance (also mentioned on the issue template) before declaring something as a bug, since then nobody needs to guess all the other details.

Did that for you, can't reproduce it / works so far:
https://test-9i5dnefmpwc9ldmhmscrt.demo-prerelease.grocy.info

&nbsp;
>  What should be the reason for a product to not be offered as a parent?

The only reason is the product hierarchy level, which is currently limited to 1 (see #1097).

**Comment by berrnd** [comment]
> But this very likely is the root cause for my problem.

Not when the example is exactly how you described it above, since that's 1 level (see the example on the demo instance referenced in my previous comment).

> While digging around I stumble over the master data 'product groups'. What are these?

It's just a kind of "tag" for products, can be used to filter or group them on other pages, nothing more und totally unrelated to a parent/child relation.

But please use the [subreddit](https://www.reddit.com/r/grocy) for general questions, this here is the place for issues and feature requests ([README ref](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests)).

**Comment by HiranChaudhuri** [comment]
I can confirm the above example exactly renders what I have in my database.
Now try to change Tafeläpfel to have the parent Äpfel. I cannot do it since that value is not part of the drop-down, and just entering the value 'Äpfel' will not show an error message but when I reopen the product the parent field is empty.

What I understood so far is that I have on level configured and fail on configuring a second.

**Comment by berrnd** [comment]
So I think that's the third time saying that here, once again:

> Now try to change Tafeläpfel to have the parent Äpfel.

Would result in 2 levels of product hierarchy, currently still not possible, but still tracked in #1097 to extend that.

Obst **_Level 0_**
&nbsp;&nbsp;Äpfel **_Level 1_**
&nbsp;&nbsp;&nbsp;&nbsp;Tafeläpfel **_Level 2 <-- Currently not supported_**
