### ISSUE TITLE
Feature Request: Optionally list out of stock products on the location content sheet

### ISSUE THREAD

**Issue by HiranChaudhuri** [grocy/grocy#1641]
Edit by @berrnd:

**//TODO for this request:**
Make it possible to optionally show out of stock products on the [location content sheet](https://demo-prerelease.grocy.info/locationcontentsheet) (at the product's default location).

---

I am using Grocy 3.1.2 (dockerized ghcr.io/linuxserver/grocy:latest).

When running an inventory, I first go to the stock overview and print the location content sheet.
With that I can efficiently check if the goods that Grocy thinks exist really exist. But whenever I stumble over additional goods that are unknown to grocy (or where grocy thinks the amount is zero for that location) there are no lines on the paper so I have to check manually what to look out for.

Could there be some complete stock goods listing regardless how many products should be on stock?

**Comment by berrnd** [comment]
> Could there be some complete stock goods listing regardless how many products should be on stock?

That's basically the master data products list: https://demo.grocy.info/products

So you want to have each product on the [location content sheet](https://demo-prerelease.grocy.info/locationcontentsheet), regardless of the amount? And at which location, at the  product's default one? And what if the product is currently in stock, but entirely at not the product's default location? I doubt that makes so much sense, at least the location **content** sheet is then no longer a **content** sheet...

Related other feature requests: #1387, #1188

&nbsp;
Practical example how I personally do that (without that thing called paper, since it's 2021 and grocy doesn't run on that architecture 🤪):
- One tab open with the [/stockoverview page](https://demo-prerelease.grocy.info/stockoverview)
  - Filtering by location and using "Stock entries" from the context/more menu as needed
  - Using "Inventory" from the context/more menu there, if an amount doesn't fit reality
- One tab open with the [/inventory page](https://demo-prerelease.grocy.info/inventory) for all those things missing in grocy, but existing in reality

**Comment by HiranChaudhuri** [comment]
I do need paper as my storage in the basement is not equipped with internet access.
It could work however if there were some offline possibility that syncs with grocy when the network becomes available again.
AFAIK patzly/grocy-android is incompatible with current versions of grocy.

So if what I want to have is called "master data products list" I am willing to take it. However that seems not filterable by location, although it allows listing the products with zero quantity. So it seems I'd like to have a mix between 'location content sheet' (listing also products with 0 quantity) or 'master data products', limited to only one storage location.

Looking from that perspective, these lists could all be one single function that simply allows different filters to be applied. Isn't there some API that I could use to query for the products myself?

**Comment by berrnd** [comment]
> However that seems not filterable by location,

Maybe grouping is in alternative workaround (any table can be grouped by any column, check the left top corner eye icon).

> Isn't there some API

Well, "some" API is there, at least that much API, to allow anything what the frontend itself or any community contributed app needs/does ([README ref](https://github.com/grocy/grocy#rest-api), [API overview](https://demo.grocy.info/api)).

And in general you mix things:
A product is a product with a default location.
Stock amount of a product can be at any location, the product's default location is just the default (prefilled for example when using the [/purchase page](https://demo.grocy.info/purchase) to add something).
So when you speak technically about _"these lists could all be one single function"_: No, definitely not.

So let's note for this request (if I now got what you mean, still personally think that doesn't make so much sense, but offline things are not so my thing in general, at least because you always do the work basically twice):

**//TODO for this request:**
Make it possible to optionally show out of stock products on the [location content sheet](https://demo-prerelease.grocy.info/locationcontentsheet) (at the product's default location).

**Comment by berrnd** [comment]
There is now this new checkbox at the top of the page:

![grafik](https://user-images.githubusercontent.com/2161815/161332789-30547252-f397-44dc-a42f-ae6fe5b5654f.png)

When disabled, also out of stock products will be shown at the products default location.
