### ISSUE TITLE
Shopping list,

### ISSUE THREAD

**Issue by DevEDVColin** [grocy/grocy#1657]
IT would bei great If there ist an Option, to Print the list on A5 or A6.

The Shopping list now ist top small for DIN A5 or DIN A6.

**Comment by DevEDVColin** [comment]
Yes thats an Option, but to Print the Shoppinglist in Full wide of the Paper would be much better.... And Not so small

**Comment by berrnd** [comment]
Also that's up to your browser - same example screenvideo above, option "Scale", a similar option is in every browser.

I will personally most likely not invest any time in print stuff optimization. It's 2022, just don't print things, use your smartphone.

**Comment by berrnd** [comment]
Default grocy print options, default (Firefox) browser print settings ("Fit to page width"), normal A4 paper size:

![IMG_20220424_204500](https://user-images.githubusercontent.com/2161815/164991752-df54ffdc-e579-425a-b048-dfefaf3734e6.jpg)

The same, but used 100 % scale instead of "Fit to page width":

![IMG_20220424_204616](https://user-images.githubusercontent.com/2161815/164991764-8d5c5e1a-8d27-406c-9668-15ff6d786a13.jpg)

Don't have a plotter at hand to test poster paper sizes.

Sorry, but I still and once again don't understand the problem.
