### ISSUE TITLE
Bug: adding products, undoing transactions leaves bad product count

### ISSUE THREAD

**Issue by corbolais** [grocy/grocy#1668]
Hi,

1. Just added product A, 2 items (same due date).
2. Realized they're not of same due date after all.
3. Added product A, 1 item, due date 1.
4. Added product A, 1 item, due date 2.
5. Undo transaction of "added product A, 2 items (same due date)".

Resulting product count: 1, the one with due date 2 (IIRC).

Should be: product A, 2 items, 2 due dates.

**Comment by berrnd** [comment]
Please be so kind and either provide the _exact/detailed_ steps (and not only what you roughly remember, since most of the time details are missing) or, even better and mentioned on the issue template, prepare a reproducible example on a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) when reporting something as a bug.

I took the time to do that:

Demo instance: https://test-qo31qaq0zn9m9lykde3kw8.demo-prerelease.grocy.info

Screenvideo of what I did:

https://user-images.githubusercontent.com/2161815/140609042-8961f783-6d8a-494b-9922-479c81d2472e.mp4

=> The result is _product A, 2 items, 2 due dates_, so not reproducible with the steps provided.
