### ISSUE TITLE
Feature request: show stock entries for product on "edit product" page

### ISSUE THREAD

**Issue by corbolais** [grocy/grocy#1670]
Hi,

It would be nice to have an overview of available stock entries while editing a product page. Optimally, this overview even featured some edit functions for those entries.

Thanks.

**Comment by berrnd** [comment]
The product edit page is already the most cluttered one (due to so much options), so this would make it even clearer and more intuitive...

Besides, in reality (at least from my experience using grocy for >4 years), you create a product once and then most probably need to visit its edit page very rarely.

There is also the option for custom JS which can be utilized to customize everything to the very end to fit your likings.
This snippet (for `data/custom_js.html`) does that by simply adding the `/stockentries` page (filtered for the corresponding product) as an `iframe` on the product edit page:
```html
<script>
if (Grocy.CurrentUrlRelative.startsWith("/product/") && Grocy.EditMode == "edit")
{
	$(".row").last().after(" \
	<div class='row'> \
		<div class='col'> \
			<iframe class='embed-responsive' height='450px' src='" + Grocy.BaseUrl + "stockentries?embedded&product=" + Grocy.EditObjectId + "'></iframe> \
		</div> \
	</div>");
}
</script>
```

![grafik](https://user-images.githubusercontent.com/2161815/140611832-a639cb96-4607-4690-a731-48422c7ff97e.png)

**Comment by corbolais** [comment]
> so this would make it even clearer and more intuitive...

Yes, please! :-) 

Seriously, you are right, the page is long. But.. I use it regularly. And at that with a wide screen with lots of white real estate available but a sore hand from having to scroll on end..

I'd much prefer a wider layout making better use of wide screens with the least scrolling available.

Thanks for the custom JS possibility. Great solution. I'd say, a popup with stock entries would be sufficient as well, no further enlarging of the edit page, then.

Thanks again, great stuff!
