### ISSUE TITLE
Feature request: Multiple barcodes per product

### ISSUE THREAD

**Issue by Vic3Q** [grocy/grocy#1674]
I recently deployed my instance of Grocy and I quite like it. I was doing the pantry inventory and came across a possible improvement - could you please add possibility to add multiple barcodes per item? I was scanning the rice packages and had them from two different manufacurers - I had to choose to keep only one barcode. Next time I buy rice, and if it will be different brand I will have to look up the barcode manually or add new product. The weight and type of item is always the same, but since the brand differs, so does the barcode. Having possiblity to add multiple ones would ease the process as no matter what brand I get, Grocy will know that it just has to add amount of particular item.

**Comment by berrnd** [comment]
> I had to choose to keep only one barcode.

Don't know which version you're using or where something like that is enforced, because exactly that is already possible since [v0.4.0](https://grocy.info/changelog#v0.4.0) (released about 4.5 years ago), so quite like since ever.

Product edit page:

![grafik](https://user-images.githubusercontent.com/2161815/140729100-0b947e4e-fade-4134-aa83-10210e443e53.png)

Workflow on purchase/inventory (when entering something unknown in the product input field):


https://user-images.githubusercontent.com/2161815/140729636-eafd973a-9098-4641-ad6f-ba524a10909c.mp4

**Comment by Vic3Q** [comment]
Thank you. I'm using the newest version, localized. Maybe the translation got me confused. Apologies for the trouble.
