### ISSUE TITLE
Feature Request: Add average product price as a column on /stockoverview

### ISSUE THREAD

**Issue by barbax7** [grocy/grocy#1677]
It could be interesting to add a column in Products table where is possible to view the last price (or an average of registered prices).

**Comment by berrnd** [comment]
If, then not the [/products list](https://demo.grocy.info/products), since that's the configuration page/list for products - currently fits more on the [/stockoverview page](https://demo.grocy.info/stockoverview), where the last price is already available as a (hidden by default) column - of course the average price can also be added there.

Beside that:
- The last price is also available as an column on the shopping list
- Last and average price are already visible on the product card
&nbsp;&nbsp;![grafik](https://user-images.githubusercontent.com/2161815/140983550-a04b394e-b9fe-41a4-bb7c-cba93ab30f52.png)

Anything else regarding that is already tracked in #64.

**Comment by barbax7** [comment]
Yes, it is already present in stockoverview
But, let's suppose that we don't have the product in stock, and we want to know what is the last price. How could we get it?

**Comment by berrnd** [comment]
> But, let's suppose that we don't have the product in stock, and we want to know what is the last price. How could we get it?

- The shopping list also has that column
- The productard also has that information

#64 is about stock analysis (not yet done, my personal biggest feature request since ever) and this is analysis - it just doesn't fit on a _master data_ page/list.

However, grocy is customizable to the very end, if it makes sense for you to have that on the products master data list, utilize [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) - here is an example snippet (for `data/custom_js.html`) which makes this happen:
```html
<script>
if (Grocy.ActiveNav == "products")
{
	$("#products-table tbody tr").each(function()
	{
		var productId = $(this).find(".product-delete-button").attr("data-product-id");
		var nameColumn = $(this).find("td").eq(1);

		Grocy.Api.Get("stock/products/" + productId,
			function(productDetails)
			{
				if (productDetails.last_price != null)
				{
					nameColumn.append("<span class='text-muted font-italic'>Last price: " + parseFloat(productDetails.last_price).toLocaleString(undefined, { style: "currency", currency: Grocy.Currency, minimumFractionDigits: Grocy.UserSettings.stock_decimal_places_prices, maximumFractionDigits: Grocy.UserSettings.stock_decimal_places_prices }) + "</span>");
				}
			},
			function(xhr)
			{
				console.error(xhr);
			}
		);
	});
}
</script>
```

![grafik](https://user-images.githubusercontent.com/2161815/140996271-bd29fb4e-bedf-49fe-a389-707af431aec9.png)

**Comment by barbax7** [comment]
Oh perfetct! That is what I want
I've installed grocy with docker, so i'll try to customize
