### ISSUE TITLE
Feature Request: can’t open chore journal for all tasks directly

### ISSUE THREAD

**Issue by ariasuni** [grocy/grocy#1680]
When opening «Chore tracking», the «Chore journal» button is greyed out and can’t be clicked. If I want to see the journal for all tasks, I have to select a chore, open the journal, click the filter button and select All for field Chore.

**Comment by berrnd** [comment]
You named this "Feature Request" and labeled it "bug" - crazy...

> When opening «Chore tracking», the «Chore journal» button is greyed out and can’t be clicked.

The context is the selected chore, if you don't select one, this is intentional, if you select one, you can click the button:

https://user-images.githubusercontent.com/2161815/141202145-a5f86b27-9cd1-4e0f-82a9-7883d21e24a7.mp4

> If I want to see the journal for all tasks, I have to select a chore, open the journal, click the filter button and select All for field Chore.

You can also use the "Journal" button on the top right corner of the [/choresoverview page](https://demo.grocy.info/choresoverview) which does exactly that:

![grafik](https://user-images.githubusercontent.com/2161815/141202340-4100afef-d924-4507-a67f-738cc01871e1.png)

**Comment by ariasuni** [comment]
Ah ok, thanks!
