### ISSUE TITLE
Stock value / average price

### ISSUE THREAD

**Issue by gerardstn** [grocy/grocy#1706]
Even when looking at the demo and trying it out myself for over 1 hour, i can't see how i add the prices in properly.

Take these eggs for example [from the demo](https://en.demo.grocy.info/stockoverview):
<img width="325" alt="Screenshot 2021-12-05 at 13 35 28" src="https://user-images.githubusercontent.com/55765125/144746769-aaf3daa5-6133-429c-8bb9-935ff633d728.png">

$6,20 per egg or 4,39 per egg avg, having 5 eggs means: $21,93? 

so a full package of 10 or 12 is $43,90 or 52,68?

I do hope i am missing something, or doing it wrong. I found this out while adding honey with grams, at first i tried a bottle, but then the prices were still grams, so all of the sudden my inventory was €2000,-.
So then i tried to enter the real price per gram from that store and it returns the following:
<img width="470" alt="Screenshot 2021-12-05 at 13 40 39" src="https://user-images.githubusercontent.com/55765125/144746952-4a04319a-95cc-4b1b-a7ef-350447eff74b.png">
 
 Also my apologies if i am wrong.

**Comment by berrnd** [comment]
The average price is the average price, the last price is the last price, so neither of them can be multiplied as-is with the current stock amount to get the current stock value, since every single stock item could have a different price.

Taking the current demo egg stock entries I can't see anything wrong:

![grafik](https://user-images.githubusercontent.com/2161815/144748314-fe91056a-a2fb-4db2-a89e-598f1e3c7356.png)

Stock value = `6.2 + 4.0575 + 4.4575 + 3.4625 + 3.755` = `21.93`

Average price = `(6.2 + 4.0575 + 4.4575 + 3.4625 + 3.755) / 5` = `4.39`

The price entered on the [/purchase page](https://demo.grocy.info/purchase) is related to the selected unit (internally this will be converted to the value per stock quantity unit since that's the base for all, so rounding differences can happen).

&nbsp;
> I found this out while adding honey with grams, at first i tried a bottle, but then the prices were still grams, so all of the sudden my inventory was €2000,-.

Having a real example is possible by using [persistent demo instances](https://www.reddit.com/r/grocy/comments/jwnk9b), much easier to understand the particular problem by that - I did that for you:
=> https://test-gnncudyigpcgkujw5xhs49.demo.grocy.info

[Honey](https://test-gnncudyigpcgkujw5xhs49.demo.grocy.info/product/27) is purchased in bottles, stored in grams - 1 Bottle = 500 Grams.

Purchased 5 Bottles for 5 USD per Bottle = 2.500 Grams in stock = a stock value of 25 USD = a last and average price of 0.01 USD per Gram.

![grafik](https://user-images.githubusercontent.com/2161815/144748823-6c079c86-6453-4319-8371-5f3cce55ae3c.png)

&nbsp;

> So then i tried to enter the real price per gram from that store and it returns the following:
> <img width="470" alt="Screenshot 2021-12-05 at 13 40 39" src="https://user-images.githubusercontent.com/55765125/144746952-4a04319a-95cc-4b1b-a7ef-350447eff74b.png">

Don't know what's wrong with the error message, the amount of decimal places allowed is up to the [stock setting `Decimal places allowed for prices`](https://demo.grocy.info/stocksettings#group-stock_decimal_places_prices).

Btw. the better place for general usage questions is the [r/grocy subbreddit](https://www.reddit.com/r/grocy), this is the place for bugs and feature requests, both is [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) and on the issue template.

**Comment by gerardstn** [comment]
My appologies, and thank you for your very detailed explanation. Will use the subreddit in the future unless I have an actual bug/feature, and keep up the great work on this application!
