### ISSUE TITLE
Bug: Button to add all week items  from meal plan to  shopping list is not visible

### ISSUE THREAD

**Issue by Dahu88** [grocy/grocy#1708]
Version: 3.1.3

I'm missing the button "Put missing products on shopping list", even if I have several meal planned with missing products from inventory.

On the grocy homepage there's a screen capture that shows it https://grocy.info/img/mealplan-en.png but I didn't found how I can enable it.
On the demo pages it also looks missing https://demo-prerelease.grocy.info/mealplan?start=2021-12-05. But when I add a meal for an empty day, the button appears but it's disabled.

Shouldn't the button be always visible (and enabled  if missing products)

**Comment by berrnd** [comment]
> Shouldn't the button be always visible (and enabled if missing products)

That's the case ([code ref](https://github.com/grocy/grocy/blob/c8c63bea5dcb43554c2e30b2dbb7940112aebe2a/public/viewjs/mealplan.js#L97-L105)).

On the demo there is a timezone mismatch: It shows next week, but starting today (so on Sunday), but the server uses the CET timezone (and a week starts on Monday). That's why it has no single recipe internally for the week displayed (as of now, here, Sunday 11:30 PM CET), that's why the button is missing.

To make time related things work (not only for particularly that), it's currently necessary to use the same timezone and "first day of week" setting on the server (PHP and OS settings) and the client. Should be no problem when all that matches, double check that when you have that problem.

References #214 and #808.

Therefore the demo can't be really a reference for timezone related things. The same applies for any screenshots on the website or anywhere on the internet.
