### ISSUE TITLE
Feature Request: Keep recipes fixed when unit conversions are modified

### ISSUE THREAD

**Issue by djorna** [grocy/grocy#1721]
I found that changing a unit conversion will alter all recipes that are affected by that conversion. This happens when the unity that was used in the recipe is not the default quantity unit for that item (e.g. if a recipe calls for 1 tbsp of salt, but the QU of salt is grams, and you change the tbsp->salt conversion, the recipe will be altered).

It looks like the quantity in the recipe changes to keep the QU of the item constant. However, I think it would make more sense to keep the unit used in the recipe constant instead, since that is usually copied directly from an external source.

**Comment by berrnd** [comment]
Any amount anywhere is stored related to the products stock QU (that's also why the products stock QU can't be changed once the product was in stock).

So when you change the definition about how much Grams a Tablespoon of salt is, of course this will change on any dependent place, since the conversion is a dependency.

In reality, I don't know why a QU conversion should change, unless it was wrong, in which case it would make even less sense to not correct any dependent place.

When you (really) want to have that, exclusively use the products stock QU in recipes or create unique QUs for each dependency relation (I again doubt that this makes sense for reality, at least not for mine).
