### ISSUE TITLE
Add more info to product card (e. g. product location)

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#173]
I'd like to know where a given product is stored when clicking on the product's information, but it doesn't show in the pop-up:

![show_product_location](https://user-images.githubusercontent.com/17844465/54087315-f5659d00-4351-11e9-9fc7-56e6552e511c.PNG)

Of course, you can expect chicken to be in the fridge. But what about other products? :)

**Comment by berrnd** [comment]
I already thought of adding some more infos to the product card (the "Product overview" is the same on all pages where shown).

So:
- Location (the default location of the product, since #124 it's possible to set a different location on purchase)
- Average shelf life
- "Spoil rate" (% of spoiled products in the past)

Do you have any other ideas what information could be useful to be displayed there?

Also relates to #64.

**Comment by hannahswain** [comment]
> "Spoil rate" (% of spoiled products in the past)

That would be so neat to see! 

We just started using Grocy today, so I'm not sure what else could be useful. I'll keep an eye out and will comment if anything else comes to mind.

**Comment by hannahswain** [comment]
The product description would be helpful, too, especially if you could show the first 200 characters and then a read more option!

**Comment by berrnd** [comment]
Everything mentioned above is now added, looks like this:

![2019-04-22_10-13-30](https://user-images.githubusercontent.com/2161815/56490999-6074c880-64e7-11e9-950b-9f295cf8da35.gif)

**Comment by hannahswain** [comment]
That looks awesome - thank you for adding all of that information!
