### ISSUE TITLE
Feature Request: allow consuming stock-id grocycodes to consume the entire amount

### ISSUE THREAD

**Issue by drtconway** [grocy/grocy#1736]
The use case is pretty simple:

I buy some beef mince at the butcher. I asked for a kilo, but the actual amount was, say 1024g.

I add it as a stock entry for the product "Beef Mince - Loose", which is stocked by grams, and print a barcode which I slap on the bag, and stick it in the fridge.

When it comes to use the mince, I'm going to use the whole bag - which is the common case for us.

I scan the barcode with the kitchen barcode scanner.

What happens next?

Well, the current behaviour, which makes perfect sense, but is not what I want, will consume 1 gram from that stock entry. What I really want, is for grocy to consume all 1024g.

You could get approximate behaviour by setting up "loose" quantities like you might a pre-packed product, and for some kinds of products that might work. Eg. make separate products for 500g, 1kg, 1.5kg, or whatever, and just approximate the 1024g to 1kg. 

However, it's a hack, and either you need to make lots of products, or you have to quantise heavily, and you don't have an accurate picture of your stock level.

What I'd like to be able to do is to configure the product so that when I consume a specific stock item (e.g. via the grocy code), grocy defaults the amount to the total amount for that particular stock item. (We tend to buy mince by 1kg increments, so we could probably get away with it for mince, but chicken breasts are another similar example, but they can vary greatly in weight.)

A possible way to implement the feature would be to have a "default consume amount" as part of the product, with a distinguished value that denotes that the default should be the entirety of the specific stock item being consumed ("0" could be used for this purpose). There may be better ways to do it, and if so, I'd love to hear ideas.

The "quick consume amount" almost but not quite does this already, since the quick consume does not use an identified stock item. It doesn't strike me as a good idea to fiddle with that.

I'm pretty keen to get a method to achieve this. We've got the grocerypi, the barcode scanner, and the label printer all sitting on the kitchen bench, but the current semantics for consuming by stock-id grocycodes means that we can't currently get the nice workflow we'd like.

If we can arrive at a good model for doing it, I'm happy to do the implementation work. I forbore to implement and put up a pull request before working out a good model though.

Tom.

**Comment by drtconway** [comment]
A related use case which motivates the idea of a "default consume amount" is flour.

Currently, we just "open" a bag when we open it, and when we dispose of the wrapper we consume it - and we stock it by "pack". However for 10kg bags of flour this means we can't rely on the stocked amount (in kg), when we're going to make a pile of homemade pizzas for a party! The open bag could have 100g or 9.9kg in it!

However, we pretty much always measure it out a cup at a time (185g), so being able to stock it by grams, but have a grocycode to scan which consumes 185g would be pretty nice.

That use case might be too different, but if we can kill 2 birds with 1 stone....

**Comment by berrnd** [comment]
Thanks, of course all that makes totally sense.

You could currently also consume whole stock entries on the [/stockentries](https://demo.grocy.info/stockentries) page.

The technical problem is that there is currently no real relation to the "purchase amount".
When a product is stored in Grams, all amounts anywhere are stored in Grams - using any other unit for entering or displaying just uses the conversion factors to translate the entered/saved amount.

Additionally, stock entries are identified by `Product + Due date + Purchased date + Price + Opened/Not Opened + Location + Store where you bought it`, so multiple "purchases" maybe will get compacted into a single stock entry (probably not practically due to the fields involved, ref #1343 and #1676).

Here is a demo instance where "Beef Mince - Loose" is stored in Grams and multiple purchase transactions with different actual amounts (and different other fields; due to grouping/compacting stock entries otherwise) were done:
https://test-zhxrcbb94oilkljg36py29.demo-prerelease.grocy.info

So when you for example scan the grocycode `grcy:p:27:61d6a6a256ca0` (the stock entry with an amount of 1011 Grams), maybe the solution would be just to also prefill the amount to 1011 Grams (the whole stock entry) on [/consume](https://test-zhxrcbb94oilkljg36py29.demo-prerelease.grocy.info/consume)?

&nbsp;
> When it comes to use the mince, I'm going to use the whole bag - which is the common case for us.

Like any other workaround you mentioned, if you buy minced meat commonly in Packs/Bags and also consume whole Packs, it makes also kind of sense to just store it in Packs (personally also do it like that and doesn't care/track if the Bag contained actually 100 Grams more or less).

**Comment by berrnd** [comment]
> So when you for example scan the grocycode `grcy:p:27:61d6a6a256ca0` (the stock entry with an amount of 1011 Grams), maybe the solution would be just to also prefill the amount to 1011 Grams (the whole stock entry) on [/consume](https://test-zhxrcbb94oilkljg36py29.demo-prerelease.grocy.info/consume)?

That's now added, hope that fits for what you thought of.
