### ISSUE TITLE
Feature Request: Price (history) per quantity unit purchase

### ISSUE THREAD

**Issue by RaitaroH** [grocy/grocy#1743]
Hello, thank you a lot for the software, much appreciated. 

I think it would be useful to be able to show price per quantity unit purchase in addition to per QU stock. For example inside Stock entries page, Product overview etc.
This is useful for me when it comes to recipes. So for example, I buy one pack of butter for $D which is then converted to N grams. In recipes I use grams, but obviously the price per grams is hard to judge as a human; being able to see the price (in tables and history) per QU purchase (so for the pack of butter) would be easier to appreciate price fluctuations.

Thank you in advance and sorry if anyone posted a similar issue; I didn't find it.

**Comment by bababash** [comment]
This would be really useful for tracking costs of recipes!

**Comment by berrnd** [comment]
The following is now done regarding that - changelog excerpt:

> - Product card, stock overiew and stock entries page optimizations regarding displaying prices:
>    - Prices are now shown per default purchase quantity unit, instead of per stock QU and when clicking/hovering, a tooltip shows the price per stock QU
>    - The price history chart is now based on the value per purchase QU, instead of per stock QU

![grafik](https://user-images.githubusercontent.com/2161815/161390732-e1342fc9-4b08-4927-ad47-a2ab92430444.png)

![grafik](https://user-images.githubusercontent.com/2161815/161390704-846dbf17-a8f5-4700-8b76-2492b8b5fb3c.png)

Hope that fits.

**Comment by berrnd** [comment]
Just as a follow-up on this: There is now a separate QU for displaying prices (ref #2225) - changelog excerpt:

- _New product option "Quantity unit for prices"_
  - _Prices are now shown related to this quantity unit (instead of per "Default quantity unit purchase") on the product card, price history chart, stock overiew and stock entries page_
  - _Defaults to the product's "Default quantity unit purchase" (so no changed behavior when not configured)_
