### ISSUE TITLE
Allow linking quantity units for related measurements

### ISSUE THREAD

**Issue by Thndr** [grocy/grocy#177]
For common measurement units that have multiple names for different amounts it would be nice to be able to use them for recipes rather than making a new product entry for the smaller amount of the same product if the larger unit product is already measured in a compatible unit.

Eg: I have 1 gallon of water, but I only want to use 1 cup.
At the moment the only solutions would be:
1)I could calculate the math and do all the work myself to determine the new stock amount//the amount of stock needed for 1 cup. This is just too much work really.
2)I could create a smaller unit and then only really track the larger unit for resupply needs. This is less work than the first solution, but still less than ideal.

A third solution could be
3)I create multiple measurement units, then link them via a ratio. 8 oz to a cup, 2 cups to a pint, 2 pints to a quart, 4 quarts to a gallon.

If the ratios also linked between all of the non-directly linked units that would ensure that each unit is exactly that amount in the smaller units. (link 8oz to 1 cup, 1 gallon is read as 128oz even though it was only initially linked to quarts)

The ability to use sub-units of larger unit stock would make upkeep a lot easier for the end-user

**Comment by berrnd** [comment]
Great idea, your third idea would be the way to go, I think.

From UI side maybe just something like (example for unit "Litre"):
New option "This is the same as" in the unit edit screen.
Below a table where rows can be added:

| Factor        | Unit           | 
| ------------- |:-------------:|
| 1000      | Milliliters |
| 3,52      | Cup      |
| 0,23 | Gallons      |

All linked units should then be changeable at any place a unit is displayed, doing the calculations on change. But I would prefer still to have only one unit per product for everything not on the shopping list, and one different unit for purchase only (as of now). Doing the caluculations only for displaying the amount in the different unit...

**Comment by mathieugfortin** [comment]
I'd include the concept of density.  Some recipe talk about cups of chocolate chips, other are by weight.

I think I'd store everything in g, ml, unit and optional g/ml then calculate everything else on the fly according to the output unit

**Comment by mflagler** [comment]
Maybe a separate conversions page for doing the linking between units, and maybe a specification of units being categorized by weight or volume so that on a specific product you could select to convert a unit of weight to a unit of volume since each product would be different and it would prevent someone selecting a conversion of cups to gallons for a product by accident if that conversion was part of the built-in volume conversions.

As for the only link 8oz to 1 cup, 2 cups to 1 pint, 2 pints to 1 quart, and 4 quarts to 1 gallon, I'm just trying to think how you could do this easily without trying to have the code go through every possibility however many layers deep to convert cups to gallons or gallons to oz. I would think it would just be easier to put in all the conversions for each similar unit (all different volumes) and it would be a single lookup for the program then.

**Comment by boardwarp** [comment]
In an Excel spreadsheet I'd built into a rudimentary version of Grocy before knowing about Grocy's existence, I found this was managed fairly easily by having three "conversion ratio" values for each product: One for mass, volume and a single unit. If a product was purchased by mass, its mass ratio would simply be 1 or vice-versa. Not all products had single unit conversion ratios, of course. Each product also had a "primary purchase unit" allocated as either mass or volume, which would tell the spreadsheet which to use for the single unit conversion.

There was also a separate global table for ratios between different measurements of the same property, e.g. litres, cups, and tablespoons, or kilos and pounds, or a bunch of odd ones like cloves of garlic or bunches of bananas for single units.

From here, a recipe could have any unit of a product specified regardless of what purchase unit is configured. If it was a simple conversion like cups to mL it would just use the global table, but anything regarding density would use the product-specific ratios.

**Comment by cyberlink1** [comment]
I just ran into this. Im testing the system for my wife to use and the test recipe I went to put in was for making rice. (2 cups of rice to 2.5 cups of water) We buy water by the gallon and Rice by the lb but use them by the cup. 

After reading through the comments and thinking about it a bit, this is a complex issue. 1lb of rice is 2.5 cups, however 1lb of water is 16 cups. 

Many items will have to have multiple measures. For example we buy Flour by the lb, there are 3.5 cups of flour to the lb. Which works for making bread but if I am making a rue Ill use a few tbsps and there are about 16 tbsps of flour to the cup or 58 to the lb. A single conversion rate would not work because if you multiply the number of cups of flour by the number of tbsps it works out to 56 tbsps. The two tbsps being lost in the weight --> volume --> volume conversion. 

The easiest way I can see it working is if you had the user enter the conversion into the recipe. So if you enter a recipe and change the amount to something other than the default. It would prompt the user asking "how many x in a <default amount>?" Using the flour example, changing it from lb to cups in the recipe would prompt asking "how many cups in a lb?" 

The way the recipe entry is currently set up with an amount for inventory and an amount to show is complicated and Ill say right now my wife would not do it. Using rice as the example. 2.5 cups to the lb but the recipe calls for 2 cups. That comes out to something like .8lb for the recipe. If it asks for the conversion rate when entered, you can easily google "how many cups in a lb of rice" and get the answer to enter. Then let the computer do the math.

**Comment by berrnd** [comment]
I started working on this. :)

It's now possible to define unit conversions, what's left is to use them in any place an amount is referenced.

Just what @cyberlink1 mentioned above, I also think it's necessary to have conversion factors per product. But of course it would be annoying to define for example "1 kg is 1000 g" again and again  - so I used a kind of "hybrid" approach:

There are default conversion factors per quantity unit, they can be overriden per product. On the product edit page the default conversion factors for the products stock quantity unit are displayed and also the product specific ones. I hope this will work for you all like that. :)

### Quantity unit edit page:
![grafik](https://user-images.githubusercontent.com/2161815/64923490-8f634200-d7da-11e9-898e-b6676ba0777d.png)


### Conversion edit page:
![grafik](https://user-images.githubusercontent.com/2161815/64923485-81adbc80-d7da-11e9-8b2a-14afd8ad7aea.png)

### Product edit page ("Flour" is in stock in unit "Kilogram"):
![grafik](https://user-images.githubusercontent.com/2161815/64923513-cfc2c000-d7da-11e9-97fc-6acfa8258a87.png)

**Comment by berrnd** [comment]
This is now finished! :)

But I decided to only enable picking any product related unit only for recipe ingredients for now, the initial request here was about recipes - let's see if everything is working well, then maybe expand to any place an amount can be entered later...

Demo recipe is "Sandwiches", where cheese is in stock in packs and the recipe needs 2 slices:
https://demo-prerelease.grocy.info/recipe/3/pos/9
https://demo-prerelease.grocy.info/product/10
