### ISSUE TITLE
Bug: Management of deletion of Quantity Units

### ISSUE THREAD

**Issue by Chacsam** [grocy/grocy#1770]
When deleting a quantity unit, several data consistency issues are created:
 1) Products who had that QU as Stock QU cannot be assigned any new Stock QU anymore (after purchase)
 2) Conversions using that QU still remain even after deletion 
All examples have been reproduced in https://test-77jynfwutdas5ixctz26gk.demo.grocy.info

Steps to reproduce:
1) Create a QU (in my case Centiliter, cl)
2) Create some conversions like 100 cl = 1 liter
3) Create a product based on that QU (https://test-77jynfwutdas5ixctz26gk.demo.grocy.info/product/27)
4) Purchase that product
5) Delete the initial QU

Product 27 cannot be assigned any new QU anymore (even though it was possible to delete the QU, that might be the 'quick solution')
Product 28 which has been created before deleting the QU (between step 4 & 5) still displays conversion from its QU to blank

Even after deleting the QU, that conversion to blank appears in newly created products (eg product 29)

Even after manually deleting the conversion from the remaining QU (in this case deleting the conversion from the "Liter" screen), the blank conversion remains. (eg. product 30)

On my local instance I also have some issues when encoding recipes (where, for some products, 1 gram is trated as 1 kilogram), but I haven't been able to reproduce.

And for the ones wondering "why would one delete QU's?", in my case it was about simplifying a too detailed initial setup

**Comment by berrnd** [comment]
This is not only related to quantity units, but to any referenced objects - grocy doesn't handle dependencies anywhere (currently and mostly forever, unless rewriting everything, because of how "the core" works).

And what would be the solution beside to simply prevent to delete a anywhere referenced QU?

grocy follows the [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) principal. When you want to simplify your setup, I don't know how grocy should guess what to do when deleting a QU "Liter" which is used in multiple products.

**Comment by Chacsam** [comment]
Sorry, I only wanted to share my observation, I didn't mean anything wrong by it.
Thank you for making and sharing the app
