### ISSUE TITLE
Bug: Modifying a task with no due date loads 1970-01-01 when editing it

### ISSUE THREAD

**Issue by RubenKelevra** [grocy/grocy#1774]
If I open a task to modify it, the due date field will be filled in by 1970-01-01 and when I save it, this due date will be used as valid date.

This seems to be three bugs:

- First an empty due date shouldn't be loaded as 1970-01-01, so it's likely that the data is saved as zero not as null.
- Secondly, 1970-01-01 shouldn't be assumed to be valid. When it's being saved, the data should just be removed
- Thirdly 1970-01-01 shouldn't be assumed valid and it shouldn't be loaded from the database on a view but instead, the field should be left blank.

Also a database job to clean up those zero-unix-timestamps would be nice on the next update. :)

Affected version: 3.1.3
Installed via: HA add-on
Browser: Chromium 98.0.4758.87

**Comment by berrnd** [comment]
> If I open a task to modify it, the due date field will be filled in by 1970-01-01 and when I save it

Only happens when the task had no due date before, any other case works.

---

&nbsp;
> so it's likely that the data is saved as zero not as null

True, happens across the whole codebase, `NULL` and `<empty>` is (should, here not, thanks for finding that) treated the same. If you like `NULL` more, feel free to improve that across the same whole codebase, I won't do that.

> 1970-01-01 shouldn't be assumed to be valid

The format is checked, nothing else - again, not only for tasks.

And no, in that case an empty string is saved, not `1970-01-01` - verifying things a tiny bit before claiming here about what's right or wrong would be kind of great.

**Comment by RubenKelevra** [comment]
> > If I open a task to modify it, the due date field will be filled in by 1970-01-01 and when I save it
> 
> Only happens when the task had no due date before, any other case works.
> 
>  
> 
> > so it's likely that the data is saved as zero not as null
> 
> True, happens across the whole codebase, `NULL` and `<empty>` is (should, here not, thanks for finding that) treated the same. If you like `NULL` more, feel free to improve that across the same whole codebase, I won't do that.

I'm just used to use "None" extensively for sanity checks in python - that's why I brought that up. Not familiar enough with PHP to do any work - sorry!
