### ISSUE TITLE
Bug: Can't add new default conversions in Slovak translation

### ISSUE THREAD

**Issue by kapitan-iglu** [grocy/grocy#1784]
With language switched do Slovak (sk_SK) I'm not able to add new Default Conversion:
- select 'Balenie' unit (Pack)
- click 'Pridať' button (Add)
- in ComboBox 'Na jednotku množstva' (Quantity unit to) select 'Kus' (Piece)
- button 'Uložiť' (Save) stays disabled :(

In default (english) and german languages Save button gets enabled once destination unit is selected (as expected).

Reproducible in [stable demo](https://sk.demo.grocy.info/quantityunit/3) and [pre-relase demo](https://sk.demo-prerelease.grocy.info/quantityunit/3).

**Comment by berrnd** [comment]
The underlying problem is a JS error, this one (captured from the browser console):
```
Uncaught SyntaxError: [sprintf] unexpected placeholder
    y sprintf.js:202
    y sprintf.js:26
    e sprintf.js:30
    format translator.js:202
    __ translator.js:109
    __t grocy.js:247
    <anonymous> quantityunitconversionform.js:182
```

References this localization string:
https://github.com/grocy/grocy/blob/37744822d8975d8c5cc69714de377511e4735cdd/localization/strings.pot#L1235

This is the `sk_SK` translation:
https://github.com/grocy/grocy/blob/37744822d8975d8c5cc69714de377511e4735cdd/localization/sk_SK/strings.po#L1332

So someone mixed up `$` and `%` for the last placeholder when translating that string.

Translations are managed on Transifex, that's this string there:
https://www.transifex.com/grocy/grocy/translate/#sk_SK/strings/182058972

Translations are maintained by the community, but I fixed the problem for that string just now.
