### ISSUE TITLE
Bug: 'returnto=' doesn't work when installed in subdirectory

### ISSUE THREAD

**Issue by kapitan-iglu** [grocy/grocy#1785]
URL parameter `returnto` should not include BASE_PATH. Example:
1. From sidebar choose 'Manage master data' -> 'Quantity units'
1. From top menu select 'Settings' -> 'User settings'
 URL is: `http://IP.ADD.RE.SS/grocy/usersettings?returnto=%2Fgrocy%2Fquantityunits`
1. Choose Language and press 'OK'
1. I get redirected to `http://IP.ADD.RE.SS/grocy/grocy/quantityunits` and "_This page does not exist_" shows up. After 5 seconds I'm redirected to '/stockoverview'.

If I remove `%2Fgrocy` from `returnto` value in step 2 it behaves as expected (in step 4 I'm redirected back to 'Quantity units' page).

My setup in `config.php` is:
```
Setting('BASE_PATH', '/grocy');
Setting('BASE_URL', 'http://<IP.ADD.RE.SS>/grocy');
```

Not reproducible on demo-prerelease because it is not installed in a subdirectory.

**Comment by berrnd** [comment]
Is reproducible, but just to clarify the mentioned technical part;
`BASE_PATH` is not involved in any URL building function, that's only `BASE_URL`.
`BASE_PATH` is needed for [Slim](https://www.slimframework.com/), the used Framework, to make the routing work (ref #568).

Encapsulated in that function for the server side:
https://github.com/grocy/grocy/blob/37744822d8975d8c5cc69714de377511e4735cdd/helpers/UrlManager.php#L21-L31

And that function for the frontend:
https://github.com/grocy/grocy/blob/37744822d8975d8c5cc69714de377511e4735cdd/public/js/grocy.js#L229-L232

The problem is that this is currently not used for the "returnto URLs".
