### ISSUE TITLE
Bug: Cannot edit quantity unit after adding new product to inventory

### ISSUE THREAD

**Issue by geeksrus** [grocy/grocy#1794]
I added new products using the Android Grocy app (version 2.1.0) by scanning barcode and filled out required fields like default location and quantity unit (unit stock and unit purchase).  When I go into Grocy web (version 3.2.0) afterwards to edit the product, I am unable to edit the Quantity unit field under Edit Barcode.  It is grayed out for me.  I am able to go back to the Android app and edit it from there.  With the web version, I'd have to delete the barcode and re-create it again. 

![Screenshot 2022-02-20 083136](https://user-images.githubusercontent.com/16872960/154845543-5c55dece-34b5-4924-9e07-be34c9d29313.jpg)

**Comment by berrnd** [comment]
When the corresponding product has only 1 related unit, it's normal that the quantity unit dropdown of the barcode edit form is disabled, since only product related units are shown there.

Setting a quantity unit for the barcode is up to the API client, so here the app - but none of the community contributed apps are maintained here.

**Comment by berrnd** [comment]
Whatever, I've optimized in https://github.com/grocy/grocy/commit/777fcbae77388b399b95df6da4e5b577bb386545 that the products stock QU is used, when no unit for a barcode is provided.
