### ISSUE TITLE
Bug: Performance issues with large amount of products

### ISSUE THREAD

**Issue by alexrsagen** [grocy/grocy#1808]
Hello, first of all thanks to everyone involved for making such a useful ERP for home use.

I made a script to import the full stock list of a retail store chain using the API and this in itself works fine. However, now that I have ~4000 products in Grocy, the following issues become apparent:
- increased page load times (could be solved by not loading all product data on page load, but instead doing an API call when using typeahead inputs and when loading data for datatables, this also allows for implementing neccessary pagination for the datatables)
  - `/products`: 11.96s, 12.01s, 12.08s
  - `/purchase`: 2.98s, 3.00s, 3.70s
  - `/inventory`: 3.02s, 3.03s, 2.99s
- the typeahead function of [@danielfarrell/bootstrap-combobox](https://github.com/danielfarrell/bootstrap-combobox) is extremely slow with such a large amount of items, because it uses the CSS `display` property to show/hide 2-18 DOM elements for every row/product * ~4k products = ~8k-72k DOM elements every time it is opened/closed, requiring a full re-render of all elements by the browser. Modern solutions to this include pagination, infinite scrolling and windowing (windowing works best for this use case). None of these solutions are utilized by the plugin. It would be better to replace this plugin than to lodge an issue, as [the project is abandoned](https://github.com/danielfarrell/bootstrap-combobox/issues/250).
- interacting with the [datatables](https://github.com/DataTables/DataTables) plugin (sorting, hiding/showing groups, changing display settings) is extremely slow with such a large amount of items, but it has a solution to this which is not used by Grocy: pagination

`/consume` seems to be unaffected (735ms, 796 ms, 820 ms), probably because it does not have a typeahead input and as such does not load all products on page load. Though, as a result of this the input on the page requires exact product names or barcodes. Might open a separate issue for this, because typeahead functionality could still be useful (although hopefully with a new plugin, eventually).

Issue #848 seems to be related.

**Comment by berrnd** [comment]
grocy is, and will always be, optimized for home use and thus my focus is on making it snappy for handling common amounts of data for that use case.

Importing 4000 products sounds fancy, but I doubt it makes sense, it's more just bullshit.
Reminds me of the time when someone complained about that everything is slow after feeding a 50 GB recipe data dump into grocy, well...

It's true that the frontend currently doesn't utilize most of what you call "modern solutions", that's the state of the frontend, changing this is kind of a complete rewrite, which won't happen from my side anytime soon. Probably that's also just a different project.

I'm not against speed optimizations in general (ref #1750 about recipes), but only where it makes sense. Having 4000 (enabled/active) products is out of scope for this project.

**Comment by berrnd** [comment]
And just to add about the technical part:

> interacting with the [datatables](https://github.com/DataTables/DataTables) plugin (sorting, hiding/showing groups, changing display settings) is extremely slow with such a large amount of items, but it has a solution to this which is not used by Grocy: pagination

It's entirely not about enabling pagination, it's about that tables are currently DOM sourced, enabling pagination without changing that will change nothing about performance.

> the typeahead function of [@danielfarrell/bootstrap-combobox](https://github.com/danielfarrell/bootstrap-combobox) is extremely slow with such a large amount of items

[@danielfarrell/bootstrap-combobox](https://github.com/danielfarrell/bootstrap-combobox) is not directly used, it's [this fork](https://github.com/berrnd/bootstrap-combobox) - but yes, was not the best decision to use it, I already wanted to replace it by [Select2](https://select2.org/) some time ago, but wasn't finished. However, also that works pretty well with a common amount of products.

> Issue https://github.com/grocy/grocy/issues/848 seems to be related.

Completely unrelated, #848 was about that the backend (API endpoints) was slow, you talk about the frontend. Most API endpoints already have filter and pagination/limit capabilities.

> /consume seems to be unaffected (735ms, 796 ms, 820 ms), probably because it does not have a typeahead input and as such does not load all products on page load

All stock transaction pages (purchase/consume/transfer/inventory) use the exact same product picker, the only difference is that /consume (and /transfer) only loads in-stock products.

**Comment by alexrsagen** [comment]
> It's entirely not about enabling pagination, it's about that tables are currently DOM sourced, enabling pagination without changing that will change nothing about performance.

Yes I am aware of this, agree that both pagination and dynamic loading of data would be necessary to improve performance.

> Completely unrelated, https://github.com/grocy/grocy/issues/848 was about that the backend (API endpoints) was slow, you talk about the frontend. Most API endpoints already have filter and pagination/limit capabilities.

My apologies for the confusion, it seems that [Grocy-SwiftUI](https://github.com/supergeorg/Grocy-SwiftUI) does not use the API pagination features. Thus that issue is indeed unrelated.

Anyway, thanks a lot for taking the time to respond and give feedback.

I will clear out my Grocy database and write a barcode lookup plugin instead, to avoid filling up the database. In the future I might contribute some improvements such as implementing Select2 or improving the datatables usage, we'll see 😄

**Comment by Dinth** [comment]
> Importing 4000 products sounds fancy, but I doubt it makes sense, it's more just bullshit.

Hi @berrnd. We are ordinary family of 3 who was using Grocy for a few years now. Never imported any products, we're just adding what we've bought on our weekly grocery shopping, i would say underutilising Grocy's functionality, because we use it only to track "perishables" (ie. things with expiry date). Yet, at the moment we've got 4000 item types in stock and a master list of over 10000 items. The whole database is 11MB. 
Unfortunately, Grocy is now crawling - i dont know if its actually Grocy what cant cope with the database, or the linuxserver container is not optimised (ls290 is crawling, never versions had zend plugins added and since then they dont work at all with my database), just wanted to say that Grocy/linuxserver-Grocy performance is not some kind of abstract problem of users who imported whole supermarket stock or 50GB recipe data dump, but a problem faced by casual Grocy users who havent done any of those things.

**Comment by Dinth** [comment]
>I don't really get what you want to hear here now - should I take several months off of my life to rewrite this all here to make it work for your 10k products, while maybe not even having fun doing that (and of course for free)?
(...)
>Fortunately my life isn't Grocy and maybe spending more time elsewhere is what I needed anyway, thank you haters.

That's completely not what i meant. I really do appreciate what you've build, Grocy is amazing, visionary piece of software and i love it. The fact that over the last 6-7 years me and missus been adding almost every shopping and consumption to it, is the biggest proof of our dedication i believe.
If you took my posts as "hate", then the only thing i can say is to apologise and i can only blame my bad english for that. I just wanted to i ask you as a developer of Grocy too acknowledge that 4k products in stock (not even in the master list, but just in the current stock), is not b%%t, but a normal pantry of a small, 3 person family with a toddler. 
Waiting 10-15 sec for a product add or consumption time 50x when scanning a shopping, is painful. But you know - it is what it is. As much as i would like, i dont have PHP skills to optimise the code myself and submit a PR/ I cant do much about it, and the only alternative is keeping those 4000 products, together with their expiry, dates in my head. 
But what really upset me before and forced me to post a comment, is not the performance of Grocy itself, but belittling my - reasonably normal - usage as something absurdly high, ridiculous and quoting yourself - "b%%%%t". Not just in this post, but  on a few others in the past, because it is only the op, who reported performance issues over the years. I know that i am actually under-utilising Grocy, it offers much more to what im doing with it, for example product conversions, recipes, etc., but i am not using it because i dont want to bloat the database even more. 
Perhaps - im not a coder myself, but just perhaps - if you would account that 4000 items in stock is not, or at least not always a b%%%%%t, then Grocy would now run faster for you, for me, for bigger families, without any extra effort from you over the years? 

Anyhow, peace man! Really, dont take my posts as an offence or hate..

**Comment by Dinth** [comment]
You know, while i cant do much about PHP code, but i can definitely play around with LS container's config trying to optimise it and maybe contribute.

Firstly, i removed all the mess which accumulated in LS container by backing up /config, removing it, recreating the container and just uploading database and Grocy config. That has improved things actually a lot. Now stock overview takes around 6 seconds to load which is... not bad, like reversed at least 2 years of slowness accumulation. 
Lighthouse - score between 9 and 25.

Then i have tried moving /config to tmpfs. It feels even more snappy, but the gain is smaller than i thought - Lighthouse score 20-45. Im not sure if i will find a safe (and shareable in a persistent way) way of doing it in production though. 

Now, the biggest thing. I want to fix the zend. Basically a while ago, i have asked the LS team to add php-opcache, to match your demo instance config - and they added the relevant files to the image in LS291 afair - but instead of running faster, LS291 and newer run much slower than LS290. Im gonna try to find the problem and fix it.

Last but not least

**Comment by berrnd** [comment]
> Then i have tried moving /config to tmpfs. It feels even more snappy

Sounds a bit like spinning disks are involved, which is more than often the biggest bottleneck of all.

> i have asked the LS team to add php-opcache

From what I can tell, they just added the package without configuring it, so probably relying on defaults whichever they are.

[`opcache.max_accelerated_files`](https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.max-accelerated-files) (the higher, the better) and especially [`opcache.validate_timestamps`](https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.validate-timestamps) (should be `0` / disabled) makes a big difference.

**Comment by Dinth** [comment]
Hi. Just wanted to report that i have upgraded SATA SSD on the server to NVME (just normal one, optane did not work with my server). The difference is MASSIVE. Every single service is much, much faster, but above everything else Grocy is now flying super fast.

LS still havent fixed the broken image unfortunately, so we are stuck with -ls290 which doesnt have opcache. But with NVME drive, caching is not even needed.

**Comment by berrnd** [comment]
> i have upgraded SATA SSD on the server to NVME [...] Every single service is much, much faster

And that's really a surprise? I'm still wondering why in just like every thread about performance at the end it's related to hardware. Of course SSDs are not spinning disks, but NVMe (with affordable disks) is not something we have only since this year and 5x to 15x more throughput (especially for high small file I/O workloads; check how many .php files need to be parsed for every single web request - I guess a couple of hundreds), is, well, notable.
