### ISSUE TITLE
Feature Request: Open ID connect

### ISSUE THREAD

**Issue by dorianim** [grocy/grocy#1834]
Hey there,

I'd love to have support for OIDC, so I can connect grocy to my SSO provider. Any chance of adding this?

Regards,
Dorian

**Comment by berrnd** [comment]
Duplicate-question of #1729.

**Comment by dorianim** [comment]
I don't really think, the issue is fixed, tough. OpenID Connect is the only option in some cases, for example when you want to authenticate against GitHub.

**Comment by berrnd** [comment]
It was a question, so there is no "fix".

grocy ships with LDAP and Reverse-Proxy-Auth options ([config options ref](https://github.com/grocy/grocy/blob/f0db2a77095faa2f8ed02a94dca6aa95f3d68781/config-dist.php#L77-L91)).

No other authentication providers will be built-in, you can add anything you want by implement a middleware based on/extending [`AuthMiddleware`](https://github.com/grocy/grocy/blob/master/middleware/AuthMiddleware.php).

If that's not an option for you, use Reverse-Proxy-Auth and something like [Authelia](https://www.authelia.com/), at least that's what comes up here and on the subreddit often when it's about SSO.

grocy is about #selfhosting and #ownyourdata. So this is generally against that principal and that's why I will not implement something like that. But, as said, everything is possible by the options/possibilities provided.

Single Sign-on is for me also a single point af failure and a "single point of attack", I would personally never use that anywhere.

**Comment by dorianim** [comment]
> It was a question, so there is no "fix".

It was a feature request

> I would personally never use that anywhere.

I work for a non-profit organization with 100+ members. Creating accounts in every individual service is not feasible in this scenario. 

> you can add anything you want by implement a middleware based on/extending [AuthMiddleware](https://github.com/grocy/grocy/blob/master/middleware/AuthMiddleware.php)

Is it possible to alter the login UI like that? And add new http routes to accept the oidc redirect?

**Comment by berrnd** [comment]
It's PHP, it's Open Source - everything is possible.

I haven't said that everything needed is already there, I only said that no specific auth provider, beside LDAP and Reverse-Proxy-Auth (which is able to handle kind of everything else by using [Authelia](https://github.com/authelia/authelia) or [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) or whatever) will be implemented due to the reasons mentioned above.

`AuthMiddleware` currently clearly provides to abstract methods which need to be implement in the derived middleware / auth provider:
- [`ProcessLogin`](https://github.com/grocy/grocy/blob/f0db2a77095faa2f8ed02a94dca6aa95f3d68781/middleware/AuthMiddleware.php#L92), which takes the username/password from the login page and is responsible for validating that
- [`authenticate`](https://github.com/grocy/grocy/blob/f0db2a77095faa2f8ed02a94dca6aa95f3d68781/middleware/AuthMiddleware.php#L99), which is responsible for validating every request

Or just see [LdapAuthMiddleware](https://github.com/grocy/grocy/blob/master/middleware/LdapAuthMiddleware.php) as a reference implementation.

So if it's about the terms "feature request" and "question" I gladly change the label of this to "wontfix/out-of-scope" to make my decision for this project clear.

**Comment by dorianim** [comment]
Ok, I'll use the oauth2 proxy then.
