### ISSUE TITLE
Feature Request: API for (Product) Quantity Units

### ISSUE THREAD

**Issue by jurredejongh** [grocy/grocy#1877]
Heya! I'm currently working on a scanning app that automatically adds products based on the barcode. I've set quantity units for specific barcodes, but when I use the `/stock/products/by-barcode/{barcode}/add` call it doesn't use the QU. I've looked through the code and it appears that this is the (only?) area where no API is used to calculate the units. There also appears to be no API for Quantity Units.

Is it possible to add an API call that gets the Quantity Units for a product? Or for the `/stock/products/by-barcode/{barcode}/add` API to take into account the barcode QU?

**Comment by berrnd** [comment]
> There also appears to be no API for Quantity Units.

That's generally unlikely the case, since the UI uses the API for everything what it does, there is an endpoint for everything. A very easy way to find out which endpoints are used for that is to use e.g. your browsers developer tools and just have a look at what happens.

> Is it possible to add an API call that gets the Quantity Units for a product?

Sure, example, the product has it's stock and default purchase QU - look at the product object, example:
`GET /objects/{entity}/{objectId}`
https://demo-prerelease.grocy.info/api/objects/products/10

Then there are maybe more product specific QU (conversions), example:
`GET /objects/{entity}`
[https://demo-prerelease.grocy.info/api/objects/quantity_unit_conversions?query[]=product_id=10](https://demo-prerelease.grocy.info/api/objects/quantity_unit_conversions?query%5B%5D=product_id%3D10)

> Or for the `/stock/products/by-barcode/{barcode}/add` API to take into account the barcode QU?

Any amount (and price) on any API endpoint is related to the products stock QU.

**Comment by jurredejongh** [comment]
Ah yes of course. I saw `Grocy.QuantityUnitConversionsResolved` and drew conclusions. I've gotten it now, thanks!
