### ISSUE TITLE
navbar shows on macOS

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#189]
The navbar needs to be set to `hidden` on macOS otherwise the scrollbar shows.

```css
ul.navbar-nav {
    overflow: hidden;
}
```

**Comment by berrnd** [comment]
We had this multiple times before and tried a lot of combinations with different browsers, see #15 and the referenced issues there.

Maybe just add this [custom CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself), if this works for you.

**Comment by berrnd** [comment]
I looked into this again - and found no difference with current Chrome/Firefox on Windows and macOS - the scrollbar shows inside the menu container when the window height is smaller than the menu.

![grafik](https://user-images.githubusercontent.com/2161815/55669702-d2f47000-587a-11e9-8dad-79950f57253a.png)

I think this is ok.

The problem in #15 was that the scrollbar showed outside the menu container. Then we removed it as a workaround. Then it was added again in #90 because of problems on touch devices...

So closing this, [custom CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) is still a valid option if you want to changed this for you.
