### ISSUE TITLE
Clarify product field validation hint (purchase/consume/inventory page)

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#192]
When you purchase a product that isn't currently in Grocy, you need to:

1. Create the product
2. Purchase the product

This works, and you can make it go quickly using two different browser windows. To make this more smooth, it would be great to see:

1. Create product > two submit options, "Add" and "Add and purchase" - the "Add and purchase" would send you to the purchase screen and preselect the created product.
2. On the Purchase Product screen, add a link to "Create a product".

The first option here would be lovely, and the second would let you quickly jump back to creating a product if you need to do that.

**Comment by berrnd** [comment]
grocy actually has this since it's birthday: :D

Just enter something unknown in the product field, leave the field (or `TAB`), then this will popup:

![grafik](https://user-images.githubusercontent.com/2161815/54437288-9bd7e680-4734-11e9-9b72-f371d8d164b3.png)

When you click the green button or just press `p`, you will be send to the "create product"-page while prefilling what you entered as the new product name, when you save it, you will get back to the purchase page while prefilling the just created product...

**Comment by hannahswain** [comment]
Oh, very cool!

I hadn't tried it, as the validation was "you need to select a product".  How about this instead:

> Select an existing product, or add a new product by typing the name and then hitting tab.

**Comment by berrnd** [comment]
Sure, I changed the title of this issue to track this here...
