### ISSUE TITLE
Feature Request: Make expiry date not required

### ISSUE THREAD

**Issue by JeffersonBledsoe** [grocy/grocy#1920]
I've got some products that don't have an expiry date, or ones where the expiry date is so far in the future I don't really care about it. Is it possible to make this field not required, or to have an option that says "Doesn't expire"?

**Comment by berrnd** [comment]
> to have an option that says "Doesn't expire"?

Well that's possible since [v1.0.0](https://grocy.info/changelog#v1.0.0), so since a little over 5 years:

- Date input field [shorthand `x`](https://github.com/grocy/grocy#input-shorthands-for-date-fields)
&nbsp;
- Date input field "shortcut checkbox" `Never expires`
  ![grafik](https://user-images.githubusercontent.com/2161815/174129819-926b5f9c-c048-4c6d-afb8-b539c7181739.png)
&nbsp;
- Product `Default due days` option `-1`
  ![grafik](https://user-images.githubusercontent.com/2161815/174129999-cb8ae25c-2c48-4a8b-aa2e-7ce7386a4e97.png)

![grafik](https://user-images.githubusercontent.com/2161815/174130155-ed4793d2-5f09-4e8e-96b4-995b1befacf0.png)
