### ISSUE TITLE
Bug: Barcode gets locked in DB

### ISSUE THREAD

**Issue by tonytonyistony** [grocy/grocy#1928]
Im re-reporting this with proper steps to replicate. From my findings, and Im not sure how I accidentally did this, but if you accidentally try to add a bar code to an item inside the phone app and delete the item in the web portal while still editing the item in the phone app, then hit save in the phone app, the barcode will be saved even though it errors and will no longer be able to be used or deleted

**Grocy App: v3.3.1
Grocy Fdroid: v2.2.1
Fresh Install**

**Steps to reproduce**

NAVTO: Open F-Droid phone app version 2.2.1
NAVTO: Master Data
NAVTO: Products
CLICK: Add
SET  : Name (Item1) 
SET  : Location (any)
SET  : Quantity Unit Stock to "Peice"
SET  : Default Quantity Unit Purchase to "Peice"
CLICK: Save
CLICK: Item1 Product
CLICK: Edit
CLICK: Barcodes
CLICK: Add
CLICK: Barcode icon to open camera
SET  : Scan the barcode for Item1 product
SET  : Amount to 1
CLICK: Save
CLICK: The back arrow
CLICK: Save
NAVTO: Open and login to the Web Portal
NAVTO: Manage master data > Products
CHECK: Make sure Item1 is present
CLICK: Item1 Product in the phone app
CLICK: Edit
CLICK: In the web portal hit Delete for Item1 product
NAVTO: Back to phone
CLICK: Barcodes
CLICK: Plus sign to add a barcode
CLICK: Barcode icon to open camera
SET  : Scan the barcode for Item1 product again
SET  : Amount to 1
CLICK: Save
CLICK: The back arrow
CLICK: Save again and "An Error Occurred" will display in the phone app.
CLICK: The back arrow
CHECK: Item1 is now no longer present
NAVTO: Back to home screen and select Purchase
CLICK: Barcode icon to open camera
SET  : Scan the barcode for Item1 product
CLICK: Create new product
SET  : Name (Item2) 
SET  : Location (any)
SET  : Quantity Unit Stock to "Peice"
SET  : Default Quantity Unit Purchase to "Peice"
CLICK: Save
SET  : Amount to 1
SET  : Never due date
CLICK: Save and "Could not upload barcode" will display in the phone app.
CLICK: The back arrow to return to the home page
NAVTO: Back to the web portal, products page
CLICK: Edit on Item2
CLICK: Add in the barcode section
SET  : The "Barcode" to the barcode number that is located below the actual barcode on the item.
SET  : Amount to 1
CLICK: Save (Error displays)
CLICK: Show technical details
ERROR: ""{\"error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: product_barcodes.barcode\"}""
CLICK: Ok
CLICK: Close
NAVTO: Back to the products page
CLICK: Add
SET  : Name (Item3)
SET  : Location (any)
SET  : Quantity Unit Stock to "Peice"
SET  : Default Quantity Unit Purchase to "Peice"
CLICK: Save & Continue
CLICK: Add in the barcode section
SET  : The "Barcode" to the barcode number that is located below the actual barcode on the item.
SET  : Amount to 1
CLICK: Save (Error displays)
CLICK: Show technical details
ERROR: ""{\"error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: product_barcodes.barcode\"}""
CLICK: Ok
CLICK: Close

**Comment by berrnd** [comment]
This is not the repository of any of the community contributed mobile apps.

**Comment by tonytonyistony** [comment]
This effects the web app as much as it effects the phone app.

But whatever, Im done trying to help. Literally spent an hour or two trying to isolate this issue for you. 

Good luck with your project.

**Comment by berrnd** [comment]
Each and every problem, which was reported with proper reproduction steps, was fixed before each and every release so far.

Of course this here is about the "web app" and therefore only problems reproducible there will be fixed.

Self-quote from https://github.com/grocy/grocy/issues/1926#issuecomment-1170792216
> I did (on the [pre-release demo](https://demo-prerelease.grocy.info)):
> 
>     * Added a new product with barcode `123`
> 
>     * Deleted that product
> 
>     * Added a new product with barcode `123`
>       
>       * => No problem

This it what you basically described and as said there, I can't reprodcue it.

However, thanks for your kind whishes, grocy works for me personally, if it doesn't work for you and you can't solve the problem yourself and think I don't want to - well, then most probably is not the right software for you. Gladly the world has more to offer, or just built the thing which 100 % fits and is bug free yourself - that's what I did.

Mabye the app somehow adds/saves a barcode for a not (longer) existing product. That could result in the that the barcode is not visible anywhere on the web app, but is technically there, hence producing a "duplicate error" when trying to use this same barcode in a second product.

In any case, I would say this is a kind of edge case and very rarelly happens in "production use", mabye more on the initial setup when trying to fiddle with things. It could be resolved easily by using the API or having a look into the database directly and clean things up, but I guess you don't want help regarding that.

**Comment by Forceu** [comment]
Since one of the last updates (I think 3.1?) grocy locks up when adding a barcode to an existing product via the API. Unfortunately I was not able to reproduce the problem, as it seems to be rather random. Maybe this is related to this?

**Comment by berrnd** [comment]
Whatever "locks up" means exactly, nothing was changed in the area of product barcodes recently.

It's technically pretty simple:
- Products are stored in the [`products` table](https://github.com/grocy/grocy/blob/bef261d8696268dc5dcb3c1599373783954f3d84/migrations/0155.sql#L6)
- Product barcodes are stored (`1:n`) in the [`product_barcodes` table](https://github.com/grocy/grocy/blob/bef261d8696268dc5dcb3c1599373783954f3d84/migrations/0103.sql#L12)
- The [index `ix_product_barcodes`](https://github.com/grocy/grocy/blob/bef261d8696268dc5dcb3c1599373783954f3d84/migrations/0128.sql#L17) enforces barcodes to be unique (accross all products)
- The [trigger `cascade_product_removal`](https://github.com/grocy/grocy/blob/bef261d8696268dc5dcb3c1599373783954f3d84/migrations/0183.sql#L10) removes all product specific barcodes when deleting a product
- The ["Generic entity interactions"-API endpoints](https://demo.grocy.info/api#%252FGeneric+entity+interactions) are direct interfaces to those tables (as known and since ever)

&nbsp;
> if you accidentally try to add a bar code to an item inside the phone app and delete the item in the web portal while still editing the item in the phone app, then hit save in the phone app

Like already mentioned, this will most likely produce a `product_barcodes` entry without a corresponding product which will result in having a barcode which is nowhere visible (on the web frontend), but still there.

And yes, this is not prevented, like the 120256 other edge cases. The one who uses the API is responsible for not adding invalid stuff.

Adding a barcode to a product in a companion app (or a separate web frontend session), not saving there and deleting the same product in the meantime via another session / frontend - sorry, so edgy that I will not invest any minute in "fixing" that.

**Comment by berrnd** [comment]
Despite what I've just said - done in a80e048c2d054cb24fdc4a3c263eb75aace9c8a2:
- During migration all barcodes referencing an invalid / not longer existing product will be removed
- It's now not possible to add a barcode referencing an invalid / not existing product
