### ISSUE TITLE
Which product settings to allow product to be marked as open? 

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#193]
I can't get this option to consistently be available - is there a specific setting to use? 

Thanks!

**Comment by berrnd** [comment]
Don't know exactly what you mean...

Each product can be marked as opened.
On the consume page, the grey button "Mark as opened" instead of "OK" or ENTER.
On the stock overview page, there only a fixed amount of 1, so this button is disabled there when the current stock amount is < 1 (can only happen when you enabled "Allow partial units in stock" in the product or when the product has a minum stock amount and is currently not in stock, otherwise the product is not shown on the overview page).

**Comment by hannahswain** [comment]
That clarifies it - thank you for explaining!

**Comment by navirom** [comment]
Sorry to reopen, but the button on the stock overview page actually appears to be disabled when the quantity is less than or equal to one, not just less than. I have a couple items with quantity 1 that I can't mark as open from the overview. 

![image](https://user-images.githubusercontent.com/16004771/54497124-5e01cc00-48b4-11e9-87c4-f10d4dbc71c8.png)

**Comment by berrnd** [comment]
Thanks @navirom, I created a separate issue #197 to track this.
