### ISSUE TITLE
support older SQLite versions

### ISSUE THREAD

**Issue by mokkin** [grocy/grocy#1939]
I tried to install your app on a shared Netcup Hosting. Unfortunately I'm running into:
```
SQLSTATE[HY000]: General error: 1 near "OVER": syntax error
```
After a short investigation the reason seems to be the old SQLite version. Unfortunately most hosting providers won't upgrade the big server for a single user request...
Do you think you can support older SQLite versions? Mine is 3.16.2 for example.

That would be great because grocy is really easy to install on standard webhostings.

**Comment by berrnd** [comment]
> Do you think you can support older SQLite versions?

Definitely not. I will never require bleeding edge stuff, but I also don't want to use never features due to relying on dependency from the stone age.

The currently mentioned minimum [SQLite version 3.27.2](https://www.sqlite.org/releaselog/3_27_2.html) was release 3.5 years agao. If your hosting provider can't support that, mabye it's not the right provider or shared webhosting is the way to go in general.

**Comment by stefan-muc** [comment]
Would it be possible to at least add a version check as you did with #104? It's not good to upgrade a running grocy instance and then face a not working system.

**Comment by berrnd** [comment]
> Edit: Using SQLite 3.22.0 works with grocy 3.2.0 but not with grocy 3.3.0

I don't check which exact SQLite version supports everything needed currently used, but I've raised the minimum version to `3.22.0` in ff056f8d81fbd1e696abf46599e965bffe04ad48.

What's [mentioned in README](https://github.com/grocy/grocy#how-to-install) (currently `3.27.2`, nothing on the bleeding edge, [released Feb. 2019](https://www.sqlite.org/releaselog/3_27_2.html)) is what I use and what's bundled with the PHP version mentioned at the same place (currently `8.0`). I still don't get why it's common (obviously especially in shared hosting environments, which can only mean to avoid that) to use more than outdated runtime stuff.
