### ISSUE TITLE
Feature Request: Using same barcode, Purchase as bulk/container to be converted, Consume as set amount of pieces

### ISSUE THREAD

**Issue by TheMethodicalJosh** [grocy/grocy#1947]
To be honest, This may already be applicable but I can't figure it out. If so, could someone explain how this works?

I would like to be able to use the barcode on a bottle of vitamins to "purchase" or add the inventory in purchase mode as a container "unit" that gets converted to pieces and then when in consume mode, the same barcode would consume the "quick set amount" of pieces instead of trying to consume the entire "container" unit. I can manually change it over to the correct unit when quick scan is used in the app, but that kind of defeats the purpose of the quick scan. If using the grocycode barcode, it seems to consume as the set pieces but it's easier for some objects to just use the barcode already provided on the product.

Sorry if this has been explained somewhere, I haven't been able to find it.

Images will explain the issue hopefully.

![Factor Correct](https://user-images.githubusercontent.com/48694854/179305925-e2b32f1e-ed6f-4889-8e19-f182c8e09267.png)
![Barcode for container correct](https://user-images.githubusercontent.com/48694854/179305934-21b74366-8675-47a4-9a59-9ddbe2543ed0.png)
![Screenshot_2022-07-15-16-27-56-78_ded3d01f237383c8e0209ace216d3455](https://user-images.githubusercontent.com/48694854/179305939-323eec97-f5bb-474e-91b8-14af6650329c.jpg)

**Comment by berrnd** [comment]
- Set the products `Default quantity unit purchase` to `Container`
- Set the products `Quantity unit stock` to `Piece`
- Don't set a `Quantity unit` on the barcode entry
- => It will work

**Comment by carsonbird** [comment]
There are use cases that this doesn't cover. For example, when a product comes in a pack, and the individual items don't have a barcode. For me, I'd want to scan the barcode to purchase the pack (of N pieces), then consume per piece by scanning the barcode in consume mode. This CAN be accomplished by not setting default units in the barcode, and using default unit quantities in the product. But what about when Pack A has 10 pieces, and Pack B of the same product has 20 pieces? That's a barcode-specific quantity.

**Comment by berrnd** [comment]
@carsonbird Duplicate of #1421. Please check existing requests before spamming random other threads, thanks.

**Comment by carsonbird** [comment]
> @carsonbird Duplicate of #1421. Please check existing requests before spamming random other threads, thanks.

@berrnd Hmm, I'm not seeing how this is a duplicate - I think it more closely aligns with this issue, not the one you linked.

In [your example](https://github.com/grocy/grocy/issues/1421#issuecomment-803834127), you suggest creating a unit conversion between the two, but I'm saying that the units are too generic to handle this situation. For example, let's say Product A (cans) is sold in a pack of 8 and a pack of 12. They aren't labeled for individual sale (and don't have a barcode on each product). I can't create a unit conversion for Packs/Cans because the conversion depends on how the product was packaged. Is the conversion 1-to-8 or 1-to-12? 

Let's use Graham crackers as another example. If you're not familiar with them, Graham Crackers come in a Box, which usually contains plastic Bags, which contain 9 crackers (but the US serving size information assumes 8 crackers per bag, oddly enough). The crackers have scoring marks to make them easy to break into halves and quarters.

At Walmart (barcode W), you can buy a large box of Graham Crackers (containing 6 bags of 9 crackers each, 54 crackers total). At Costco (barcode C), you can buy a box of Graham Crackers which contains 4 interior boxes (also barcode C) which each contain 3 Bags of 9 crackers each, 108 crackers total.

Now, here are my assumptions as to how you'd want to enter this into a food tracking system (let's forget about Grocy's current design). The product is Graham Cracker. The base unit would be a single cracker, or a serving (2 crackers), or something like that. You could even say you want the fundamental unit to be a Bag (of 9 crackers) if you eat them by the bag like we do... The issue still stands that we can't create a Box-to-BaseUnit conversion because it depends on the box the barcode is on. That's fine, we can create 2 barcodes which specify that Barcode W contains 6 Bags and Barcode C contains 12 bags. This is great for the purchase flow, but then as soon as I go to scan either barcode to consume a single cracker, it defaults to consuming the quantity (6 or 12) Bags of that barcode - it doesn't look at the fact that the barcodes are for the same Base product (graham cracker) and that Graham Crackers should be consumed by the Cracker, regardless of the quantity associated with the barcode.

Hence, I asked about specifying a separate consume and purchase quantity on each barcode.

Help me understand where I'm wrong, or how I'm misusing Grocy's data model?

**Comment by berrnd** [comment]
> I can't create a unit conversion for Packs/Cans because the conversion depends on how the product was packaged. Is the conversion 1-to-8 or 1-to-12?

Exactly what #1421 is talking about and not this one, a kind of "barcode macro" (or however you want to call it) is needed, unit conversions as-is aren't sufficient - don't know why it's needed to talk about the same stuff over and over again, just read the referenced other thread in its entirety and not the headline only, leads at least to less wasting of (my) time.

&nbsp;
> The issue still stands that we can't create a Box-to-BaseUnit conversion because it depends on the box the barcode is on.

Exactly what #1421 is talking about.

&nbsp;
> Hence, I asked about specifying a separate consume and purchase quantity on each barcode.

Unrelated to the "barcode macros" feature requests, and off-topic here and also for #1421 - one topic per request is handled only since everything else produces clutter nobody can look through when working on this tomorrow or in 10 years.

&nbsp;
> how I'm misusing Grocy's data model?

You simply want something which isn't currently possible, don't know why it's so hard to understand that - implement #1421 and you'll be a whole lot closer where you want Grocy to be for your personal use case.
