### ISSUE TITLE
Bug: Recipe Units for an Ingredient Doesn't Update Properly When Ingredient Unit is Changed

### ISSUE THREAD

**Issue by OthmanEmpire** [grocy/grocy#1959]
## Foreword

Firstly, thank you very much for developing Grocy! Lately I've been transforming my household from no system (not even pen and paper!) to a digital ERP household. I'm looking very forward to the efficiency gains and time saved using Grocy.

## Bug Description

When the units of a product changes (e.g. say from "Litres" to "Pieces"), if that product is an ingredient in a recipe, its units aren't properly updated in the recipe. See below.

![2022-07-25_14-42](https://user-images.githubusercontent.com/5261295/180770343-91c92ef2-fc29-44d7-85f5-dd06688aa4db.png)

As a temporary work around, I attempted to manually update the ingredient from the recipe menu itself, but that doesn't work properly either. Changing the units to any value (e.g. from 5 to 10) and saving the value, causes the value to become 0. The only solution is to completely remove the ingredient and re-add it. See below.

![2022-07-25_14-47](https://user-images.githubusercontent.com/5261295/180770940-5b733e27-2f50-4663-9d81-ec034d81f1af.png)

![2022-07-25_14-44](https://user-images.githubusercontent.com/5261295/180770359-b11a7760-2be5-44d2-abe8-5607ad08e838.png)

## Bug Significance

It is likely new users will not populate all the fields for recipes in one-go but rather after in few iterations since there is a lot of information. This bug doesn't allow partial filling of information since you will have to delete your entire ingredient and re-add it again if it is modified.

So for instance, I added "Rice" to a recipe with an amount of "1 Piece" since I don't really know how we measure the amount of rice in our household. I planned on later checking out our rice and what unit we use to measure our stock (e.g. kg, cups, containers, etc). Once I find out, I will have to delete the ingredient on the recipe and re-add it so it reflects the new unit properly. This isn't bad for a single ingredient but is a major pain to do on many ingredients.

## Steps to Replicate

_Replicated demo instance: https://test-0gr961uc2s5vaz857tcuo47.demo-prerelease.grocy.info/_

1. Manage Master Data > Products > Create a new product with following properties:
    - Name = Milk
    - Quantity unit stock = Piece
    - Default quantity unit purchase = Piece

2. Recipes > Create a new recipe with following properties:
    - Name = Milk Bread
    - Ingredients = Milk (with amount = 5)
   
3. Manage Master Data > Products > "Milk" > Modify the units:
   - Quantity unit stock = Litre
   - Default quantity unit purchase = Litre

4. Recipes > "Milk Bread" > The units don't change when they should.

5. Recipes > "Milk Bread" > Ingredient("Milk") > Modifying the ingredient quantity manually and saving causes quantity to be 0.

**Comment by berrnd** [comment]
Your assumption about that a recipe ingredient unit changes when the products stock unit is changed, is wrong.

When I decide to store/track Milk now by Packs instead of Litres while having a recipe which needs 0.25 Litres, why should this be changed?

You can use any product related QU (by direct or indirect unit conversions) anywhere you can select a product amount. The absolute amount should be the same after changing a products stock QU, when having proper unit conversions in place.

For this example:
The unit conversion between Piece <-> Litre is missing, grocy can't guess the amount for the other unit. I've added that as a product specific conversion and editing the recipe ingredient is possible as always.

Just as a general reminder:
grocy is generally based around [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) which bascially means, that not every single edge case where you can potentially fuckup things by entering wrong stuff is technically prevented. Mostly only a problem when experimenting with grocy at first. Make backups.

**Comment by OthmanEmpire** [comment]
Fair enough, good point.

That also explains why the amount was 'resetting' to 0 after attempting to update the recipe ingredient amount, since no conversion of units is defined, the default behaviour is to convert it to 0 units.

I'll document this behaviour and perhaps later at some point will create some quick articles/tutorials on how to use grocy in a centralized place since reddit is rather hard to use for an old man like me ;)

Related to this 'issue' that has been solved, would you be open to pull requests to Grocy in the future related to enhancing the UX (i.e. more messages and help boxes to guide new users)?

**Comment by berrnd** [comment]
> Related to this 'issue' that has been solved, would you be open to pull requests to Grocy in the future related to enhancing the UX (i.e. more messages and help boxes to guide new users)?

When it really makes sense. Most of the time more text = just more confusion. Or text which just nobody reads. Source: More than 5 years of (not only) grocy user support requests.

The more complex details of a system you use, the more more time you have to invest to understand every detail. Also not something special for grocy.

&nbsp;
> I'll document this behaviour and perhaps later at some point will create some quick articles/tutorials on how to use grocy in a centralized place since reddit is rather hard to use for an old man like me ;)

Feel free to do so. Reddit, GitHub, your own blog - doesn't really matter. Pinned [r/grocy](https://www.reddit.com/r/grocy/) posts, [grocy.info/links](https://grocy.info/links), [grocy/grocy-docs](https://github.com/grocy/docs) - some people already started something and it was always the same: It's incomplete, not maintained in the long run and therefore outdated soon. Please don't get this wrong, but IMHO documentation in general only makes sense if it is maintained. I personally don't write documentation for grocy because it's not my favorite thing to do.

**Comment by OthmanEmpire** [comment]
I tend to work on undocumented systems quite often, so for better or worse, I've developed a habit to breathe documentation day-in and day-out.

Yes, documentation tends to go obsolete if not maintained. My hope is that I really do end up using Grocy to its fullest for my household which in turn would probably mean I would be writing documentation for it, and perhaps some pull requests in the future too.

Thank you for the feedback and the links too.
