### ISSUE TITLE
Feature Request: Battery Management with Remove Battery from Stock

### ISSUE THREAD

**Issue by thost96** [grocy/grocy#1963]
Hi,

it would be nice to add a Product to each Battery Lifecycle Entity so if a Battery is replaced, the right product is directly (automated) removed from stock. As for now, you set a new date for the Battery Lifecycle and must manually remove a battery from stock.

**Comment by berrnd** [comment]
grocy's stock feature is meant for groceries.

grocy's battery feature is meant for tracking the charge cycles of rechargeable batteries.

So if it's about single-use batteries, grocy-stock is not really the right place to "track" them and there is no need to use the batteries-feature for them, since you never recharge them.

Maybe track them as a product and "consume" them once used / put into a device - that's how I personally do it for (some) long-life button cells.

For example LR44/AG13 button cells are one kind of typical-use batteries, which are commonly only available non-rechargeable. Since it's 2022, everyone should use rechargeable batteries where possible - that's also a reason not to support something like that in grocy.
