### ISSUE TITLE
Bug: OpenAPI definition is wrong for `/userfields/{entity}*` endpoints

### ISSUE THREAD

**Issue by VikTech92** [grocy/grocy#1967]
In the Generic entity interactions controller and API methods, you cannot select the entity type 'stock'. I have tried also by calling PUT 
/userfields/{entity}/{objectid} via cURL:
```
curl -X 'PUT' \
           'http://<replace_url>/api/userfields/stock/<replace_with_stock_id>' \
           -H 'accept: */*' \
           -H 'GROCY-API-KEY: <replace_with_grocy_api_key>' \
           -H 'Content-Type: application/json' \
           -d '{"serialnumber":1}'
```
and in the stock entries my userfield was not populated. I also noticed that the 'stock' entity type is also not listed as a possible value for the 'entity' field in the api explorer, for the PUT verb, but it is listed in the GET verb.

I am currently using grocy with the release version, tag: v3.3.1. 
Is this a bug, or is out of the scope how stock entries should work?

**Comment by berrnd** [comment]
> In the Generic entity interactions controller and API methods, you cannot select the entity type 'stock'.

You mean probably the [/api](https://demo.grocy.info/api) page (Swagger UI). True that it's missing there, will be tracked here to fix that - doesn't affect any API functionality.

&nbsp;
Everything what the UI does is possible via the API, since the UI uses the API for everything. So a very easy way to find out how things actually work is using e.g. your browsers developer tools and just have a look at what happens.

Please provide a reproducible example as mentioned on the issue template.

Example request which perfectly works using the pre-release demo instance and a Userfield named `f1`:
```
curl -X 'PUT' \
  'https://demo-prerelease.grocy.info/api/userfields/stock/62f95e00b22cf' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{"f1": "xxxx1"}'
```

Unlike all for other entities, for stock entries the objects `stock_id` is used as reference (since that's the same for the entire lifecycle of the corresponding stock entry, the `id` is not).

**Comment by VikTech92** [comment]
@berrnd Oh, i was not aware of the stock_id being used as the id for adding userfields to a stock entity. Thanks for that!
