### ISSUE TITLE
Bug: Low Prices are ignored due to rounding issues

### ISSUE THREAD

**Issue by z0rgster** [grocy/grocy#1986]
When using the purchase function, the item price is calculated per base unit. If it is below 0.005 per base unit, it is rounded to zero.

This completely breaks the purchase mechanism. Such values should **always** be handled with the highest possible precision. The rounding should only be done when rendering the frontend. 

**Steps to reproduce:**
1. Create an item with base unit "g" and purchase unit "pack" 
2. Set the factor to 200 so that buying a "pack" adds 200 "g" to the inventory.
3. Begin purchase of 1 "pack" of the product. 
4. Enter 0.89 as the price per pack (which is perfectly reasonable)
5. See the value per "g" already being calculated to zero.
6. Finish the purchase.
7. Switch to inventory.
8. The total worth of the product is: 0.00
9. Begin another purchase of the same product
10. Enter 10.00 as the price of a "pack" 
11. See the value per "g" being calculated to 0.05
12. Finish the purchase. 
13. Switch to inventory.
14. The total worth of the product is now: 10.00 while the amount is 400 "g"

**Comment by berrnd** [comment]
Since this discussion came up more than a lot of times and what should be done about rounding is at the end personal preference and not law, it's entirely up to you to configure that.

Configure the corresponding [/stocksettings](https://demo.grocy.info/stocksettings) to your liking and you will be able to input 100 decimal places, while seeing only two at the same time.

![grafik](https://user-images.githubusercontent.com/2161815/187266756-efc5b9a2-0fef-4470-bc1a-0c49d96387ac.png)

**Comment by berrnd** [comment]
Also a duplicate-question of #1270.

**Comment by z0rgster** [comment]
Is "decimal placed allowed for amounts" the one that controls the calculation precision?
I expect to enter 0.89 per 200g and have a resulting price of precisely 0. 00445 € per g in the backend, no matter what is displayed in the fronted. When I buy 100 packs of 200g at 0.89€ each I expect the displayed price to be exactly 89.00€. What values should I set to achieve this?

**Comment by berrnd** [comment]
Just try things, practical example / private demo instance: https://test-ph087075afc19km3tj84f.demo.grocy.info

&nbsp;
> I expect to enter 0.89 per 200g and have a resulting price of precisely 0. 00445 € per g in the backend, no matter what is displayed in the fronted. When I buy 100 packs of 200g at 0.89€ each I expect the displayed price worth to be exactly 89.00€. What values should I set to achieve this?

You want to be able to enter 5 decimal places for prices, so of course `Decimal places allowed for prices (input) = 5`.

Purchase:

![grafik](https://user-images.githubusercontent.com/2161815/187274700-b3cf4665-a0e7-4eb0-a1f1-60a3d72dfaa2.png)

When buying 100 200g Packs for 0.89 each, even the total stock value meets your expectations:

![grafik](https://user-images.githubusercontent.com/2161815/187275712-648d5f7c-407a-4bd6-97c2-9174f1dc5f71.png)

&nbsp;

> Isn't that a sign that something should be done about it?

[Changelog v3.0.0](https://grocy.info/changelog#v3.0.0) excerpt:
_The decimal places for all amount and price inputs can now be configured (stock settings / top right corner settings menu, default for amounts is `4`, for prices `2`)_

Isn't that a sign that I did something about it? Otherwise sorry for not doing anything since more than 5 years in 2K+ commits and sorry for a just bad software.

**Comment by berrnd** [comment]
On the screenshot above the `Average price` should be of course also `0.89` and not `0.00`.

Just wanted to excuse again for not noticing that and not doing anything about it in af4715e17fe84e725e1dc81a7f33a3de8a332d0e: Sorry.

**Comment by z0rgster** [comment]
Hey man, no need to be offended about this. This is an awesome piece of software and I very much appreciate the hard work you put in there.
I realized that part of my issue was caused by using the android app, which has it's own rounding issues.
I set the input decimal placed to 6 and got the desired results. So this works for me I guess.
Nevertheless I think that separating the displayed values from the internal calculations would be a good thing for the future. That way users can set how many decimal places they want without affecting the calculations done in the background. My approach would be:
1. User enters string "0.89" as price 
2. System converts to a float/double: 0.890000000000....
3. User enters string "3" as count of packs
4. System converts to a float/double: 3.0000000000
5. User entered "200" as factor from packs to grams. System saved it as 200.000000000
6. System calculates 2.67000000000 as total price
7. System calculates 0.004450000000 as price per gram
8. System (set to 2 dec places) displays 0.00 € per gram
9. System displays 2.67€ as total

I made up an arbitrary amount of zeros, might be more actually. But I think you get by point. The system should always work as precise as possible and just make the numbers more appealing to the user.

**Comment by berrnd** [comment]
No, I don't get the point, because exactly that is already possible - configurable to the user, because I'm tired of discussing the "arbitrary amount of zeros, might be more actually" of decimal places to use. When you expect to use "a lot" and we'll change it now hardcoded to "a lot", the next "bug" will be opened right after the next release about that ("where in the world do you live, prices should always be calculated by 2 decimal places" or something like that will be the complain - there is no law, but a lot personal preference about that topic). So why is having that configurable not the best option to fit just all personal preferences? 

&nbsp;
> I think that separating the displayed values from the internal calculations would be a good thing for the future. That way users can set how many decimal places they want without affecting the calculations done in the background.

Again, that future is now and since v3.0.0: The configuration options are already there! Just mentioned that now here more than a lot of times...

Please have again a look at [/stocksettings](https://demo.grocy.info/stocksettings) and note that there are two options to exactly distinguish about input/calculation and output/display:

![grafik](https://user-images.githubusercontent.com/2161815/187294261-b0ca9824-d540-4630-8531-236392790737.png)

That means that any price input is possible by 10 decimal places (max., less is of course also possible and valid) and any price calculation is done and stored in the database with 10 decimal places and you'll see only 2 (rounded) at any place a price is displayed.

Please just try things, I'll provided the exact example on the demo instance mentioned above, and you'll notice that it will behave exactly like you expect it when setting the appropriate "Decimal places allowed"-settings. Sounds a little bit you never tried it once so far. And only the web frontend is the reference for reproducible "bugs" here, none of the community contributed apps are maintained here and by me.

**Comment by Blubberland** [comment]
This bug is really annoying especially when u didn't notice it directly.
Maybe setting the Decimal places allowed for prices by default to (maybe) 10 would be nice.

So if you really want to use the generated data to follow the prices over time, it corrupts the data with faulty values.
Because once you have entered all the stuff you have into the system, you can't change all the entries back.
...well there is a way: by deleting the whole product, and restoring its whole history manually.

**Comment by berrnd** [comment]
Nothing mentioned here is a bug and currency values are commonly handled by 2 decimal places around the world, that's why that's the default.

But of course that also depends on personal preference and on how you organize everything in grocy and that's then why grocy enforces nothing and even small details like how much decimal places are used for inputs and for displaying amounts and currency values are configurable.

grocy is generally following the [GIGO principal](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) and what happened is just that.
