### ISSUE TITLE
Feature Request: Android App that works offline?

### ISSUE THREAD

**Issue by ignacio82** [grocy/grocy#199]
Is there an android app that works when I don't have internet access and syncs to my server when I do?

**Comment by berrnd** [comment]
No.

The UI is responsive, works pretty well on mobile devices, I use it personally almost daily - but I don't have the problem to have areas without an internet connection...

The API should cover everything needed to build an app, feel free to build it - there was also already an idea about an app to do the scanning part, see https://github.com/grocy/grocy/pull/171#issue-259752589.

**Comment by ASMfreaK** [comment]
@ignacio82 You can launch grocy from @termux (via nginx, for example) and use browser on your phone to navigate to it. Syncing may be not hard if you sync your database and config between devices using rsync/dropbox/syncthing/etc. AFAIK, sqlite databases are portable, if grocy does not rely on some sqlite extensions like fts5, which may not be compiled into termux's php sqlite binding. 
Please, @berrnd , cc which extensions grocy use.
**Beware of data losses and make backups of database before syncs!**
This method is only useable with exclusive device switch (e.g. you *use* **only** your phone , then *sync* and *switch* to *use* **only** your pc, sync, switch back to use **only** phone and so on). It will make you lose data if you don't sync all devices **before** you switch to them.

**Comment by Altheran88** [comment]
I agree, mobile app should be another repo. Using API is a better approach vs DB cloning.

**Comment by BlizzWave** [comment]
This is what alot of us want, but i requires someone to actually develop it. Bernd is a busy man trying to keep up with all feature requests and bugs. Is there anyone of you that could assist in developing a android/ iphone app?

**Comment by berrnd** [comment]
grocy does not use any SQLite extensions - the default `pdo_sqlite` PHP driver works. The only requirement is that it needs to be at least SQLite version 3.8.3 - there will be SQL errors otherwise (I think Window Functions were not part of SQLite before, which are used in some views).

So syncing the database should absolutely work.

Running grocy completely on the phone with Termux could also work, although it would be a little bit heavy - I haven't really used Termux with a complete webserver so far...

Maybe Termux could also be used to package grocy into a standalone app (?), that's the way I do it with [grocy-desktop](https://github.com/grocy/grocy-desktop) - a (Windows) desktop application wrapper which runs the in PHP integrated development server to host grocy (available since this week also [directly through the Microsoft Store](https://www.microsoft.com/de-de/p/grocy/9nwb1trnnksf) 😄).

Personally I don't know if it's worth it to develop a standalone (cross plattform) mobile app. Everything from UI side need to be done then at two places, when the mobile should behave exactly the same / should have the same feature set.
For smaller use cases as mentioned in https://github.com/grocy/grocy/pull/171#issue-259752589 (the shopping list or for scanning, /CC @matejdro) I can imagine that it would be cool to have a little "companion" app.

I have little experience with [Xamarin](https://visualstudio.microsoft.com/xamarin), so making such a little cross plattform "Shopping list" helper app would be doable for me, I think - but at the moment I don't even really get all these requests here fulfilled - so maybe any time not so soon from my side, but I'd be delighted if anyone starts something in that direction and of course would be happy to help extend the API when maybe something is missing there...

**Comment by matejdro** [comment]
Yes, my plan is to (eventually, at some point in the future when I will have time)  to create scanner companion app that I could use to just quickly scan all items after grocery shopping. I see the utility in having offline app, but unfortunately I do not have the time to develop or maintain this.

**Comment by dadosch** [comment]
The scanning of barcodes is very unresponsive for me (on Android, takes about 30 seconds to scan).

However, it is possible to launch ZXing app (THE standard app for scanning barcodes) via a URL, let it scan the barcode and then return to a new url. I think this should be easier to implement than a whole app (but still no offline support)


> ZXing (zebra crossing) provides the capability to initiate the bar code scanner via a webpage through a button click event, anchor tag, or other action that could call a URL on a mobile device.
>
> When the barcode scanner application is installed on an android device, a URL call to:
>
> `zxing://scan/?ret=http://foo.com/products/{CODE}/description&SCAN_FORMATS=UPC_A,EAN_13`
>
> Will bring up the device bar code reader, the user scans the code, and the code is returned via the callback URL parameter supplied in the zxing URL.


https://stackoverflow.com/a/13555591/7418348

**Comment by MrJohnZoidberg** [comment]
Hey, I am working on an Android app right now - together with my brother!

Hopefully there will be a pre-alpha version soon, where you can quickly scan barcodes with your smartphone. But I can't promise that the app will have full offline support, although I planned to definitely have the possibility for looking up (offline) the last state of the shopping list.

Please give a :+1: so that I have more motivation to develop the app :-)

**Comment by gabriel-lucas** [comment]
Great idea, looking forward to try it.
Give us the link to the repo when you have it ready.
Thank you very much :-D

**Comment by BlueBlueBlob** [comment]
> Hey, I am working on an Android app right now - together with my brother!
> 
> Hopefully there will be a pre-alpha version soon, where you can quickly scan barcodes with your smartphone. But I can't promise that the app will have full offline support, although I planned to definitely have the possibility for looking up (offline) the last state of the shopping list.
> 
> Please give a  so that I have more motivation to develop the app :-)

Maybe gdrive (or other cloud solutions) can be a way to synchronize. And for this I guess we need a plugging in Grocy to share the db.

Just some ideas 👍👍 and good luck 👍👍

Kind regards

**Comment by MrJohnZoidberg** [comment]
After a little more than a month of development and ~22.000 lines of Java code, the app is now available on [GitHub](https://github.com/patzly/grocy-android) and in the [Playstore](https://play.google.com/store/apps/details?id=xyz.zedler.patrick.grocy)!
We hope that you enjoy it. Support for some disabled features (best before date or location tracking) in the grocy config is coming in a few weeks, currently the app will not work with such a config.

Cheers!

**Comment by r0bbie** [comment]
> After a little more than a month of development and ~22.000 lines of Java code, the app is now available on [GitHub](https://github.com/patzly/grocy-android) and in the [Playstore](https://play.google.com/store/apps/details?id=xyz.zedler.patrick.grocy)!
> We hope that you enjoy it. Support for some disabled features (best before date or location tracking) in the grocy config is coming soon, currently the app will not work with such a config.
> 
> 
> Cheers!
> 
> Edit: New features are coming in a few weeks, because we have to study for our Abitur now :smile:

Been trying the app out tonight - amazing job! Thanks so much for releasing this. Excited to see it develop and for F-Droid release!

**Comment by berrnd** [comment]
Wow, thank you so much for creating this! 🤩

**Comment by Forceu** [comment]
Looks amazing! Great job!

**Comment by IPuserX** [comment]
Thank you so much for all the effort you did!!! I'm really impressed! I hope you will maintain this app for a long time :-)

**Comment by berrnd** [comment]
I think I'll close this now.

grocy has now good app support thanks to the community contributations g[rocy-android](https://github.com/patzly/grocy-android) and [PantryParty](https://github.com/PantryParty/pantry_party/).

https://play.google.com/store/apps/details?id=xyz.zedler.patrick.grocy

https://apps.apple.com/app/pantry-party/id1510485755

https://play.google.com/store/apps/details?id=org.nativescript.PantryParty
