### ISSUE TITLE
Feature Request: Clear all marked as done items from shopping list

### ISSUE THREAD

**Issue by szerencl** [grocy/grocy#1999]
Please add an option to the shopping list to clear all done items. Similar to clear shopping list, but leave all items that are not marked as done.

**Comment by berrnd** [comment]
This is not yet released, check the milestone - nothing needs to be configured, otherwise this would be of course stated here and on the changelog - [preview changelog](https://grocy.info/changelog#preview) excerpt:
> - Added a new button "Clear done items" (to clear all done items with one click) 

&nbsp;
Looks like that when e.g. trying that out using the [pre-release demo](https://demo-prerelease.grocy.info/):

![grafik](https://user-images.githubusercontent.com/2161815/232711081-cd6e26d1-c48b-4dd9-b70a-727b2b88811b.png)
