### ISSUE TITLE
Bug: Grocy hangs on creating a barcode (quantity) | Grocy bleibt beim Erstellen eines Barcodes hängen (Menge)

### ISSUE THREAD

**Issue by FeedbackReporter** [grocy/grocy#2002]
- Describe the bug as detailed as possible by providing the exact steps how to reproduce it
  - Install Grocy 3.3.1 freshly on a Raspberry Pi 3B (PHP 8.0), insert storage locations, a product and then scan a barcode (using an Adafruit one with USB) and then the quantity - the comes the hang on my instance
- ~~Attach screenshots where useful~~ (Don't think it's useful here)
- Check if the problem was maybe already reported or fixed by searching open and closed issues here
  - Couldn't find anything
- Keep it to one topic per issue
  - Aye, capt'n :)

Please also try to reproduce the problem on the pre-release demo: => https://demo-prerelease.grocy.info
- ~~Use a private demo instance to make your example persistent~~
- If the problem is not reproducible there, it's most likely not a bug - please use the r/grocy subreddit for general questions / help: => https://www.reddit.com/r/grocy
  - Couldn't reproduce. It even works strange there. On my instance, I get a mask with barcode, quantity, unit, store and note (as it is in the demo instance). When I scan the barcode, I can still enter the quantity (where it hangs). On your demo instance, the whole mask vanishes after scanning the barcode. **How is it supposed to react on 3.3.1?**
  - I have about a million accounts out there. Most of them I even can't remember. For a few years now, I don't create accounts anyone wants to force on me. Instead, I try to delete unneeded accounts. I don't have a "subreddit" account, and I don't want one. It is enough I'm spied upon from Microsoft on Github... (anybody heard about Codeberg?)

**Comment by berrnd** [comment]
Bugs are something that is a reproducible problem, it brings nothing to bypass the issue template - I can't help by guessing every single detail of your setup.

&nbsp;
> When I scan the barcode, I can still enter the quantity (where it hangs). 

Check your browsers developer console for errors, most likely the API call for creating/saving the barcode fails (which is most likely caused by URL related configuration problems).

&nbsp;
> I have about a million accounts out there. Most of them I even can't remember. For a few years now, I don't create accounts anyone wants to force on me.

I don't force anyone for anything and it's more than ok if this doesn't fit you. But please follow what's mentioned in README for this project. Supporting each and everyone in their very personal comfort zone way takes more time than developing grocy lately, and I can't and want provide that, sorry.
