### ISSUE TITLE
NGINX Setup

### ISSUE THREAD

**Issue by schildgenb** [grocy/grocy#201]
Do you have a step by step guide on setting this up with NGINX? I have been trying to get this setup but I am struggling with it. I would love to be able to use this program. I am getting an internal server error so I know I am missing something somewhere.

**Comment by berrnd** [comment]
It's really nothing special - just ensure that your root directory points to `/public`, that the data directory is writable and that you include `try_files $uri /index.php;` in your location block or otherwise disable URL rewriting in the config file - everything is also mentioned in README. Or maybe try [grocy-docker](https://github.com/grocy/grocy-docker).

Feel free to reopen this when you have a specific error message (check the webserver/PHP logs).

**Comment by emk2203** [comment]
I had the same issues as OP, including the server error.

For someone who has never set up a web server or just a practice one years ago, the first step is quite steep, since there are so many differing generic instructions out, partly even contradicting each other.

I have listed some boilerplate instructions which worked for me on a minimum Ubuntu 18.04 install on a ARM system:

# Install nginx, php, sqlite on minimal system

Get root, ideally with `sudo -i` for this install marathon.

Install `nginx` and check status, should be up and running. You can make extra sure with `systemctl enable nginx` that this survives a reboot.   

```
apt install nginx
systemctl status nginx
```

If you are not starting from a minimal system, make sure that the firewall (`ufw` or other) don't interfere with the `nginx` install:

```
ufw allow 'Nginx Full'
```
and check with `ufw status`.

Now you can install sqlite with `apt install sqlite3`.

When you want install just the default `php`, apache gets installed as dependency. To avoid this, install `php-fpm`. Don't forget `php-sqlite3`.

```
apt install php-fpm php-sqlite3
```
The Ubuntu and Debian installation is a bastard child to accomodate both nginx and apache and forcing some defaults on nginx which come from apache. One of the signs for this is that the standard www root directory is `/var/www/html/`, and the user for nginx is set to 'www-data'.

The files served should belong to this user. My first-level suffix for the home intranet is `.lan`, change this according to your environment.

```
mkdir /var/www/html/grocy.lan
wget https://releases.grocy.info/latest
unzip latest -d /var/www/html/grocy.lan && rm latest
chown -R www-data:www-data /var/www
cp /var/www/html/grocy.lan/config-dist.php /var/www/html/grocy.lan/data/config.php
vi /var/www/html/grocy.lan/data/config.php
```
Now is the time to do the edits to customize your installation. Most important to avoid an error when accessing the server: **Make sure to disable URL rewriting when you use nginx!** This is the setting you need to have:

```
Setting('DISABLE_URL_REWRITING', true);
```

When you access this now with http://localhost or [http://<intranet_server_name>](http://localhost) from elsewhere, you will still see the default nginx landing page - a good sign since it shows that the web server functionality is there.

Now to configure the server and php. There are several .ini and .conf files now in your `/etc/php` folder, you can leave them alone. Same goes for the `/etc/nginx/nginx.conf` file. What you want to do is to make a file `/etc/nginx/conf.d/fastcgi_params` to setup your installed system correctly:

```
include fastcgi_params;
fastcgi_split_path_info ^(.+?\.php)(|/.*)$;
fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
```
Make sure that the last line fits your installed php version. Test with `php --version` if necessary.

To set the web root, do the following:

```
cd /etc/nginx/sites-available
cp default grocy.lan
ln -s grocy.lan ../sites-enabled/grocy.lan
rm ../sites-enabled/default
```
Now edit the `grocy.lan` file with the following changes:

``` 
 root /var/www/html/grocy.lan/public;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html index.php;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri /index.php;
                #try_files $uri $uri/ =404;
        }

        # pass PHP scripts to FastCGI server
        #
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;

                # With php-fpm (or other unix sockets):
                fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        #       # With php-cgi (or other tcp sockets):
        #       # fastcgi_pass 127.0.0.1:9000:
        }
```
On reload of nginx with `systemctl restart nginx.service`, you should be able to access the grocy pages now. Or, if necessary, reboot. Grocy should now work without issues from the install process.

**Comment by berrnd** [comment]
Why do you need to disable URL rewriting?
`try_files $uri /index.php;` is exactly for this...

Does not really matter, just produces ugly URLs...

Also just for reference: I posted the complete config of the [demo-en instance](https://demo-en.grocy.info) (which includes another nginx as a reverse proxy in front) yesterday here: https://github.com/grocy/grocy-docker/issues/15#issuecomment-486579894

**Comment by emk2203** [comment]
It simply didn't work during my setup with URL rewriting enabled. Only after changing this I got the web page to display, before, I had an error from sqlite. Now I enabled it again, and it still works.

**Comment by berrnd** [comment]
Thanks again @emk2203 for sharing your install guide, because this could maybe help others too, I added this now as a link on https://grocy.info/links.

**Comment by alemoh1234** [comment]
I was trying to install this on a raspberry pi, and by god, this program is awesome, but please guys, this is torture to get running, and if not for this totorial I would have given up.

In the process I discovered some things, and if @emk2203 can update his guide it would be even better for future users.

I will recommend changes and explain why, given the problems I had.

> apt install php-fpm php-sqlite3
should be `apt install php-fpm php-sqlite3 php-gd`
php-gd was missing in my sistem after following your steps.

> The files served should belong to this user. My first-level suffix for the home intranet is .lan, change this according to your environment.
This section only confused me, since I had no prior knowledge of nginx, please just use a normal directory or explain that the .lan on the name won't change the ulr, and is not some kind of configuration, as I has missinterpreted myself (if I'am wrong please correct me, as I still didn't find a good guide as to the workings of nginx)

> Make sure that the last line fits your installed php version. Test with php --version if necessary.
Thanks for the warning, but please make it clear that there are more instances of that version on the following instructions that should be changed acordingly as well.

> ln -s grocy.lan ../sites-enabled/grocy.lan
Please change this to use the full path, like this `sudo ln -s /etc/nginx/sites-available/grocy.lan /etc/nginx/sites-enabled/grocy.lan`, I discovered this issue can happen https://serverfault.com/questions/484678/linux-symbolic-linking-not-working-as-expected.

I think the only thing left holding this back from wide adoption is the dificulty of installation, if not for me, my mother (that was running the windows version, and has no knowledge of linux, would not have adopted it as a solution (since now we just have a raspberry pi running it) ease of use is everything, I hope y'all keep the good work, and thank you very much for this awesome tool.

**Comment by berrnd** [comment]
> I think the only thing left holding this back from wide adoption is the dificulty of installation

Feel free to contribute documentation. There are so much examples around here and elsewhere, even documentation will not fit everybodys taste...

However, everyone not so familiar with webservers and such use grocy-desktop or the Docker images or the Home Assistant integration. Otherwise there would be such posts daily, which is not the case.

**Comment by emk2203** [comment]
@alemoh1234 I put the first line in bold now to make sure that it is not easily overlooked.

**Comment by alemoh1234** [comment]
Thanks @emk2203, sorry for only noticing that later, my fault.

**Comment by garbled1** [comment]
just did this on bookworm rc2.  Needed to install php-mbstring php-intl and php-gd, other than that, works great.
