### ISSUE TITLE
Feature Request: Multiple due date / best before date

### ISSUE THREAD

**Issue by XisoP01** [grocy/grocy#2015]
I would love to see an update (no high priority) to add multiple best before dates for one product. When you reach your safetystock and go buy a new product, the date will be different in most cases than the products allready in stock. This means all the "old" inventory will change to the new date, or all the "new" products keep the old date.
If it was possible to add 2 or more lines for one product, the issue would be solved. Maybe it can be done in a piece of code that compares the used barcode to the best before date and this way determines to generate a new line in the database

**Comment by berrnd** [comment]
Well, if grocy only allows to set the very same due date for all of my 5 Packs of Cheese in my fridge, then grocy would have failed its very basics - so of course this is already and since ever possible.

Base concept (also already mentioned for example [here](https://www.reddit.com/r/grocy/comments/iz949b) or [there](https://github.com/grocy/docs/blob/master/tutorial.md)):

- [/products](https://demo-prerelease.grocy.info/products) is the "products list", so where you define your different products, one row/line per product there
- [/stockoverview](https://demo-prerelease.grocy.info/stockoverview) shows the total amount in stock per product, one row/line per product here
- Each product can be of course x times in stock (with a different due date, price, etc.), [/stockentries](https://demo-prerelease.grocy.info/stockentries) shows those different entries, x rows/lines per product there
- On each add-stock transaction ([/purchase](https://demo-prerelease.grocy.info/purchase), [/inventory](https://demo-prerelease.grocy.info/inventory)) you can set a different due date, price, etc.

The better place for general usage questions is the [r/grocy subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests).
