### ISSUE TITLE
Bug: API endpoint /objects/products returns error for barcode and userfields

### ISSUE THREAD

**Issue by vfhrr** [grocy/grocy#2023]
## How to reproduce

1. Open [https://demo.grocy.info/api](https://demo.grocy.info/api)
2. Select the endpoint (POST) /objects/{entity}
3. Select "products" as an entity
4. Keep the default request body
5. Click on Execute
![image](https://user-images.githubusercontent.com/2681913/195413473-391915c2-d333-4e1f-9696-636980b64745.png)

The following error will be shown:

```
{
  "error_message": "SQLSTATE[HY000]: General error: 1 table products has no column named barcode"
}
```
![Screenshot 2022-10-12 at 19 55 11](https://user-images.githubusercontent.com/2681913/195414255-1a85a685-0735-44cd-8bc2-c6685fdb995e.png)

A similar issue is observed with the `userfields` parameter in the request.

The issue is present in both: actual and pre-release versions.

**Update:** The same issue is present in the PUT request

**Comment by berrnd** [comment]
Those are just example request bodies, nothing more.

The the API returns an error for invalid requests is really not a bug.

**Comment by vfhrr** [comment]
@berrnd but this is a valid request, at least the schema describes both: `barcode` and `userfields` parameters.

![image](https://user-images.githubusercontent.com/2681913/195420194-9b3e0b01-51cd-4754-95aa-c050bd16286d.png)

**Comment by berrnd** [comment]
> It seems that there is no way how one can add/modify the barcodes of products via API.

Can't be true for just like everything, since the web frontend uses the API for anything. So the most simple way to find out how things work is to use the UI, while also having a look at your favorite browsers developer tools and see what actually happens.

Use the ["Generic entity interactions" endpoints](https://demo-prerelease.grocy.info/api#/Generic%20entity%20interactions) and the entity `product_barcodes` to add/edit/delete product barcodes.
