### ISSUE TITLE
Feature Request: Add power, gas and water (hot, cold) consumption

### ISSUE THREAD

**Issue by dvonessen** [grocy/grocy#2027]
Hi, I'm considering using grocy. Thank you for writing this useful application. I thought about how to track mentioned consumptions to keep track of them.

Possible values to enter:
Common: company, contract date and runtime, base fee
Electricity: Common + kWh consumption, price per kWh
Water: common + m^3 + price per m^3
Gas: common + kWh consumption + price per kwh

Maybe Meter reading date to get notified. 

Hope you will come back to my suggestion to discuss this further. 

Regards

**Comment by berrnd** [comment]
grocy is and will be for managing your fridge and chores and things related to that, nothing more.

Maybe have a look and Userentities and Userfields, by that maintaining arbitrary lists is possible.

For particularly this topic here, IMHO it makes much more sense to combine this with your home automation system, not your fridge ERP software. It makes even more sense, because tracking for those things should happen automatically - such another thing which common open home automation systems already have integrations for the corresponding hardware needed.
