### ISSUE TITLE
Feature Request: choose between webhook and normal printer mode for labels

### ISSUE THREAD

**Issue by alabiana** [grocy/grocy#2029]
Actually printing labels is only possible via webhooks. I have a Dymo labelprinter and i can not write a webservice myself for printing via webhook. Would it be possible to make the usage of normal cups printers available? Maybe a config option for choosing?
Normal printers are available for Thermoprinters so maybe this shouldnt be too difficult?

Thanks

**Comment by berrnd** [comment]
Label printers are always more to setup/think about/implement than "just print a page" and that all is also vendor/model specific. That's why nothing is and will be implemented in grocy directly for printing on them.

> Normal printers are available for Thermoprinters

Well, thermal printers are more than not normal printers and even have their [own protocol](https://github.com/mike42/escpos-php), so completely unrelated.
