### ISSUE TITLE
Link products of different size

### ISSUE THREAD

**Issue by Wdavery** [grocy/grocy#204]
During my last grocery shop, we got an 18 pack of eggs; we usually buy a 12pk. It would be great to have two different products linked to one inventory item: "eggs".

Barcode XXXX = +18 eggs
Barcode YYYY = +12 eggs

Some sort of "sub-product" system would be ideal for things like this.

**Comment by berrnd** [comment]
Maybe the same idea as #196.

**Comment by OmgImAlexis** [comment]
This is slightly different to #196 as this would merge multiple input items to a single product and #196 is about different types of the same product.

**Comment by Wdavery** [comment]
I agree with @OmgImAlexis, merging input items is definitely what I mean here. 

#196 would keep products separate, but could have a "master product".
White Milk + Choc. Milk + Straw. Milk = "Milk", which would have no input item at all.

I'm going to move some thoughts over to #196

**Comment by tedstriker** [comment]
I share @Wdavery and @OmgImAlexis point of view.
The same product comes in a plethora of different serving sizes, packages and multipack sizes. Also all of them have their own barcode.
If we could have an 1..n relation for the product to "a combination of everything in the screenshot" + QU conversions as a consequence of it.
### The fields necessary in the relation
![image](https://user-images.githubusercontent.com/795203/71251070-8f1a9b80-2321-11ea-8f5d-93e45cc4bf15.png)
![image](https://user-images.githubusercontent.com/795203/71222093-61a50200-22cf-11ea-82d3-f031baf426b0.png)

We could capture the reality better than having an entire new product for every size-package type-purchase unit combination. But I guess it might be a lot of work.

**Comment by kriddles** [comment]
Perhaps a simple option for this would be to add a radio button under the Amount in the Purchase page to offer purchase in quantity units instead of qu_id_purchase. 
The radio button would only be visible if the qu_id_stock is different than the qu_id_purchase.

This would prevent having to make unique products for an occasional different unit purchase.

**Comment by berrnd** [comment]
If I understand it correct, the main idea is to have different barcodes for different products amounts (same product), so to prefill the amount based on the scanned barcode / have an amount saved/attached to the barcode.

As mentioned above:
Barcode XXXX = 18 eggs (QU Piece)
Barcode YYYY = 12 eggs (also QU Piece)

Making a QU selectable on the purchase page would not solve that the amount is automatically prefilled based on the scanned barcode...

**Comment by tedstriker** [comment]
I second @berrnd s view. As it not only the quantity that varies but also the package size and package type (think of cola bottles and cans) the quantity aspect wouldn't be enough.
From my point of view, we're talking about how to (re)structure the data so it's able to reflect reality better while reducing overhead.
How to improve the user experience and reduce necessary user interactions would be the second step IMHO.

**Comment by DellanX** [comment]
As an add in idea, it may be worth making a mechanism for variant products.
To quickly increase the chaos, a future idea may be to allow for tracking costs by barcode, or calories by barcode.
for example:
store A - 12 eggs for $1.83 ~78 Cal
farmers market - 18 eggs for $1.47 ~90 Cal

I don't think eggs vary in calories enough for me to personally care. I'm just trying to point out that the quantity isn't the only thing that varies by barcode.

As for possible ideas for a solution, you may be able to make it work by adding a column for a "base product"(similar to parent product, except these items would be combined in the stock overview)
Products that have an identifier in this field will be variations of the base product, and will assume the  base products properties until defined otherwise. I'm still learning the codebase, so I cant gauge the overhead introduced yet.

**Comment by KennyStier61** [comment]
I ram into this issue today when adding two boxes of Ritz crackers, one a 18 pack the other an 8 pack.

**Comment by Wordna1** [comment]
I am very much looking forward to a resolution to this issue - It's the sole thing preventing me from enthusiastically using this otherwise amazing piece of software

**Comment by Wordna1** [comment]
@berrnd , Any chance this feature could be released before July?  I am really hoping to use Grocy to organize the inventory, menu and grocery lists for a kids summer camp during July & August, but I think this issue will cause a lot of complications since we don't always order eggs, tomato sauce, etc in the same sizes.

I am especially aware that the additional COVID-19 mitigation measures will cost a lot of staff time and therefore Grocy would be an even bigger life-saver than during a "normal" summer.

This is an amazing program and I am very excited to use it.

**Comment by vorkuta** [comment]
Looking forward to seeing this one bear fruit. Would really make the barcode scanning powerful, as there would be no worries about different brands having different qtys. 

@berrnd Are barcodes currently stored in a single field with a delimiter in the products table, or are there foreign keys out to a barcode table already?

**Comment by kriddles** [comment]
> Looking forward to seeing this one bear fruit. Would really make the barcode scanning powerful, as there would be no worries about different brands having different qtys.
> 
> @berrnd Are barcodes currently stored in a single field with a delimiter in the products table, or are there foreign keys out to a barcode table already?

Work is in progress (not yet in master) to transition the product table single field delimiter to a new barcode table along with quite a few other updates. #801 feel free to check it out
It's near the tail end of getting the changes done but will require much more testing.

**Comment by Wordna1** [comment]
> It's near the tail end of getting the changes done but will require much more testing.
I have several staff who would be very interested in helping test this feature.

**Comment by berrnd** [comment]
This is now done! :)
The UI is here and there not completely detail-ready, but if you want, you can play around with it on the [pre-release demo](https://demo-prerelease.grocy.info).

Excerpt from the changelog:
> ### New feature: Link product of different sizes
> - Imagine you buy for example eggs in different pack sizes
> - The "Factor purchase to stock quantity unit" can now be set during purchase (if the products purchase and stock QU are different)
> - Additionally, each product barcode can be assigned a different "Factor purchase to stock quantity unit" (on the product edit page), which is then automatically prefilled on the purchase page
> - (Thanks @kriddles)

**Comment by berrnd** [comment]
@dkbarn This is the very wrong place for general usage questions ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests)) and what you've mentioned is even off-topic in this year old thread, frustrating af.

&nbsp;
> It seems like what's missing is a way to define 2 different QU conversions for each of the barcodes to get from can -> gram.

Each and every barcode can have an amount and unit - example:

![grafik](https://github.com/user-attachments/assets/117b867c-6b66-4f12-9677-3c070e9d582f)
