### ISSUE TITLE
Bug: New stock amount in Inventory is unreadable

### ISSUE THREAD

**Issue by dgoethals** [grocy/grocy#2047]
Hi,
When viewing the Inventory page and selecting an existing product, the New Stock Amount field has so much spacing in it that the number is unreadable.
This has been tested locally with the latest version and can also be seen on the demo site online.
Navigator: Safari on iPad without any pending update
Thanks for your help

**Comment by berrnd** [comment]
Please provide a screenshot, the exact screen size or whatever is needed to reproduce that, as mentioned on the issue template.

Common desktop (1920px width):

![grafik](https://user-images.githubusercontent.com/2161815/202913066-b26dca29-fb82-4107-8baa-968ace5adb2b.png)

Common tablet (portrait, 820px width):

![grafik](https://user-images.githubusercontent.com/2161815/202913187-6ad27b2e-95ba-41cd-a226-f5a010c7e698.png)

Common smartphone (portrait, 380px width):

![grafik](https://user-images.githubusercontent.com/2161815/202913242-336868aa-cd1c-469d-a759-281b22da9f30.png)

I can't see problems by that and by what you described above so far.

**Comment by berrnd** [comment]
Just to add: If the (any) page is generally shown too big or too small on some devices / screen sizes, a very simple option is to use your browsers zoom feature.

**Comment by dgoethals** [comment]
Thanks for your prompt reply.

Here a screenshot from my iPad Pro (screen resolution: 2732 x 2048). It
looks as if there was a large padding on the right of the field.
The same happens with the Amount field on the Purchase, Consume and
Transfer pages.
Hope it helps.


Le dim. 20 nov. 2022 à 17:21, Bernd Bestel ***@***.***> a
écrit :

**Comment by dgoethals** [comment]
![IMG_6568](https://user-images.githubusercontent.com/56114318/202917413-56275a48-1785-42e6-9031-d5252c394c45.PNG)

**Comment by berrnd** [comment]
Well, making every single element pixel perfect for every possible screen / viewport size on this planet is a very time consumable task. Since it generally fits, I will do nothing for specifically that, sorry.

&nbsp;
> Here a screenshot from my iPad Pro (screen resolution: 2732 x 2048).

It's not about the screen resolution in browsers, it's about the viewport size, which is something different - reproducing that with the given size looks like that:

![grafik](https://user-images.githubusercontent.com/2161815/202917860-9b0484e6-1de8-44a6-8d01-533094acff6f.png)

&nbsp;
Multiple options are available to fix / improve it for yourself:
- Use your browsers zoom feature
- or simply collapse the left sidebar menu to have more space
- or use [custom CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to make everything fit your device's viewport size.
