### ISSUE TITLE
Bug: Consume gives error when `FEATURE_FLAG_STOCK_LOCATION_TRACKING` is disbled

### ISSUE THREAD

**Issue by JavaPieChan** [grocy/grocy#2053]
Hi,

I sporadically encounter the problem, that when I use the consume function, I get the error, that the amount should be between 0,0001 and 0, even when the stock amount is > 0. This problem does not always occur and the affected products sometimes differ. The "Quick Consume" function in the Stock Overview works however.

![image](https://user-images.githubusercontent.com/50845872/204321950-b5e82667-eade-414f-a49a-0ab39ae18fd8.png)

For this item I use two units: "Packung" for unit purchase and "Stück" for unit stock. I do not utilize any QU conversions for this product.

When this problem occurs, I get the following error message in the browser console:

![image](https://user-images.githubusercontent.com/50845872/204322031-d7677d7b-5a78-477a-a214-2ec79d0599b2.png)

I run grocy version 3.3.2 with php version 8.1.12

So far, I couldn't reproduce this behaviour on a pre-release demo

**Comment by JavaPieChan** [comment]
Additional comment: When I turn on the feature "FEATURE_FLAG_STOCK_LOCATION_TRACKING", edit the product and set the location to e.g. default and then go into the consume form, as soon as I enter the location there, everything works fine. 

But even with this feature enabled, as long as I don't input any location in the consume form, I still get this error.

**Comment by berrnd** [comment]
As mentioned on the issue template, the exact steps to reproduce a problem are needed, then I'm happy to solve it, just like every issue so far - but by "sporadically this happens with some data on my instance" it's impossible to do so for me, sorry.

By the error message above, I've just optimized something around that in f03bb5eeee4cd9fd66aa6dab87c42e1ab0d2dbdf. Replace the file `public/viewjs/consume.js` by [that one](https://raw.githubusercontent.com/grocy/grocy/f03bb5eeee4cd9fd66aa6dab87c42e1ab0d2dbdf/public/viewjs/consume.js) if you want to try it out.

&nbsp;
> I run grocy version 3.3.2 with php version 8.1.12

Only PHP 8.0 is supported ([README ref](https://github.com/grocy/grocy#how-to-install)) since [v3.1.0](https://grocy.info/changelog#v3.1.0).

**Comment by berrnd** [comment]
Reproducible example for that originally posted by @JavaPieChan in https://github.com/grocy/grocy/commit/f03bb5eeee4cd9fd66aa6dab87c42e1ab0d2dbdf#commitcomment-91328976:

>I tried the solution, it didn't work (when you disabled the feature location tracking) .
> 
> However, when line 381 is changed to
> ` if ((productDetails.product.default_consume_location_id || "").toString().isEmpty())`
> and line 383 is changed to 
> ` defaultLocationId = (productDetails.product.default_consume_location_id || "").toString();`
> 
> it seems to work with both feature flag "**FEATURE_FLAG_STOCK_LOCATION_TRACKING**" enabled and disabled.
> 
> In my case _default_consume_location_id_ contained either a number or null

**Comment by berrnd** [comment]
Unfortunately still not reproducible by that.

&nbsp;
> However, when line 381 is changed to
> ...
> and line 383 is changed to

Line 383 doesn't run when the product has no default consume location (what this `if` checks), so can't be the problem at all.

&nbsp;
> In my case default_consume_location_id contained either a number or null

Which is naturally always the case, it's an id of a location, as the name implies.

**Comment by JavaPieChan** [comment]
It might be that I miss something, but afaik both lines

1) `if ((productDetails.product.default_consume_location_id || "").isEmpty())`
and
2) `if ((productDetails.product.default_consume_location_id || "").toString().isEmpty())`

will absolutely run line 383 when the product has no default consume location. When it's null the condition is met and the default location id will be set to an empty string (my proposed change) or null (current - which didn't work for me).

The first code line will however break if the id is of type number because isEmpty() then throws the error I screenshotted above

**Comment by berrnd** [comment]
`productDetails` is an API response and everything what the API returns is technically always a string (see #1564), so both of your lines are practically the same.

So let's not make this a funny quiz game, but simply and finally provide a reproducible example, either the exact steps, or a reproducible example on a [private/persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b), or, if really not possible (practically just like never the case) and ok for you, send me your database file + config.php and I'll have a look.

**Comment by JavaPieChan** [comment]
I sent you an email with the config file and db file as a zip file - perhaps it is then reproducable

**Comment by berrnd** [comment]
Well, simply turns out that once again neither README nor the release notes were read:
**Only PHP 8.0 is supported ([README ref](https://github.com/grocy/grocy#how-to-install)) since [v3.1.0](https://grocy.info/changelog#v3.1.0).**

PHP 8.1 has some bigger changes which let you see different data types from API outputs (ref: https://github.com/php/php-src/commit/438b025a28cda2935613af412fc13702883dd3a2), not a real surprise that this isn't compatible without taking care, which is not done yet and therefore nowhere mentioned that it works.
