### ISSUE TITLE
Bug: iCal broken on armv7 - Epoch doesn't fit in a PHP integer

### ISSUE THREAD

**Issue by bitte-ein-bit** [grocy/grocy#2058]
I'm running Grocy on an 32-Bit Raspberry Pi using Docker. Having some products never expire will break the iCal feed
```
{
   "error_message":"Epoch doesn't fit in a PHP integer",
   "error_details":{
      "stack_trace":"
#0 \/app\/www\/vendor\/eluceo\/ical\/src\/Domain\/Entity\/TimeZone.php(46): DateTimeImmutable->getTimestamp()
#1 \/app\/www\/controllers\/CalendarApiController.php(79): Eluceo\\iCal\\Domain\\Entity\\TimeZone::createFromPhpDateTimeZone()
#2 \/app\/www\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(38): Grocy\\Controllers\\CalendarApiController->Ical()
#3 \/app\/www\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(358): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()
#4 \/app\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Slim\\Routing\\Route->handle()
#5 \/app\/www\/middleware\/JsonMiddleware.php(13): Slim\\MiddlewareDispatcher->handle()
#6 \/app\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): Grocy\\Middleware\\JsonMiddleware->__invoke()
#7 \/app\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#8 \/app\/www\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(315): Slim\\MiddlewareDispatcher->handle()
#9 \/app\/www\/vendor\/slim\/slim\/Slim\/Routing\/RouteRunner.php(68): Slim\\Routing\\Route->run()
#10 \/app\/www\/middleware\/LocaleMiddleware.php(16): Slim\\Routing\\RouteRunner->handle()
#11 \/app\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(269): Grocy\\Middleware\\LocaleMiddleware->__invoke()
#12 \/app\/www\/middleware\/AuthMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#13 \/app\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(269): Grocy\\Middleware\\AuthMiddleware->__invoke()
#14 \/app\/www\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php(45): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#15 \/app\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\RoutingMiddleware->process()
#16 \/app\/www\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#17 \/app\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\ErrorMiddleware->process()
#18 \/app\/www\/middleware\/CorsMiddleware.php(30): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#19 \/app\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(269): Grocy\\Middleware\\CorsMiddleware->__invoke()
#20 \/app\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#21 \/app\/www\/vendor\/slim\/slim\/Slim\/App.php(199): Slim\\MiddlewareDispatcher->handle()
#22 \/app\/www\/vendor\/slim\/slim\/Slim\/App.php(183): Slim\\App->handle()
#23 \/app\/www\/app.php(106): Slim\\App->run()
#24 \/app\/www\/public\/index.php(45): require_once('...')
#25 {main}",
      "file":"\/app\/www\/vendor\/eluceo\/ical\/src\/Domain\/Entity\/TimeZone.php",
      "line":46
   }
}
```

Adding to the `controllers/CalendarApiController.php` file in line 66 as below makes the error go away. If this is a good idea, I can't tell as I lack overview of the project.
```php
                                if (PHP_INT_MAX <= 2147483647 && $compareDate->format('Y') >= 2038) {
                                        continue;
                                }
```

If you are happy with this approach, I can create a PR.

**Comment by berrnd** [comment]
Your proposed change simply skips / excludes any calendar item with a start date later than 2038-01-01, sorry but no, this is really not a good idea.

So of course this affects currently mostly never overdue stock items (since they use internally 2999-12-31 as the due date), but also any other calendar item (chores, tasks, everything) when created for such a date.

I will not invest time to do something for that - it's 2022, use a 64-Bit OS.

If a real solution is possible and provided as PR for that, I'll maybe have a look into and merge it.

**Comment by bitte-ein-bit** [comment]
@berrnd Looking at the file, I'd say you are not correct about it skipping the addition to iCal as this happens before line 66. What it will skip however is the TZ details past 2038.
Tentatively I agree about using a 64-bit OS with one exception. 64-bit support for Raspberry was only officially released beginning of this year. It would be fair to give people some grace to migrate.

**Comment by berrnd** [comment]
Whatever, exlcuding timezone information maybe breaks some clients, that's why it was added (ref #1637).

If your proposed change works for you, why not simply stay with it.

Otherwise a way to go is to stay with an old release (this here was added in [v3.1.3](https://grocy.info/changelog#v3.3.1), so any release before that - running (not only) grocy on old platforms / runtime stuff naturally often requires to stay with old releases). This particular problem is also generally nothing new and suprising about the limitations of the 32-Bit platform.

I have also not the aim with grocy to support any platform on this planet, if a 32-Bit Pi doesn't fit, then it doesn't fit. Personally I'm also running Pis for some stuff, but for me it's generally too slow for web applications like grocy. But that's of course personal preference, I like stuff fast.
