### ISSUE TITLE
Feature Request: Create multiple products quickly (mass creation)

### ISSUE THREAD

**Issue by schnillerman** [grocy/grocy#2072]
- Describe what you would find useful TRYING - See below)
- Check if your idea was maybe already requested by searching open requests here DONE
- Keep it to one topic per request TRYING

Adding multiple products is very time consuming.
Adding products by just naming them, hitting ENTER, would be very helpful.

This might require some robust methods on the quantities and other mandatory fields. I would like to, e.g. in this case, fix them later via mass update (see [feature request](https://github.com/grocy/grocy/issues/2071))

**Comment by berrnd** [comment]
A product is much more than just a name, and just leaving everything else unset and fix that later will mean practically for most people that "later" is "never" and this leads to bullshit, because grocy is generally based on the [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) principal. So not a good idea and therefore nothing that will be added like that.

There is already a worklfow to create products just while doing a purchase transactions and on more places - just enter something unknown in a product dropdown field - quick video demo:

https://user-images.githubusercontent.com/2161815/208662668-a6fcd9b2-bf7d-40fa-80e3-c6c47093594f.mp4

Another approach is to use barcodes and maybe [Barcode Buddy](https://github.com/Forceu/barcodebuddy).
