### ISSUE TITLE
Feature Request: When adding Barcode via purchase also add amount

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#2085]
Demo:
https://test-p55029cif3xmshjxneuxq.demo-prerelease.grocy.info

What have i done:
Go to purchase and insert a unknown barcode.
123456
Add barcode to existing product
Pick produkt Eggs
Insert 12 piece
click okay to finish purchase

Have a look at Eggs masterdata barcode section
![grafik](https://user-images.githubusercontent.com/71584438/209933076-b389a34c-9e35-4220-8c5d-55f0b3cf3086.png)

The inserted amount of 12 pieces was not set to the barcode 123456.
I would suggest to put the amount directly to the barcode information when assigning a unknown barcode to a product.

**Comment by Saturo78** [comment]
Does it make sense to handle the barcode info text in the same way and take it from the stock entry info text when adding a new barcode?

**Comment by berrnd** [comment]
> Does it make sense to handle the barcode info text in the same way and take it from the stock entry info text when adding a new barcode?

Off-topic here. And for what exactly practically? Also more than highly depends on what you use note fields for - since they are just free text fields, it's up to you for what to use them. Binding two independent note fields together in a way that fits you most likely doesn't fit the entire grocy user base...

**Comment by Saturo78** [comment]
I use mostly generic products and put the brand information into the barcode info field.
I'm looking for a way to fill the barcode info field when assigning a new barcode to an existing product in the purchase dialog.

With the existing workflow the barcode info field keeps empty. 
There is no way to filter for barcodes without an info text. So its quite difficult to fill the barcode info fields.

I have to check regularly if there are new assigned barcodes without info text and then add it.

But if that's your opinion, I can live with it.

**Comment by berrnd** [comment]
> I use mostly generic products and put the brand information into the barcode info field.

That's a very specific use case, grocy is there to fit them all (by providing free fields, Userfields, not forcing how to organize everything and so on), but it doesn't make sense to make a very specific way of using grocy of you or one of mine the new and only default - since it fits you, maybe someone else, but a lot of other users simply not.

Use [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to customize everything to your personal needs, or think about how this could be added in a generic way and open a separate request (still one topic per request, as mentioned on the template), to not force someone into a specific way of how to use / organize grocy.
