### ISSUE TITLE
Feature Request: Set barcode note on purchase (InplaceAddBarcodeToExistingProduct workflow)

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#2093]
Since it is possible to assign a new barcode to a product via the purchase dialog i would like to ask for a feature to also fill the barcode info text in the same step.

**Comment by berrnd** [comment]
Related to https://github.com/grocy/grocy/issues/2085#issuecomment-1370192466 and the comments below that.

The barcode note field is nowhere shown and nothing is done with it anywhere.

But let's simply add for the sake of fulfilling the "since it's possible there so it needs also to be possible there" complains.

**Comment by Saturo78** [comment]
Maybe of  interest for some other users.
The android app (nightly version) offers a option to put the barcode info text to the stock entry info text on purchase.
So its possible to use generic products but have also the brand information in the stock entry info text.
