### ISSUE TITLE
Add automatically products to shopping list does not seem to work

### ISSUE THREAD

**Issue by dgoethals** [grocy/grocy#2094]
Here are the steps I followed on the private instance (https://test-zeozjszbzvm3a6ez7q1yzl.demo-prerelease.grocy.info/shoppinglist)
1. Create a second shopping list "Store XX"
2. In the "shopping list settings" select the checkbox "Automatically add products that are below their defined min. stock amount to the shopping list" and set it to "Store XX"
3. Create a product "Freezer bags" with a min. stock amount = 3

In the Stock Overview, the product is listed as below min. stock amount.
But the product does not appear on the shopping list "Store XX".

Is this the intended behavior?

Thanks for your help

**Comment by berrnd** [comment]
Any consume or open product transaction triggers adding missing products to the shopping list when `Automatically add products that are below their defined min. stock amount to the shopping list` is enabled - there is no single stock transaction for your example product.

**Comment by Saturo78** [comment]
To clarify this, adding a new product with stock = 0 and min stock = 5 will not be set on the shopping list because there is no consume or open transaction?

**Comment by berrnd** [comment]
> To clarify this, adding a new product with stock = 0 and min stock = 5 will not be set on the shopping list because there is no consume or open transaction?

Yes, can also be easily verified by just trying it.

**Comment by Saturo78** [comment]
Well, than i have to say thats a really good solution!

**Comment by berrnd** [comment]
@Saturo78 if grocy still doesn't fit in so many aspects for you, obviously by your daily complains not only here, why bother with it, are you forced to use it? And yes, your initial comment here above is still visible and says everything.

&nbsp;
> To clarify this, adding a new product with stock = 0 and min stock = 5 will not be set on the shopping list because there is no consume or open transaction?

Let me briefly translate what you meant by that: "Your crap software once again does things just wrong."

No problem, I can read between the lines and already know that grocy is just crap, since I hear that multiples times a week since more than 5 years now. But people seem to love crappy things, it's crazy.

&nbsp;
> There should be a batch job witch checks periodicaly if there are products with stock below min stock.

I try to make setup things easy and could imagine that you would be the first one having problems setting up such a job. It's practically also not necessary, since everything related to that is event driven.

So it's currently missing to do `AddMissingProductsToShoppingList` (when `Automatically add products that are below their defined min. stock amount to the shopping list` is enabled) when changing a product's `Minimum stock amount`, hence technically on saving a product. I've just added this in the here above referenced commit.

Practically this is just a "problem" when creating new products initially. It's not forbidden to add products manually to the shopping list when setting up a new one. I personally once again don't understand the big problem. If tracking stuff is too time consuming for you all, grocy is definitely not the right thing, since everything here is about tracking stuff.

Sorry for supporting you daily lately and often kind of instantly fixing things and implementing what you request, I hope it didn't bother you too much.
