### ISSUE TITLE
Bug: Quantity Groups keeps failing

### ISSUE THREAD

**Issue by Xiondewah** [grocy/grocy#2102]
I originally had Grocy installed on Home Assistant but because the Quantity Groups failed I moved out and into Docker.  I'm new to Docker by the way.  After using for a short time, the same problem has materialised - the Quantity Groups just show a tick mark, though only on Quantity Unit in Stock this time.

**Comment by berrnd** [comment]
Here bugs and feature requests for grocy are tracked, not anything related to community contributed apps / integrations.

Please provide a reproducible example (the exact steps, at best reproduced on a [private/persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b)), just like mentioned on the issue template which you obviously have ignored, if you think you've found a bug. General setup help and anything related fits better on the [r/grocy subreddit](https://www.reddit.com/r/grocy), as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests).

**Comment by Xiondewah** [comment]
I really don’t think there is any need for you to be rude.  I won’t use Grocy any further.

**Comment by berrnd** [comment]
Sorry for answering at all then, nothing rude is included in my two sentences above - but I also don't know how to help with anything, since you haven't provided any details at all. Without that, I even cannot guess what the problem could be, which is what I always did in the last 5 years for every reported problem/question/whatever, even when nothing reproducible and no proper details were provided.

But I agree, not using grocy is the best way to solve those problems (and also sorry for creating it, it's crap and I've wasted your time by doing that).

**Comment by Xiondewah** [comment]
And there it is again, the immediate aggressive reply.   ‘… which you have obviously ignored’

I am not a programmer.  I am someone who had to look up every single step because there is, as far as I can see, no complete source of documentation.  I have spent a long time on this because it looked like it was precisely the thing I had been searching for.  I don’t know how to find the details requested in the ticket, but all you had to do was to gently ask or, better yet, advise how.  

Clearly this is not intended for anybody without significant technical skills and is provided by someone with limited people skills.
