### ISSUE TITLE
Bug: iOS/iPadOS 16.3 - Stuck when saving shopping list

### ISSUE THREAD

**Issue by master-kw** [grocy/grocy#2112]
Hi Bernd,

today I‘ve updated my iPhone/iPad to version 16.3. Hereafter, the WebGUI always freezes when I want to add and save an article.

The screen stucks until I refreshed it. After that restart, I had to renew login but the item was added to shopping list. 

Regards, 
Oliver

**Comment by berrnd** [comment]
Please provide any useful details (check the browser developer console, check your webserver logs) to be able to reproduce that as mentioned on the issue template - I'm unable to guess all the things and can't fix stuff without details and/or having it reproducible.

**Comment by berrnd** [comment]
`#shopping_list_id` is either the first dropdown on the shopping list item form or, if [`FEATURE_FLAG_SHOPPINGLIST_MULTIPLE_LISTS`](https://github.com/grocy/grocy/blob/efc7b999bb1ded27448a1c4ce64327c9d9bc53dc/config-dist.php#L142) is disabled, a hidden input field.

Code ref:
https://github.com/grocy/grocy/blob/efc7b999bb1ded27448a1c4ce64327c9d9bc53dc/views/shoppinglistitemform.blade.php#L40-L58

So this can never be `null`, at least for any case I can guess - it's still that funny guessing game for me, since I still don't have it reproducible. Have you reproduced it on the [demo](https://demo-prerelease.grocy.info/) as also mentioned on the issue template? What grocy version and which PHP version do you use (also that is mentioned on the issue template)? If it works on the demo and not on your installation, it's, as always, not a bug and more something which went wrong on your installation.
