### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by teitrand** [grocy/grocy#2115]
Calories seems to be a source of confusion in Grocy and changes from product to product.

Food is marked (at least here in Norway) with calories per 100g or 100ml as standard.  Additionally there can be a per serving column too. 

Why not base the calories on per 100 grams/mililitres? Or show how the calculation of calories is done in a comment by the title of the calories field? There is just too much guesswork and to little intuitivity to get calories count to work as expected. 

I would also want the same fields and calculations for other nutricients like fat, protein and carbs.

**Comment by berrnd** [comment]
> Why not base the calories on per 100 grams/mililitres?

There are no built-in quantity units in grocy, the product option "Energy (kcal)" relates to the product's quantity unit stock.

&nbsp;
> Or show how the calculation of calories is done in a comment by the title of the calories field?

That's already done, since ever:

![grafik](https://user-images.githubusercontent.com/2161815/215353774-865d0f33-1bee-42ad-9c28-f90b1af4907a.png)

&nbsp;
> There is just too much guesswork and to little intuitivity to get calories count to work as expected.

It's a one-time action to fill that field properly when initially setting up the product, just like each and every other product option.

&nbsp;
> I would also want the same fields and calculations for other nutricients like fat, protein and carbs.

You can add any field you want to any entity (= products, chores, etc.) you want by using Userfields. Summing them up on recipes is already requested and tracked in #413.
