### ISSUE TITLE
Bug: text entry of userfield on product disappears in edit mode

### ISSUE THREAD

**Issue by Blubberland** [grocy/grocy#2116]
Couldn't find a related bug, sorry if repost:

1. I made a userfield _trademark_ for products. Please note, that the Caption is _Marke_. <img width="550" alt="Screenshot_2" src="https://user-images.githubusercontent.com/109285352/215561987-884a0b32-ce64-4478-b3b4-244a26a1f0f8.png">

2. When saving, it's displayed correctly. <img width="550" alt="Screenshot_2" src="https://user-images.githubusercontent.com/109285352/215562343-9bc11f8c-70f3-4535-8caa-1ee2f9686ef5.png">

3. When entering the edit-mode for the product, the previous entry disappears. <img width="550" alt="Screenshot_3" src="https://user-images.githubusercontent.com/109285352/215562526-78791868-a76f-4680-9dee-222c63102fe3.png">

This is my first bug report ever on github, please don't kill me.

**Comment by berrnd** [comment]
Which version of grocy do you use, which PHP version and which Browser? Is there maybe an error message in your webserver logs and/or your Browser's Developer Console?

The issue template mentions to first try to reproduce problems an a demo instance - I took the time and did that for you: https://test-tkc6ebs31ks4bfbh1ahe03.demo-prerelease.grocy.info/products

https://user-images.githubusercontent.com/2161815/215565583-b3c745f0-798a-4af9-847f-ceeb7093ba1e.mp4

So most likely a problem on your installation and not a bug. Otherwise please provide more information, I can only fix reproducible problems.

**Comment by Blubberland** [comment]
Yep, I'm using the docker-compose of linuxserver/docker-grocy. Should probably address them or try to figure out myself first.

Thanks anyway!
