### ISSUE TITLE
Feature Request: Auto fill due date in inventory

### ISSUE THREAD

**Issue by JJK96** [grocy/grocy#2122]
When editing the inventory of a product, it would be useful to me if the due date would be filled automatically on the current value. Sometimes only the number needs to change, not the due date.

**Comment by berrnd** [comment]
Please clarify where exactly this is related to.

On [/stockentries](https://demo-prerelease.grocy.info/stockentries) all properties of your stock items can be edited, and of course the due date is prefilled by the due date of the corresponding stock entry, just like all other fields.

On [/inventory](https://demo-prerelease.grocy.info/inventory) it's about correcting the total stock amount per product. So based on the amount entered there, maybe something get removed or added. The due date entered there only applies to added products (as the help tooltip also mentions). Since there can be `n` items of that product in stock with `x` different due dates, which one do you expect to be prefilled there?

**Comment by JJK96** [comment]
Ah, it seems I have been using this feature incorrectly. I should be
editing the stock entries.
