### ISSUE TITLE
Define "quick open amount" independently from quick consume amount

### ISSUE THREAD

**Issue by manuelkue** [grocy/grocy#2127]
As far as I can see the "quick open amount" is always the same as "quick consume amount".
It would be great if one could define that amount independently from the consumption amount. 

Alternatively, I think adding a checkbox for "Open whole product on consumption" would be an even better approach, but that might be a breaking change?

I think most products can't be consumed without opening the whole packaging and I'm not sure which product would be opened with a specific amount but is then not consumed (like it's done currently when clicking the "quick open button") 

(It was already mentioned in #1265 but that one included too much requests, I guess) 

Thank you so much already and kind regards,
Manuel

**Comment by berrnd** [comment]
Just to clarify here once more how grocy handles stock items, since there tends to be confusion about that when talking about opening stock entries:

The product's quantity unit stock is the base, all amounts everywhere are stored related to that unit. So when taking the famous example of a Pack of Milk and you want to be able to track opening Packs, the only way which makes sense is to use Pack as the products QU stock (not Liters or whatever else).

In reality of course it only makes sense to open a integral number of Packs, but grocy doesn't enforce that and anything else, since ever and forever, because it's a (very) open system to support everyone's use cases (and the Milk example is just the most simplest one).

That was also already mentioned in your referenced other request #1265.

&nbsp;
> Alternatively, I think adding a checkbox for "Open whole product on consumption" would be an even better approach, but that might be a breaking change?

So for the topic of this request: Of course it's possible to split the existing product option "Quick consume amount" into another "Quick open amount" and you can of course enter simply `1` there to fit the Milk (tracked in Packs) example. But it's not required to enforce that at all.

**Comment by manuelkue** [comment]
Thanks Bernd for that quick reply!
I understand your thoughts on that point.
It would be really great if the option "Quick open amount" could be configured as well. According to some other issues, requests and even Reddit posts this might be useful for this cases where people decide to use grams, kilos, as units ... ;-)

Just for some background-info for what I would use this:
Fresh coffee beans tend to taste best if used within 4 weeks when the pack is opened and the CO2 disappears slowly.
The coffee grinder always grinds the same 15g of coffee and therefore I would love to track the bag opening as well as the gram-wise consumption of the bag.
Therefore opening the bag should lead to opening all 500g of the coffee bag so I have an overview how long the bag has been open already.

If that's a strange or wrong usage of the unit system I have still to find a better way of tracking the coffee consumption 😏️

**Comment by berrnd** [comment]
Changelog excerpt for this:

_The product option "Quick consume amount" (the amount used for the "quick consume/open buttons" on the stock overview page) has been split into another option "Quick open amount", to be able to set different amounts for consume and open (defaults to the "Quick consume amount" per product, so no changed behavior when not configured)_
