### ISSUE TITLE
Bug: Unable to run grocy: SQLite 3.22.0 is required, however you are running 3.7.17

### ISSUE THREAD

**Issue by aralom** [grocy/grocy#2142]
Actually I'm using 3.41.0
Any Advice?

**Comment by berrnd** [comment]
This here is the tracker for reproducible Bugs and Feature Request, the place for general help requests is the [r/grocy subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests).

You obviously already found that, since it's a double post of https://www.reddit.com/r/grocy/comments/117gfyp.

&nbsp;
> Actually I'm using 3.41.0

Can't be the case when the error message in grocy says something else. Maybe note that the SQLite version PHP uses is not necessarily related to your systems `sqlite3` executable.

Beside that, you haven't mentioned how you run grocy, which version (grocy and PHP) you're using and all the other details (also mentioned on the issue template) - personally I'm unable to help in such a case.
