### ISSUE TITLE
Feature Request: Shopping List: Mark as shopped by just touching/clicking on it

### ISSUE THREAD

**Issue by superpower10** [grocy/grocy#2147]
I would like to have the option to mark an item as shopped by just touching/clicking on the name (not the green button).

And if I touch/click on the name to mark them as not_shopped.

This would make it easier to understand for beginners/not so technical people and for making an Apple Watch App for grocy.

**Comment by berrnd** [comment]
Clicking on a (unlabeled for that action) product name is more intuitive than having a (for that action labeled) corresponding button? I doubt it.

Just to clarify what this refers to (since this is not the repository of any of the community contributed mobile apps):

![grafik](https://user-images.githubusercontent.com/2161815/220319083-331e5518-c596-4b67-9c44-330df5590d86.png)

Clicking a product name opens the product card (product overview) on any place throughout grocy's web interface.

If you want to have clicking the product name on [/shoppinglist](https://demo-prerelease.grocy.info/shoppinglist) marks the corresponding item as "done", consider utilizing [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to customize everything to your very personal needs.

Here is a snippet (for `data/custom_js.html`) to make that happen (click the product name to mark the item as done / "shopped"):

```html
<script>
if (Grocy.ActiveNav == "shoppinglist")
{
	$(".product-name-cell").removeClass("product-name-cell").addClass("my-product-name-cell");

	$(document).on("click", ".my-product-name-cell", function(e)
	{
		$(e.currentTarget).parent().find(".order-listitem-button").click();
	});
}
</script>
```
