### ISSUE TITLE
Bug: Wrong calculation

### ISSUE THREAD

**Issue by Ofloo** [grocy/grocy#2151]
When purchasing a new product https://url/purchase

![afbeelding](https://user-images.githubusercontent.com/2203497/221409220-ac95dabe-cfc1-4484-be96-06ca93da4494.png)

result:
![afbeelding](https://user-images.githubusercontent.com/2203497/221409283-450f3f0e-e5de-4ad3-84af-02eb558097f1.png)

I think the screenshots speak for it self.

It says last price 8.53 euro /kg !!!

![afbeelding](https://user-images.githubusercontent.com/2203497/221409529-a970cc49-d74a-4268-9ce0-66e2b90bb751.png)

**Comment by berrnd** [comment]
The issue template mentions to first try to reproduce issues:
_Please also try to reproduce the problem on the pre-release demo: => https://demo-prerelease.grocy.info_

I guess you've missed that, no problem - I took the time and did that for you:

https://test-zkbcy28w9ebzdeb7mkz2q.demo-prerelease.grocy.info

![grafik](https://user-images.githubusercontent.com/2161815/221410252-ade84ec5-91ef-40a1-b051-aecc02a40f26.png)

I also think the screenshot speaks for itself.

I've additionally tested the same on the current release v3.3.2 demo and it also works there in the same way: https://test-zi31n86qywb4v3n3ewr2e.demo.grocy.info

Maybe more details are needed to reproduce that, but you haven't provided anything of that.

**Comment by Ofloo** [comment]
closing it because you can't reproduce it doesn't solve the issue. If you need more information you can just tell me what it is you're looking for. But I guess for you it's more important to close something then to actually fix something. The fact is that the screenshots speak for themself and that something isn't working as it should. But I guess the most important thing of the fact is that you've closed your issue.

**Comment by Ofloo** [comment]
![afbeelding](https://user-images.githubusercontent.com/2203497/221412425-834fb926-a079-46f5-a964-b032f2354ef3.png)
I've figured out your bug btw.

**Comment by berrnd** [comment]
> If you need more information you can just tell me what it is you're looking for.

Sorry, I've tried to reproduce it by what you've provided and I asked for more information (the issue template also kind of already did that). It's kind of obvious by itself that any / all information is needed, since the result (the wrong last price) is not based on a single action / screenshot.

Closing as invalid means it was reported in a not reproducible way and of course any issue can and will be reopened and fixed once the required information is provided, at least that was the case for any reported problem in the last 6 years.

&nbsp;
> But I guess for you it's more important to close something then to actually fix something.
> But I guess the most important thing of the fact is that you've closed your issue.

By that it sounds to me you even don't want it to be solved. And btw., it's your problem at that time I guess, I don't have it.

Almost insulting me that I am only out to close tickets instead of fixing them is of course ok and makes my day better - can also be proofed that I'm only fixed > 400 reproducibly reported bugs so far, sorry for that and of course also for making mistakes at all.

I guess the most important thing for you is then to just open bugs instead of investing a single minute on trying to reproduce them?

I have no obligations to anyone - I'm happy to and fixed any bug and answered any question in the last more than 6 years grocy. But I'm slowly going to be tired of this kind of requests and I'm maybe going to stop investing any time in those in the near future. Since it brings nothing - grocy is my hobby, and it should be fun to "work" on it - you've lowered my desire on it once again, thanks for that. You don't need to understand that at all, but please just keep in mind that it was your choice using grocy and I'm even not obligated to respond to any question or fix any bug at all.

**Comment by berrnd** [comment]
Back to the topic: The product option "Factor purchase to stock quantity unit" was already removed because for the next release quantity unit conversion handling will be reworked and improved at all. So this is no longer relevant / solved by that.

**Comment by Ofloo** [comment]
I expected no less, but obviously because the last 6 years no one bothered reporting it there are no issues few months ago there was discovered a bug in unix ping that was there for 24 years https://sha256.net/fuzzing-ping.html obviously you're so perfect that you can't have such bugs !

Even though you've released a new version only months ago but of course you've not rewritten any code you're just releasing versions ! So no new bugs can be introduced. 

But after your latest release you've broken the conversion previously when you adjusted the ratio it would automatically generate the correct conversion but as of your latest release this isn't working either anymore. Obviously this issue is also fixed because it's not relevant anymore.

**Comment by berrnd** [comment]
> Even though you've released a new version only months ago but of course you've not rewritten any code you're just releasing versions !

So you mean in the past there were releases were just the version number was increased without any new features or fixed bugs? Have you had a look at [the changelog](https://grocy.info/changelog) at all?

However, to conclude that again: The product option "Factor purchase to stock quantity unit" was already removed, and _every_ part related to unit conversion handling was already kind of rewritten for the next release. It most likely will have bugs for some edge cases, be warned - better don't use grocy or any software to have a bug free life.

Otherwise, please provide a reproducible example related to the current development state (pre-release [persistent/private demo instances](https://www.reddit.com/r/grocy/comments/jwnk9b) are there for that). Just again: The product option "Factor purchase to stock quantity unit" was removed, so this can be no longer the cause for this problem.

I'm going to lock this thread, since everything on-topic and off-topic has been said.
