### ISSUE TITLE
Feature Request: Bulk item purchase entry

### ISSUE THREAD

**Issue by thystra** [grocy/grocy#2177]
Please implement a screen where a whole shopping trip can be entered rapidly.  I envision this being a spreadsheet type set up with one line per item with fields.  The intent is so a user can sit down with the receipt from the shopping list and quickly add each item on the list then submit all at once.

**Comment by berrnd** [comment]
> a screen where a whole shopping trip can be entered rapidly

Exactly for that the "shopping list to stock"-workflow is there, check the "Add all items to stock"-button on [/shoppinglist](https://demo-prerelease.grocy.info/shoppinglist).

Changelog [v1.23.0 excerpt](https://grocy.info/changelog#v1.23.0):
_New feature: "Shopping list to stock workflow"_
- _Add a single shopping list item or all at once to stock directly from the shopping list_
- _There are new "stock settings" under settings menu in the top right corner_
- _You can enable there, that all products which have "Default best before days" set, are added without confirmation in this workflow_
- _=> This means, you can add the whole shopping list to stock with one click, if you want_


&nbsp;
> can sit down with the receipt from the shopping list and quickly add each item on the list then submit all at once.

Will practically not work, since due dates or not mentioned on receipts (at least on no one I have seen seen on this planet so far).

**Comment by berrnd** [comment]
What's wrong / not practical with the current workflow? Have you tried it? It works, fast. With one click when all products have their corresponding defaults for all fields. Otherwise with manual input for only any missing / not pre-populated field.

**Comment by thystra** [comment]
I'm currently building out my product list/DB.  I went shopping but not with a grocy shopping list.  So I'm sitting at the table manually adding each item to the DB, then 'purchasing it'.  If the wife goes shopping, she's not going to use the app, so I then must go back and manually make the 'purchase' based on the receipt and/or what's on the table in front of me.

**Comment by berrnd** [comment]
Using [/purchase](https://demo-prerelease.grocy.info/purchase) with enabled "Scan mode" (and a barcode scanner) would be pretty much the same as the "shopping list to stock"-workflow in regard to automatic prefilling fields where possible / defined by the corresponding product.

Sounds like a lot / double work doing it that way...

**Comment by thystra** [comment]
Ok, I will look at it. Don't have a scanner yet.
