### ISSUE TITLE
Feature Request: Move custom fields to any part of the item

### ISSUE THREAD

**Issue by martin-arg** [grocy/grocy#2180]
I like to enter a brand or a flavor for an item in a field, so I create a new custom field name brand or flavor, but they will be at the end of the item, which is not very comfortable or intuitive. So I would like to be able to change their position to the beginning of the upload sheet right after their name.

**Comment by berrnd** [comment]
Userfields are implemented in a generic way across all entities (= products, chores, a shopping list item, etc.). This means entity specific options (since every add/edit page would be different, Userfields are even rendered on pages like /purchase and so on) are not part of that and this will stay that way.

Consider using [custom JS/CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to customize everything to the very end (technically it's possible to move fields around using some JS for example).
