### ISSUE TITLE
How to add barcode lookup

### ISSUE THREAD

**Issue by bob5731** [grocy/grocy#2181]
Several years ago I had this working and set up then my computer crashed. How do I add external barcode lookup to grocy?

**Comment by berrnd** [comment]
[Once](https://github.com/grocy/grocy/issues/1929) [again](https://github.com/grocy/grocy/issues/1764): This here is the tracker for reproducible Bugs and Feature Requests, not the the place for general help questions - please finally check what's mentioned in README: https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests

&nbsp;
> How do I add external barcode lookup to grocy?

Check README also for that: https://github.com/grocy/grocy#barcode-lookup-via-external-services

Or have a look at Barcode Buddy: https://github.com/Forceu/barcodebuddy

Even more links:

https://grocy.info/addons

https://grocy.info/links

https://www.reddit.com/r/grocy/search/?q=barcode&restrict_sr=1

**Comment by bob5731** [comment]
I'm running the windows version of grocy and I followed your steps and still do not have barcode lookup. I have it working through an Android phone though. I would like to use my PC and a handheld barcode scanner to do the same. Can you give me step by step instructions please?

**Comment by berrnd** [comment]
I don't know what you want exactly (you haven't mentioned that; I haven't provided any steps, just linked plenty of information resources) and I don't know anything about Barcode Buddy or about any of the community contributed mobile since, simply since I don't use anything of that.

And this here is still not the place for help requests and even grocy-desktop is not maintained here.
