### ISSUE TITLE
Feature Request: Optimize tracking button handling on the chores overview page

### ISSUE THREAD

**Issue by karwosts** [grocy/grocy#2186]
I'm using monthly chores for a couple things, but the logic for tracking the chore does not feel right. 

For example I have a monthly chore due on the 1st of every month. It is now March 31, and my next due date is April 1. If I "track chore" today, the day before it is due, the due date does not advance, the only way I can "track" an April chore is to track it during the month of April, otherwise it keeps resetting the next date to April 1. 

I feel like the logic for this is not quite right, and it makes chores that are due in the early days of the month impossible to track early. 

If I had a chore due on the 31st, I could track that chore as complete any time in the weeks leading up to it, and it would advance to the next month, but I can't do that with a chore due on the 1st. 

Some possible ideas for improvement:
 - allow a configurable date in the monthly chore for which is considered to track for the next month, instead of the current month
 - or, if next chore due date is in month X, and it is tracked in month X-1, then move the next due date to month X+1.

**Comment by karwosts** [comment]
I'm thinking of something like a chore to pay a bill monthly that is due on the 1st. It's a chore that needs to be done once a month, before the due date. It does not need to be done _on_ the due date, just something done once a month before it is due. 

Perhaps this is just not something that can be mapped to a chore. Repeating daily / 30 days is no good because it will wander over time and not keep the due date of the 1st.

Right now I have a custom script that is spawning a Task each month to remember to do this. Was hoping I could remove that and just treat it as a recurring chore instead, but there is no existing chore that can handle this type of schedule. 

If the due date was on the 31st it would work fine, since then anytime I track it would be done for the month. Just feels weird that I can't have same functionality for a chore due earlier in the month. 

Anyway, I'm disappointed you see it that way, but thanks anyway for acknowledging and for all your hard work.

**Comment by berrnd** [comment]
> If the due date was on the 31st it would work fine, since then anytime I track it would be done for the month. Just feels weird that I can't have same functionality for a chore due earlier in the month.

Feels weird (for you), works practically just fine - I still just don't see the problem.

And also just another reality check related to the example: I guess paying a monthly bill due on the 1st is naturally most of the time not payed on that 1st, but on a day or two or whatever before to meet the condition on the receiver side. So it makes even more sense to have the corresponding task set to be due on that last day of each month (also ref #816).

For the sake of not disappointing you I've changed the following:
- Changed the handling of the tracking buttons on the chores overview page:
  - The green button now tracks an execution of the corresponding chore on the next scheduled time, rather than for now/today
  - New context-/more menu option "Track chore execution now" to track an execution for now/today (so the same what the green button did before)
- Removed the limitation on the chore tracking page that the tracked time couldn't be in the future

Translates to: Your example works now how you expect it.

**Comment by berrnd** [comment]
Pre-release demo example: https://test-r5ansb0oq2k2wvu6pu9s.demo-prerelease.grocy.info/choresoverview


https://user-images.githubusercontent.com/2161815/229199853-daf07a0d-36aa-414b-95d4-fc606e5cebae.mp4
