### ISSUE TITLE
Feature Request: Enable entry into "Manage Master Data" > Products > "Factor purchase to stock quantity unit" field

### ISSUE THREAD

**Issue by MaxOfLondon** [grocy/grocy#2188]
Currently (v3.3.2), when defining or updating a product, one have to use the adjoining spinner to set a value in the input with ID `qu_factor_purchase_to_stock` labelled `Factor purchase to stock quantity unit`.

This becomes cumbersome if a product with a considerable value is defined, for example 750g.

It would be desirable to allow the user to enter the value manually, as well as change the value with the spinner.

---
**TIP:** Workaround for desktop Chrome/FF users: To set value to 100, open development console (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>) then enter:
```javascript
jQuery('#qu_factor_purchase_to_stock').val(100)
```
---

**Comment by berrnd** [comment]
I don't really understand your problem, as of v3.3.2 the product option `Factor purchase to stock quantity unit` is editable when the `Quantity unit stock` doesn't equal the `Default quantity unit purchase` - no other restrictions / dependencies are involved.

But anyways, that's irrelevant since the product option `Factor purchase to stock quantity unit` doesn't exist as of now / any future version - please relate any Bug Reports or Feature Request to the current development state (= the `master` branch which is always available on the [pre-release demo](https://demo-prerelease.grocy.info/) for testing).

Related [preview changelog](https://grocy.info/changelog#preview) excerpt:
> - The product option "Factor purchase to stock quantity unit" was removed
>    -  => Use normal product specific QU conversions instead, if needed
>   -  An existing "Factor purchase to stock quantity unit" was automatically migrated to a product specific QU conversion
