### ISSUE TITLE
Feature Request: Recipe types

### ISSUE THREAD

**Issue by TarryDan** [grocy/grocy#2194]
(did search but didn't see this)

There should be category tags for recipes ('sandwich', 'dinner', 'snacks', 'vegan', 'special occasion' etc) for quicker filtering.

I'm using the program as a disability aid - i forget what food i have or even what I can make, so I can see a big cluttered recipe field being a sticking point, vs being able to filter "what breakfast recipes do I know" or "what can i have as a snack". 

Could be implemented as an open tags field, categories you create in Manage Data Types, or tick boxes for predictable tag types (what mealtime is this for; allergies/dietary/religious requirements)

**Comment by berrnd** [comment]
> Could be implemented as an open tags field, categories you create in Manage Data Types

This is called Userfields and it's there since [v2.4.0](https://grocy.info/changelog#v2.4.0), so since about 4 years - not only for recipes, you can add any field you want to any entity (= recipes, products, chores, shopping list items, everything) you want.

&nbsp;
> (did search but didn't see this)

Well, exactly this specific question about recipes has been asked at least in those duplicates: 
#1936
#1968
#2162
#324
#1126
#1930
