### ISSUE TITLE
Bug: API endpoint /objects/products/$ID GET vs PUT inconsistence

### ISSUE THREAD

**Issue by cniry** [grocy/grocy#2195]
API endpoint /objects/products/$ID with PUT doesn't accept GET's response as input.
It's hard to implement this endpoints because it's requirements vs responses are not consistent.

In my case, I have some userfields, which GET returns as null/array, but when I send it back to PUT, then throws: 
```
{"error_message":"SQLSTATE[HY000]: General error: 1 no such column: userfields_id"}
```

**Comment by berrnd** [comment]
Userfields have their own endpoint(s) since ever:

![grafik](https://user-images.githubusercontent.com/2161815/233634914-c51657f7-e331-45c5-8081-3cb23c0bfb49.png)

&nbsp;
> API endpoint /objects/products/$ID with PUT doesn't accept GET's response as input.

It's nowhere stated that that's the case generally, so I cannot follow how you come to the conclusion to report this as a bug.

And what is "hard" or not is at the end a kind of personal taste - grocy's web frontend uses the API for everything, so also for Userfields, and it's really not hard there pratically.

**Comment by berrnd** [comment]
> `General error: 1 no such column: userfields_id"}`

By the way: There is no column / field named `userfields_id` anywhere - so this can't be a "GET's response as input".
