### ISSUE TITLE
Bug: SQL injection in /api/stock/products

### ISSUE THREAD

**Issue by novalis** [grocy/grocy#2201]
I don't think this one is exploitable, but only because PDO SQLite doesn't support multiple statements in prepare.  But I'm not very good at SQL injection, so maybe you could do something like union the users table to get the hashed passwords for offline cracking?

Anyway, the multiple statements thing doesn't seem like a great thing to rely on; what if you later decide to support MySQL? 

Here's the URL:

https://example/api/stock/products/4);create%20table%20injection(name%20integer);select%20product_id%20from%20products_resolved%20where%20(1=1/entries

The problem is approximately here, where you create a SQL statement by concatenating a user-provided string:
https://github.com/grocy/grocy/blob/edfa404ed6b5da4609eee6a664fb5ab54c0e5aa2/services/StockService.php#L737

**Comment by berrnd** [comment]
> what if you later decide to support MySQL

I don't (ref #89), so this is in conclusion pretty much irrelevant, but kind of thanks for reporting - I've already fixed this theoretical and practically irrelvant security problem in df4907f5d43df42167cdceebf0737eaba7311b36.

As stated in this projects [security policy](https://github.com/grocy/grocy/security/policy), anything which can't be exploited unauthenticated is not relevant, since only a theoretical problem (for the target use case of this project) - please keep that in mind for any further security issue reports, thanks.
