### ISSUE TITLE
Consuming specific product

### ISSUE THREAD

**Issue by aproimadis** [grocy/grocy#2202]
Assuming there is a product with 2 or more barcodes, because it is the same product (Gin) with multiple brands (Hendrick's. Tanqueray, Bombay, etc)
From the stock overview, when you press the button to consume or open a product you should be able to choose which barcode product you want to consume or open.

**Comment by berrnd** [comment]
Barcodes are there for scanning them, they are never relevant when using buttons.

&nbsp;
> From the stock overview, when you press the button to consume or open a product you should be able to choose which barcode product you want to consume or open.

Maybe first clarfing grocy naming stuff:
- A product can have multiple barcodes
- A barcode can have an amount, store and note attached which is used to prefill that on purchase
- Regardless of which barcode you scan, it's always the same product in stock (since there is only one product)
- But there are separate stock entries, each can have a different due date, note and so on

You can of course consume each specific stock entry separately, at multiple places:
- [/consume](https://demo-prerelease.grocy.info/consume) - mind the `Use a specific stock entry` option
- Context/more menu of each entry on [/stockoverview](https://demo-prerelease.grocy.info/stockoverview) => Stock entries
- [/stockentries](https://demo-prerelease.grocy.info/stockentries)
