### ISSUE TITLE
Feature Request: Options for customize home app

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2210]
Some people maybe have not interesting manage batteries, equipments, chores or meal plans.
It would be interesting to have check box to enable/disable that sections on system preferences

**Comment by berrnd** [comment]
Since that was also my thought since the beginning, each major and minor feature set can be disabled in `config.php`:

https://github.com/grocy/grocy/blob/8bdb74a8e084232c87db5e9b312f220e576b06cf/config-dist.php#L127-L154

Ultimately you can customize the complete frontend using custom JS/CSS without the need to change any code (means all that will survive updates just fine): https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself

Since that's not the first question of that kind from you lately, I highly recommend reading README and going through all the `config.php` options once to get an overview what's general possible in that area.

Also again a duplicate-question of #1446 and #1278 and many other threads on the [r/grocy subreddit](https://www.reddit.com/r/grocy) - doing a little a search beforehand would be cool.
