### ISSUE TITLE
Feature Request: Better separation of "opened" text 

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2214]
(Please be patient. It's hard for me to find similar previous requests.)

I believe that no one has not yet suggested this.

In table grids, when an item is open, have greater text separation, for example using parentheses.
Ex: 1 un _1 opened_ => 1 un _(1 opened)_

**Comment by berrnd** [comment]
Very minor and at the end personal taste - such things are not considered to be a Bug or Feature Requests.

But, as mentioned in README and also mentioned in previous requests of you - grocy got you covered to customize every little detail to the very end using [custom JS/CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself).

Here is a snippet (for `data/custom_js.html`) which does what you want:
```html
<script>
$("span[id*='opened-amount']").each(function()
{
	var element = $(this);
	if (element.text())
	{
		element.text("(" + element.text() + ")");
	}
});
</script>
```

Will look like that:

![grafik](https://github.com/grocy/grocy/assets/2161815/97a34a5a-0510-4c77-88ce-27df6017a358)

**Comment by berrnd** [comment]
> Please be patient.

I am, always - but at some time I will running out of that patience. You've opened 7 requests here in the last couple of days, which were all duplicates or help/usage questions (which are at the wrong place here, since that's the tracker for reproducible Bugs and Feature Requests, clearly mentioned in README and on the issue template).

Don't really understand what's so hard about using that little search field here above, works pretty great.
