### ISSUE TITLE
Bug: "Factor purchase to stock quantity unit" string missing for translation

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2233]
At transifex, there's no string for "Factor purchase to stock quantity unit" translation

**Comment by berrnd** [comment]
Because that's no longer needed / part of grocy, was removed in 0229d187aedfe50446ad42887810e70ba0b86109.

When you want to do translations, the current development state (= [pre-release demo](https://demo-prerelease.grocy.info)) is the reference ([README ref 1](https://github.com/grocy/grocy#give-it-a-try), [README ref 2](https://github.com/grocy/grocy#localization)).

Related [preview-changelog](https://grocy.info/changelog#preview) excerpt:
> - The product option "Factor purchase to stock quantity unit" was removed
>   - => Use normal product specific QU conversions instead, if needed
>   - An existing "Factor purchase to stock quantity unit" was automatically migrated to a product specific QU conversion
