### ISSUE TITLE
Inventory affirmation message shows wrong amount

### ISSUE THREAD

**Issue by lukebo** [grocy/grocy#224]
Hi Bernd,
i noticed a small issue concerning the affirmation message of the inventory function.

Here are the steps to reproduce.
1) Go to "Inventory"
2) Select so product and enter a new value.
3) Enter a new best before date and hit OK
4) There is a little green affirmation box at the top right edge of the displays stating the wrong (old) amount.
I would expect, that i shows the same amount, that i just entered.

By the way, would it be a good idea to prefill the "New amount" box, so that you just have to klick the +1 oder -1 arrow? Currently, i need to look up the current amount and change it, when i "find" something new.
Keep up the good work!
Thanks!
Luke

**Comment by berrnd** [comment]
Thanks, can reproduce it...

By the way, would it be a good idea to prefill the "New amount" box, so that you just have to klick the +1 oder -1 arrow?

Sound reasonable, will also do that (while not allowing to post the same amount as currently is in stock, also need to check the API response, that's currently `null` when executing a `POST` to `/api/stock/products/{productId}/inventory` with the in-stock-amount).

**Comment by lukebo** [comment]
Hmm, but you do not have chance to change the bb date, when entering the same amount is not allowed, don't you?

**Comment by berrnd** [comment]
The best before date entered during inventory only applies to added products (as the hint above the field states).

When you mean to be able to just change the best before date of products which are currently in stock - that's as of now only possible by undoing the corresponding purchase/inventory booking and post it again. In https://github.com/grocy/grocy/issues/191#issuecomment-473299770 it is tracked to add that editing stock entries should be possible somehow.

**Comment by lukebo** [comment]
Yes, i was talking just about changing the best beforde date. however, probably not that relevant... ?
