### ISSUE TITLE
Bug: Add on apps (Pantry Party and Grocy Mobile (IOS app)) both fail with same error when attempting to add product to database when using bar code scanning.

### ISSUE THREAD

**Issue by kingswindsor** [grocy/grocy#2240]
The error is reported from both apps as an SQL error where there is no column named qu_factor_purchase_to_stock.  Screenshots attached (ignore all but top entry on Grocy Mobile log)! ![image](https://github.com/grocy/grocy/assets/7615805/bd1a4f8f-a419-4ef6-8dbd-fbfb88967975). ![image](https://github.com/grocy/grocy/assets/7615805/0a657667-7b33-401a-a1b6-550b2c6c0b4b)The product is not added to the database.

Adding a new product via the web interface works fine.  However I would like to use the barcode scanning from either Party Pantry or Grocy Mobile app (i.e. Quick-Scan).  
Reporting as a bug here as it appears to be common to the behaviour of both apps.

Grocy instance is self hosted on an RPi4 accessed via reverse proxy. Version 3.3.2
Grocy Mobile - version 2.9.0
Party Pantry- version 1.1.1
IOS 16.4 on an iPhone 13 Pro

**Comment by berrnd** [comment]
So when you're running v3.3.2 and the `products` table doesn't have a column `qu_factor_purchase_to_stock`, I really can't say what went wrong, but probably a lot. Database migrations run when visiting the root route ([README ref](https://github.com/grocy/grocy#database-migrations)) and this columns exists since ever.

&nbsp;
> Adding a new product via the web interface works fine.

So it can't be the case that this column is missing. The web frontend uses the exact same API for everything.

&nbsp;
Are you really sure you run v3.3.2 and not the current development state / `master` branch, for whatever reason? If that's the case, then this won't be a surprise, since that column no longer exists there and in any future release.

However, this is the tracker for reproducible Bugs and Feature Requests for _Grocy_, not any of the community contributed mobile apps.

**Comment by kingswindsor** [comment]
So if that column is expected by the two community apps, but it isn't there (any more), that is probably why they are not working.  
I'll report them as bugs on the Pantry Party and Grocy Mobile github pages and hope someone is able to make them work again.  If they are now incompatible with Grocy, then maybe a note on the Grocy site would be helpful.

**Comment by berrnd** [comment]
So you run the current development state / `master` branch instead of the current release v3.3.2? I hope you then take care about database migrations and everything else carefully, if you don't want to loose data at any point. As [mentioned in README](https://github.com/grocy/grocy#database-migrations), database migrations are supposed to work between release, not between commits.

So just again for clarification:

- The current release as of today is [`v3.3.2`](https://grocy.info/changelog#3.3.2) and there that column exists.
- In any future release this column will not longer exists.

I personally don't use any of these apps, but I guess they aim for compatibility with the current release, not the current development state (it's a development state, so naturally any part can change unless there is a new release).

&nbsp;
> then maybe a note on the Grocy site would be helpful.

Of course any breaking API change was and will be communicated clearly. As of today, the reference is the preview changelog where exactly that is already mentioned: https://grocy.info/changelog#preview

**Comment by kingswindsor** [comment]
"So when you're running v3.3.2 and the products table doesn't have a column qu_factor_purchase_to_stock, I really can't say what went wrong, but probably a lot."   OK I misunderstood this - I thought you were saying v3.3.2 didn't have that column so if the apps were looking for it a lot would go wrong.  

According to the Settings>>About>>System Info, I'm running v 3.3.2 released on 2022-11-12 (and PHP v 8.2.6 and SQLite v 3.34.1) so, if I understand you, the column qu_factor_purchase_to_stock should be there - despite the community apps reporting that it's not.  Sorry, I don't know enough SQL to check the columns.   

I'm just trying to get Grocy up and running for the first time so database migrations are not an issue for me at the moment.

**Comment by berrnd** [comment]
Doesn't seem anything useful turns out here, but I try it one last time:

How have you installed Grocy? Checked out manually from GitHub? Used the official release ZIP?
By that the web frontend works and any app not with the mentioned error, I can only guess you don't run v3.3.2, it would produce exactly that (at least).

v3.3.2 is the current release since about half a year, on that particular column nothing has changed since years. Kind of a surprise that nobody else has noticed exactly that problem so far, at least there are no reports about it, when this should be a generic problem with both mentioned apps.

&nbsp;
> I thought you were saying v3.3.2 didn't have that column

Haven't said that anywhere. Can also be easily verified by simply using the stable public demo: https://demo.grocy.info/api/objects/products

&nbsp;
> According to the Settings>>About>>System Info, I'm running v 3.3.2

When you checkout and use the `master` branch that would be the same, since that information is contained in and displayed from [`version.json`](https://github.com/grocy/grocy/blob/master/version.json). But you, and most likely only you, can know how you installed it.

&nbsp;
> I'm just trying to get Grocy up and running for the first time so database migrations are not an issue for me at the moment.

Not correct, the database is always populated by running migrations, there is no other way to do that.

&nbsp;
> PHP v 8.2.6 

Also that can be a problem: [README](https://github.com/grocy/grocy/tree/v3.3.2#how-to-install) and [changelog](https://grocy.info/changelog#v3.1.0) clearly mention that since v3.1.0 only PHP 8.0 is supported.

&nbsp;
So to finally answer if you really have v3.3.2 or not, if you can't answer the question about how you have installed grocy:
Have a look into the `migrations` folder.
If that folder contains files up to `0202.sql` ([release ref](https://github.com/grocy/grocy/tree/v3.3.2/migrations)), you run v3.3.2.
If it contains more, you don't run v3.3.2 ([master branch ref](https://github.com/grocy/grocy/tree/master/migrations)).

&nbsp;
And also just once again: No community contributed apps are maintained here.

**Comment by kingswindsor** [comment]
OK, we are not all software developers and could do without the condescending tone, but thanks for your help anyway.  I've done a re-install to be clear on what steps I went through originally and troubleshoot.   

So, using an RPi 4 with 4Gb RAM, installed RPi OS Bullseye followed these instructions on the Grocy website.   [https://othmanalikhan.github.io/installing-grocy-on-a-raspberry-pi-with-apache](url)     

Needed to install separate repository for php on Bullseye .  Used 
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list

Installed php8.0 and various php8.0 extensions (more than those in the referenced instructions) - by trial and error with php compose and some Apache2 error messages, I also installed -curl, -xml, -sqlite3 and -zip to get it working.  

The instructions include:
sudo git clone https://github.com/grocy/grocy.git
which installs the Master release as default - which seems to be the problem for compatibility with the community apps.

When this runs after configuring Apache2 etc, http://<MY_IP> says
Unable to run Grocy: PHP 8.1.0 is required, however you are running 8.0.28
This is what I had before and set me off on the path to install a later version of php.  

So I deleted the existing /var/www/grocy directory and did
sudo wget https:/releases.grocy.info/latest and unzipped back into /var/www/grocy
Then got it to work again locally and via the reverse proxy.

Re-did the API in the Grocy Mobile (IOS) and Pantry Party apps and they work without throwing up errors.    I guess they will stop working with future releases if the qu_factor_purchase_to_stock column is not going to be present.

**Comment by berrnd** [comment]
> The instructions include:
> sudo git clone https://github.com/grocy/grocy.git
> which installs the Master release

Of course that installs / "downloads" the current development version / `master` branch..
The referenced websites also mentions above exactly that command:
_Clone the **_bleeding edge_** release of grocy_
So this pretty obviously sounds like you blindly executed commands found on a random site on the internet, which is of course and always the best thing to do in general.

&nbsp;
> Unable to run Grocy: PHP 8.1.0 is required, however you are running 8.0.28
> This is what I had before and set me off on the path to install a later version of php.

So belated congrats on that: The message clearly says PHP 8.1 is required and you'd installed PHP 8.2. 🤦

&nbsp;
Before I'll close this here, since it finally turns out nothing useful:
[README mentions](https://github.com/grocy/grocy#how-to-install) the minimal instructions needed to set up Grocy. For all those not so technically affine (which is totally fine), [multiple Docker images](https://github.com/grocy/grocy#how-to-run-using-docker) and also [grocy-desktop](https://github.com/grocy/grocy-desktop) is available, both also mentioned in the same README. Don't know why you prefer the (for you - again: that's totally fine) hard way instead. But reading README is a requirement, which obviously was the problem here - not so much pity from my side on that.
