### ISSUE TITLE
Feature Request: Prevent insane amount of labels being printed

### ISSUE THREAD

**Issue by TinkerTob** [grocy/grocy#2241]
Hi,

I just had to pull the plug on grocy because my label printer started spitting out an insane amount of labels. This is due to me making a small mistake when using the label printing option on the purchase page.

I'm tempted to make this a bug report, but I guess grocy was working as intended... Still, I would very much appreciate if this could be prevented from happening again.

### Steps to Reproduce
I just added (purchase) a pack of cream with a preset QU of 200 ml per pack. And I accidentally set label printing to "Label per Unit", because I want to label each pack of cream with its due date.

### Expected behaviour (my expectation, at least)
One label, for the pack of cream. Two labels, if I had bought two packs of cream. 

### Actual behaviour
200 labels. Well, at least it would have been 200 labels, if I hadn't manually pulled the plug...

As I said - user error. "Unit" is obviously a stock unit, not a purchase unit. But still, it's easily avoidable. 

Thus, my
## Feature request:

1. Split the option in two: Not just "Label per Unit" but "Label per Stock Unit" and "Label per Purchase Unit" (if the two differ).
2. Introduce a sanity check: If it's more than 5 ( / 10) labels being printed, please ask. "Do you REALLY want to print 200 labels? <Yes> <No>"

Thank you!

**Comment by berrnd** [comment]
Stock entry labels are thought to be uniquely identify a stock entry. Means instead of manually searching for exactly that Pack of Ice Cream you've taken that time, out of the x ones you have at home, you put a sticker on them (on purchase) and scan that on consume.

So when you want to do that with Ice Cream, it practically really doesn't make sense to have the product's `Quantity unit stock` set to `ml`, unless you really put a sticker on each `ml` (however that would be practically possible at all).

&nbsp;
> but I guess grocy was working as intended
> As I said - user error.

Right, bullshit in = bullshit out, or, expressed politically correct, [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) - the base principal everything in Grocy is based on.

**Comment by TinkerTob** [comment]
Dear Bernd,

please don't take this personal - I get that this is your project, I am grateful for you making it public and I appreciate all the work you put into it. Also, thank you for fulfilling my other request so quickly.

However, I feel like you're being a little bit harsh here (and in other issues you've closed down).

First: 
> Right, bullshit in = bullshit out, or, expressed politically correct, [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) - the base principal everything in Grocy is based on.

Part of my suggestion was:
> Introduce a sanity check: If it's more than 5 ( / 10) labels being printed, please ask. "Do you REALLY want to print 200 labels? "

I don't see how a small sanity check - "if (X > 10) {popup("really!?!")}" would change anything about that policy. In fact, I see no downside to it at all. On the contrary, it is usually considered good practice to foresee and adress possible user errors.

And even if you don't see the usefulness and if you're not willing to take the time to include this - why not just tell me and leave the issue open? This way, I (or others) might be motivated to solve it, create a pull request and over time become contributors to your project. In another issue, I thought I detected some frustration on your end because you're having to do all the work alone... Well, right now, I feel like you don't want anyone to chime in.

Second:
> Stock entry labels are thought to be uniquely identify a stock entry. Means instead of manually searching for exactly that Pack of Ice Cream you've taken that time, out of the x ones you have at home, you put a sticker on them (on purchase) and scan that on consume.
> 
> So when you want to do that with Ice Cream, it practically really doesn't make sense to have the product's `Quantity unit stock` set to `ml`, unless you really put a sticker on each `ml` (however that would be practically possible at all).

My use case is: In just about all recipes (not only talking about those added to grocy, where QU conversion can do the trick!), cream ("Sahne", not ice cream) is given as ml, so when I need to check how much of it I have in stock, it makes sense to have the stock units set to ml.
And I don't use the labels to identify "that specific ml of cream" - I use it, so i can see "this specific pack [holding 200 ml] of cream" expires in one week" at a glance, instead of picking it up and searching for the tiny print. The barcode is actually secondary - it would be sufficient if it was the product barcode, no stock entry barcode required for my use case. The Due Date however would be unambiguous, as the labels would be printed on purchase and there's only one due date to be entered on the product page.

I would be happy to take this on myself sooner or later, if you see it as a waste of time. However, you closing down this issue without due consideration would force me to create a fork instead of contributing to this project, and I feel like this would be a waste since I see absolutely no harm in these changes.

Soo.... as a suggestion... maybe don't set issues to `wontfix/out-of-scope` and close them when it's just a case of "i don't think that's necessary [even tough it would hurt noone]", but instead set them to something like `contributions-accepted` and leave them open?
Of course, if there actually was potential for harm in a suggestion, that's another matter. But in these cases, it would be great if you could actually give those reasons instead of being unfriendly to someone who's taken the time to give you feedback and suggestions.

Again, thank you for the work you're doing here and please don't take this rant personally. I just felt it had to be said.

Best regards,
Tobias

**Comment by berrnd** [comment]
>if you're not willing to take the time to include this - why not just tell me and leave the issue open? This way, I (or others) might be motivated to solve it, create a pull request and over time become contributors to your project.
> In another issue, I thought I detected some frustration on your end because you're having to do all the work alone... Well, right now, I feel like you don't want anyone to chime in.

Over the past 6 years Grocy (and other projects), it practically turned out that drive-by-contributions at the end most of the time take more time than just doing it myself. Changes need to be maintained over a longer time, side effects need to be considered, that's just so often missing. Which is of course ok, but brings practically only frustration, something I don't need for a hobby project. Having fun working on Grocy slowed down recently due to that, posts like yours here (and several other things).

&nbsp;
> would force me to create a fork

Looking forward to that. There were at least 3 other big announcements about a "so much better and just right Grocy" in requests like that over last couple of years. What I've always said there is still true: When such a fork finally exists and is just so much better, I'm the first one switching to that (and I would finally have a place where to put my personal rants). I have a lot other app ideas which maybe then get more attention. As of today, nothing more than an announcement happened in all those cases.

&nbsp;
> Soo.... as a suggestion [...]
> instead of being unfriendly
> please don't take this rant personally

Thanks for all the suggestions, but no. And I'm never unfriendly here, just always clear, without flowery words, since that's who I am. You don't need to like me or Grocy and not using Grocy solves all those problems for you, it's really that easy.

And please reconsider where to put such personal rants, this here is the wrong place for that, definitely and even if you have a feeling that _"it had to be said"_. And even if you say _"don't take this rant personally"_, it's personally - kind of those flowery words I meant. I'm not obligated to accept anything for Grocy and owe no single Grocy user anything. Sometimes I regret that I started this project / made it public and I ask myself once again why I take the time to answer such rants, instead of just deleting that bullshit. Bye.

**Comment by berrnd** [comment]
The amount of "Label per unit" stock entry labels (on purchase and inventory) is now displayed, to help prevent printing a lot of labels where this maybe is not intended:

![grafik](https://github.com/grocy/grocy/assets/2161815/bee77247-ad3f-471a-9847-30a1b6c6d2a8)
