### ISSUE TITLE
Feature Request: PHP 8.1 support

### ISSUE THREAD

**Issue by Atemu** [grocy/grocy#2251]
Hi, this is less of a technical issue and more of a heads-up:

[Nixpkgs has marked Grocy as broken in its rolling channel](https://github.com/NixOS/nixpkgs/pull/232276) because PHP8.0 will go EOL before the next stable release goes EOL in ~one year. PHP8.0 also depends on legacy openssl meaning that users must currently need to set a special insecurity exception for Grocy.

Other distros might have similar timelines and constraints.

I see that master notes 8.1 support in the README. Could you create a new stable release with 8.1 support so that we can unbreak Grocy?

**Comment by berrnd** [comment]
> I see that master notes 8.1 support in the README. 

Not only [README](https://github.com/grocy/grocy#platform-support), also the [preview changelog](https://grocy.info/changelog#preview) mentions that PHP 8.1 (and only PHP 8.1) will be supported for the next release.

&nbsp;
> Could you create a new stable release with 8.1 support

Gladly clarifying that here once again: The next release will support (only) PHP 8.1. There were and will be never schedules about when that will be ([README ref](https://github.com/grocy/grocy#roadmap)).

&nbsp;

For the rest I don't really I understand why it's needed to going crazy about a runtime EOL date a longer time ahead. I personally even more don't understand the _practical_ (security) issue running that (in most likely isolated environments / containers) beyond that date. For Grocy I only care about the practical issues, not the theoretical ones. What's your fear on what will happening at the end of November?

Funfact: Here and on the [r/grocy subreddit](https://www.reddit.com/r/grocy) there are kind of weekly reports about upgrading issues (e. g. [that of yesterday](https://www.reddit.com/r/grocy/comments/143d7dc)) where the issue is using PHP 7.2 or older. For Grocy practically this caused so far problems like mentioned in the just linked report, but never real world relevant security issues. Even when there is no new Grocy release before that PHP 8.0 EOL date, the world will (most likely, at least I guess and hope) don't stop spinning and Grocy v3.3.2 will work just fine.

**Comment by Atemu** [comment]
>  don't really I understand why it's needed to going crazy about a runtime EOL date a longer time ahead

It's just about being prepared. In the end of November, all PHP8.0 packages must be either upgraded to 8.1 or marked as broken/removed because that state will be the stable release for the next 6 months and we don't ship EOL software. Things that go EOL during that time, must be removed beforehand.

We're just a bunch of volunteers with no real commitment; getting things rolling early helps getting things done.

> in most likely isolated environments / containers

That is not an argument for ignoring security issues. We don't know what people use Grocy for or in which environments. People might be exposing their instance to the internet; without any containerisation or hardening. Letting them run known insecure or unmaintained software would be negligence and a breach of trust IMO.   
Additionally, we don't only carry PHP for Grocy. We have many other PHP projects packaged and wired up into NixOS too; applications where you can't reasonably expect to only be used in private settings.

Even then, arguing that potentially vulnerable software is fine because it's running inside a container is dangerous thinking and we don't support it.  
I highly doubt we're the only distro with this mindset, hence the heads-up.

> where the issue is using PHP 7.2 or older

I don't see why Grocy should care about software that has been deprecated for >3 years and unmaintained for >2. If not even its own developers want it, how can you be expected to support it?

If some stale distro takes on the burden to maintain it further, alright but then it's also up to them to make Grocy work with their internal PHP, not Grocy.

> Even when there is no new Grocy release before that PHP 8.0 EOL date, the world will (most likely, at least I guess and hope) don't stop spinning and Grocy v3.3.2 will continue to work just fine.

That only works as long as distros continue to ship PHP8.0. Given that it's EOL this November, any sane distro will drop PHP8.0 dependant software beforehand.

**Comment by berrnd** [comment]
Whatever, once again: Grocy will support PHP 8.1 with the next release and there is no date for when that release will ship.

If you / the project / the distro decides to not ship a PHP version for whatever reason at a point in time, then that's IMHO the wrong distro for the corresponding software. There is far more real world software requiring outdated runtime dependencies (not limited to PHP) on that planet and enforcing what "your" users should use is honestly kind of crazy, at least not open at all. I have never used a distro / operating system limiting me on what software I want to run on it and I will happily continue to do so.

I don't care if NixOS is compatible with Grocy now and in the future and don't have a release schedule that I could arrange with your loved EOL dates. Grocy has and will always support a reasonable up to date runtime, not bleeding edge, not stone age - just how I handled that since 2017 for this project. Development is sometimes faster, sometimes (as currently) slower due to reasons. I'm also just that volunteer doing this here for fun as one of my hobbies and I don't arrange hobby schedules with any EOL dates.

Closing this since all has been said on that topic.
