### ISSUE TITLE
Bug: Grocy Hosted Demo Environment down

### ISSUE THREAD

**Issue by georgegebbett** [grocy/grocy#2254]
https://en.demo.grocy.info/ is giving me a 502

**Comment by berrnd** [comment]
And how is this related to a Grocy _Bug_, hence what's the point of reporting this here?

The demo instance have no uptime guarantees in any manner, they can be down due to maintenance on my side and everything else (and no worries, I have proper monitoring so I'm always and everywhere aware of how each and every part of my infrastructure performs).

If you rely on the demo instances for development or anything else, that's the problem.

**Comment by georgegebbett** [comment]
I just wanted to make sure you were aware - I apologise if this is the wrong forum - yes I use the demo instances for my own development but I was just trying to alert a fellow developer, just in case, whilst staying away from the subreddit for the various reasons that people are avoiding Reddit at the moment. 

Apologies, I won't do this in future...

**Comment by berrnd** [comment]
> I use the demo instances for my own development

Which is not the intended use case of those instances. The downtime today was in fact due to monitoring improvements regarding abuse of those instances. There were way too much above "I just want to try Grocy" resource usage patterns, especially in the last couple of weeks. I don't host private use case Grocy instances for free there.
