### ISSUE TITLE
Feature Request: Optimize sidebar scroll bar content spacing (on Chrome)

### ISSUE THREAD

**Issue by 1bubble1** [grocy/grocy#2255]
I don't know if this can be called a bug, but it's more of a UI issue.

Screenshots:
https://ibb.co/gVqXRSP
https://ibb.co/xYWsWk9

The problem remains even after increasing the width of the web browser window.

**Comment by berrnd** [comment]
Since everything you see in your Browser is dependent on exactly that Browser, which Browser is that?

Looks pretty ok on recent Firefox:

![grafik](https://github.com/grocy/grocy/assets/2161815/5dd247fd-08fe-46e5-8790-c5052b9c8714)

&nbsp;
> I don't know if this can be called a bug, but it's more of a UI issue.

Right, that's by far not a problem that breaks something and rather a very minor cosmetic thing, so please don't report such insignificant "problems" as a Bug in the future.

&nbsp;
And it seems that we had that 5 years ago: #15

**Comment by 1bubble1** [comment]
1. It's Google Chrome, last version (114.0.5735.134).

2. Then sorry for duplicating. 
Where can I report such cosmetic things in the future?

**Comment by berrnd** [comment]
>  Where can I report such cosmetic things in the future?

If it's something like this, then of course here, but as a Feature Request (a _Bug_ is something that breaks something or makes something impossible to do, not a minor UI glitch). If it's even more minor, then nowhere would be the best place, since I don't care.

**Comment by berrnd** [comment]
Seems that this is caused by that Chrome dropped `overflow: overlay;` support in 2021 or so, for whatever reason.

I've added a workaround to show the sidebar scroll bars only when hovering the sidebar (they will still be displayed outside of the sidebar in those Browsers):

https://github.com/grocy/grocy/assets/2161815/686cf0da-116e-435c-8adc-4dd76a81f3b7

If someone has a better solution on this, feel free to propose it.

**Comment by 1bubble1** [comment]
It's still bad layout, see: https://ibb.co/Yfs2trC :\
If I had skills, I would fix it. Open this issue please

**Comment by berrnd** [comment]
1. Make sure to test unreleased stuff on the [pre-release demo](https://demo-prerelease.grocy.info/), it's not a surprise that unreleased things are not yet available on the stable demo ([README ref](https://github.com/grocy/grocy#give-it-a-try)).
2. This here was about the sidebar scrollbar "problem", nothing else - you're screenshot doesn't even shows that scrollbar due to enough viewport height.
3. "bad layout" is at the end also dependent on personal taste, so would be cool to specify what exactly is "bad" (in a separate request if it's not about the sidebar menu scrollbar, since one topic per request).

**Comment by 1bubble1** [comment]
The pre-release looks good. 
But it will still be necessary to change the bar somehow differently. 

Ok, when I can fix the bar, I will open a new issue or write here, thanks.
