### ISSUE TITLE
Bug: Releases website 502 Bad Gateway

### ISSUE THREAD

**Issue by KimpiegamesYT1** [grocy/grocy#2273]
When trying to download the latest release (button from homepage) it gives an 502 Bad Gateway error

Site: https://releases.grocy.info/latest

![image](https://github.com/grocy/grocy/assets/76051904/12561c76-6a09-4890-8c07-dbc13be284f5)
-
![image](https://github.com/grocy/grocy/assets/76051904/2e761fd6-1ad1-4010-a2a4-230c06a951cc)
-
![image](https://github.com/grocy/grocy/assets/76051904/e6e8db8a-eacf-41c3-ac11-e95c515f4f01)

**Comment by berrnd** [comment]
This is the tracker for reproducible Bugs and Feature Requests for Grocy, as mentioned on the issue template and [in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) - this is neither of them.

There are no uptime guarantees on the by me provided infrastructure hosting `grocy.info` and everything related to that (see also https://github.com/grocy/grocy/issues/2254#issuecomment-1594876729).

**Comment by berrnd** [comment]
Btw: The overall uptime of `grocy.info` since 2017 is, according to my monitoring: 99.974 %

Translates to: The website (and/or demo instances) was down for about 2 hours per year or about 12 hours in total since 2017. So sorry, that's really a big bad problem I'm rather going to solve immediately I guess.

Just for you, since all your recent requests on that topic in less than an hour still show a big urge: https://releases.grocy.info/latest is up again! Grab your release now!

**Comment by KimpiegamesYT1** [comment]
Thanks for the quick response. i appreciate your work.

**Comment by tteck** [comment]
It's reproducible now.

**Comment by berrnd** [comment]
> It's reproducible now.

Just like yesterday (mentioned above here) there is still no uptime guarantee for everything related to `grocy.info`.

And this is also still the tracker for reproducible Bugs and Feature Requests for Grocy, so please don't report unrelated "problems" in the future at this place, thanks.
