### ISSUE TITLE
Feature Request: Redirect the user away from login page if user already logged in

### ISSUE THREAD

**Issue by TurnrDev** [grocy/grocy#2274]
My Grocy bookmark was accidentally bookmarked to the login page, but I already had a session. This caused me to need to log in every time as the page didn't check if I already had an active session and redirected me.

Let's add functionality to solve that.

**Comment by berrnd** [comment]
I already took care of that, about 5 years ago or so.

Config ref:
https://github.com/grocy/grocy/blob/9ae7c72e876b6418a8a4bce55c1bae9c1ccdff7f/config-dist.php#L73-L76

Code ref:
https://github.com/grocy/grocy/blob/9ae7c72e876b6418a8a4bce55c1bae9c1ccdff7f/controllers/SystemController.php#L26-L39

&nbsp;
> My Grocy bookmark was accidentally bookmarked to the login page, but I already had a session. This caused me to need to log in every time as the page didn't check if I already had an active session and redirected me.

As just mentioned, all that already works, when you use / bookmark the root route ([`/`](https://demo.grocy.info/)) instead of any specific page, that's at least what makes the most sense practically.
