### ISSUE TITLE
Bug: grocy/Equipment/add Freases the instalation even the demo site

### ISSUE THREAD

**Issue by dorjor** [grocy/grocy#2291]
Bug: grocy/Equipment/Add freezes the program, even the demo site! the feature works but after a long waiting time; the interactions with the equipments created are also very slow.

**Comment by berrnd** [comment]
Please provide reproducible steps as mentioned on the issue template, it's impossible to fix anything without that.

It works (and is not slow):

https://github.com/grocy/grocy/assets/2161815/2c56362c-2c1f-4631-a695-1f158d82db2f

General performance of the demo instances can of course vary, those are provided without any warranties on that at all, so nothing to report on that topic here. For the rest performance of course depends on your server and client speed. E.g. using a the by a lot loved Raspberry Pi as a server and/or client would naturally lead to a not so fast experience, but that's also not really a surprise. But you also haven't mentioned any details (PHP / SQLite  version and all the rest) of the environment in question, so I can't help there either.

**Comment by berrnd** [comment]
Cool, the probably 105th problem Safari-only problem. Avoiding this Browser prevents headaches.

In any case, the output of the Browser console would be needed to track down what's happening - I only optimize/test Grocy for current Firefox and Chrome (includes Edge).

**Comment by berrnd** [comment]
I've just tried that on the recent Safari on macOS:
- [`/equipment`](https://demo.grocy.info/equipment) loads just fine
- The "Add"-button makes the browser hang indefinitely, as shown in your screenvideo
- Loading/accessing [`/equipment/new`](https://demo.grocy.info/equipment/new) manually works just fine

The "Add"-button is nothing more than a link to `/equipment/new`, so even more strange. There is also no output in the browsers's developer tools at all. I will not invest any more time in Safari-only problems of any kind.

[Platform support](https://github.com/grocy/grocy#platform-support) has been expanded that only Firefox and Chrome/Edge will be officially supported (that was practically the case since ever), so in conclusion this report is now completed as out of scope of this project.
