### ISSUE TITLE
Feature Request: Make it possible to fix stock_log history of already consumed entries

### ISSUE THREAD

**Issue by alkuzman** [grocy/grocy#2295]
I create this issue as a discussion point since I don't have a complete idea of how it should be solved.

# Issue
Since the latest release and the new Stock Reports feature (thank you very much for the contribution) I realized I had nasty errors since I started using Grocy. Products have prices of 4000 Eur instead of 4 Eur. This results in a Report where 40% of the money had gone to one product only, all the rest have 0%. I fixed these issues directly in the database but it was quite time-consuming if you want to make sure that the stock and stock_log tables remain completely consistent.

# Request
Make it possible to fix old price and amount mistakes.

# Solution
I was thinking about two possible solutions which I will not discuss in detail since I don't have the whole picture right now.

1. Keep all stock entries (even ones with 0 amount) just filter them in the Frontend. This might require also keeping the initial amount (before consumption or transfers).
2. Allow more advanced editing/creating/undoing of transactions. This can end up problematic in so many ways :skull:

**Comment by berrnd** [comment]
> Allow more advanced editing/creating/undoing of transactions. 

Undoing a transaction undoes everything, redoing it (properly) fixes everything. I don't know what "more advanced" could ever be. Grocy can't auto-guess / fix inputted bullshit of any kind ([GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out)). So concludes to: Incorrect transactions can already be fixed by simply undoing/redoing them.

And when you have thousands of wrong stock transactions this can of course take time if you want to have it fixed, but again, bullshit in = bullshit out. Maybe simply ignore or discard the stock journal completely in that case (or even restart your Grocy journey).

**Comment by alkuzman** [comment]
This issue is that it is not all wrong, it is only 1 transaction on purchase. However, undo is not really possible (or I don't know if it is) since many correct transactions (consume/open/transfer) were done after that first transaction. So if the entry still existed it would be possible to change the price as now it is possible to take the last price fixed here: https://github.com/grocy/grocy/issues/2292. Or maybe make it possible to add edit transactions for given stock_id.

### Question
Do I have to discard my whole log for and price history for 1 or 2 purchase mistakes? Is there a way to discard specific history? 

Also, I cannot completely prevent them from happening since I am not the only one who uses Grocy in our household. I guess one way would be to build an AI scanner that will recognize the product size, read the product price from the receipt and create the transaction. I am sure that one will make mistakes too. Also, bugs happen in Grocy itself not to say some prefer to use Grocy Android for scanning for example (great work by the way) which can introduce additional problems (bugs).

**Comment by berrnd** [comment]
> This issue is that it is not all wrong, it is only 1 transaction on purchase. However, undo is not really possible (or I don't know if it is) since many correct transactions (consume/open/transfer) were done after that first transaction.

Simply mind and use that button on [/stockjournal](https://demo.grocy.info/stockjournal):

![grafik](https://github.com/grocy/grocy/assets/2161815/a03edff5-076b-4e1c-89b3-c51e8e0e1130)

Naturally any subsequent/dependent transaction(s) would also be needed to be undone if you want to fix everything. The base problem is just about that you obviously didn't care before - once again: [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out).

&nbsp;
> Do I have to discard my whole log for and price history for 1 or 2 purchase mistakes? Is there a way to discard specific history?

Sounds like you're familiar with editing a database manually, simply delete/edit any `stock_log` entry you want, this won't affect anything, it's just a journal and the base for calculating historic stuff (also ref #64).

&nbsp;
> Also, I cannot completely prevent them from happening since I am not the only one who uses Grocy in our household.

So sounds like you need something which auto detects any practically possible error and maybe also auto-fixes that. That's rather something for an external tool / integration, feel free to build that. Having wrong prices, or something else, in Grocy for probably years, or at least a long time, without noticing that sounds for me just that you practical don't care at all. So maybe a reconsideration if you really want to track prices in Grocy (or if you need Grocy at all) is what's missing at that point.

**Comment by alkuzman** [comment]
It does not matter whether something like this can be done for me, at least. But not all in my household and others that probably use Grocy know how to manipulate database or code. I could make a tool, but it won't be nicely integrated to be used by non technical people. 

However, if we decide to use Grocy, that means it is useful for us, and we don't have a problem spending the time fixing things since it is a bigger problem for us not using it (I am greatful for your contribution).

> Having wrong prices, or something else, in Grocy for probably years, or at least a long time, without noticing that sounds for me just that you practically don't care (or need that) at all.

I am sure you also have products that you use or buy rarely. For me, it was Almond Oil, which I use to lubricate particular musical instruments. I have to buy it every 2 years and consume a very small amount, which I do with NFC tag by executing a Chore (great feature, btw). So I don't check its price and stock very often, but I want to be reminded to buy a new one.

# My Issue
As I said in the beginning in the Stock Reports, it said that I spent 33% on this product, which is crazy, rendering this feature unusable for me.

I guess as I have hadfull of products that I don't buy on regular basis also others have. On the other hand, the stock reports feature will help detect such problems quickly, and maybe better fixing system won't be necessary. Time will tell.

**Comment by berrnd** [comment]
Whatever once again to conclude this:

You have wrong stuff entered and fixing this is pretty easily doable when undoing/redoing the corresponding stock transaction(s).

Doing that years later when having a lot subsequent/depended transactions is making this naturally harder, but bullshit in = bullshit out, that's the base principal Grocy is built around.

If you don't notice entered bullshit in a reasonable time frame, it's rather likely you don't care about the tracked details (prices for at least that product) at all.

And no, I don't have products where I care about prices and noticed wrongly entered stuff only years later.

Nothing will be changed or added for this, just one more time: Undoing/redoing of any stock transaction is possible (since kind of ever).

If that's a breaking point for you, maybe Grocy is not the right tool, nobody on this planet is forced to use Grocy and sometimes another (or no) tool just fits the personal use case better.
