### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Ofloo** [grocy/grocy#2306]
Upgrade from versiohn 3.3.2 run update.sh && chown -Rh www:www  ./* from the grocy directory

```
=> /var/log/nginx/access.log <==
10.x.x.x - - [13/Aug/2023:14:47:26 +0200] "GET /stockoverview HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0" "-"

==> /var/log/php-fpm.log <==
[13-Aug-2023 14:47:26] WARNING: [pool www] child 18520 exited with code 124 after 168.314027 seconds from start
[13-Aug-2023 14:47:26] NOTICE: [pool www] child 99184 started

==> /var/log/nginx/access.log <==
10.x.x.x - - [13/Aug/2023:14:47:26 +0200] "GET /favicon.ico HTTP/1.1" 499 0 "https://grocy.xx.xx/stockoverview" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0" "-"
```

1. Tried increasing max_execution_time too 600, "without success."
2. Tried upgrading to 4.0.0 instead going to 4.0.1 right away, "without success"
3. Tried manually removing grocy direcory and moving data directory from previous installation and emptying viewcache without success
4. Checked php version and sqllite version, checked if no libs where missing.

**PhpInfo shows:**
1. PHP Version 8.2.8
2. pdo_sqllite 3.42.0
3. gd 2.3.3, ctype enabled no version
4. fileinfo enabled no version
5. json enabled no version
6. intl 73.2, tzdata version 2023c, unicode verison 15.0
7. mbstring libmfl 1.3.2, regexp oniguruma 6.9.8
8. zlib 1.2.13

NGinX 1.24.0_11,3
![afbeelding](https://github.com/grocy/grocy/assets/2203497/fb81853d-9f2b-4e4b-a1d7-62671ef105b5)

os: FreeBSD 13.2-RELEASE-p2

Side note change the header of your update script to "#!/usr/bin/env  bash" not every nix system has it under /bin/bash

I'll do a docker test in a bit I'll let you know the result.

**Comment by berrnd** [comment]
Please be so kind and do a little search beforehand, everything about performance related problems regarding v4.0.1 is explained in #2297 and all the other there referenced threads.

It's about having (a lot of) redundant default quantity unit conversions conflicting with the new indirect/transitive unit conversion feature since v4.0.0 - [changelog](https://grocy.info/changelog#v4.0.0) excerpt:

> - _Explained by a practical example: When a conversion between Teaspoons and Milliliters and another one between Milliliters and Liters exists (and so forth; unlimited levels), Grocy can now calculate Teaspoons to Liters (before a direct conversion definition between Teaspoons and Liters was required)_
> - Heads up: If you have such "each to each absolute conversion definitions" currently (for the example above the conversion between Teaspoons and Liters), you should clean them up, since they are no longer needed

So either try cleaning up your default unit conversions or otherwise wait for the next release, which will be all about fixes for those performance problems.

**Comment by Ofloo** [comment]
I'm wondering if this is now fixed in version 4.0.2 as this was released a week ago?  You've suggested that these issues would be resolved in the next release. However when I perform the update script, all of the above issues are still present. So do I wait until 4.0.3 or .. open a new bug or what.

**Comment by berrnd** [comment]
I've only guessed it's related to that, since that was most performance issues were about - you've provided no real details at all to give a more thorough answer.

Triple check you've did what the changelog mentions (removing redundant default QU conversions), then feel to provide a fully reproducible example, it's impossible to fix anything without that. And yes, the next release will contain at least one further enhancement about performance things (see the [preview changelog](https://grocy.info/changelog#preview) if you're interested).

**Comment by Ofloo** [comment]
Well I'm not sure what kind of information you expect, all I can show you is what you log or debug. You should include more verbose logging so there's more details. I'm willing to run commands or whatever. But you need to indicate what information you want.

The upgrade just hangs after upgrade and times-out that's exactly what you've indicated in the other bug.

**Comment by berrnd** [comment]
And I don't know what you expect that I should fix by having nothing reproducible. Grocy v4.0.2 runs just fine for thousands of users, so it's more than obviously about a special edge case or server configuration you have.

Since you wouldn't have the problem when I wouldn't have created this project, it's of course my fault. So if you expect I owe you personal support, feel free to send me your database and I will invest hours for having a look, as I did many times so far, even if it turned out most of the time that it was about not reading what's mentioned in README or the changelog - pretty frustrating, but again my choice as I created Grocy. Of cource for free in my spare time.

&nbsp;
> You should include more verbose logging so there's more details

In the case of timeout problems (when it "hangs") it would exactly log nothing then, since it "hangs". If you know how to technically log anything useful in such cases, feel free to tell me (and the world; this would make a big difference in not only Grocy I guess) how to do that.

**Comment by berrnd** [comment]
> Tried upgrading to 4.0.0 instead going to 4.0.1 right away, "without success"

And just to add: As pretty clearly mentioned in the referenced issue and also on the changelog, the known problem was resolved in v4.0.2. So if you haven't tried, for whatever reason, to upgrade from v3.x to v4.0.2 "right away", simply give that a test drive.

**Comment by Ofloo** [comment]
I did that upgrade doesn't work. But sounds to me that you have no intention or interest to figure this out.

**Comment by berrnd** [comment]
And it sounds to me that you're not interested in the same way and just want to have your problem fixed, without trying to understand or help what it is about. Again: Grocy v4.0.2 runs fine for thousands of users, so it can't be a general problem.

Whatever, I'm tired for such requests and it's even not the first time with us here. The only alternative for you is then to stay with v3.x or not using Grocy at all I guess. I would prefer if you do the later. Bye.
