### ISSUE TITLE
Bug: the application always respond with HTTP 302

### ISSUE THREAD

**Issue by Procsiab** [grocy/grocy#2307]
After updating the Docker images for front-end and back-end to version `4.0.1-0`, the following happens to whatever HTTP request is sent to the front-end:

```
2023-08-14T14:31:26.320503132+02:00 stdout F 10.0.2.100 - - [14/Aug/2023:12:31:26 +0000] "GET / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0"
2023-08-14T14:31:26.604822853+02:00 stdout F 10.0.2.100 - - [14/Aug/2023:12:31:26 +0000] "GET /stockoverview HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0"
2023-08-14T14:31:26.844891370+02:00 stdout F 10.0.2.100 - - [14/Aug/2023:12:31:26 +0000] "GET /login HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0"
2023-08-14T14:31:27.095469045+02:00 stdout F 10.0.2.100 - - [14/Aug/2023:12:31:27 +0000] "GET /login HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0"
...
```

In this case I tried as usual to log in to `https://IP:PORT/` where the front-end component is listening, however the client gets redirected indefinitely and never reaches the target resource (in the example above, the `login` page)

I am running this inside the following environment, and **rolling back to the `4.0.0-0` images stops this behaviour**:
- OS: `Fedora IoT 38.20230812.0`
- Architecture: `ARM64`
- Container engine: Podman `4.6.0`
- Orchestration: Consul `1.16.1`, Nomad `1.6.1`
- HTTP connection: from Firefox `116.0.2` directly to the Grocy's front-end proxy

Do you have any hints to give me to help in finding the cause?
Thanks for your time.

**Comment by berrnd** [comment]
None of the community contributed apps/tools/integrations are maintained here and this is clearly about a configuration issue, not a Grocy bug - please mind the issue template for future requests.

**Comment by berrnd** [comment]
Also maybe doing a little (re)search session beforehand helps for just like so much cases - have a look at https://github.com/linuxserver/docker-grocy/issues/72#issuecomment-1676297003 and the referenced other threads there.

**Comment by Procsiab** [comment]
@berrnd thanks for the reference: I did not think about looking also the "linuxserver"'s image; I posted here after looking at the commits between the two version since I could not figure out what would have led to this behaviour. I will move this discussion over there at the link you provided, since it seems definitely related.

**Comment by mafe** [comment]
I stumbled upon that, too, and emptying the viewcache solves that in the first stage, but if I reload the page, the redirect errors occur again. If I then only rm the file viewcache/route_cache.php loading the webpage does work again.
I commented out the following:
```
/////$app->getRouteCollector()->setCacheFile(GROCY_DATAPATH . '/viewcache/route_cache.php');

"app.php" 112L, 2796B written
```
This overcome the issues also after reloading the page.
Before grocy-4.0.1 were no problems at all. Can you see already where the relation is? Shall I do more research to get more insight?

P.S.: One of the very greatest apps, by the way. Thank you!

**Comment by berrnd** [comment]
> but if I reload the page, the redirect errors occur again

Anything most likely cached that file, maybe simply reload or restart your PHP process at the same time. But this here is the wrong place for debugging individual server setup problems.

**Comment by berrnd** [comment]
> Before grocy-4.0.1 were no problems at all. Can you see already where the relation is?

Of course more than obvious: This can only be a "problem" when routes have changed, which is naturally not the case for each and every release.

**Comment by AD-Wright** [comment]
Is there a reason that "viewcache" is not cleared on every startup?  If it's a cache it should start empty, no?

**Comment by berrnd** [comment]
> Is there a reason that "viewcache" is not cleared on every startup? If it's a cache it should start empty, no?

Grocy is a PHP application, so what's "on every startup" referring to for you? Basically every single web request (and every single frontend page view generates a couple of them) is technically a new "startup" of the whole application.

So no, it should definitely not be cleared on every startup. What's stored there is expensively to compute, that's why it's stored on disk on and not recomputed for every request - just like most likely every other application on this planets does it's business.

If you think this should be cleared more often, feel free to do so - it will not hurt anything, but please then don't open yet another issue about performance issues.

I just don't understand what's the problem on clearing this folder on updating / noting what's [mentioned in README](https://github.com/grocy/grocy#how-to-update). So far, there was no new Grocy release every other hour, so that's really not a full time job, more 2 seconds two or three times per year...

If this all relates to a Docker container, maybe simply finally reach out to the respective maintainers and let them somehow add a way to automatically clear that directory (or do that yourself). I did that for the "`update.sh` way" (also [mentioned in README](https://github.com/grocy/grocy#how-to-update)).

**Comment by AD-Wright** [comment]
So it seems that you have had quite a bit of discussion about this in the past (and perhaps this thread is not the right place for it).  It seems that non-Docker updates are completely covered with `update.sh`.  The reason "there's a problem" is the general Docker update method does not involve running scripts after the update - it just kills the old container, downloads the new one, and maps it to the same config directory.  So all the automation built into running a bunch of Docker containers and updating them is seamless, unless it's the Grocy container, in which case sometimes it *seems* to bork itself and therefore you get these questions.  

This really should be on the container maintainers, but I'm just going to mention one option here because it involves the architecture of Grocy, not the Docker:

If the `/config/data/viewcache` directory were mapped somewhere else, then it could be kept inside the Docker container and would be wiped on every update, so that the normal Docker update method works as expected.  The persistent data is normally kept outside the container and everything else is wiped during an update.  But because of where the viewcache is stored (as a subdir of data you want to keep), it's kept as persistent data.  I'm guessing moving it would involve rewriting a bunch of paths in Grocy though.  Is it worth bringing all "cache" things to a `/cache/` dir?  

Would you accept a pull request that moved `/config/data/viewcache/` to `/cache/`, solely for the purpose of Docker compatibility?

**Comment by berrnd** [comment]
Still off-topic here, but: I decided now to somehow automate that for the next release, because I think it won't get better with the inability of people to read README's nowadays, I fear it's more the opposite. But I'm also tired of the more and more invalid reports after each and every release - will be tracked in #2384.
