### ISSUE TITLE
Bug: Problem with editing or consuming products

### ISSUE THREAD

**Issue by lgbelowbridge** [grocy/grocy#2316]
Error source:
```
/opt/grocy/production/packages/morris/lessql/src/LessQL/Database.php:110
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such table: cache__quantity_unit_conversions_resolved (View: /opt/grocy/production/views/productform.blade.php)
```

Stack trace:
```
#0 /opt/grocy/production/packages/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /opt/grocy/production/packages/illuminate/view/Engines/CompilerEngine.php(72): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /opt/grocy/production/packages/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get()
#3 /opt/grocy/production/packages/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /opt/grocy/production/packages/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /opt/grocy/production/packages/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /opt/grocy/production/packages/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /opt/grocy/production/controllers/BaseController.php(186): Slim\Views\Blade->render()
#8 /opt/grocy/production/controllers/BaseController.php(209): Grocy\Controllers\BaseController->render()
#9 /opt/grocy/production/controllers/StockController.php(205): Grocy\Controllers\BaseController->renderPage()
#10 /opt/grocy/production/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\StockController->ProductEditForm()
#11 /opt/grocy/production/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /opt/grocy/production/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#13 /opt/grocy/production/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#14 /opt/grocy/production/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#15 /opt/grocy/production/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#16 /opt/grocy/production/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /opt/grocy/production/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /opt/grocy/production/middleware/AuthMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /opt/grocy/production/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /opt/grocy/production/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /opt/grocy/production/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#22 /opt/grocy/production/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /opt/grocy/production/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#24 /opt/grocy/production/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /opt/grocy/production/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /opt/grocy/production/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /opt/grocy/production/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#28 /opt/grocy/production/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#29 /opt/grocy/production/app.php(112): Slim\App->run()
#30 /opt/grocy/production/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.0.2",
        "ReleaseDate": "2023-08-19"
    },
    "php_version": "8.1.2-1ubuntu2.13",
    "sqlite_version": "3.37.2",
    "os": "Linux 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/115.0.0.0 Safari\/537.36"
}
```

**Comment by berrnd** [comment]
You did another upgrade ignoring what's [mentioned in README](https://github.com/grocy/grocy#how-to-update) about how to do updates - quoting myself from https://github.com/grocy/grocy/issues/2281#issuecomment-1656838049:

You forgot to execute database migrations, this is automatically done when visiting the root route (`/`, simply click the logo on the left upper edge when you most likely otherwise access a specific page only, e.g. because of having a bookmark pointing to it or whatever) - that's also [mentioned in README](https://github.com/grocy/grocy#database-migrations).

**Comment by lgbelowbridge** [comment]
Works now. Sorry about that. Panicked. Thx for really quick response.

**Comment by berrnd** [comment]
> Panicked.

Doing backups before starting upgrades reduces heart attacks, especially when ignoring READMEs.

**Comment by lgbelowbridge** [comment]
I do have backups. To both storage and USB-stick. I am an old unix/linux sysadmin. Backup is imprinted in the sysadmin part of my brain. I need to imprint the need of reading README files too. Into my brain that is.

**Comment by lgbelowbridge** [comment]
But did you introduced a data base change between 4.01 and 4.02 ?

**Comment by berrnd** [comment]
> But did you introduced a data base change between 4.01 and 4.02 ?

Yes, simply have a look at what happened to the database schema if your interested, this is Open Source:

&rarr; https://github.com/grocy/grocy/compare/v4.0.1...v4.0.2

And also since your "issue" was resolved after doing database migrations, it's more than obvious that there were changes. But in any case: Simply always do the simple and few update steps mentioned in README to avoid problems and unneeded bug reports.

**Comment by lgbelowbridge** [comment]
Will always read README for now on. Promise. Since this was a patch release I didnt expect any such changes.

**Comment by lgbelowbridge** [comment]
I have just discovered Grocy  and I just love it. I am using it in a basic way. Products and chores are my main uses.

**Comment by berrnd** [comment]
> Since this was a patch release I didnt expect any such changes.

Would mean any bug requiring database schema changes can only be done in a major release? Lol.

**Comment by lgbelowbridge** [comment]
I have read this document: https://semver.org/ . A few years ago, when I was still working, a very annoyed teammate sent this to me so I would understand how to properly set the correct version for my part of the software when I made updates.

But I have just read the document and I am not sure how to handle a database change. Minor or patch ? Major is of course changes in the API which is used by other applications.

**Comment by berrnd** [comment]
I do whatever is required to fix something, if that's a problem for anyone, simply don't upgrade at all. It's natural to follow what Semantic Versioning basically  is about, but it's also not a holy grail I blindly follow, since for what.

And come on: Would you have read README if the version number had a little bigger bump? I doubt it. For each and every release there are at least a handful of exactly that "bug" reports where people are just incapable of reading READMEs. There was even a more funny [comment last time](https://github.com/grocy/grocy/issues/2302#issuecomment-1673064086) that the problem was/is that the ["How to update" headline in README](https://github.com/grocy/grocy#how-to-update) is a `<h2>` tag instead of a `<h1>`. At least it's always not a problem to find excuses for the own inability...

But I'm out here now, it's my pleasure when Grocy is useful for you and I'm getting more and more familiar with all those just-annyoing-and-time-consuming-requests, as this project gets bigger in terms of the amount of users, so no problem on that part.

**Comment by lgbelowbridge** [comment]
To be honest. If it had been a minor I would have upgraded and then, when the problem occurred, I would, hopefully, read the README. And I agree, Semantic Versioning is not that easy to follow. 

I will not use more of your time now. Thx for the interaction.
