### ISSUE TITLE
Bug: Blank pages after 4.0.2

### ISSUE THREAD

**Issue by zunami** [grocy/grocy#2317]
this time the upgrade to 4.0.2 worked.

only a few problems occurred

1. the page load process has tripled noticeably

2. when loading some areas they become blank white pages
stockoverview OK
shoppinglist OK
recipes 502 Bad gateway
mealplan blank page
choresoverview OK
tasks OK
batteriesoverview OK
equipment OK
calendar OK
purchase blank page
consume blank page
transfer blank page
inventory blank page
choretracking OK
batterytracking OK

3. firefox console errors were reported. the bug report is attached to
[firefox-console-export-2023-8-20_7-6-31.txt](https://github.com/grocy/grocy/files/12387295/firefox-console-export-2023-8-20_7-6-31.txt)

4. the errorlog of php is at
[php8.2-fpm.log](https://github.com/grocy/grocy/files/12387296/php8.2-fpm.log)

is there any other error log?

**Comment by berrnd** [comment]
In all those logs is no single useful information at all, I still can't help without having something reproducible. Have do you even imagine I, or anyone else on this planet, could do this by that. 🙄

&nbsp;
> is there any other error log?

You asked that multiple times in the last weeks, I answered multiple times in the last weeks - once again: No.

&nbsp;
If you still encounter performance problems, have you finally (doing that even before the upgrade is also an option) cleaned up your quantity unit conversion definitions? I doubt it. Since looking [at the changelog](https://grocy.info/changelog#4.0.2) is hard, here an excerpt for you:

>  Fixed that the upgrade failed when having (a lot of) redundant ("each to each") default quantity unit conversion definitions
>  - More on that by a practical example: When a conversion between Teaspoons and Milliliters and another one between Milliliters and Liters exists (and so forth; unlimited levels), Grocy can now (since v4.0.0) calculate the derived factor to convert Teaspoons to Liters on its own (before a direct conversion definition between Teaspoons and Liters was required)
>  - So you might have a lot of such "each to each absolute conversion definitions" currently, when you were affected by failed upgrades (timeout problems due to that resolving indirect conversion factors took very long)
>  - **Heads up:** This is now fixed, but you should clean up those redundant "each to each" definitions (in the example above the conversion between Teaspoons and Liters), since they are no longer needed
&uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr; &uarr;

&nbsp;
If nothing of all that helps, feel free to send me your database and I will have look - investing another couple of hours for your personal problems, on a sunday morning, for free - but all your recent requests sound like that you think I'm obligated to do that, so...

**Comment by zunami** [comment]
i have no idea what aggression i am calling out in you.

But I don't know what kind of support you are expecting. I'm not a programmer, I'm just a user in this case. I've been working in master data and analysis for over 20 years and I have to talk to programmers every week. In German, but I have been doing this for years because I understand structures and errors behind them.
But I stand there and ask how I can get you the information. Only I don't ask you to spend your holy Sunday morning doing my stuff. I'm a collective thinker, so I don't know why you think it's about me. If I have the mistake, then someone else will have it too, I think to myself.

I will now cease all involvement.
It's your project and it's your headache.

**Comment by berrnd** [comment]
Wow, after weeks, you even can't answer this simple question - what the (performance) problem is most likely is about (!!!): **Have you finally cleaned up your redundant quantity unit conversions definitions???** Again: It's more than likely that this will solve this "problem". (!!!)

And for the rest, just once again:
At the first posts, all you've said was just "it doesn't work", nothing more.
Then you started throwing random webserver logs in, which are useless - you don't need to understand that, but it was told you so more than once.
You've invested not a single minute in helping creating a reproducible example (persistent demo instances are still there for that), you even have not checked your quantity unit conversions, as also told endlessly.
There was only a short quick response like "it still doesn't work" every other day in the morning, just like now.
All that gives the expression to me that you're not interested in helping, just wanting your problem fixed - that's ok, but you use the wrong product/service then (as also already mentioned quite a few times).
The "aggression" is about that the bigger this projects gets in terms of user count, the more idiots pop up here and there (and what is publicly readable here is just the tip of the iceberg, most of the more fun stuff happens via private messages and even calls).

But you're right, it's my headache for that part - and you're headache for having a not working Grocy instance. Mine works perfectly, and I guess about thousands others too. So me too: Unless something useful comes up, I'm also finally out here.

And if you have the tech background, I even more can't understand all that, really wow.
