### ISSUE TITLE
Bug: vendor folder is not created when update.sh is used

### ISSUE THREAD

**Issue by AzmoCoin** [grocy/grocy#2319]
Hello !

Just updated my grocy in version 3.2.2 to 4.0.2 using the update.sh script embedded.
My grocy installation is on a raspi4 without Docker

After the script finished without errors, I tried to connect to grocy and I had : "Unable to run grocy: /vendor/autoload.php not found. Have you run Composer?"

After looking it up a little, I used the backup vendor folder which allows a smooth use of the android app but not a so smooth use of grocy through navigator.

Anyone having a solution or understanding where I did something wrong ?

**Comment by berrnd** [comment]
The folder `vendor` was renamed to `packages` and is, as always, included in the release ZIP.

&nbsp;
> Unable to run grocy: /vendor/autoload.php not found. Have you run Composer?

This can't be v4.0.2, since the line changed as the folder was renamed as just mentioned ([code ref](https://github.com/grocy/grocy/blob/dedbee3181198c8aeb8ad9e9a19c5d22047f5485/helpers/PrerequisiteChecker.php#L31)), I can't say what you did wrong.

&nbsp;
> After looking it up a little, I used the backup vendor folder

If it's really v4.0.2 (I doubt it) this can't work - manually fiddling with stuff without understanding what happens makes things just like always worse than better. Simply do a manual proper upgrade, when for whatever reason any script doesn't work: https://github.com/grocy/grocy#how-to-update

**Comment by AzmoCoin** [comment]
I followed everything in  the readme and don't understand where I missed.
But I've tried what you suggested : I removed everything and downloaded the latest package (version 4.0.2) and still have the same issue.

Thanks for your response but I think the issue is not in the update process, maybe the $vendorDir var is set somewhere in my data directory and overloading the new one but can't find where and it is my only clue.

**Comment by berrnd** [comment]
> maybe the $vendorDir var is set somewhere in my data directory

Grocy doesn't do that, but I can't say what you have changed for whatever reason. I guess you've also restarted your PHP process manager (or the whole machine) at least once to rule out any caching stuff or similar.

&nbsp;
> downloaded the latest package (version 4.0.2) and still have the same issue

That's the content (top level) of the [v4.0.2 release ZIP](https://releases.grocy.info/v?4.0.2):

![grafik](https://github.com/grocy/grocy/assets/2161815/8eb437a7-af87-4720-ac5e-0cb92135f3cd)

There is no `vendor` directory, there is a `packages` directory - if you have a `vendor` directory and no `packages` directory after unpacking that ZIP, something more than strange must go on.

Also, as already mentioned in README:
Triple check that you've deleted the `data/viewcache` directory after updating.

Grocy can't be the problem in any case here.

**Comment by AzmoCoin** [comment]
I did not change anything except in the data/config.php, but...

You were right and I was a dummy : I restarted my php and nginx services but not the machine and it worked.
Forgot rule number one.

Thanks for the help and sorry to bother you !
