### ISSUE TITLE
Bug: kcal calculation doesn't seem to work correctly in recipes

### ISSUE THREAD

**Issue by Hazarth** [grocy/grocy#2321]
**System:**
I'm using the docker version of Grocy provided by linuxserver here: https://github.com/linuxserver/docker-grocy.
Using latest version: 4.0.2.
![image](https://github.com/grocy/grocy/assets/30556348/02934a88-3716-4062-8a17-81b0e5179b3b)

**Problem Description:**
I have specified two units, "package" and "ml". I also defined a product "Milk" that I want to count and manage in "package" amounts, but I have defined a conversion from "package" to "ml" as 1 package = 1000ml, so I can use e.g. 80ml of milk in a recipe. I have also defined that the whole package of milk is 619kcal

Now I have a recipe where I'm only using 80ml of milk per portion, so the expected kcal conversion is 49.52kcal (or 50kcal rounded up obviously), but what I get instead is 0kcal... I can see in the ingredient list that 80ml of Milk is 0.08 packages, so this seems to be set-up correctly. And in fact, if I change the units to "package" and specify that I want to use "0.08 package" of milk in the recipe, the kcal calculation starts working, however changing the units back to "80 ml" again results in 0kcal.

I suspect there's some sort of conversion error somewhere, because if I specify 1000ml it returns "1 kcal"... Actually setting the recipe to 80 000ml actually returns 50kcal correctly... so for some reason I'm getting values that are converted reversely...

**Screenshots**
Example with 1000ml (which should be 1 whole package)
![image](https://github.com/grocy/grocy/assets/30556348/c8cb555a-a1cd-4e50-828b-f2a553548c36)

Shows how 80ml looks in the recipe ingredient form. "Balenie" is "Package" in my language, you can see it correctly calculates it as 0.08 package:
![image](https://github.com/grocy/grocy/assets/30556348/b195f8b4-68aa-43d6-b328-139ef9605c52)

But it never calculates the calories correctly:
![image](https://github.com/grocy/grocy/assets/30556348/a960a86c-7617-4f1b-899a-27444312482b)

However if I manually set this as 0.08 Packages, it comes out correctly... so the calories calculation is correct, the conversion unit calculation is also correct, but when they are put together it doesn't look correct
![image](https://github.com/grocy/grocy/assets/30556348/29f00995-0617-43e4-8d34-edebc21fe1a2)

For reference, these are the only defined conversion units for this product:
![image](https://github.com/grocy/grocy/assets/30556348/8bea7692-1ef0-4742-a1bb-4eb63891fe94)

I have checked with the pre-release demo, and it seems it works there correctly, but I have the same version and same setup on my side and I get the bug... Surely it can't just be my configuration since grocy actually understands that 80ml is 0.08 package, and 1 package is 619kcal... so I have no idea where this inconsistency is coming from...

Or was this fixed in the pre-release but not in the latest 4.0.2? Or is there something extra I need to do to get this fixed when migrating from 4.0.1?

**Comment by berrnd** [comment]
> I have checked with the pre-release demo, and it seems it works there correctly

Related/duplicate issue: #2301

So without having a reproducible example ([persistent demo instances](https://www.reddit.com/r/grocy/comments/jwnk9b) are there for that), I can only guess that this is about yet another upgrade ignoring [what's mentioned in README](https://github.com/grocy/grocy#how-to-update) - quoting myself from https://github.com/grocy/grocy/issues/2281#issuecomment-1656838049:

You forgot to execute database migrations, this is automatically done when visiting the root route (`/`, simply click the logo on the left upper edge when you most likely otherwise access a specific page only, e.g. because of having a bookmark pointing to it or whatever) - that's also [mentioned in README](https://github.com/grocy/grocy#database-migrations).

&nbsp;
> Or was this fixed in the pre-release but not in the latest 4.0.2?

The current pre-release demo is exactly v4.0.2, since there was not single change/commit since then: https://github.com/grocy/grocy/compare/v4.0.2...master

**Comment by alkuzman** [comment]
Hi @berrnd i can also confirm that I have simmilar issue (and I did all the necessary updates). The prices seem to work correctly, but the kcal seems to be off. I will make demo if I manage to reproduce the issue.

**Comment by berrnd** [comment]
> I will make demo

Yes, simply do that as mentioned on the issue template. I'm still unable to look behind screenshots or descriptions of problems, don't know why I have to repeat that on just like every request here.

**Comment by alkuzman** [comment]
I understand your frustration, but I guess sometimes is quite hard to set all the data right like in their local database, especially if they don't know how the calculation is performed (it might have to include product-specific or general conversion units or both, number of base servings, number of desired servings, whether it is included recipe or not) and I learned all this by looking into [this commit](https://github.com/grocy/grocy/commit/2d2039f9884838361496a3e14b57d11a06b3e25e). I am not saying that you should not push people to do a little bit more research, but if you leave the issue a little bit longer open (especially if it is a bug) others might have a chance to see the issue and help :).

The issue is on [this line](https://github.com/grocy/grocy/blob/dedbee3181198c8aeb8ad9e9a19c5d22047f5485/migrations/0229.sql#L28) because desired servings are not taken into account.

I guess it does not make sense for me to create a private demo instance because on any instance (including the demo) you can try to change the desired servings and the calories won't change.

**Comment by berrnd** [comment]
> change the desired servings and the calories won't change

Yes, because their meant to be displayed per serving:

![grafik](https://github.com/grocy/grocy/assets/2161815/79632f3d-f25b-4dbc-8497-46f22b8282c3)

Also already [mentioned at the origin of the request](https://www.reddit.com/r/grocy/comments/15lci9q/comment/jvk8re7/?context=3) (the topic about frustration and that people not invest a single minute in (re)search, I love it and there is fortunately no single day currently without it).

**Comment by alkuzman** [comment]
Sorry, I did not notice that. Before this release, I just assumed they are not correct and I was ignoring them, now I just saw that prices are changing and calories don't. 

I believe the disparity between calories and prices will be the point of many future issues created by confused people. I believe they should behave the same or maybe include both total and per-serving values.

**Comment by berrnd** [comment]
> I believe the disparity between calories and prices will be the point of many future issues created by confused people

There was discussion about that, calories are displayed per serving since v3.1.0, because it turned out that it just makes more sense - and of course that was also [mentioned on that changelog](https://grocy.info/changelog#v3.1.0) nobody seems to read either. If you cook for the whole family, the total calories are pretty much irrelevant practically.

[Custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) is still there to fit everyone, I provide snippets for each and every request popped up anywhere - here is another one (for `data/custom_js.html`) for displaying calories per total servings instead:

```html
<script>
if (Grocy.View == "recipes")
{
	var kcalElement = $(".card-body").find("h3.locale-number-generic");
	var desiredServings = $("#servings-scale").val();
	var kcalPerTotalServings = Number.parseFloat(kcalElement.text()) * desiredServings;

	kcalElement.text(kcalPerTotalServings.toLocaleString());
}
</script>
```

You can change stuff like that and then those who expect it just the other way round are confused in the same way. But that confusion is always just about the inability to read. I make stuff clear by at least help tooltips directly on the UI, I explain every little change on the changelog - all that is just ignored by so many for reasons I just can't understand, but I also don't know what to do more for that.

[There are people saying](https://github.com/grocy/grocy/issues/2302#issuecomment-1673064086) that they missed the [update instructions in README](https://github.com/grocy/grocy#how-to-update) because the headline there is a `<h2>` tag instead of a `<h1>` one, [others say](https://github.com/grocy/grocy/issues/2316#issuecomment-1685026933) they only read changelogs if the version bump is a little bigger than a patch release and you don't want to hear what else I need to look at (well, my fault that I [mentioned also that in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests)) in private messages and even calls, on daily basis lately. I can't heal the world regarding that, the only thing for me would be to finally end this project completely if my frustration about all that reaches a certain level, which is not so far away currently.

**Comment by alkuzman** [comment]
> I can't heal the world regarding that, the only thing for me would be to finally end this project completely if my frustration about all that reaches a certain level, which is not so far away currently.

I am sorry you feel that way. I really appreciate this project and your work. Honestly, I hope you will not give up :). I am sorry I did my part by not reading everything properly. I will try to be more thorough next time.

I am a bit of a late commer and still haven't read everything (don't know the whole Grocy history). I hope I will get conftable with the codebase soon and will be able to contribute more actively. 

I will try to answer some common questions/issues for which I am sure I know the answer if that is ok with you.

**Comment by Hazarth** [comment]
To be fair, I did say I tried to reproduce the issue in the Demo app but was unable to. Never the less, that doesn't change the fact it's wrong on my instance for some reason and I don't see why. This doesn't seem like a serving size issue, since my Milk get completely wrong calculation while the oats don't... 

I'll make a PR if I ever find out what the problem, but if you actually red the Issue I created you'd see that I *did* try to reproduce it in the demo, and wasn't able to... I did as much research as I could without delving into the source code and once again, just because the demo doesn't have the issue doesn't mean there isn't a bug. Maybe it's a language thing, maybe it's a default configuration thing.. maybe it's some checkbox somewhere that makes no sense, but it's still happening to me none the less, as the pictures prove.

Look man, I appreciate the software, I really do, best of it's kind and Open Source? Amazing! And obviously you don't owe any of us anything. I just reported my findings and if you just check the pics you can see that something is clearly not working right. :woman_shrugging:

**Comment by berrnd** [comment]
> just because the demo doesn't have the issue doesn't mean there isn't a bug

Bullshit. If you reproduce exactly your scenario (with all details around, quantity units, conversions, everything) then there will be exactly the same behavior there. Everything what Grocy does is deterministic, no magic involved.

&nbsp;
> Maybe it's a language thing

Language doesn't matter for any calculation or any other algorithm, it's just a UI thing.

&nbsp;
> I just reported my findings and if you just check the pics you can see that something is clearly not working right.

Thanks for that. But what exactly should I do when people throw hundreds random screenshots at me with no reproducible example / all the details needed to get the "problem"? If you know how to do that, no specifically for Grocy, write a book or something like that and get rich as hell.

**Comment by berrnd** [comment]
Since I've offered that to everyone so far, although it turned out to be a user problem at the end most of the time: If you don't have the time to reproduce all the details on a demo instance and if it's ok for you, send me your database and I will most likely invest a couple of hours and have a look. Since I really have nothing better to do and you would not have the problem, if I had not created this project, so of course it's my fault.

**Comment by Hazarth** [comment]
@berrnd Actually I just checked again now and the problem resolved itself out. Only thing that changed is that my instance crashed in the meantime and I had to restart the server (running in Docker on  a Raspberry pi 3, so I'm not exactly surprised when stuff crash randomly lol).

I maintain that this is a bug, I have changed nothing since the original report and it went from 0kcal to 50kcal somewhere in between. So right now I'm not sure what the problem was, maybe a caching issue? Eitherway for now it's gone. If I ever see it again I'll try to dig deeper and figure out what exactly happened.

**Comment by berrnd** [comment]
> maybe a caching issue?

Grocy doesn't cache "kcal calculations". The most obvious explanation would that you have simply not applied database migrations at first, as pointed out in my first answer here above. Since the fix about the duplicate (reproducibly) reported bug was technically a database migration.

But if it make you feel better, feel free to "maintain that this is a bug" aka my and not your fault.

**Comment by berrnd** [comment]
> I'll try to dig deeper and figure out what exactly happened

Look into the database, check the table `migrations`. This table records timestamps of executed migrations. If migration `0229` was executed just now, and not at the time of your initial v4.0.2 upgrade, it was exactly about the now for the third time mentioned (user) problem related to not applied database migrations.

If it turns out that that's the case, don't report that back here (important!), as this would destroy the impression that everything not working in Grocy is my fault.

**Comment by Hazarth** [comment]
@berrnd what are you talking about, ofc it's all your fault. It's open source which means you are completely responsible for everything that goes wrong with it and you have to provide free updates and support in real time pretty much until the end of times otherwise you'll be seen as lazy and incompetent! 

Yeah man, most people are ungrateful b*atches, I understand why looking at dumb issues that have been solved for the 1000th time is really annoying. I wouldn't have reported if I didn't have the latest version, I was under the impression migration scripts would run automatically (I'm mostly used to that being the case) and I only read the linuxserver README regarding the update and not the grocy one. 

I can confirm that migration 0229 was only ran after the restart:
```
227        2023-08-17 09:13:44     
228        2023-08-23 13:32:51     
229        2023-08-23 13:32:51     
230        2023-08-23 13:32:51     
231        2023-08-23 13:32:51     
232        2023-08-23 13:32:51
```

I'm not exactly sure why this restart caused migrations to run, but stopping the container, pulling a new image, starting the container again didn't I guess?

Anyway, thank you for your time and once again I really appreciate what you're creating here. It's a really cool project and I enjoy using it

**Comment by berrnd** [comment]
> I can confirm that migration 0229 was only ran after the restart

Cool, so after investing way too much time in this "discussion" and 4 days it turns out that it was once again about ignoring README and even not reading my first answer here, where exactly all that was mentioned. I get in love with all that more and more and maybe someday I will understand what's the hard thing about reading READMEs or answers - looking forward to that time.

&nbsp;
> but stopping the container, pulling a new image, starting the container again didn't I guess

Once again: Migration run when visiting the root route! Again: When clicking the fucking logo on the left upper edge when your bookmark you always use to access Grocy points to specific page. When fixing this bookmark to that root route it would even happen kind of automatically (the magic you're used to).
