### ISSUE TITLE
Improvement: make UserService::GetUserSetting() cheaper performance wise

### ISSUE THREAD

**Issue by alkuzman** [grocy/grocy#2323]
`UserService::GetUserSetting()` is a method that calls the database to get a specific user setting. This method is called quite often resulting in high cumulative processing costs.

I did a short recipe consumption profiling session of (6.1 seconds) and I got the following results:

![image](https://github.com/grocy/grocy/assets/7229627/4f21630f-335d-4e6c-a738-bfea906b7ffa)
![image](https://github.com/grocy/grocy/assets/7229627/452f093d-ba9a-43fd-bc92-559b4b0bd7e5)
![image](https://github.com/grocy/grocy/assets/7229627/38d3259a-0e8f-4ca3-a87c-ec22d8a276a0)

From a total of 6.1 seconds of runtime, the app spent 2.6 seconds on this method (with around 13k calls). 

I would like to give this issue a try as a PHP noob. I might need some help :). My initial idea was to make this method call cached. Second I feel the number of calls is kind of high, I am not sure whether that is expected or not.

Note: there are other queries (that are a bit slow) that are visible on the screenshots but I will be looking into them in separate issues. They are related to the `recipes_resolved` and `recipes_pos_resolved` views I believe.

**Comment by berrnd** [comment]
> Second I feel the number of calls is kind of high, I am not sure whether that is expected or not.

I only expect that stuff runs as fast as it feels ok to work with, this excludes e.g. optimizing stuff for low end devices like a Raspberry Pi where slowness is exactly what you payed for. Of course 13k `GetUserSetting()`calls for a single request / recipe consumption is more than high. Also the underlying recipe would be interesting, since with the default demo data a random recipe consumption action takes < 2 seconds (no the demo server) and I kind of doubt that in that time 13k SELECTs were executed...

**Comment by alkuzman** [comment]
I think the 13k are collective executions from other calls from the frontend not only the API call

**Comment by berrnd** [comment]
Feel free to do whatever you have fun with. As long as a contribution solves/improves something practically relevant (means not overengineering a only theoretically existent problem) and doesn't rewrite the whole project, I will most likely have a look and merge everything, just how it went the last 6 years with this project.
