### ISSUE TITLE
Bug: Bad link to uploaded File to Userfield added to chores_log if filename contains a -

### ISSUE THREAD

**Issue by sharkmerry7** [grocy/grocy#2327]
Private instance here with it recreated

Seems if filename contains a - the link to the file is bad. 

Uploaded two of the same file, only change is a - in the filename and that one gets me a bad link

![image](https://github.com/grocy/grocy/assets/19986741/b10a5e07-8ab6-4b12-805b-42b12d520887)

https://test-wn320697g1rxbtrvrtxbq9.demo-prerelease.grocy.info/

**Comment by sharkmerry7** [comment]
underscores break it too it seems

**Comment by berrnd** [comment]
I just uploaded a same named PDF file with a `_` and one with a `_` without problems on that same private demo instance:

https://test-wn320697g1rxbtrvrtxbq9.demo-prerelease.grocy.info/choresjournal

![grafik](https://github.com/grocy/grocy/assets/2161815/f36bc5cc-0025-4822-98fa-c850b887604b)

The problem is not that the "link is bad", the problem is that the file wasn't uploaded at all. Generally any special characters are handled in the same way (all is Base64 encoded to avoid all those problems). Maybe triple check what your browser does or temporarily disabled some of your various browser extensions - would be not the first time that any of those break any site.
