### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by Sectorchan** [grocy/grocy#2342]
Hi,

It would we awesome if it is possible to change the language beside the browser language or OS language

**Comment by berrnd** [comment]
Well, since that would be really awesome, it's possible since ever:

The default language can be set in `config.php`:

https://github.com/grocy/grocy/blob/35766bf5b3bebc68654b3e048812610cf4413ada/config-dist.php#L22-L24

Beside that, each and every user can overwrite that default setting in the top right corner settings menu:

![grafik](https://github.com/grocy/grocy/assets/2161815/32eb0934-35c6-4b11-bbd9-7227dc5172ac)

&nbsp;
[README](https://github.com/grocy/grocy#localization) excerpt:

> The default language can be set in data/config.php, e. g. Setting('DEFAULT_LOCALE', 'it'); and there is also a user setting (see the user settings page) to set a different language per user.
