### ISSUE TITLE
Bug: Certain pages render incorrectly

### ISSUE THREAD

**Issue by Disastermind** [grocy/grocy#2347]
I'm running lighttpd on a Raspberry Pi, and have installed grocy using a combination of [these instructions](https://github.com/grocy/grocy/issues/649) along with [this comment](https://github.com/grocy/grocy/issues/623#issuecomment-617941564) which is what got me to the point of being able to use grocy at all.

I'm able to login to grocy, but certain pages seem completely broken. For example, this is the default _stockoverview_ page:

![image](https://github.com/grocy/grocy/assets/145842239/e9c1389e-d983-4226-aece-701ad7767b12)

As a comparison, if I click the word Journal then I get sent to the _stockjournal_ page:

![image](https://github.com/grocy/grocy/assets/145842239/b8e0cb54-73e1-4dc6-a088-2065971737ca)

Another example would be the _users_ page, which looks correct to me:

![image](https://github.com/grocy/grocy/assets/145842239/c2797ae5-94e2-42e6-b16f-541366680b2d)

However, if I click the Add button in there and move to the _/user/new_ page, it looks completely different and is broken in that I'm unable to add a new user, and the "Passwords do not match" text remains static even when the passwords do match:

![image](https://github.com/grocy/grocy/assets/145842239/7139cba9-f059-4f0b-afa1-d9f4ef358a26)

I'm not sure if there's an installation step I'm missing here, or if this is a configuration issue on my end, but there are multiple 'broken' pages like I've shown above, and multiple other pages that seem to work with no issue, leading me to believe it's a bug rather than an environmental issue?

**Comment by berrnd** [comment]
Of course that's not a (reproducible) bug and more a configuration issue on your end - please use the appropriate place as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) and don't abuse this issue tracker for help requests.

Probably an issue related to URLs, since pretty clearly assets (CSS/JS/and so on) are missing for the aforementioned problems.

Or if you recently did an update, you simply ignored [README](https://github.com/grocy/grocy#how-to-update) and not emptied out your `data/viewcache` directory (+ a restart of your PHP process manager or the whole machine, maybe needed depending on how exactly you've configured caching stuff).

**Comment by Disastermind** [comment]
My apologies, this was my first time posting on Github and I clearly misunderstood the protocol and what was expected of me - I will be more mindful of this in future.

I've since [posted to your subreddit](https://old.reddit.com/r/grocy/comments/16qt4jv/help_with_certain_pages_rendering_incorrectly/) as you've requested of me, any advice you can give me there would be greatly appreciated.

This is a fresh install and not an update.

**Comment by berrnd** [comment]
> any advice you can give me there would be greatly appreciated

I have no experience with Lighttpd (and would never consider running applications like Grocy on a Raspberry Pi at all, but I also like stuff fast) and you've provided no environment details (e.g. the used PHP version and everything else) or useful logs (PHP / webserver) - that's most likely the cause that I and nobody else answered there so far, since it's just impossible to say anything useful by that (unless replicating the exact setup, which I can't / want do for each and every of the thousands Grocy users in my free time, since it's just not fun - sorry if you expected that).

It seems you have not that much experience with the technical part regarding webservers and stuff, which if course just fine. But why then go the hard way and not use the much more easy route, e.g. [the Docker way](https://github.com/grocy/grocy#how-to-run-using-docker)?
