### ISSUE TITLE
Feature Request: remote hardware barcode scanner

### ISSUE THREAD

**Issue by legomind** [grocy/grocy#235]
This idea is not really concrete yet, so I would like some input.

Here is what I have at the moment:
I have a usb barcode scanner that I would like to use with grocy. It is connected to a raspberry pi zero, running a python script that handles the barcode scanning.

When a barcode is scanned, the python script sends the scanned value & a client id to grocy via a rest call. The client id specifies what mobile device the barcode should be sent to.

The client id can be changed by scanning a special barcode that can be attached to the back of the mobile device. This is useful if more that one device is used (eg. different locations)

Here is the part that remains: getting the barcode to the client.
From what I see, there is two ways to approach the issue.

1) Serve up a websocket server from Grocy, and let Grocy forward the barcode to the appropriate client when a barcode is received VIA a REST api call (from the python script)
2) Serve up a websocket server directly from the python scanning script, and have the client connect directly to the scanning rasberry pi.

I prefer option 1, but option 2 has simplicity going for it, especially if grocy ever adopts a modular plugin architecture.

Thoughts?

**Comment by berrnd** [comment]
I think I didn't get the point what this should help with at the end...

Have a look at [grocy/grocy-pyscanner](https://github.com/grocy/grocy-pyscanner) and #220 - that's a Python script which provides a "scan mode" to simply remove or add 1 QU by scanning a product barcode.

I prefer to have it simple. Any cheap USB barcode scanner emulates a HID, hence sends keyboard inputs of the scanned string just like when you typed it by hand. Any application which can handle normal keyboard input, can handle this. As currently all product input fields in the grocy UI. The barcode scanning by HID emulation is the way also used in the big enterprise systems.

#221 is about to extend that, attaching own barcodes ("grocycode") to any object in grocy and be able to select it by scanning that code.

**Comment by legomind** [comment]
Well the end goal was to use a barcode scanner with a tablet using the web application. The goal is to essentially use a remote usb scanner wirelessly with a device that does not have a usb port.

**Comment by berrnd** [comment]
Sounds complicated to me, I prefer to just use hardware which fits the use case at the place I need it ... e. g. [a 99 EUR cheap small notebook with a 29 EUR cheap wireless USB HID barcode scanner in my kitchen](https://grocy.info/img/kitchen-terminal-en.jpg)...

And for (Android) tablets - there are "keyboard" apps which use the built in camera to do the scanning (too slow in my opionion compared to a laser scanner) and then send the scanned string also just as typed input. Would assume that you can also just connect a HID USB barcode scanner (via an OTG adapter), since android can handle physical keyboard input.

So feel free to contribute everyhting needed to handle this, will of course add it, maybe it's useful for anyone else too...

**Comment by legomind** [comment]
Thanks.
