### ISSUE TITLE
Bug: No way to change quantity unit

### ISSUE THREAD

**Issue by trustno1foxm** [grocy/grocy#2357]
I am using latest docker version "linuxserver/grocy". There is no way via Browser or App to change the quantity unit. So if I enter something wrong, I can't correct it afterwards.
Thank you in advance.

so long

**Comment by berrnd** [comment]
That's not a (reproducible) bug and neither a feature request - please use the appropriate place as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) and don't abuse this issue tracker for help requests.

Of course quantity units can be edited as you please on [/quantityunits](https://demo-prerelease.grocy.info/quantityunits).

If you're referring to changing a product's QU stock once after it was created, you need to tell Grocy a corresponding conversion to be able to use the corresponding unit. That has been asked multiple times, a little search will help - did that for you: https://www.reddit.com/r/grocy/comments/16vsvwe/correcting_quantity_unit_stock/

&nbsp;
> I am using latest docker version "linuxserver/grocy".

None of the community contributed apps/tools/integrations are maintained here.

**Comment by berrnd** [comment]
And since you were more than unspecific, it could also be about simply changing/editing a purchase transaction - of course that's also possible, so let's recap once again a quick lesson on Grocy stock management basics:

- Products can be defined on [/products](https://demo-prerelease.grocy.info/products)
- A product can be in stock of course _n_ times (not only once), since that's how the reality works
- Such a product in stock is called a stock entry, those can be edited on [/stockentries](https://demo-prerelease.grocy.info/stockentries)
- Each and every stock change/transaction is recorded in a log called stock journal, visible on [/stockjournal](https://demo-prerelease.grocy.info/stockjournal)
- [/stockoverview](https://demo-prerelease.grocy.info/stockoverview) is a "high level, kind of aggregated" overview what's in stock, means there is only one line per product
- At each and every place an amount can be entered, any product related unit can be used
  - The base is always the product's QU stock, there needs to exist a conversion (either a global or a product specific one) to be able to use the corresponding unit (since Grocy stores everything related to the products QU stock and it needs to know how much Pieces a Pack has, for example - it's impossible to magically guess that)
