### ISSUE TITLE
Bug: Calendar buggy

### ISSUE THREAD

**Issue by trustno1foxm** [grocy/grocy#2358]
I am using latest docker version "linuxserver/grocy". When adding new products you can choose the first time the calendar for choosing the best before date. Buuuut if you scan before or afterwards the barcode that option disappears and you just can enter the best before date as a number value. That's pretty annoying. Could you please fix that?
By the way grocy is awesome and I try to motivate my partner to use it ;)

Thank you in advance!

so long

**Comment by berrnd** [comment]
When you provide a reproducible example, I fix each and every bug - just as I did since more than 6 years Grocy, the vast majority of them even within hours after they were reported.

But I need a reproducible example, tried what you briefly described and can by that only say: It works, see the screen video below.
- Using [/purchase](https://demo-prerelease.grocy.info/purchase)
- Doing 4 transaction, all by scanning a barcode
- => The date picker works just fine each time and it also doesn't "disappear" in any way

https://github.com/grocy/grocy/assets/2161815/9af54d9c-9706-4513-978e-faa76123d1e8

So provide a detailed reproducible example if you want to have something fixed.

&nbsp;
> I am using latest docker version "linuxserver/grocy".

Again: None of the community contributed apps/tools/integrations are maintained here.

**Comment by trustno1foxm** [comment]
Hello,

first thank your for your fast response and detailed help. I am really sorry, we have checked it again and now found out the mistake. Thank you for sharing the video. To understand "our" wrong way, here what we did:
"We select purchase and scan a barcode via the camera symbol. Then we select "Add as new product" and there is no calendar option. Here was the error, we have to create the product first and then the corresponding fields can be filled in."

Sorry for wasting your time, but thank your a lot for helping us! It's really awesome now to use! ;)

so long
