### ISSUE TITLE
Shopping a product does not remove it from the shopping list 

### ISSUE THREAD

**Issue by jacotec** [grocy/grocy#2359]
Thank you very much for this really awesome project!

I found an issue with shopping products: When I'm in the shop, using the "Einkauf" (Shopping) function in the app to add the shopped products directly to Grocy, they are unfortunately not removed from the shopping list. As a workaround I still need to delete them from the shopping list afterwards.

In my opinion, when you shop a product which is on the list, the shopping action should remove it from the list.

**Comment by berrnd** [comment]
Generally something that works, but is just not implemented how you personally like it, is not a bug - a bug is something that's broken.

&nbsp;
> "Einkauf" (Shopping) function in the app

None of the community contributed apps / tools / integrations are maintained here.

&nbsp;
Using this button on [/shoppinglist](https://demo-prerelease.grocy.info/shoppinglist) adds the corresponding item to stock and  removes the line from the shopping list:

![grafik](https://github.com/grocy/grocy/assets/2161815/b640b8e2-1c8c-4b32-b0c5-3fb0d2b8e3d2)

Using this button on [/shoppinglist](https://demo-prerelease.grocy.info/shoppinglist) does not remove the line from the shopping list, but marks it as done / displays it crossed out:

![grafik](https://github.com/grocy/grocy/assets/2161815/a04e62da-b098-4c42-a532-6c7fb6e651fa)

Both works as it's supposed to work, therefore not a bug.

**Comment by jacotec** [comment]
@berrnd Thanks for explanation, got it ;-)

I'll add it as a feature request later as IMHO it would be very useful not to touch the shopping list as well when stocking up (shopping)

**Comment by berrnd** [comment]
Please read again what I just wrote - when using the "Shopping list to stock workflow", exactly that already happens, since years.

Mind again those buttons on [/shoppinglist](https://demo-prerelease.grocy.info/shoppinglist):

![grafik](https://github.com/grocy/grocy/assets/2161815/0d95a9f4-03ea-40f0-941d-38fde34638ef)

Each and everything is explained on [the changelog](https://grocy.info/changelog) when something new is introduced, this was introduced in [v1.23.0](https://grocy.info/changelog#v1.23.0) (almost 5 years ago) - excerpt:

> New feature: "Shopping list to stock workflow"
> - Add a single shopping list item or all at once to stock directly from the shopping list
> - There are new "stock settings" under settings menu in the top right corner
> - You can enable there, that all products which have "Default best before days" set, are added without confirmation in this workflow
> - => This means, you can add the whole shopping list to stock with one click, if you want

&nbsp;
> not to touch the shopping list as well when stocking up

The shopping list was invented for shopping, so I don't get that. Practically you can even do that directly when the checkout queue in the supermarket is once again quite long and slow. I do this kind of daily. Easy. Fast. Works.

**Comment by jacotec** [comment]
Hi Bernd,

yap, I'm aware of this feature ... but maybe we talk "aneinander vorbei" ;-)

Just thinking ... I'm using the feature to automatically add items under minimum stock to the shopping list, which is awesome (the list is synced to Bring because we have some shops which lacks of mobile coverage). In a shop with coverage I scan the products, enter quantity and due date - quantity can be more than the minimum amount Grocy gives me.

If the server API would check the stock of the product with the occurrence of a shopping transaction against the shopping list and would automatically remove the product from the list if the stock is above or equal the minimum amount, this would not need any additional action by any mobile app as it fully happens on the server backend.

Just negotiating if you think it's worth a feature request.

Have a great weekend!

**Comment by berrnd** [comment]
> quantity can be more than the minimum amount Grocy gives me

The "Shopping list to stock workflow" also doesn't limit that, it essentially just opens [/purchase](https://demo-prerelease.grocy.info/purchase) prefilled accordingly.

&nbsp;
> If the server API would check the stock of the product with the occurrence of a shopping transaction against the shopping list and would automatically remove the product from the list [...]

I repeat myself the third time here now on that, but exactly that is what the "Shopping list to stock workflow" does. Any community contributed apps are still not maintained here. And no, this can't be the job of the "server backend", there is even no direct relation between a random purchase transaction and a shopping list item (when not starting the transaction from exactly that shopping list item). Grocy has multiple shopping lists, products can occur multiple times on the same or different lists. Maybe not for you based on how you personally use Grocy, but Grocy is built for and used by a couple of thousands more.

&nbsp;
> Just negotiating if you think it's worth a feature request.

Definitely not, since everything is still possible by simply using the now too often mentioned "Shopping list to stock workflow".

&nbsp;
Btw: Living in the same country which invented the Funkloch, any supermarket I walked in the last 10 years or so has either proper mobile coverage or provides Wifi. Bad mobile coverage is also often just caused by bullshitty smartphone hardware or the wrong provider (yes, Telefonica) not always only by the building / area itself. Personally using Grocy longer that it exists publicly without any companion app daily and it works. Everywhere.
