### ISSUE TITLE
Bug: conversions of unit of measure wrong in recipe

### ISSUE THREAD

**Issue by tom1104** [grocy/grocy#2362]
I created products with different conversions:
example:
bottle -> ml -> factor 700 "means 1 bottle equals 700ml"
tablespoon -> ml -> factor 10 "means 1 tablespoon equals 10 ml"
and so on..
in the product data, it is shown correct.
![image](https://github.com/grocy/grocy/assets/42472540/75976dce-f776-4a57-b7aa-5d193820bd75)

when i add the product to a recipe
example:
2 tablespoons
it already shows below the amount field
"this equals 20 bottles"
but it should equal 20 ml or 0,029 bottles
![image](https://github.com/grocy/grocy/assets/42472540/e23b1bed-efbf-41c6-9b4f-60a9d539d990)

when i then press save it shows 20 tablespoons..
![image](https://github.com/grocy/grocy/assets/42472540/39db1091-a221-4130-82a6-5a329a10045a)

in the units of measurement I only convert for example milliliters to liters or grams to kilograms
there are no conversions for tablespoons.

has anybody else this problem?
I'm running on verion 
Version 3.3.2
Veröffentlicht am 2022-11-12 vor einem Jahr

PHP Version 8.1.14
SQLite Version 3.40.1
in a docker container on my Qnap-NAS..

**Comment by berrnd** [comment]
> has anybody else this problem?
>  Version 3.3.2

Everyone running this outdated version has this problem, since multi-level QU conversions are a new feature of v4.0.0 and were never supported before.

Solution: Simply use the current release, which is always the only supported version.

See #1360 and the ~30 linked other threads there for more insights if you're interested.
