### ISSUE TITLE
Feature Request: running https with free SSL and how to scrape the barcode from AH and Jumbo step by step for dumbo's like me

### ISSUE THREAD

**Issue by gewoondemax** [grocy/grocy#2367]
hello thank you for grocy

it is wonderful but missing or donot know how to implement - installing free SSL https on grocy because the scan programs only want to accept https ..
I have installed NGinx but now ...?? how to go further maybe a manual or step by step?

how to implement the barcode for groceries like Albert Heijn and Jumbo this in a step by step how to in a way novices understand I am a nono .. sorry for that!

thank you for the great work!!

**Comment by berrnd** [comment]
This is the tracker for reproducible Bugs and Feature Requests, this here is neither of that ([README ref](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests)).

[grocy.info/links](https://grocy.info/links) mentions more than a handful of guides, the [r/grocy subreddit](https://www.reddit.com/r/grocy) has even more + people which might give you an individual step by step guide based on your personal setup of choice (I personally don't have the desire nor time for that, sorry).

Beside that, there is nothing special regarding "SSL on Grocy", so pretty much each and every NGINX related guide on that topic applies and I guess there are trillions of that out there in the wild west internet, all of them ready to be searched for at any time.

I guess you also already did a search on the other part, I quickly did that and it turned out this: https://github.com/PaulVerhoeven1/grocy-dutch-supermarket
