### ISSUE TITLE
Feature Request: Cost View in Table Options

### ISSUE THREAD

**Issue by gdreelin** [grocy/grocy#2373]
I would love to see a feature of cost view in the Products section to allow you to see if you missed entering a cost of an item under the table options.

**Comment by berrnd** [comment]
Grocy has not only a single page were something about products / stock entries is displayed. So [once again](https://github.com/grocy/grocy/issues/2346): Please be so kind and specify a little more detailed where you want to have what exactly.

The last and average price per product is already there on [/stockoverview](https://demo-prerelease.grocy.info/stockoverview).

The price for each and every stock entry is already there on [/stockentries](https://demo-prerelease.grocy.info/stockentries).

**Comment by gdreelin** [comment]
Sorry I was referring to the Manage Master Data / Products section. If you view the Table Options it does not have a way to show the price or cost of an item. Something like this image attached. This way it give you a spreadsheet view of all the data and you can see what you may have missed when entering the data.  Hope that explains it?

![Untitled](https://github.com/grocy/grocy/assets/802649/b792fed5-394d-4fdf-8fda-af4adcc7eae3)

**Comment by berrnd** [comment]
> Sorry I was referring to the Manage Master Data / Products section. If you view the Table Options it does not have a way to show the price or cost of an item. 

Yes, by design - because what price do you expect there? Let's recap once again a quick lesson on Grocy stock management basics:

- Products can be defined on [/products](https://demo-prerelease.grocy.info/products)
- A product can be in stock of course _n_ times (not only once), since that's how the reality works
- Such a product in stock is called a stock entry, those can be viewed and edited on [/stockentries](https://demo-prerelease.grocy.info/stockentries)
  - By nature, each and every stock entry can have a different price (and amount, due date, location and so on)
- Each and every stock change/transaction is recorded in a log called stock journal, visible on [/stockjournal](https://demo-prerelease.grocy.info/stockjournal)
- [/stockoverview](https://demo-prerelease.grocy.info/stockoverview) is a "high level, kind of aggregated" overview what's in stock, means there is only one line per product
- At each and every place an amount can be entered, any product related unit can be used
  - The base is always the product's QU stock, there needs to exist a conversion (either a global or a product specific one) between that and the unit you want to use to make it selectable (since Grocy stores everything related to the products QU stock and it needs to know how much Pieces a Pack has, for example - it's impossible to magically guess that)

Concludes to for this: Everywhere, where stock entries are displayed, the corresponding price is already displayed. Master data is only the definition of a product, which has no price - a stock entry has a price. What you want is the list on [/stockentries](https://demo-prerelease.grocy.info/stockentries). When you do a purchase transaction without a price, it's properly visible there and you can even correct that at the very same place.
