### ISSUE TITLE
Itens in shopping list not deleted after purchase 

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2374]
Item "Carne Moida" on shopping list:
![Captura de Tela 2023-11-09 às 16 11 35](https://github.com/grocy/grocy/assets/6339761/8de5b6c0-52f5-4f9f-a187-57f45dcd6261)

Adding products via Purchase option
![Captura de Tela 2023-11-09 às 16 12 07](https://github.com/grocy/grocy/assets/6339761/54e606dc-2ab0-4272-a6fd-cef08d49df50)

Back to Shopping list and Carne Moida remains there
![Captura de Tela 2023-11-09 às 16 12 38](https://github.com/grocy/grocy/assets/6339761/8c720f89-bf00-4b2e-b2e5-8590ba604953)

Stock contains new purchases
![Captura de Tela 2023-11-09 às 16 12 47](https://github.com/grocy/grocy/assets/6339761/6eaf2f19-29cc-4397-bf29-1e3ef1791040)

**Comment by berrnd** [comment]
A random purchase transaction does not remove a random item from a random shopping list - it's also nowhere stated that that's the case, so I really don't get how you came to to the conclusion to report that as a Bug.

But the the "Shopping list to stock workflow" was invented for that. Simply use one of those buttons and exactly what you expect happens:

![grafik](https://github.com/grocy/grocy/assets/2161815/b9061785-d709-4d2e-b28f-98c29f50a371)

&nbsp;
Only when triggering such a workflow from a shopping list item there is a relation to it, otherwise not - remember that Grocy has multiple shopping lists and even the same product can occur multiple times on the same shopping list. So assuming you have Carne Moida on 3 shopping lists with 3 different amounts and you do a purchase transaction (at the purchase page, so without a relation to a shopping list item), which shopping list item, out of those 3, do you expect to be removed and what's the rule behind which one to pick?

Has also been asked in #2359 lately and I know we did not hear each other for a month or so, but searching beforehand is still a thing.
