### ISSUE TITLE
Feature Request: expand equipment details

### ISSUE THREAD

**Issue by igorsantos07** [grocy/grocy#2378]
Currently, "equipments" are very simple entities, mostly to archive instruction manuals.

My idea is to expand them to include:
- purchase date, store, price and receipt file (useful for warranty claims)
- manufacturer, serial code and model
- warranty date (or lifetime) & details
- storage location?
- more than one instruction and receipt files? E.g. my grill has a general manual and a receipts booklet.
- picture?

I was considering installing Homebox (check the [demo](https://homebox.fly.dev/)) on my HA instance, but discovered that...
1. there's no add-on yet, since Homebox itself seems pretty new
2. Grocy already has something like that!
3. Grocy is in PHP, which I work with for... 18 years??

-----------

Thus, I'm not only suggesting the feature but also willing to implement it on my non-existing free time :)
If this seems interesting, I guess we would need to discuss some details on the interface:
- [x] most of those details are simply new fields, so it's a no-brainer - add to form, add to table, call it a day
- [ ] however, the current interface would get a bit cumbersome, since the instruction file shows at the side of the table, which then would have more columns and scroll horizontally... Would it be reasonable if the list became block-based (like Homebox) instead of a table? This way it's responsive, in a way a table cannot be. Another option is to just get rid of the auto-show booklet, or make that an option.
- [ ] question-mark ideas:
  - [ ] storage locations make sense for this section of Grocy? If so, would it be possible to integrate the storage location with the stock locations? Maybe add a new field to locations as to indicate if that's used for stock, equiment, or both?
  - [ ] is it doable to create more than one file for the instructions / receipts, or would this get way too complex on the current Grocy db?
  - [ ] I think the pic would make a lot of sense on a grid list, but not so much for the table - unless people find it useful for other users to locate what they're talking about, for instance.
- [ ] any other remarks?

This very, very slightly touches #1558, which is also a feature on Homebox. However, I wouldn't venture down this path since I have no clue where to start with calendar appointments, repeatable tasks, integration with the task system, etc.

**Comment by berrnd** [comment]
Since it's impossible to add each and every individual field each and everyone on this planet can think of for every entity in Grocy, Userfields were invented a long time ago. By utilizing them, you can add any field _you_ want to any entity (= an equipment record, a product, a chore, a shopping list item, everything). So simply try that and all the fields you've mentioned will be right there, without touching a single line of code.

When we now add all the fields you find useful built-in, be sure to have a little shitstorm right after the next release about the clutter + 165 new field requests. This really makes no sense.

Using file-Userfields even renders separate tabs for [/equipment](https://demo-prerelease.grocy.info/equipment), have a look at #441 and #978.

**Comment by igorsantos07** [comment]
Awesome, it covers 90% of what I was expecting :pray: 

I'm thinking of some better way to let new users discover userfields and how versatile they are... Without veering into a tutorial, of course :clown_face: 
Maybe it could be mentioned at the bottom of some of those screens, such as Equipments, since it's a veeery lightweight entity where people might feel more fields are lacking?

![image](https://github.com/grocy/grocy/assets/532299/44320b5e-66aa-4d06-aad5-70348c312115)

![2023-11-14_22-28](https://github.com/grocy/grocy/assets/532299/27c8432c-f565-4958-8f89-e2e5861cd721)

**Comment by berrnd** [comment]
> Your answer even sounds a bit rude

Let me know next time if you need more flowers between words, I prefer facts based on reality - always remember you don't need to like me or Grocy, this here is not about love. It's my pleasure when it works for you.

&nbsp;
> Maybe it could be mentioned at the bottom of some of those screens

Sure, you could write it on every screen on 10 places, but this won't help with requests like that, since people don't read (even not READMEs) or search beforehand. If you're also a developer for public (free) software stuff, I guess you know that. Grocy is a couple of years old and is used and has a community of thousands in the meantime, which is mostly my pleasure, but yes, you learn the lessons on that road.

**Comment by igorsantos07** [comment]
You definitely sound more likable on the Grocy website and in your own pages (although I just skimmed through them). You can still be rooted on facts while being kind to **people** - it's not like I wrote this long suggestion based on hate on your product, much on the contrary. I also don't think it's this way you're getting people to actually contribute to your software.

You can't exactly blame users for "not reading" if there's _nothing_ to read. No help page, no guide, no startup tutorial or tips, no nothing. The user is just thrown into the interface and got to figure it all by themselves. You see, you wrote this userfields feature _a long time ago_ and yet you get angry (or feel like you are) when people suggest new fields because they don't even realize such feature exist. Why could that be?

**Comment by igorsantos07** [comment]
To make sure this mess is not a culture difference between both of us, I tried to look around and found it amusing the title ChatGPT gave to the question :man_shrugging: 

![image](https://github.com/grocy/grocy/assets/532299/010636cb-46fa-467a-b3dc-2647503992a8)

**Comment by berrnd** [comment]
> Why could that be?

Because people (of course not everyone, in fact even more the smaller number, as always on such sayings) tend to be lazy, a lot of them even can't put the exact question they have into one's search engine of choice beforehand, which (un)surprisingly brings the answer as the first result. And that's not only the case for Grocy and, based on my personal life experience, more a problem of the younger generation (wow, seems I'm getting finally old).

Yes, I don't write step-by-step-for-the-lazy tutorials (just because it's something I have fun with) and I blame people for being lazy and/or putting zero effort into their requests. I can say I put more than a lot effort into this, since years (in time: several full months have gone into Grocy to make it what it is today) and I demand just a little bit of the same. And you're very wrong about "there is nothing to read", there is: ~2k other requests here + most likely the same amount on Reddit on questions about Grocy and everything, easily discoverable with many search engines we have on this planet. You just need to start using 2023 information system capabilities. But you can also write me a letter next time if you want (here in Germany we even have a fetish called Fax, try that, it's great - after that dig into Teletext, the next generation internet or something like that).

This is a hobby project, driven by (my) desire, intended to be fun (again: for me). Just like every hobby, hope yours too. People also often mix up that this (or any Open Source volunteered tool) is not a product you've paid for and can have expectations. That even includes the (my) tone used for support requests. I don't owe anyone anything, I am who I am and how I am. Seems also you mix up that this is really not about love, you don't need to like me or Grocy and anything around it and if the opposite is the case, I would remove all that from my life immediately, at least I do that with everything of such. Makes smiling more.

Another false assumption you've mentioned: I'm not doing this to get 500 trillion users or begging for contributions (in fact, over the years it turned out that drive-by contributions are nice, but need just more time on the long run than doing it myself, since one that came just driving by fixing one bug or implementing one feature just doesn't have the full application in mind when doing stuff, and that's just ok, but it is how it is then at the end - also nothing special only happening on this project).

I initially built Grocy for my very own needs. In the meantime it has features I don't use myself, I just built them for fun as part of the mentioned hobby - also something often surprising for "users", since they have (sometimes big) exceptions for a zero dollar product.

And thanks for the social educational lesson, but don't worry: Sarcasm was intended and the rest too (remember: I am who I am). Lol that you need a KI to explain that.

Let's please finally stop this off-topic talk here, that's the issue tracker for reproducible Bugs and Feature Request for a software called Grocy, not for the human Bernd Bestel.

If you have another question/issue/whatever with Grocy, feel free to go on with that and when using concrete messages and not being lazy beforehand, you get a short answer, without any sarcasm but still also without flowers, or even a fix / new feature within hours, since that's also who I am and despite it was more a thing of the past, people's ideas are still my motivation, at least sometimes and I don't get why I even try to justify on all that, but well (check the mentioned other requests if you need a proof on that). Maybe at some point you can admit to yourself that the origin of this request was exactly laziness, because of: https://www.google.com/search?q=grocy+equipment+custom+fields
