### ISSUE TITLE
Bug: disable barcode button when it's not supported

### ISSUE THREAD

**Issue by igorsantos07** [grocy/grocy#2383]
After reading the README, looking for actual documentation on userfields, I realized why the barcode button is not working in my scenario: Grocy is not being served via HTTPS. Hadn't read it in the past since it seems focused on developers, which I am not, and installation was made a breeze through Home Assistant.

This is easily identifiable and thus, the button should be hidden to avoid user confusion, or at least add a warning when trying to press that. Not to mention the popup doesn't help much with an empty select box either... I guess that's for selecting a camera, but if no camera permission is given (not even requested because of no HTTPS), why does the popup stays there?

![image](https://github.com/grocy/grocy/assets/532299/dfcfe73f-3684-4c6b-9711-eb74738c5efb)

**Comment by berrnd** [comment]
Not using HTTPS is generally a thing of the past. That the camera is unavailable when not using a secure connection is a security restriction of all major common web browsers, but it's still not impossible to configure your Browser to allow that even on insecure connections, if that's really what you want.

Grocy even points that out directly above the error message popping up on any camera stream error. No need to dive into README (which is definitely not targeted on developers only, however you came to that conclusion) for that here.

Technically using an unsecure connection is just one of the endless possibilities of practical problems. You can deny camera requests (on multiple levels Browser/OS/etc.). There can be hardware issues. Just to mention a few.

![grafik](https://github.com/grocy/grocy/assets/2161815/9baf47d8-8a55-478c-be1d-daa056c4c86d)

If, then this would be a Feature Request, definitely not a bug and hiding that button on insecure connections on purpose always is just wrong.

If you tend to click on that button daily while still not having a secure connection, just disable camera barcode scanning - there is a `config.php` option for exactly that ([README ref](https://github.com/grocy/grocy#disable-certain-features)):

https://github.com/grocy/grocy/blob/8f52aaeadce14ea0ee1de4514acc1d27287e42c5/config-dist.php#L154

**Comment by igorsantos07** [comment]
So the fact Grocy shows a non-functioning button that takes me to a meaningless popup is **not a bug** for you?

**Comment by igorsantos07** [comment]
Checking console, I see the camera lib throws a silent error. Again, this is a bug and should be caught by Grocy and shown accordingly in the UI:

>Uncaught (in promise) Error: enumerateDevices is not defined. This may mean that the user has declined camera access, or the browser does not support media APIs. If you are running in iOS, you must use Safari.

**Comment by berrnd** [comment]
The button is only not functioning for you, because you have decided to use a Browser / connection with corresponding limitations. And Grocy shows that.

I don't get why you simply don't disable that feature then, but ok. You don't help, you just whine around out of principal or whatever, it's not the first thread with us - again: There is a `config.php` setting to disable this immediately if you don't need it because it's not working in your environment due to limitations out of Grocy's scope. I just repeated that now 3 times here. Fun fact: No other user had a problem with that in the last 6 years. Not clicking the button again, if you already know it's not working and why, is just another simple and very practically oriented option for such a "problem".

In any case, I've read your answer before the last edit and because of that I'm now stopping here wasting my time. Don't use Grocy if it's full of bugs for you.

&nbsp;
> enumerateDevices is not defined

Technically this is due to what I just mentioned: Your Browser hides this API on unsecure connections, so this error is of course not a surprise.
