### ISSUE TITLE
Bug: Add/view works, edit/delete doesn't

### ISSUE THREAD

**Issue by fiber-ee** [grocy/grocy#2390]
Fresh install: http://gr.mooni.ee/
login/pass still default - can't change.

I can add / view anything, but can't add/change anything.

Feel free to test on url above.

 Version 4.0.3
Выпуск от 2023-09-02 3 месяца назад

PHP Version 8.1.23
SQLite Version 3.44.2
OS Linux 4.19.0-25-amd64 #1 SMP Debian 4.19.289-2 (2023-08-08) x86_64
Client Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0

**Comment by berrnd** [comment]
> Feel free to test on url above.

Sorry, but this here is not personal Grocy support and individual setup problems are really not a bug - would be super great if you could mind what's mentioned on the issue template and [in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests).

&nbsp;

Your web server more than obviously blocks anything else then `GET` / `POST` / `HEAD` requests, Grocy (and just any other web application having and using a REST API) also needs `PUT` (that's why you can't change existing data) and `DELETE`. However you came to the conclusion that blocking those request methods is a good thing...

So I would recommend triple checking and rectifying that and everything will work.

**Comment by fiber-ee** [comment]
Thanks.
PUT/DELETE was disabled for security reasons, now all works.
Maybe add to install section, that server must support PUT/DELETE ?

**Comment by berrnd** [comment]
> Maybe add to install section

No.

&nbsp;
> for security reasons

What reasons exactly are you referring to? It's just a request method, technically everything what a `POST` request is capable of, a `PUT` or `PATCH` or `DELETE` request is capable of in the very same way, nothing more or less secure or insecure.

**Comment by berrnd** [comment]
> Mostly: https://www.imperva.com/learn/application-security/http-verb-tampering/

Completely unrelated to a web application like Grocy, but ok - of course disabling e.g. `DELETE` makes Grocy much more secure, you even can't delete anything that, how secure is that.

You're hosting your Grocy instance publicly, even shared the URL publicly and said "login/pass still default" while even having no TLS in place - so without any doubts, security is your most important concern I guess. But disabling random HTTP request methods compensate all that, I'm sure.

All the best.
