### ISSUE TITLE
Feature Request: Cache support

### ISSUE THREAD

**Issue by webysther** [grocy/grocy#2396]
Support for memcached/redis/apc cache for some levels, like views, controllers and databases items. This will be one step in direction to be session transient between servers, which provide some scale.

**Comment by berrnd** [comment]
> provide some scale

The target use case of Grocy is your home, so how big is your family that such scale is needed? Or is your current instance just slow as hell for whatever reason?

The [demo instances](https://demo-prerelease.grocy.info) run more than snappy on below-average hardware while serving more daily page views any real world Grocy family instance will ever see ([insights here](https://www.reddit.com/r/grocy/comments/15lm1he)).

I don't solve theoretical problems, only the practical ones - so this won't be added, sorry.

**Comment by webysther** [comment]
Hi @berrnd scale is not the main focus, is the performance for page loading, after the latest release I saw a few improvments but with PHP is almost impossible to get a good performance without at least apc.

**Comment by webysther** [comment]
> > session transient between servers, which provide some scale
> 
> The target use case of Grocy is your home, so how big is your family that such scale is needed? Or is your current instance just slow as hell for whatever reason?
> 
> The [demo instances](https://demo-prerelease.grocy.info) run more than snappy on below-average hardware while serving more daily page views any real world Grocy family instance will ever see ([insights here](https://www.reddit.com/r/grocy/comments/15lm1he)).
> 
> I don't solve theoretical problems, only the practical ones - so this won't be added, sorry.

This point about the demo is insteresting, if you have constant access the opcode will get more hit rate, but for a home with 2 users like me, the few pages after hours without access is slow as a hell, after while get fast because opcode is used.

With memcached or even apcu this can be more fast main for the view, there lots of databas dictionary that don't get update and this can be put in cache until the table receive update.

**Comment by webysther** [comment]
I think to start working in something in future, just let me know if you is keen to accept the PR.

**Comment by berrnd** [comment]
If your personal instance is slower than the [official demo instances](https://demo-prerelease.grocy.info/), you just did not the best job regarding web server / PHP configuration, that's all. Simply have a look at the [publicly shared](https://www.reddit.com/r/grocy/comments/15lm1he) NGINX / PHP-FPM configuration of those instances, tweak yours based on that and if that all doesn't help, share your concrete problems / real world numbers on the [r/grocy subreddit](https://www.reddit.com/r/grocy) (this here is not the place for general usage / configuration help as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests))

&nbsp;
> if you have constant access the opcode will get more hit rate, but for a home with 2 users like me, the few pages after hours without access is slow as a hell

Complete bullshit and just, once again, a configuration thing. I use the same config for my personal instance and it runs even faster, since the underlying hardware there has more horsepower compared to the demo server one. Funfact: My personal instance is used by me and only me. Simply share real world scenario problems (configuration / hardware / software used / what slow means in real numbers) instead of getting lost in theory. Generally sounds to me more like the general PHP allergy some people have, most of the time due to ignorance rather than technical limitations - step out of your comfort zone and experience how fast modern PHP can be, we don't life in 1998 anymore.

&nbsp;
> just let me know if you is keen to accept the PR.

As already said: No. Grocy runs fast for the desired target use case (a home / family) and even beyond with proper web server / PHP configuration. Proof of that: The official demo instances, as just pointed out.
