### ISSUE TITLE
Bug: Cannot change quantity unit of product

### ISSUE THREAD

**Issue by kevinholtkamp** [grocy/grocy#2405]
I cannot change the quantity unit of a product after creating the product:
![image](https://github.com/grocy/grocy/assets/32170328/26041a9b-a502-428e-8413-efbc09a1358c)

I have multiple quantity units as shown here:
![image](https://github.com/grocy/grocy/assets/32170328/59ccd661-c60c-47d7-8eaa-3afec1115a86)

**Comment by berrnd** [comment]
This is nowhere a Bug, please be so kind and do a little search beforehand and use the [r/grocy subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) for general usage questions.

Once a product is added to stock, you need to tell Grocy how much a Pack is related to your desired other unit, since Grocy needs to convert all existing amounts everywhere - it's impossible to guess that - you can tell Grocy that by creating corresponding unit conversions.

Just mentioning a few recent threads about that, easily discoverable in seconds:
- https://github.com/grocy/grocy/issues/2369
- https://github.com/grocy/grocy/issues/2357
- https://www.reddit.com/r/grocy/comments/16vsvwe
