### ISSUE TITLE
Feature Request: Automatically derived userfield values

### ISSUE THREAD

**Issue by turmoni** [grocy/grocy#2406]
I'm finding it hard to see if something like this already exists, but it would be nice to be able to automatically generate some userfields. As an example, I have alcoholic drinks in my Grocy instance, and I enter the ABV, the container size, and the number of UK units. Any one of those could be derived from knowing the other two, although in practice I'd be deriving the number of units.

My data isn't entirely clean so there would need to be some kind of pattern matching (e.g. I have "500ml can" and "500ml bottle" as sizes, and ABV ends with a "%"), and also I'd want to specify an arbitrary precision.

It would also be useful to be able to still manually specify a value (e.g. I don't actually have every single size of drink listed so for some unusual ones I just put "large"), but I imagine that adds complexity compared to one that's solely derived from other data.

Some extra keywords for people doing similar searches to those I did: math, maths.

**Comment by berrnd** [comment]
Please provide a real practical example what exactly should be derived from what and also the general logic behind (how the derived value can be actually derived) - at least commented screenshots or (even better) a concrete example on a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b).

Generally sounds for me like a very special use case and [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) will already be able to support very specific and custom use cases.

Would also be interesting how you would expect to define such highly customizable rules at the end. When it turns out to be something like JS, then custom JS is essentially exactly the same.

**Comment by turmoni** [comment]
The specific example is deriving units - as an example, if a drink is 440ml, and 5.3% ABV, then the number of units is 5.3*(440/1000) = 2.3 (to one decimal place). This would then be usable as any other field.

I assume your suggestion with custom JS is to have it as something that calculates it on the product creation screen to fill in to the existing userfield? That sounds like it would work for what I want, I just need to look into that.

**Comment by berrnd** [comment]
> I assume your suggestion with custom JS is to have it as something that calculates it on the product creation screen to fill in to the existing userfield?

Exactly. And since this can be as custom / specific as nobody can imagine, it's kind of impossible (or at least more than much work) to put this into a UI which has limitations at the end in any case. (Custom) JS can fulfill all those customization needs without limitations, so closing this in favor of using that for this.

Just practically speaking: This calculated number is filled in once and doesn't change for the corresponding product after that, as far as I understand it. So unless you create such new products hourly, I personally most likely wouldn't even fiddle around some custom JS for this and simply fill it it in manually, like any other field.

**Comment by turmoni** [comment]
I probably will look into the custom JS, simply because I often find myself having to add a load of new products at once and the ABV and volume are always there whereas units might not be, thanks for the suggestion (and hopefully this issue is helpful for pointing anyone else with a similar use case in that direction).
