### ISSUE TITLE
Bug: "Iframe modals" not properly displayed in Firefox 121

### ISSUE THREAD

**Issue by Janovlk** [grocy/grocy#2421]
hello,
I am able to reproduce it in: https://en.demo-prerelease.grocy.info/shoppinglist.
When I add a random item into a shopping list in /stockoverwiev using Add to shopping list menu item few (3 - 8) times, then when I switch to /shoppinglist page and do the same using Add item again few times, finally, it doesn't display the Create shopping list item window properly.

At first I noticed it in my copy of Grocy 4.0.3 only in Firefox (currently 121.0 (64-bit), Windows 10 22H2) and I wasn't able to reproduce it in demo (or prerelease) version. But now I am. There is a way how to rectify the display of "Create shopping list item" window: use Ctrl+- or Ctrl++ to resize the whole page and then Ctrl+0 to put it back to 100% view.

It never happened in Edge (which I'm using for Grocy now, in order to avoid this glitch). So it isn't exactly the Grocy bug. But I'm reporting it here along with a screenshot.

![FirefoxGlitch](https://github.com/grocy/grocy/assets/140972046/e69be5cc-10ce-40b0-a70c-b6e5f69e126b)

Thank you for your great work,

(P()P)

**Comment by berrnd** [comment]
I already noticed this myself, also on several other places where "iframe modals" are used, starting with Firefox 121. It happens pretty random, never got it reproducible anywhere so far, also your description doesn't provide an always reproducible example (in fact, different pages in Grocy don't know anything about each other).

Since Edge/Chrome is not affected, definitely something in Firefox seems to have changed with v121 - haven't consulted their issue tracker so far or tried to investigate using e.g. Firefox Developer Edition / Beta if the problem is maybe already gone there.

**Comment by berrnd** [comment]
It was related to [this change](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/121#html) in Firefox 121.

Since this problem was not always reproducible, would be great if you could give it a test drive by replacing the file `public/js/grocy.js` by [that one](https://raw.githubusercontent.com/grocy/grocy/efae5fea5b9e8497169ce5320047378eb0cafdc6/public/js/grocy.js) (this is compatible with the current release Grocy v4.0.3).

If you do so, please make also sure that your Browser isn't accidentally caching that file - "cache busting" is only handled between different Grocy releases.

**Comment by Janovlk** [comment]
Thank you,
I deleted all the site data and it works after some 30 attempts.

**Comment by Janovlk** [comment]
After some other testing the previous bug is gone but there is another similar when I press the Purchase button in Shoppinglist page.
The problem is intermittent here as well. I'm getting it in my own Grocy instance, it never occurred for me in demo version.
BTW the Firefox is now 121.0.1.
![FirefoxPurchase1](https://github.com/grocy/grocy/assets/140972046/afbffe54-9d01-4543-866c-26079b0dd924)
![FirefoxPurchase2](https://github.com/grocy/grocy/assets/140972046/625ac2d9-ac2e-4b2a-adc6-0fb0da5e30a4)

**Comment by berrnd** [comment]
> but there is another similar when I press the Purchase button in Shoppinglist page
> it never occurred for me in demo version

That's because that was also already fixed as part of efae5fea5b9e8497169ce5320047378eb0cafdc6, to test it you'd need to additionally replace the file `views/shoppinglist.blade.php` with [that one](https://raw.githubusercontent.com/grocy/grocy/efae5fea5b9e8497169ce5320047378eb0cafdc6/views/shoppinglist.blade.php) (+ clearing `data/viewcache`, [README ref](https://github.com/grocy/grocy#how-to-update)).

The changes in `grocy.js` target most places, but there are a few other ones (e.g. meal plan too), have a look at efae5fea5b9e8497169ce5320047378eb0cafdc6 for all changes.

**Comment by Janovlk** [comment]
I replaced all the fixed JS files from link (and one PHP), deleted viewcache folder, deleted local data but it didn't help this time. The Purchase dialogue never appears like my second example but always like the first one. When I close the Purchase dialogue, it sometimes displays properly afterwards.

**Comment by berrnd** [comment]
I did extensive tests on all affected places using my private instance too (where I experienced exactly this problem daily since Firefox 121 was released, but no longer since yesterday), it definitely works in Firefox 121 when properly applying the changes did in efae5fea5b9e8497169ce5320047378eb0cafdc6. So triple check again that nothing is cached anywhere (if you e.g. use OPcache also make sure to restart the PHP runtime or the whole machine) or simply wait for the next release - it's more than most likely about caching stuff or simply not properly applied changes.

**Comment by Janovlk** [comment]
I restarted my server, cleaned up viewcache again.
It never happens in demo version for me. Only in my version. Maybe it's connected with speed of my server. The dialogue shows up properly when called for the second time.

**Comment by berrnd** [comment]
Whatever, unless having another reproducible example I can't do more. The base root cause related to the changes in Firefox 121 is solved in any case. If it's a about machine slow af, like a Raspberry Pi, I won't do any optimizations for that area, like since ever.

**Comment by berrnd** [comment]
Did some more best-guess optimizations in fc072b13f28537d612fd105b261fc0ec654de244, feel free to replace `public/js/grocy.js` by [that one](https://raw.githubusercontent.com/grocy/grocy/fc072b13f28537d612fd105b261fc0ec654de244/public/js/grocy.js) again.

**Comment by berrnd** [comment]
More event timing related optimizations in 33d5ec44d23eb8ec37c7a9b633cecd29f8cabadf, all changed files are attached in the ZIP below for easy testing.

[grocy_changes_33d5ec4.zip](https://github.com/grocy/grocy/files/13929265/grocy_changes_33d5ec4.zip)

**Comment by Janovlk** [comment]
Thank you,
I restarted PHP service, cleared Viewcache. All the windows appears without any glitches.
