### ISSUE TITLE
Feature Request: Details for tracked battery charge cycles (Userfields)

### ISSUE THREAD

**Issue by TheDodger** [grocy/grocy#2437]
Hello,

as the title should sufficiently describe I would suggest an additional optional data field to track changes in capacity over time. I already tried that with custom fields, but these aren't usable with charge cycle tracking. In my opinion at least, such data should generally be possible to store when tracking batteries.

This field could simply be added to charge cycle tracking entries and sometime in the future be used to create graphs (in Grocy or externally).

Also I thought about a field for noting stated capacity for general battery entries, but this could either be included in the battery description or created as a user defined field.

If I had time and programming skills, I would submit a pull request.

Thanks for all your great work!

**Comment by berrnd** [comment]
As mentioned on the request template, let's keep it to one topic per request, since everything else is simply untrackable.

And also a generic approach is always the way to go to fit everyone, so let's track here to make it possible to add Userfields for [/batterytracking](https://demo-prerelease.grocy.info/batterytracking) which are then visible on [/batteriesjournal](https://demo-prerelease.grocy.info/batteriesjournal) on the corresponding tracked charge cycle (practically in the same it's already possible for chores, ref #825)

**Comment by TheDodger** [comment]
Had a quick look at userfields. Nice work!

See my PR #2490, vNEXT maybe? :)
