### ISSUE TITLE
Feature Request: Hide functionalities not wanted from the left menu

### ISSUE THREAD

**Issue by gabt92** [grocy/grocy#2438]
Hello!

It would be great to hide the functionalities that we are not using (ex: Recipes, Meal plan or Batteries) to clean up the screen a little bit. From the admin settings or somewhere else, a simple checkbox to show or not would be enough.

![image](https://github.com/grocy/grocy/assets/38195308/adf047c1-920d-48e3-a6d6-0aa3a53480f1)

**Comment by berrnd** [comment]
That's possible since ever, please have a look [at README](https://github.com/grocy/grocy#disable-certain-features), your [`data/config.php` file](https://github.com/grocy/grocy/blob/efae5fea5b9e8497169ce5320047378eb0cafdc6/config-dist.php#L128-L155) and please be so kind and do a little search beforehand, this has been asked numerous times.

**Comment by berrnd** [comment]
And if you [still](https://github.com/grocy/grocy/issues/2086) use Grocy via the Home Assistant Add-on, it's of course also possible there, even without manually touching config files: https://github.com/hassio-addons/addon-grocy/blob/main/grocy/DOCS.md#option-features

(Don't use HA myself, discovered that by a quick and easy search using the title of this request on my search engine of choice).
