### ISSUE TITLE
Calorie Tracking

### ISSUE THREAD

**Issue by kevinholtkamp** [grocy/grocy#2450]
A simple feature to sum up the calories of all items consumed on a specific day/week/month to track calories more easily

**Comment by berrnd** [comment]
Grocy is about managing your home, not your health and this will stay like this.

**Comment by kevinholtkamp** [comment]
May I ask why even have the option to enter calories?

**Comment by berrnd** [comment]
You can utilize Userfields to extend the available fields kind of everywhere throughout Grocy.

Products of course have a energy field ([demo ref](https://demo-prerelease.grocy.info/product/20#calories)) and this is accordingly summed um on recipes (since ever), if you meant that.

In any case, this is not the place for general usage help ([README ref](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests)) - the health related Feature Request was declined, so everything has been said for that and I'm going to close this.
