### ISSUE TITLE
Open API definition missing several ExposedEntity_* properties

### ISSUE THREAD

**Issue by ericblade** [grocy/grocy#2455]
I just created an API definition using openapi-typescript, which works great, but at some point things all start going south when tsc gets ahold of the whole source tree, due to the following missing schemas, all starting with "ExposedEntity_"

NotIncludingNotListable, NotIncludingNotEditable, NotIncludingNotDeletable, IncludingUserEntities, IncludingUserEntities_NotIncludingNotEditable

**Comment by berrnd** [comment]
A Bug is something that doesn't work as defined, this is nothing regarding that - please simply ask if something is unclear (on the [r/grocy subreddit](https://www.reddit.com/r/grocy), [README ref](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests)) and don't report anything which is maybe not super clear at a first sight (which is of course ok and I'm happy to answer each and every question which comes up, did that since 7 years, kind of daily).

First: Simply don't take [`grocy.openapi.json`](https://github.com/grocy/grocy/blob/master/grocy.openapi.json) "as is" (the file), but use the API endpoint [`/openapi/specification`](https://demo-prerelease.grocy.info/api/openapi/specification) which resolves "placeholder entities", probably leading to things not going that much south.

Second: The sole defined purpose of [`grocy.openapi.json`](https://github.com/grocy/grocy/blob/master/grocy.openapi.json) is to feed the the [/api](https://demo-prerelease.grocy.info/api) page, nothing else.

Also a little search beforehand doesn't hurt, related thread: #2198

**Comment by ericblade** [comment]
I appreciate your plight, Bernd, I've been developing software for 40 years, so I'm pretty familiar.  I'm also not too bad with Google, so it's not like I haven't given some cursory attempts at solving the issue myself.  

I actually pointed the openapi-typescript package at the master branch here at github, and also referenced the PR from a few weeks ago that solved several other issues with the open API specs.  Please don't assume we are all helpless.

I'm going to apologize for not making this bug report as clear as I probably should've, but assuming that anyone who tries will land on a random branch of the project... no.  

Even knowing *exactly* *what* *to* *search* when given links to related threads, doesn't really land me in the correct place.  This trip started with "how do i get an openAPI spec from my grocy server", and ended on "filing a bug report because I didn't land on #2198 ".  What I *did* land on, though, was the PR from a couple of weeks ago that fixed other problems in the openAPI spec, so I thought I would point out where there were a few more holes.  

It's OK, though, because they've already been fixed in a different branch that isn't indexed.  Cool.  

Sorry to waste your time.

**Comment by berrnd** [comment]
> I was not able to locate a reference to /api/openapi/specification until I specifically was told about that

Because, by (my, always bad, I know - I only do things wrong on anything Grocy) definition nothing and nobody else than the [/api](https://demo-prerelease.grocy.info/api) page needs that, as already pointed out above. It's nowhere stated that throwing that into a random API client generator is supposed to work and therefore not a surprise when it's not and not a bug.
