### ISSUE TITLE
Feature Request: Dynamically Define Parent Products picture from Child Products

### ISSUE THREAD

**Issue by saya6k** [grocy/grocy#2464]
It is common practice that use parent products as category like 'Milk', and child products as real product, milk bottles from specific brand.

It would be useful to dynamically assign parent categories, like 'Milk', based on child products in such case.

This feature should prioritize child products on a first-in-first-out basis, helping users decide which product to use first.

I haven't found a similar request after searching.

**Comment by berrnd** [comment]
Well, it would make practically more sense that child products could inherit any product property from its parent - #1304 is all about that.

&nbsp;
> This feature should prioritize child products on a first-in-first-out basis, helping users decide which product to use first.

So instead of just setting the product category of the parent "Milk" to whatever you want, you want to be able to pick a child product to take it from there then? What's the real practical benefit?

Or does "first-in-first-out basis" mean the first child ever created for the corresponding parent? Beside that this event would need to be technically tracked somehow, it sounds pretty random to me...

&nbsp;
Please describe a real practical example for what this would be useful for, please create a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) for that.

**Comment by saya6k** [comment]
I agree that child product should have inherit properties from parent product.

However, In picture, I prefer to give each child product their own picture. It's because child product can have different appearance or method to store. Think about alcohol beverage. It can be can, bottle, barrel etc. Or maybe chocolate. It can be candy, bar, powder, drink and such.

I think having pictures from child product can be better approach in cases like this.

What do you think? If you don't agree or can suggest a better practice, let me know.

**Comment by berrnd** [comment]
So it's only about the picture, nothing else (a product has many more properties).

So that "first-in-first-out basis" would be at the end a pretty random rule to pick a picture from a random child for the parent product.

Let's face the reality: I doubt you change your products daily and I also doubt that simply setting the picture you want (instead of a random one) at the parent is that much more work beside what you need to do anyway to have a properly organized Grocy. So nothing will be changed or added for that.

**Comment by saya6k** [comment]
OK, I understand. Maybe I'll just define parent picture.
