### ISSUE TITLE
Feature Request: QU for included recipes

### ISSUE THREAD

**Issue by VitalyVaryvdin** [grocy/grocy#2465]
Just started with grocy and stumbled upon workflow breaking issue.

I've got a recipe for a sauce which I'd like to use in a different recipe. However, I can only specify serving amount if I add the sauce recipe as "Included Recipes", which is pretty useless in that case - I'd like to specify QU such as tablespoon, gram, etc.

I'm either missing out on something here or my use case is just different.

I see three possible solutions here:

1. Auto produce product. Would be neat addition to stock management for meal prepping.
2. Add QU as an alternative option to "Servings" in "Included Recipes" 
3. Allow recipe selection in an ingredient list

**Comment by berrnd** [comment]
The "QU" of a recipe is exactly the serving amount.

If you want to include a recipe, but redefine all the ingredient (amounts) of that included recipe, that would be just another recipe and not something for an included recipe.

When you just started using Grocy I highly recommend using the [r/grocy subreddit](https://www.reddit.com/r/grocy) for general usage questions ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests)) instead of reporting everything which is not crystal clear for you at first sight as a bug or feature request here, most of the time it's already possible (Grocy not only exists since this morning and is used by thousands of people). Most of the recreating your specific use case on a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) is also helpful, since just like every time there is more around than words or screenshots can tell.

&nbsp;
> Auto produce product. 

A recipe can produce a product, check the recipe option "Produces product":

![grafik](https://github.com/grocy/grocy/assets/2161815/d6fae13d-8980-4f10-b898-37267985adc1)

&nbsp;
> Add QU as an alternative option to "Servings" in "Included Recipes"

The serving amount of an included recipe is basically that QU, as just pointed out.

&nbsp;
> Allow recipe selection in an ingredient list

An included recipe is exactly that. Basically every ingredient the included recipe needs (and even the included recipes of that recipe; unlimited levels) is then "virtually" part of the recipe you included it.

**Comment by VitalyVaryvdin** [comment]
None of what you said solves the issue. Sadly, software that is born not today still can't handle basic use case.

Go on, create a recipe of a sauce and add two tablespoons of that sauce in a different recipe without manually copying all of that into a product.

Thanks for your time.

**Comment by berrnd** [comment]
It is possible, you just need to define your serving amounts accordingly - go on and create a practical example on a persistent demo instance and then I maybe go on and help you based on that (but not here, this is not the place for general usage help).

&nbsp;
> Sadly, software that is born not today still can't handle basic use case.

If that's your conclusion that Grocy can't handle what you need, Grocy is just not the right tool for - I'm not aiming to fulfill your personal needs in every detail. I would simply go on and try the next tool on my list in that case, or build my own.
