### ISSUE TITLE
Feature Request: "Add to shopping list" from context menu: Default shopping list

### ISSUE THREAD

**Issue by mawwinius** [grocy/grocy#2472]
When adding a product to a shopping list via the "Add to shopping list" button on the Stock overview, Stock entries or Stock journal page, the shopping list which comes first when sorting all of them alphabetically is pre-selected in the "Create shopping list item" form. In my opinion, it would make more sense to select the default shopping list (the one you land on when selecting "Shopping list" from the menu).

### Steps to reproduce:
- Create multiple shopping lists, make sure the one with ID 1 is not the first when sorting them alphabetically (e.g. create a shopping list named "AAA")
- Go to Stock Overview page (Or Stock entries or Stock journal for a specific product, maybe more I missed)
- Click the three dots next to an entry, select "Add to Shopping list"

### Current behavior
(validated on the pre-release demo): The alphabetically first shopping list ("AAA") is selected

### Expected behavior
(would be consistent with the Android and iOS app): The default shopping list (with id 1) is selected.

### Potential solution
This could be achieved by appending `&list=1` to the link of the "Add to shopping list" button. If you like, I could try to implement this and create a Pull Request.

**Comment by berrnd** [comment]
> Expected behavior
> The default shopping list (with id 1) is selected.

That's fine that you expected that, but how is something you personally expect supposed to be a Bug?

I'm open to improve or change stuff and that's what naturally a Feature Request is for, but allergic when each and every little detail is reported as a Bug.

**Comment by mawwinius** [comment]
Okay, that answers the question which of these two types I should have chosen. Honestly, I was unsure, and would like to apologize for mis-categorizing this one. Thank you for changing the label accordingly.

Do you agree with my opinion on the expected behavior? And if yes, would you be interested in a Pull Request implementing my suggestion?

**Comment by berrnd** [comment]
> Do you agree with my opinion on the expected behavior?

Doesn't sound not right at a first sight, but I don't think each and every request to the very end before working on it.

&nbsp;
> And if yes, would you be interested in a Pull Request implementing my suggestion?

Feel free to do whatever you want. In any case, please make sure to not only have your specific workflow in mind - test stuff you change thoroughly. Grocy e.g. has [Feature Flag `FEATURE_FLAG_SHOPPINGLIST_MULTIPLE_LISTS`](https://github.com/grocy/grocy/blob/edf973df00b327344c589536a3b67be45890196d/config-dist.php#L148C10-L148C50) which most likely has to be taken into account for this - just saying that due to I had it multiple times in the past where even such rather simple changes introduced kind of triple the time needed to review it, than simply doing it myself.
