### ISSUE TITLE
Feature Request: Set "Desired Servings" to recipe servings by default

### ISSUE THREAD

**Issue by controlaltnerd** [grocy/grocy#2479]
I can't find any discussion on this, so I'm suggesting it here. When a recipe is created and its servings are set, the "Desired Servings" field in the recipe summary/preview on the recipes main view displays the ingredients needed for a single serving, resulting in odd measurements such as "0.0834 Teaspoons", and requiring the user to modify that field in order to see the ingredient amounts according to how the recipe was written.

I would suggest changing the default behavior of this field to match the servings listed in the recipe editor, to avoid extra work on the user. This is how the meal plan editor works when selecting a recipe, so it seems that this change would provide more consistency in the user experience.

**Comment by berrnd** [comment]
Just for clarification, maybe it's not super clear what the two numbers are about although that's pretty well explained on the corresponding help tooltips:

Recipe Base Servings, what you edit when editing a recipe ([demo example](https://demo-prerelease.grocy.info/recipe/5)):
The amounts entered for each ingredient on the recipe edit page are related to this amount of servings.

Recipe Desired Servings, what you edit when viewing a recipe ([demo example](https://demo-prerelease.grocy.info/recipes?recipe=4)):
The amount of servings you want to make this time, all the there shown ingredient amounts are then recalculated based on what's entered there. Naturally this is a number you edit every time you want to make another amount as last time.

So prefilling "Desired Servings" with "Base Servings" at the initial recipe creation would be a very (very) minor enhancement, if it's an enhancement at all. I doubt that editing just another number is that much additional work at all when creating a recipe.

**Comment by controlaltnerd** [comment]
Where I see the potential for added work on the user, is that immediately after saving a recipe, I'd likely remember what the Base Servings number was and could edit the Desired Servings to match (although the tooltip doesn't make it clear whether changing that number results in a preserved change). But if I didn't make the change and came back in a month to reference the recipe while cooking, it wouldn't be immediately obvious how many servings the recipe originally intended without opening the recipe editor to check what I'd entered previously.

For example, I enter a recipe for soup that makes 8 servings. One of the ingredients is 1/8 teaspoon of cumin. Without modifying the Desired Servings, the recipe preview will tell me that I need 0.015625 teaspoon of cumin for 1 serving. I then either have to enter a few numbers to find reasonable measurement amounts, or open the editor to remind myself that this recipe is for 8 servings.

I could just mark the recipe as a single Base Serving, but then there would be cases where I might want to plan for enough soup to serve 12, and while I could add 1.5 servings to the meal plan in that case, I'd first have to go check somewhere, either in my recipe book or in the directions of the recipe in Grocy, to find how many servings the recipe was written for.

**Comment by berrnd** [comment]
> One of the ingredients is 1/8 teaspoon of cumin. Without modifying the Desired Servings, the recipe preview will tell me that I need 0.015625 teaspoon of cumin for 1 serving

Which is mathematically correct, or not?

&nbsp;
> I then either have to enter a few numbers to find reasonable measurement amounts, or open the editor to remind myself that this recipe is for 8 servings.

Why? The number is correct, you said you want only 1 serving this time (= what "Desired Servings" is for), don't understand that at all. "Desired servings" is about to say how many servings you want to make "this time", "Base Servings" is nothing to be considered at the same time, unless your recipe definition is just wrong.

&nbsp;
> But if I didn't make the change and came back in a month to reference

We talk here about initially prefilling "Desired Servings" when creating a recipe with "Base Servings". Desired Serving is remembered per recipe, regardless if you check back in a minute or in 5 years. And since I understand that this prefilling action on recipe creating will save so much time throughout Grocy of all, I better hurry up and will add that immediately (fun fact: not using Grocy saves even more time).

**Comment by berrnd** [comment]
> a new user

My recommendation: Simply use Grocy for a couple of days or weeks or months to get comfortable with it (if that's what you want, not everyone on this planets needs a tool like Grocy at all, in fact the vast majority does not) and don't report each and everything which pops up on your side / is not super crystal at a first sight. Grocy exists since years and is used by thousands of people, based on that it's unlikely that basics are missing or not already known (= tracked here).
