### ISSUE TITLE
Bug: Scanmode is not able to fill all fields sometimes. Next time, it works with the same barcode.

### ISSUE THREAD

**Issue by chris-h14** [grocy/grocy#2495]
Hi, first of all: Thank you for this great application!!

english:
If I scan using a barcode scanner lots of items as consume, the app says sometimes: "Scanmode is activated, but not all necessery fields could't filled out automatically". But all fields are filled out correct and you only have to press enter and then it works. This is very annoying :(

german:
Wenn ich mehrere/viele Produkte mit einem externen Barcodescanner scanne um diese zu verbrauchen oder einzukaufen, funktioniert es eine Zeit lang. Irgendwann kommt aber bei jedem Scan die Fehlermeldung, dass obwohl der Scanmodus eingeschaltet ist, nicht alle erforderlichen Felder ausgefüllt werden konnten. Was aber nicht stimmt, denn er füllt alle Felder automatisch aus. Aber man muss manuell auf enter (auf der Tastatur) oder ok am Display drücken, dass er es übernimmt.
Das ist leider ziemlich nervig.

Anbei ein Screenshot.

![IMG_3813](https://github.com/grocy/grocy/assets/77728707/cd02024a-4726-40d8-94db-484830b06640)

**Comment by berrnd** [comment]
"Manchmal geht irgendwas nicht" - liebe es.

Provide a reproducible example (I've invented [persistent demo instances](https://www.reddit.com/r/grocy/comments/jwnk9b) exactly for that purpose), otherwise I can't and also don't want to help. That's even mentioned on the issue template, please don't ignore and bypass what's written there. What's your expectation what I should do exactly by providing that few information?
