### ISSUE TITLE
Feature Request: User groups for chores

### ISSUE THREAD

**Issue by GlenNicholls** [grocy/grocy#2518]
It'd be helpful for chores to be assigned to users within specific groups. For example, I have lots of maintenance tasks that only apply to me. In other cases, certain chores are just for the kids. Chores aren't always split evenly and adding groups seems like a useful feature.

In essence, when making new chores or modifying existing ones, I'd like to see a `groups` category where zero or more groups can be added to the chore config. When no group is selected, all users are available for the next assignment. However, if one or more groups are specified, then new assignment will only select from users in those groups.

**Comment by GlenNicholls** [comment]
> Duplicate of #1415 (and #2095, and #2375). Probably also related to #1935.
> 
> Once again and the last time: Search existing requests before opening new ones!

I saw those and disagree about this being a duplicate. 

Those describe assigning a chore to multiple people. This request is for assigning a chore to a single person in selected groups. User groups seem intuitive since the members of a group would be maintained in a single place instead of editing multiple chores when adding/removing a user from a chore. 

IMO, user groups seem like a reasonable parent issue for the linked issues. With groups, enabling multiple assignments could be a checkbox like `assign to all in groups` or something.

**Comment by berrnd** [comment]
> Those describe assigning a chore to multiple people. This request is for assigning a chore to a single person in selected groups.

Then read again through the mentioned duplicates. Just because the word "group" is not mentioned there doesn't change anything that multiple users are simply groups. If you really think you can add something useful not yet mentioned, then simply do it there (preferably in short concrete words, most of the time the whole life story behind only creates noise). I don't get what multiple requests about the same topic should be good for.

However, nobody has done just a little thing since three years on that topic, I doubt this will change in the upcoming 3 years that much and recommend start working on it right tonight yourself, if it's a super duper important thing for you.

And in any case, we don't need to discuss any single feature request endlessly. I've noted you want user group assignment for chores. Already tracked in the mentioned duplicates. Thanks for the idea. So we're done here.
