### ISSUE TITLE
Bug: Shelf Life is calculated incorrectly if items are already purchased expired

### ISSUE THREAD

**Issue by w00h** [grocy/grocy#2520]
When purchasing items that are already over the best before date, the average shelf life gets calculated incorrectly.
If the best before date is in the past in relation to the purchase date, the time **span** between those two dates gets put in.

For testing, I created a new item (so no data already present) and purchased one unit that expired a year ago. Then the "average shelf life" gets populated with the corresponding time span, in this case "one year".

I would expect grocy to calculate the shelf life in my pantry always going forward from the purchase date to the expiry date, so I'd expect "0 days" here.

**Comment by berrnd** [comment]
The definition can be found here (there is never a need to guess how something is done/defined, since this is Open Source):

https://github.com/grocy/grocy/blob/af1f2aef961179f7f8d9f6d072727d3d057da239/migrations/0194.sql#L23-L31

It's fine that you expect that detail to behave differently. This works as defined, so not a bug.

**Comment by berrnd** [comment]
> so I'd expect "0 days" here

And what's even the mathematical rule behind this expectation? I would more expect a negative shelf life then...

Put the math behind your expectation into a proper Feature Request and I'll maybe think about improving that. I'm allergic to when each and every single detail not fitting personally you on a first sight is reported as a Bug instead of an enhancement request.
