### ISSUE TITLE
Bug: Javascript error when adding/editing an item in the shopping list

### ISSUE THREAD

**Issue by Sanji78** [grocy/grocy#2521]
Shopping list page, click on edit or add new item, click on the dropdown list of products, the dropdown becomes red and there is a javascript error:

popper.js:1211 Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at Object.onLoad (popper.js:1211:10)
    at popper.js:2521:25
    at Array.forEach (<anonymous>)
    at new t (popper.js:2519:20)
    at e.show (dropdown.js:167:22)
    at e.toggle (dropdown.js:120:10)
    at HTMLSpanElement.<anonymous> (dropdown.js:356:14)
    at Function.each (jquery.min.js?v=4.2.0:2:3129)
    at ce.fn.init.each (jquery.min.js?v=4.2.0:2:1594)
    at t._jQueryInterface [as dropdown] (dropdown.js:342:17)

**Comment by berrnd** [comment]
Not reproducible:

https://github.com/grocy/grocy/assets/2161815/9b325fd1-8f23-4c1c-a8cc-1aa53288c164

Please provide a 100 % reproducible example, so each and every step required to get a problem, if you want something to be looked into and fixed - I'm not a magician, so unable to guess all the details around.

And if it's only a theoretical problem, so only something you see in the JS console and it doesn't break anything practically, please don't report it here, I don't care about theoretical problems.

**Comment by berrnd** [comment]
Maybe also just the same as #1509 - which leads to: Please check existing requests before opening new ones (also mentioned on the issue template).

**Comment by Sanji78** [comment]
Please click on the dropdown list of the product while editing it (you didn't show this in the video). It's not a theoretical problem, because you lose the item selected in the dropdown.

For me it's happening 100% of the time...

**Comment by berrnd** [comment]
> click on the dropdown list of the product while editing it

Would be cool mentioning exactly this at first.

&nbsp;
> because you lose the item selected in the dropdown

Unrelated to the mentioned JS "error" and unrelated to shopping list item edit form, it's the same dropdown component ([bootstrap-combobox](https://github.com/danielfarrell/bootstrap-combobox)) used throughout Grocy. When you click/open the dropdown you essentially say "I want to select something else", so clearing the current item is expected behavior (and again: completely unrelated to the here mentioned JS error).

Not going to waste more time on that, we're done here.
