### ISSUE TITLE
Feature Request: Deactivate some functions for clarity

### ISSUE THREAD

**Issue by Tignass** [grocy/grocy#2527]
### Describe what you would find useful as detailed as possible:
I just discovered this great tool to manage my (small) community stock, thank you <3

Unfortunately, I'm not using most of the functionality (barcodes, price, tasks, due dates, energy, batteries, equipment...).
These functionalities seems to be useful for big organizations but are not for my small one (this is too much "work" for a small benefit).

I would love an option to deactivate (hide) such functionalities in order to trim out unnecessary options/functions and clear the screen.

I'm thinking something in the settings listing all the functionalities and allowing the possibility to "hide" each of them (in all of Grocy screens).

Thank you
And thank you for your great work <3

**Comment by berrnd** [comment]
> These functionalities seems to be useful for big organizations

Grocy's target audience is, and will always be, not an organization of any size, but your home and fridge.

&nbsp;
> I would love an option to deactivate (hide) such functionalities

If would find that cool too and that's why this is possible since ever:
- [README ref](https://github.com/grocy/grocy#disable-certain-features)
- [`data/config.php` ref](https://github.com/grocy/grocy/blob/efae5fea5b9e8497169ce5320047378eb0cafdc6/config-dist.php#L128-L155)

This has been asked just like thousand times here and on the [r/grocy subreddit](https://www.reddit.com/r/grocy), would be super duper kind of you if you can do just a little tiny search beforehand.
