### ISSUE TITLE
Bug: Userentity row invisible (wrongly assigned `d-none`)

### ISSUE THREAD

**Issue by QazCetelic** [grocy/grocy#2528]
I was testing out the userentity feature and noticed that none of the added entries are visisble. I looked at the HTML and it turned out that the user entity table body has the `d-none` (aka display none / hide) class. [It seems to be hardcoded into the Blade template 5 years ago](https://github.com/grocy/grocy/blame/2047d38c6e5e4e3ceb4576c9cf551084d5670763/views/userentities.blade.php#L81), I assume the tag is supposed to be removed somewhere else. 

HTML
![image](https://github.com/grocy/grocy/assets/51381523/2e092ce8-e143-44db-86ba-8b80dfff5485)

Nothing visible
![image](https://github.com/grocy/grocy/assets/51381523/6c62791d-d6ce-44ab-b87c-34bb11c84690)

Buttons visible when class is removed
![image](https://github.com/grocy/grocy/assets/51381523/21c6e643-73a3-46be-bd03-334372c4a19c)

Fields
![image](https://github.com/grocy/grocy/assets/51381523/636cbc2a-e424-4e58-bb33-e615b24b7d77)

**Comment by QazCetelic** [comment]
The class is indeed supposed to be removed [here](https://github.com/grocy/grocy/blame/2047d38c6e5e4e3ceb4576c9cf551084d5670763/public/viewjs/userentities.js#L8).

**Comment by berrnd** [comment]
> I looked at the HTML and it turned out that the user entity table body has the `d-none` (aka display none / hide) tag. [It seems to be hardcoded into the Blade template 5 years ago](https://github.com/grocy/grocy/blame/2047d38c6e5e4e3ceb4576c9cf551084d5670763/views/userentities.blade.php#L81), I assume the tag is supposed to be removed somewhere else.

> The class is indeed supposed to be removed [here](https://github.com/grocy/grocy/blame/2047d38c6e5e4e3ceb4576c9cf551084d5670763/public/viewjs/userentities.js#L8).

Bullshit. If you look at a web application like Grocy, the server side rendered HTML markup is one thing, all the client side JavaScript the other thing. So adding `d-none` here doesn't lead to an invisible table when just a handful of milliseconds later the exact same tag is removed ([code ref](https://github.com/grocy/grocy/blob/2047d38c6e5e4e3ceb4576c9cf551084d5670763/public/viewjs/userobjects.js#L8), it's about [DataTables](https://datatables.net) initial rendering performance optimization - a invisible [DOM sourced table](https://datatables.net/examples/data_sources/dom) renders faster - and happens exactly like so for each and every table throughout Grocy).

The issue template explicitly mentions to test stuff on the pre-release demo beforehand - it works there: https://demo-prerelease.grocy.info/userobjects/exampleuserentity

Otherwise please provide a 100 % reproducible example (also mentioned at the same issue template), something that does only not work on your end is just like always not a bug.

&nbsp;
> This part of the code also hasn't been changed in 5 years.

Well, I guess there are other couple of thousands lines that haven't changed either in the same amount of time - what should that mean exactly and how is it relevant for anything how often a single line of code changes?

**Comment by QazCetelic** [comment]
@berrnd Why has this issue been marked as invalid?

**Comment by QazCetelic** [comment]
> Bullshit. If you look at a web application like Grocy, the server side rendered HTML markup is one thing, all the client side JavaScript the other thing. So adding d-none here doesn't lead to an invisible table when just a handful of milliseconds later the exact same tag is removed ([code ref](https://github.com/grocy/grocy/blob/2047d38c6e5e4e3ceb4576c9cf551084d5670763/public/viewjs/userobjects.js#L8), it's about [DataTables](https://datatables.net/) initial rendering performance optimization - a invisible [DOM sourced table](https://datatables.net/examples/data_sources/dom) renders faster - and happens exactly like so for each and every table throughout Grocy).

I'm aware that the prerenderd HTML is supposed to be changed by the client JavaScript on the line I also linked to, but it isn't.

Here's a reproduced example on the public Demo server.
Link: https://test-g4r0azghrcbs4zjhijsl.demo-prerelease.grocy.info/userobjects/test
![image](https://github.com/grocy/grocy/assets/51381523/7ab69d86-3a3d-441c-ba05-c05d3768ecb0)

> Well, I guess there are other couple of thousands lines that haven't changed either in the same amount of time - what should that mean exactly and how is it relevant for anything how often a single line of code changes?

Just checking if there was a recent change that could cause a regression.

**Comment by berrnd** [comment]
> Here's a reproduced example on the public Demo server.
> Link: https://test-g4r0azghrcbs4zjhijsl.demo-prerelease.grocy.info/userobjects/test

All your defined Userentity fields (=> https://test-g4r0azghrcbs4zjhijsl.demo-prerelease.grocy.info/userfields?entity=userentity-test) don't have the option `Show as column in tables` checked. Without that much surprise, no single field defined by you to be shown in a table = no field shown in a table. When properly defining that, everything works as you expect it - and I already did that on your provided persistent demo instance. By a bit more extensive comparison with the default demo, it's pretty easy to find such things out yourself.

[According to README](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests) the better place for general usage questions is the [r/grocy subreddit](https://www.reddit.com/r/grocy) - please use that place if you're unsure how stuff is supposed to work instead of digging into random HTML, seeing bugs were no one is.

**Comment by QazCetelic** [comment]
That explains a lot, I seem to have missed the option completely. Thanks for taking your time to explain. I will make sure to go to the subreddit instead next time.
