### ISSUE TITLE
Feature Request: Quick Action to add to Shopping List

### ISSUE THREAD

**Issue by jalil-salame** [grocy/grocy#2546]
I like to go through the `/products` (`Manage master data > Products`) when I am looking for things to add to the shopping list. I would like for there to be an `add to shopping list` button in the web and app interface.

I could try to implement it but I don't have much experience with PHP/JS.

**Comment by berrnd** [comment]
> I like to go through the `/products` (`Manage master data > Products`)

That page is about master data management (hence the name), so technically it's pretty much the wrong place for any stock / shopping list management stuff there. When that page is your primary source for managing what you want to have at home, maybe you don't need Grocy and rather a simple product / shopping list tool instead.

When each and every deepest detail of everyone will be implemented built-in, we'll end up with either a very cluttered UI, or a very cluttered settings page to configure all that details rather quickly. Due to that, [custom JS/CSS](https://github.com/grocy/grocy?tab=readme-ov-file#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) was invented.

Here is a simple snippet (for `data/custom_js.html`) which makes what you probably want reality right now:
```
<script>
if (Grocy.View == "products")
{
	$(".product-delete-button").each(function()
	{
		$("<a href='" + U("/shoppinglistitem/new?embedded&updateexistingproduct&product=") + $(this).attr("data-product-id") + "' \
		class='btn btn-primary btn-sm ml-1 show-as-dialog-link'> \
		<i class='fa-solid fa-fw fa-shopping-cart'></i> \
	</a>").insertAfter($(this));
	});
}
</script>
```

Will look like that:

https://github.com/grocy/grocy/assets/2161815/9112c146-9d26-4e6c-9fe4-2792ebf06986

&nbsp;
> and app interface

This here is Grocy, it only has a web frontend.

**Comment by jalil-salame** [comment]
Thanks for the quick reply and the example code c:

**Comment by marcosaranda** [comment]
thanks, it's perfect for me, great job!
