### ISSUE TITLE
Bug: Product overview is available - Product details are empty 

### ISSUE THREAD

**Issue by grzbrum** [grocy/grocy#2549]
I have the bug that nothing is found in the product details for each item. They are there in the product overview.
![bild1](https://github.com/grocy/grocy/assets/112961981/7b71b7c4-514e-4b3f-98f6-6eb3860246d7)
![bild2](https://github.com/grocy/grocy/assets/112961981/902a5ce1-2095-4c2e-ab2e-f22dcf0432dd)
![bild3](https://github.com/grocy/grocy/assets/112961981/03e13bea-ef2f-4a73-a8c9-68261fabfd04)

**Comment by berrnd** [comment]
I'm unable to look behind screenshots (are you?), you essentially haven't provided any details, provide a fully reproducible example and I'll maybe take some time and have a look (and all that was also mentioned on the issue template, don't know what's the point of skipping all that).

However, based on the few information available on the provided screenshots I took the time and created a private demo instance for you: https://test-bri7pvlutklwyyfimr5tep.demo-prerelease.grocy.info

- When [opening and filtering /stockentries for "Toilettenpapier"](https://test-bri7pvlutklwyyfimr5tep.demo-prerelease.grocy.info/stockentries?product=1) it shows nothing, due to that this product itself isn't in-stock currently
- When [opening and filtering /stockentries for "Toilettenpapier 3-lagig, 20 Rollen x 200 Blat"](https://test-bri7pvlutklwyyfimr5tep.demo-prerelease.grocy.info/stockentries?product=2) it shows the corresponding currently in-stock item

Both is expected and I can't see anything which doesn't work here.

**Comment by grzbrum** [comment]
OK, thank you.
Since it doesn't work for me and nothing is displayed for every entry in "Stock entry", it must be a database error. Can this be repaired?

**Comment by berrnd** [comment]
> it must be a database error

Don't know how you came to that conclusion and also don't really know what a "database error" should be.

&nbsp;
> Can this be repaired?

Unless having this reproducible and being a magician being able to guess all the detail, I can't tell a single useful word about anything on that all.

**Comment by grzbrum** [comment]
I cannot reproduce it. As the problem is present with every product. Since the detail query always returns an empty result, I assume that there is a problem in the database.

Can I get the SQL code that is used to query the stock entry? Then I could go troubleshooting myself.

Specifically, it is this link to which I would need the SQL:
"grocy/public/index.php/stockentries?embedded&product=1308"
No matter which product ID I use, there are always no entries available.


Otherwise, thanks for the help

**Comment by berrnd** [comment]
> Can I get the SQL code that is used to query the stock entry?

You can get each and everything going on behind the scenes, this is Open Source, every single bit is publicly available right here.

&nbsp;
> Specifically, it is this link to which I would need the SQL:
"grocy/public/index.php/stockentries?embedded&product=1308"

It's essentially `SELECT * FROM uihelper_stock_entries WHERE product_id = 1308` or here is the full trace of SQL commands issued while viewing the mentioned page:

```sql
SELECT * FROM `users` ORDER BY `id` ASC LIMIT 1 #### 
SELECT * FROM `user_settings` WHERE (user_id = :1 AND key = :2) #### 1;locale
SELECT * FROM `user_settings` WHERE (user_id = :1) #### 1
SELECT * FROM stock_current_locations
SELECT * FROM `userentities` ORDER BY `name` COLLATE NOCASE #### 
SELECT * FROM `userfields` WHERE (`entity` = 'products') ORDER BY `sort_number` ASC, `name` COLLATE NOCASE #### 
SELECT * FROM `userentities` ORDER BY `name` COLLATE NOCASE #### 
SELECT * FROM `userentities` ORDER BY `name` COLLATE NOCASE #### 
SELECT * FROM `userfields` WHERE (`entity` = 'products') ORDER BY `sort_number` ASC, `name` COLLATE NOCASE #### 
SELECT * FROM `userfield_values_resolved` WHERE (`entity` = 'products') ORDER BY `name` COLLATE NOCASE #### 
SELECT * FROM `userentities` ORDER BY `name` COLLATE NOCASE #### 
SELECT * FROM `userfields` WHERE (`entity` = 'stock') ORDER BY `sort_number` ASC, `name` COLLATE NOCASE #### 
SELECT * FROM `userentities` ORDER BY `name` COLLATE NOCASE #### 
SELECT * FROM `userentities` ORDER BY `name` COLLATE NOCASE #### 
SELECT * FROM `userfields` WHERE (`entity` = 'stock') ORDER BY `sort_number` ASC, `name` COLLATE NOCASE #### 
SELECT * FROM `userfield_values_resolved` WHERE (`entity` = 'stock') ORDER BY `name` COLLATE NOCASE #### 
SELECT * FROM `user_settings` WHERE (user_id = :1) #### 1
SELECT * FROM `quantity_units` WHERE (active = 1) #### 
SELECT * FROM `user_settings` WHERE (user_id = :1 AND key = :2) #### 1;stock_decimal_places_amounts
SELECT * FROM `products` WHERE (active = 1) ORDER BY `name` COLLATE NOCASE #### 
SELECT * FROM `locations` WHERE (active = 1) ORDER BY `name` COLLATE NOCASE #### 
SELECT * FROM `uihelper_stock_entries` ORDER BY `product_id` ASC #### 
SELECT * FROM `quantity_units` WHERE (active = 1) ORDER BY `name` COLLATE NOCASE #### 
SELECT * FROM `shopping_locations` WHERE (active = 1) ORDER BY `name` COLLATE NOCASE #### 
SELECT * FROM `uihelper_user_permissions` WHERE (`user_id` = '1') #### 
SELECT * FROM `users` ORDER BY `id` ASC LIMIT 1 #### 
SELECT * FROM `user_settings` WHERE (user_id = :1 AND key = :2) #### 1;locale
SELECT * FROM `quantity_units` WHERE (active = 1) #### 
SELECT * FROM `users` ORDER BY `id` ASC LIMIT 1 #### 
SELECT * FROM `user_settings` WHERE (user_id = :1 AND key = :2) #### 1;locale
```

**Comment by Schlemmen** [comment]
Hello you two,

I encountered the same issue before. In my case, the stock entries for every product were also empty. I hadn't changed any settings up to the point when the problem occurred, so I initially thought it might be a database issue as well.

However, the solution turned out to be simpler:
When you have the stock entries open for a product, click on the eye icon (table options) and then click the reset button.
This action restored the stock entries for all products in my case.

Best regards from Ulm
