### ISSUE TITLE
Bug: default permissions are incorrectly enforced

### ISSUE THREAD

**Issue by qay21** [grocy/grocy#2556]
On a brand new Grocy install (using LinuxServer docker image), with the following config :

```
Setting('AUTH_CLASS', 'Grocy\Middleware\LdapAuthMiddleware');

[...]

Setting('DEFAULT_PERMISSIONS', ['CALENDAR','CHORES','CHORE_TRACK_EXECUTION','CHORE_UNDO_EXECUTION','EQUIPMENT','SHOPPINGLIST','SHOPPINGLIST_ITEMS_ADD','SHOPPINGLIST_ITEMS_DELETE','USERS_EDIT_SELF']);
```

A user authenticating against LDAP for the first time will be created with incorrect permissions by default. The permission list for this user in the web UI is not consistent.

What the newly created user can see :

![image](https://github.com/user-attachments/assets/c556990f-fe77-4818-a97b-a2376e5d69cf)

What the permission list for this user looks like for the admin :

![image](https://github.com/user-attachments/assets/fd67ee3a-f0b9-4f46-9f8d-f4623594f8a2)

As you can see, the actual permissions of the user are not matching either the config.php list or the webui-visible list.

**Comment by berrnd** [comment]
I just gave it a try by what you described above, not reproducible, works.

This is the place where the `DEFAULT_PERMISSIONS` are set (when creating a user):

https://github.com/grocy/grocy/blob/5a2600209f38df1ae78f7689c9e0f45a7e82fea0/services/UsersService.php#L21-L29

The aforementioned `CreateUser` function is exactly the same used across any shipped authentication middleware, so it even can't be `LdapAuthMiddleware` specific - code references:

https://github.com/grocy/grocy/blob/5a2600209f38df1ae78f7689c9e0f45a7e82fea0/middleware/LdapAuthMiddleware.php#L82

https://github.com/grocy/grocy/blob/5a2600209f38df1ae78f7689c9e0f45a7e82fea0/middleware/ReverseProxyAuthMiddleware.php#L54

https://github.com/grocy/grocy/blob/5a2600209f38df1ae78f7689c9e0f45a7e82fea0/controllers/UsersApiController.php#L46

A LDAP user is created in Grocy on the first (successful) login when it doesn't already exist. So you're `DEFAULT_PERMISSIONS` setting needs to be set accordingly at that time, I can only guess this wasn't the case. Or if you just changed `config.php` and maybe use OPcache or something similar, triple make sure to reload or restart your PHP process manager - `config.php` is a regular PHP file, so depending on one's configuration changes are not immediately available due to the file being cached.

**Comment by berrnd** [comment]
You've made the following edit to your initial post above:

```diff
- Setting('DEFAULT_PERMISSIONS', ['CALENDAR,CHORES,CHORE_TRACK_EXECUTION,CHORE_UNDO_EXECUTION,EQUIPMENT,SHOPPINGLIST,SHOPPINGLIST_ITEMS_ADD,SHOPPINGLIST_ITEMS_DELETE,USERS_EDIT_SELF']);

+ Setting('DEFAULT_PERMISSIONS', ['CALENDAR','CHORES','CHORE_TRACK_EXECUTION','CHORE_UNDO_EXECUTION','EQUIPMENT','SHOPPINGLIST','SHOPPINGLIST_ITEMS_ADD','SHOPPINGLIST_ITEMS_DELETE','USERS_EDIT_SELF']);
```

If that wasn't just a pretty fancy copy/paste error and you really had the removed variant as your `DEFAULT_PERMISSIONS` setting at time of testing this, of course this would be the (very obvious) problem.

**Comment by qay21** [comment]
Thanks for this quick answer. The old version (before my edit) is due to me badly reformating my originally multiline config file in a single line  with a bad regex for the purpose of opening this issue. The quoted version is what I was using when I encountered this event.

If it cannot be ldap-specific, then I will give this a few more try tomorrow and hopefully provide more accurate/reproducible feedback.

I'll keep you posted. Thanks again !

**Comment by qay21** [comment]
Ok so I was able to obtain a bit more precise usecase this morning : I was able to reproduce what I observed yesterday, but I now understand it better.

When a newly created user logs in for the first time, they properly retrieve permissions and such permissions are properly displayed in the webui for admins. I don't know how I messed it up yesterday, but nevermind. However, permissions does not seem to "disable" all buttons and menus.

Eg, this is my current default permissions :
```
Setting('DEFAULT_PERMISSIONS', ['CALENDAR','CHORE_TRACK_EXECUTION','CHORE_UNDO_EXECUTION','EQUIPMENT','SHOPPINGLIST_ITEMS_ADD','SHOPPINGLIST_ITEMS_DELETE','USERS_EDIT_SELF']);
```

This is what my admin account can see for a newly created user, as expected
![image](https://github.com/user-attachments/assets/d5a9b795-dadb-41b0-a639-62fc1c17e9ee)

However, this is the menu the new user can see upon logging in :
![image](https://github.com/user-attachments/assets/f87b27d5-9306-4e49-9d11-eb61f0b539ef)

As you can see, there is a few menu items that are grayed out, but some of them are not despite the user not being permitted to use these functions. For example, the master data editing menu is available.

This initially led me to think permissions were not properly enforced. However, I did a bit more testing today and noticed this : the new user can access the master data editing section, and can try to edit data (here is an example for trying to add a location), but upon saving, a red error box will be displayed with the following message :
`Error while saving, probably this item already exists`

The same behavior is observed with other unpermitted (but not grayed-out) features, such as the Task menu.

Clicking on the box to display details outputs this error :
![image](https://github.com/user-attachments/assets/da6ea8bd-0bd3-413f-a0ce-16923f2f661c)

In the end, permissions are indeed properly enforced, which is good. This issue is after all a user experience related problem.

Are you able to reproduce these steps ? If yes, should I open a new, properly named issue for this ?

**Comment by berrnd** [comment]
So first turns out that the initially reported problem was totally wrong and I spent once again about an hour of looking into this for nothing, I love wasting time here more and more. Please be so kind and test stuff at least twice before reporting something as a Bug. I review each and every Bug report thoroughly, but since the vast majority of those reports are simply wrong lately, I'm maybe going to simply ignore all of them in the near future.

&nbsp;
> In the end, permissions are indeed properly enforced, which is good.

So concludes no: No problem anywhere at all. And at least partially a duplicate of #1505.

What menu items and other elements to hide or disable based on permissions is at the end personal preference. Also remember that Grocy is about your home, not your highly sensitive enterprise environment with potentially monkey users.

&nbsp;
> the new user can access the master data editing section, and can try to edit data (here is an example for trying to add a location), but upon saving, a red error box will be displayed with the following message

Let me guess the next Bug report when changing to not access the master data section: "I want to be able to see all product properties, even when I don't have the permission to edit them". Again: Desired use case = your home / family. So is this really a problem for your kids or grandmother? If so, then here is a [custom JS](https://github.com/grocy/grocy?tab=readme-ov-file#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) snippet (for `data/custom_js.html`) to eliminate this problem right now, essentially making your home more secure than ever:

```html
<script>
if (
	Grocy.UserPermissions
	&& Grocy.UserPermissions.filter(x => x.user_id == Grocy.UserId
		&& x.permission_name == "MASTER_DATA_EDIT"
		&& x.has_permission == 0).length > 0
)
{
	$("#sub-nav-manage-master-data").addClass("not-allowed");
	$('a[href$="#sub-nav-manage-master-data"]').addClass("not-allowed");
}
</script>
```

**Comment by qay21** [comment]
Thanks again for your answer ;

I'm sorry for not meeting your standards of quality for reporting bugs, especially my seemingly disproportionate focus for what end up being a purely user-experience related subject. I will try and do better if I stumble upon a new problem later on.

Have a nice day
