### ISSUE TITLE
Feature Request: possibility of using api to pull recipes and other data from mealie installation

### ISSUE THREAD

**Issue by CptHowdy2012** [grocy/grocy#2565]
2 way communication with mealie installation using API for recipes, meal planning, and shopping lists would be an awesome integration, possibly a child feature under a plugin system.

**Comment by berrnd** [comment]
An integration for a specific app/tool/service/whatever will never be included in Grocy - if, then always using a generic approach.

The API can do everything the web frontend can do, since that frontend uses exactly that same API. So a very easy practical approach to find out how API stuff works is to simply do the corresponding action on the frontend, while having a look at the behind the scenes magic via your favorite Browser's developer tools.

If you have specific questions on API usage, feel free to ask at the appropriate place ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests)).
