### ISSUE TITLE
Feature Request: Price (Over)View

- View Prices of Products
- View Price History when clicking on Product

### ISSUE THREAD

**Issue by tilltmk** [grocy/grocy#2567]

**Comment by berrnd** [comment]
A little more explanation about what you want to have where exactly wouldn't hurt.

Anyways, the product card is accessible by clicking a product name throughout Grocy which already includes the price history chart, the stock report "Spendings" is just another place to lookup past purchase prices.

Since even screenshots say so much more than a headline only, I took of course also that time to provide that for you:

https://github.com/user-attachments/assets/02efd4a7-6a5c-4f99-b2cd-1ca4fc05f0f4

Additionally, you can even add the last or average price to the stock overview table directly if that's what you'd find useful:

https://github.com/user-attachments/assets/948a4dc8-002a-41c0-813d-19143bff9161

If that all not covers what you think of, please explain a little more what's missing or simply use the [more appropriate place](https://www.reddit.com/r/grocy) ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests)) for further general usage questions.

**Comment by tilltmk** [comment]
danke dir
