### ISSUE TITLE
Feature Request: Remove whitespace at the end of product name

### ISSUE THREAD

**Issue by felixschurk** [grocy/grocy#2568]
I noticed that when added new products over the android app they are saved with some whitespace at the end e.g. `Banana` would be saved as `Banana `.

This it not really "bad" however, its also not really needed.
It would be nice, if one could run a command over all entries and remove a whitespace at the end of the entry.

Maybe one could just run it against the database manually?

**Comment by felixschurk** [comment]
Manually running following command against the DB results in the wanted outcome.
```sql
UPDATE products
SET name = trim(name);
```

**Comment by berrnd** [comment]
> I noticed that when added new products over the android app they are saved with some whitespace at the end e.g. `Banana` would be saved as `Banana `.

If they (or any API user/consumer) really do that (personally kind of doubt that for Grocy Android, but why report this then here and not there?), that's pretty much bullshit and it should be of course fixed there, not here.

&nbsp;

> Maybe one could just run it against the database manually?

Of course, you can do with your Grocy database whatever you want.

**Comment by felixschurk** [comment]
I mainly added it here, because I thought of maybe a general database cleanup command somewhere in the settings. Which could maybe also be run over any possible identifiers.

More specifically the whitespace is not added by the Grocy Android App, it is more added as phone keyboards sometimes add a whitespace automatically after a word if not terminated with a point or so.

But it's more aesthetics than proper a proper bug nor problem.

**Comment by berrnd** [comment]
> But it's more aesthetics than proper a proper bug nor problem.

Agreed. Grocy general cares about the practically useful stuff, solving / helping with real world problems - all that only being a theoretical problem or something related to having a aesthetics fetish of whatever kind is nothing which will ever be added here.

Remembering the one who reported that ids in the table `recipes_pos` (shopping list items) are not re-used and the number/id visible on such a shopping list item route / URL contains pretty high numbers after a while and he doesn't like that for whatever unintelligible reasons. Never thought that this turns out to be a self-help group for the very important stuff in life, oh man.
