### ISSUE TITLE
Feature Request: Allow more than one upload per equipment item

### ISSUE THREAD

**Issue by mokkin** [grocy/grocy#2576]
Sometime it necessary to attach more than one document to an equipment item such as manual, quick start guide, warranty certificate or data sheet.
Also the invoice could be saved on the item for warranty purposes.

**Comment by berrnd** [comment]
Already possible since years by utilizing Userfields.

Please be so kind and do a quick and easy search before opening new requests, I don't have the time to be your personal search engine (sorry) - just a few references:

https://github.com/grocy/grocy/issues/441

https://github.com/grocy/grocy/issues/2376

https://github.com/grocy/grocy/issues/978
