### ISSUE TITLE
Feature Request: Preset amount of stock entry when using grocycodes

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#2584]
I often use generic products for vinegar, oil and similar liquids and the unit ml due to different container sizes.
I also use grocycodes to always use the correct stock entry. I have now noticed that the quantity in the consume and transfer dialog is preset to 1 ml when using grocycodes.

I would like to aks if its possible to set the quantity of the scanned stock entry as preset when using grocycodes in the consume and transfer dialogs.

**Comment by berrnd** [comment]
Works exactly like so since more than 2 years / v3.2.0 ([code ref](https://github.com/grocy/grocy/commit/4279bf6445fbba25b16abc832d63c882ed83900f), [original Feature Request ref](https://github.com/grocy/grocy/issues/1736)).

[Changelog](https://grocy.info/changelog#v3.2.0) excerpt:
> When using/scanning a stock entry Grocycode on the consume page, the amount is now prefilled by the stock entry amount (making it essentially possible to consume the corresponding stock entry in one go)

Demonstration using the current development release to verify it's still working (spoiler: it does):

https://github.com/user-attachments/assets/3a246b82-a605-4eac-a6fb-4ee4f0c64ad4

**Comment by Saturo78** [comment]
Hi Bernd, 
thanks for your answer!

I don't know what I did wrong. But after some testing, it now works for me too.
In the beginning, the cursor jumped into the quantity field and the field was empty.

 I would be interested to know how you manage to copy the grocycode to the clipboard. :)

**Comment by berrnd** [comment]
> I would be interested to know how you manage to copy the grocycode to the clipboard. :)

By typing it in, then Ctrl+C - casually copying text. The [format of Grocycodes](https://github.com/grocy/grocy/blob/master/docs/grocycode.md) is not a secret.
