### ISSUE TITLE
Feature Request: Update ingredient checkbox verbiage for "Only check if any amount is in stock"

### ISSUE THREAD

**Issue by UltiFix** [grocy/grocy#2585]
I found it not intuitive how to DISABLE consumption for 1 ingredient on recipe list.

After searching I found this large prior issue which includes this topic.
https://github.com/grocy/grocy/issues/548

After reading that issue then played around more and understood this check box to do what I want.
![image](https://github.com/user-attachments/assets/3d7534f6-71b6-4328-93d1-7ec089ecc938)

But, from that checkbox and the accompanying text is NOT clear to me this checkbox disables consumption.

I request the verbiage to be updated for the checkbox. Specifically change:
"Only check if any amount is in stock" to "Only check if any amount is in stock **(Disables consumption)**"

Luckily when you click
![image](https://github.com/user-attachments/assets/ce54788a-1998-4412-a2e9-d6416ce9bf81)
It does show you this window
![image](https://github.com/user-attachments/assets/a9b84aa7-f9f0-4602-9e75-3f8c76ec043e)
which in conjuction with prior linked issue help me understand to use checkbox. But if textbox text was more clear it would have been better.

Thank you so much for making grocy :)

**Comment by berrnd** [comment]
> which in conjuction with prior linked issue help me understand to use checkbox.

So concludes to: You haven't read the popup-text the first time and that's pretty much all. I can't help about reading stuff and there will be always some details one doesn't understand at a first sight, you can't make every short-text on this planet supa dupa crystal clear for each and everyone. Simply playing around with stuff (or googling, or asking) is the principal for Grocy.

Improving this topic in general is already tracked in #548, so closing as duplicate.

**Comment by UltiFix** [comment]
> > which in conjuction with prior linked issue help me understand to use checkbox.
> 
> So concludes to: You haven't read the popup-text the first time and that's pretty much all. I can't help about reading stuff and there will be always some details one doesn't understand at a first sight, you can't make every short-text on this planet supa dupa crystal clear for each and everyone. Simply playing around with stuff (or googling, or asking) is the principal for Grocy.
> 
> Improving this topic in general is already tracked in #548, so closing as duplicate.

yes it is fair i did not read the pop up text after click the recipe consume button.

But, imagine where user had never made recipe before. they are trying to make new recipe and mark certain ingredients as do not consume. that pop-up is not till AFTER you go and try to use the recipe

anyway, thank you for reply and grocy has been very nice to use.

if i make pull request changing text would you accept or no

thank you :)

**Comment by berrnd** [comment]
> imagine where user had never made recipe before.

Grocy has evolved over the years to a fair amount of complexity. So naturally just like with any kind of such software, either read the documention (Grocy has not really anything) or simply just try stuff before doing it in "production", IMHO pretty easy. And as said, there can be never a wording to make every single detail super crystal clear for personally you. What's crystal clear or not is at the end a very personal thing.

&nbsp;
> if i make pull request changing text would you accept or no

No, since we don't change every little detail back and forth to fit today you, tomorrow me and next week somebody else [... continue this endlessly...].

&nbsp;
Don't get me wrong, I do this here since multiple years, discussing such irrelevant details is something I'm pretty tired of. Yes, a pity you haven't got it right at a first sight, but maybe simply try stuff beforehand on a separate instance or something like that while exploring all the other in-depth details of Grocy, this is by far not the only / most complex one.
