### ISSUE TITLE
Feature Request: Universal QU Conversions 

### ISSUE THREAD

**Issue by HeckerSec** [grocy/grocy#2593]
**Current behavior: **
when setting up a product in the database, quality unit(QU) conversions have to be setup for each product individually

I.E. you might add a conversion rule that says 1 Box= 450gram

Or that 1 Kilogram=1000grams

**Proposed behaviour:**

If no conversion rule exists in the specific item, a master conversion rule table could be checked to see if a universal conversion rule exists

**Rationality**

Conversions between QU of the same type(I.E. mass, volume, length) will always be the same, 1kg will always be 1000g, and so defining that rule per product is a needlessly time consuming task.

**Comment by berrnd** [comment]
> quality unit(QU) conversions have to be setup for each product individually

Not true.

&nbsp;
> If no conversion rule exists in the specific item, a master conversion rule table could be checked to see if a universal conversion rule exists

Exactly that is possible since [v2.5.0](https://grocy.info/changelog#v2.5.0), so since about 5 years and in fact longer than product specific "conversion overrides" exist.

Quick refresher on Grocy QU conversion handling basics:
- Product specific conversions can be defined on the product edit page ([example](https://demo-prerelease.grocy.info/product/5), table headlined with "Product specific QU conversions") and override maybe same existing "global conversions"
- "Global conversions" can be defined on the quantity unit edit page ([example](https://demo-prerelease.grocy.info/quantityunit/13), table headlined with "Default conversions ")
- => Any to the product's QU stock directly or indirectly related unit can be used everywhere throughout Grocy for that product

&nbsp;
> 1kg will always be 1000g, and so defining that rule per product is a needlessly time consuming task.

Even the default demo data showcases exactly that: https://demo-prerelease.grocy.info/quantityunit/13

&nbsp;
The better place for general usage questions is the [r/grocy subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests).
