### ISSUE TITLE
Feature Request: Maßeinheiten für Standardmengen flexibler gestalten

### ISSUE THREAD

**Issue by HartwigHuebner** [grocy/grocy#2594]
Hallo Berrnd,
ich finde Grocy großartig. Habe mich zwar bis heute nicht disziplinieren können, jeden Einkauf und jeden Verbrauch / Umlagerung etc. zu erfassen, aber gelegentlich schaffe ich es.
Bin aktuell noch in der Produktanlagephase, so dass o.g. Prozesse etwas länger dauern als die Geduld meiner Mitmenschen erlaubt.

Es wäre schön, wenn die Maßeinheiten für
- Taragewicht
- Energie
- Schnell-Verbrauch Menge
- Schnell-Öffnen Menge
nicht ausschließlich mit der Bestandsmengeneinheit sondern auch mit anderen Einheiten angegeben werden können.
Falls man es nicht flexibel auswählen kann, dann könnte man die vorgegebenen Einheiten vielleicht anders angeben:
- Schnell-Verbrauch Menge --> Standardverbrauchsmengeneinheit
- Schnell-Öffnen Menge --> Standardseinkaufsmengeneinheit

Außerdem wäre es toll, wenn man bei den Benutzerfeldern eine Mehrfachauswahl von Entitäten-Datensätzen vornehmen könnte.

Vielen Dank für Dein großartiges Programm.

**Comment by berrnd** [comment]
_Wir sprechen hier Englisch, damit jeder auf diesem Planeten jeder Unterhaltung folgen kann, Grocy wird nicht nur (sogar zum weitaus kleineren Teil) in deiner und meiner Nachbarschaft benutzt._

&nbsp;
First: Please be so kind and check existing requests before opening new ones and please keep it to one topic per requests, simply since everything else is untrackable (and all that is also mentioned on the request template, don't get what's the point on ignoring what I wrote there).

&nbsp;
> Es wäre schön, wenn die Maßeinheiten für [...]

Duplicates related to product option quantity unit handling/relation: #2252, #2427

&nbsp;
>Falls man es nicht flexibel auswählen kann, dann könnte man die vorgegebenen Einheiten vielleicht anders angeben:
>Schnell-Verbrauch Menge --> Standardverbrauchsmengeneinheit
>Schnell-Öffnen Menge --> Standardseinkaufsmengeneinheit

Redefining something to fit your personal workflow potential means breaking the workflow of thousands of other Grocy users - this was and is never how stuff will be implement/changed in Grocy.

&nbsp;
> Außerdem wäre es toll, wenn man bei den Benutzerfeldern eine Mehrfachauswahl von Entitäten-Datensätzen vornehmen könnte.

There is already a Userfield type `Select list (multiple items can be selected)` which provides that. Maybe a duplicate of #335 if you refer to being able to reference existing other entity objects in a Userfield.

&nbsp;
>Habe mich zwar bis heute nicht disziplinieren können, jeden Einkauf und jeden Verbrauch / Umlagerung etc. zu erfassen, aber gelegentlich schaffe ich es.

I highly recommend to first get used to the current state of Grocy before trying to reinvent every little detail. Grocy exists since years, is a very open system (not forcing a specific way of working on anything) and works for thousands of people. Sounds also like your home works probably pretty well without a home ERP system if you don't feel the need to track purchases - not everybody on this planet needs one (in fact the vast majority does not). If tracking stuff only creates extra work without solving problems you maybe don't even have, why do the extra work for nothing.

&nbsp;
So nothing new not already covered by existing other requests, closing as duplicate.
