### ISSUE TITLE
Bug: Adding new location focus lost

### ISSUE THREAD

**Issue by ScooterisT5** [grocy/grocy#2598]
When adding a new location the focus on the name file got lost, so we have to re-activate the focus by clicking into the field again

**Comment by berrnd** [comment]
Please be so kind and provide a 100% reproducible example (mentioned on the issue template). You don't even mention about which place of Grocy's web frontend you're talking exactly. Locations are created on [/locations](https://demo-prerelease.grocy.info/locations) and there isn't a file input field, since locations don't have a picture or anything else requiring a file to be attached.

Please don't spam around, that's frustrating af.

**Comment by ScooterisT5** [comment]
Interesting reaction or way to improve a software product. Thanks - uninstalling...

**Comment by berrnd** [comment]
> uninstalling...

Based on your two lowest quality reports provided here: I'm glad you do that.
