### ISSUE TITLE
Bug: Scan mode submitting record before information is present

### ISSUE THREAD

**Issue by aperture1988** [grocy/grocy#2603]
Hello,

I am seeing an issue whereby when using scan mode to consume a product the changes are being submitted before other field information has been auto populated causing the the system to throw an error because mandatory information has not been supplied.

The information in question appears to be the "location" field which is being pulled in from the database.

Is it possible to manually set the delay between the time I scan a bar code and the system automatically saves changes?

I have tested this on a MacBook, MS tablet and a Windows desktop and I am seeing the same issue across all devices so assume this is a back end issue.

Thanks

**Comment by berrnd** [comment]
> assume this is a back end issue.

Wrong assumption, Scan Mode is entirely a frontend thing.

&nbsp;
> Is it possible to manually set the delay between the time I scan a bar code and the system automatically saves changes?

No and there is even no delay used anywhere. It's about events, the magic starts when the productpicker lost its focus, normally after you enter/scan a TAB or ENTER.

&nbsp;
In any case, please be so kind and provide a 100% reproducible example and provide all the details needed (the issue templates mentions all that and more) if you want me to invest more time into that, everything else is just frustrating.

Beside that I use Scan Mode pretty much daily on my personal instance without issues since years, I simply did a quick test on [the demo](https://demo-prerelease.grocy.info) for you and can't spot a problem there too:

https://github.com/user-attachments/assets/1848a782-d3bc-48eb-990e-9a0fe2741862

**Comment by berrnd** [comment]
> It happened today and I wanted to make a recording

As mentioned above: A screen recording isn't enough, I can't look behind screenshots (can you?). A 100% reproducible example is needed.

However, of course this particular thing is sensitive to timing. Data is loaded asynchronously and how fast this is, is practically dependent on client and server performance. I use Scan Mode kind of daily myself and never noticed that, so far it seems to be only noticed by 2 out of multiple ten thousand of users. Means, most likely not a general issue.

Every HID barcode scanner I had in my hands so far also had an option to add a delay before submitting ENTER. The most practical approach on this would be to simply utilize that.

This is Open Source, so you can also dig into every single bit yourself if that's an important detail for you.
