### ISSUE TITLE
Bug: Shopping list amounts appear to be in the wrong unit

### ISSUE THREAD

**Issue by BenBergman** [grocy/grocy#2607]
Calling `http://<grocy>/api/objects/shopping_list` returns the amount associated with the "Quantity unit stock" instead of the "Default quantity unit purchase" or the unit in the associated `qu_id` field.

I have tested this in a persistent private demo instance here: https://test-kgwyp03s06rv20ypf2he8e.demo-prerelease.grocy.info

After adding one pack of eggs to the shopping cart and calling `https://test-kgwyp03s06rv20ypf2he8e.demo-prerelease.grocy.info/api/objects/shopping_list` I get 

```
...
  {
    "id": 6,
    "product_id": 5,
    "note": null,
    "amount": 10,
    "row_created_timestamp": "2024-11-24 03:05:54",
    "shopping_list_id": 1,
    "done": 0,
    "qu_id": 3
  }
...
```

The amount is 10 *pieces* instead of 1 *pack*. The `amount` changes if I change the "Quantity unit stock" of the product. The `qu_id` does not change when I change any of the units on the product, so I assume `qu_id` is fixed with the unit used when adding to cart.

I would assume the `amount` should be in the units of "Default quantity unit purchase" and the `qu_id` should also be "Default quantity unit purchase".

I noticed this issue when using the Home Assistant integration and created an [issue there](https://github.com/custom-components/grocy/issues/315) first, but further investigation found that this seems to be a bug in Grocy itself.

**Comment by berrnd** [comment]
> Calling `http://<grocy>/api/objects/shopping_list` returns the amount associated with the "Quantity unit stock" instead of the "Default quantity unit purchase" or the unit in the associated `qu_id` field.

Where exactly is this stated? Every amount (and price) throughout the whole API always references the product's QU stock (since ever).

&nbsp;
> The `amount` changes if I change the "Quantity unit stock" of the product.

Sure, otherwise the amount would be "broken".

&nbsp;
> I would assume the `amount` should be in the units of "Default quantity unit purchase"

Personal preference. When doing that, amounts (and prices) throughout the API would be sometimes related to that unit and sometimes to another one - confusing. I decided to always reference amounts (and prices) to the same unit (the product's QU stock) consistently.

&nbsp;
> The `qu_id` does not change when I change any of the units on the product, so I assume `qu_id` is fixed with the unit used when adding to cart.

Have you once used Grocy's web frontend (which uses the exact same API for everything too)? Having a `qu_id` field but using a fixed one of the product wouldn't make a little sense. When adding a product to the shopping list, this defaults to the "Default quantity unit purchase" (mind the word default) of the corresponding product, however you can use any other related unit when you want.

&nbsp;
> I noticed this issue when using the Home Assistant integration and created an [issue there](https://github.com/custom-components/grocy/issues/315) first, but further investigation found that this seems to be a bug in Grocy itself.

Interesting investigations. Please don't report each and everything which is not crystal clear to you at a first sight as a bug and simply ask (or check how the web frontend does API stuff) beforehand.

**Comment by BenBergman** [comment]
> Have you once used Grocy's web frontend (which uses the exact same API for everything too)? Having a qu_id field but using a fixed one of the product wouldn't make a little sense. When adding a product to the shopping list, this defaults to the "Default quantity unit purchase" (mind the word default) of the corresponding product, however you can use any other related unit when you want.

I agree it would make little sense, but that seems to be what is happening (though it sounds like I misunderstood). I admit I didn't read through all the code for the frontend to figure out how it is determining the units, but lacking any documentation on the API beyond the API explorer (perhaps there is documentation I couldn't find), given the fields "amount" and "qu_id", I didn't think it was that much of a stretch to assume the amount was in the quantity unit referenced. So is the qu_id actually the unit used when added to the cart?

> Where exactly is this stated? Every amount (and price) throughout the whole API always references the product's QU stock (since ever).

Counterpoint - where exactly is it stated that the amount in the API is always in the stock unit? I would have assumed that too, except for the presence of the qu_id field. Obviously this was a misunderstanding on my part, but hopefully you can understand my confusion.

My end goal is to create a script that adds all my shopping list items to my grocer's online shopping cart. So does that mean the "correct" way (in my use case) to get the amount of a product in the "quantity unit purchase" is this?

1. get the product and amount from the shopping list
2. get the product and its "qu_id_stock" and "qu_id_purchase"
3. get the conversion factor from "qu_id_stock" to "qu_id_purchase"
4. multiply the amount by the conversion factor?

> Please don't report each and everything which is not crystal clear to you at a first sight as a bug and simply ask (or check how the web frontend does API stuff) beforehand.

Perhaps I should have opened a thread on the subreddit before this bug report - I'll note that for next time. From my perspective, something seemed broken as there was an apparent conflict and I didn't realize the frontend used the same API calls - I'm not a web developer. I assumed it was a niche API call on a niche piece of software that maybe didn't get used a lot. Thank you for the clarifications.

From the webpage:

>  So contributing to the project would be the thing which helps Grocy most. This doesn't have to be code - creating documentation...

The only docs I could find are the ones [here](https://github.com/grocy/grocy/tree/master/docs) and the API isn't mentioned at all. If I were to submit documentation for the API to help the next person who is confused by it, is this the best place to add it?

**Comment by berrnd** [comment]
> So is the qu_id actually the unit used when added to the cart?

Also that could be found out by simply trying it. The user adds a product with an amount and a unit to the shopping list. The amount in the database (= what you see through the API) is always related to the product's QU stock. The `qu_id` is simply that unit the user selected, regardless if it was set by a default or not. The frontend displays (so converts based on the corresponding conversion factor) the amount related to that selected unit.

&nbsp;
> where exactly is it stated that the amount in the API is always in the stock unit?

[Here](https://github.com/grocy/grocy/blob/11ea8f3716b84f23726338d442d4acfef67f7cef/grocy.openapi.json#L3062) and [there](https://github.com/grocy/grocy/blob/11ea8f3716b84f23726338d442d4acfef67f7cef/grocy.openapi.json#L3070) and on like a trillion places around here and the [r/grocy subreddit](https://www.reddit.com/r/grocy) when searching for anything API and amounts.

&nbsp;
> would have assumed that too, except for the presence of the qu_id field.

The user can select a unit, that unit needs to be stored somewhere, that's all.

&nbsp;
> but hopefully you can understand my confusion.

Absolutely no problem, I've answered each and every question that came up in the last over 7 years Grocy. However, I'm allergic when reporting questions as a big bug, hopefully you can understand my frustration.

&nbsp;
> So does that mean the "correct" way (in my use case) to get the amount of a product in the "quantity unit purchase" is this?

Again: Each and every amount (and price) posted to or returned by the API is always related to the corresponding product's QU stock. There are no exceptions on this simple rule. For shopping list items the `qu_id` simply determines how to display that amount to the user. So of course your above outlined steps are the ones to get to that destination.

&nbsp;
> I didn't realize the frontend used the same API calls

[README](https://github.com/grocy/grocy?tab=readme-ov-file#rest-api) exerpt:
_The web frontend uses exactly this API for pretty much everything. So everything you can do there is also possible via the API._

&nbsp;
> I assumed it was a niche API call on a niche piece of software

Grocy attracted way too much users for my taste (in the sense that this dropped the happiness factor for that hobby project a lot, especially lately), but I agree that more than most likely the vast majority of humanity doesn't need a ERP software to manage their fridge and that's more than ok.

&nbsp;
> The only docs I could find are the ones [here](https://github.com/grocy/grocy/tree/master/docs) and the API isn't mentioned at all. If I were to submit documentation for the API to help the next person who is confused by it, is this the best place to add it?

I personally don't write documentation because I don't have fun doing it - this is a hobby project, naturally hobbies are about the fun part only. If you contribute something, make sure to also maintain it over the long run, outdated stuff is IMHO worse than nothing. From my practical experience with not only this project, people don't read stuff anyways, regardless where exactly it was glued to. In thousands of threads more than every question has been answered over the last couple of years and we have more than great search engines in 2024. Giving a good one a visit will answer just like every question in seconds. So for me, those threads are the best and more than enough and up to date documentation.

**Comment by BenBergman** [comment]
Got it, thanks for your help!
