### ISSUE TITLE
Bug: Userfields are always output as a string in the API

### ISSUE THREAD

**Issue by DarkShortie** [grocy/grocy#2610]
I have created different userfields for products. I want to use them also with the Grocy API. The userfields are of different types (int, float, bool, date) but in the json from the API they are all enclosed by quotes and therefore handled as strings.

The type of the userfield should be reflected in the API, so no quotes for int and float, true or false for boolean. For the date I'm unsure, maybe it would be easier to handle if it would be a timestamp/epoch, then it would also be not affected by any timezones.

**Comment by berrnd** [comment]
I'm very allergic to reporting stuff you personal expect to behave differently as a big Bug instead of simple Feature Request or by simply asking beforehand how things were implemented.

Userfields are by nature a very generic approach to add any fields you want to any entity you want, so technically the corresponding value can only be stored as strings when following that generic approach to the end. The Userfield type is just another property of a Userfield to instruct the web frontend how to display the corresponding input/output.

&nbsp;
> and therefore handled as strings

Grocy doesn't enforce what you do with API output on your side, parse the values according to the Userfield type if you need that.

&nbsp;
> The type of the userfield should be reflected in the API

No, they were implemented using a generic approach, this works as designed.

&nbsp;
> then it would also be not affected by any timezones

Grocy doesn't handle timezone information anywhere as of today and since ever (ref #214) and expects every date-time value to be related to your local timezone and this also means it's expected that your client and server (keep in mind that your OS and PHP runtime may use different settings) timezone should match, which should be just the normal case for any setup out in the wild.
