### ISSUE TITLE
Bug: Chores not correctly assigning

### ISSUE THREAD

**Issue by lgnmcrules** [grocy/grocy#2617]
Hello,

The Chores Overview section for Grocy shows chores for when they are supposed to be done and who they are to be done by.  The chores have a setting for assigning people to a chore by who did the least of a chore.  The chore is not correctly setting who is supposed to do a chore.  

![image](https://github.com/user-attachments/assets/1a2820d6-f640-4edc-8e89-6c940dcae16d)
![image](https://github.com/user-attachments/assets/7c259892-159d-4f82-94da-0444d92176ef)

In the above screenshots, you can see that while 'N' has done the most of this chore, they are being selected to do the chore.  This is even after rescheduling and completing the chore multiple times.  This issue is present on multiple chores.  All correct users are assigned to the chores.  

This issue can likely be reproduced on a long standing system with chore completions spread out over a very long period of time while using the who did least first option for chore assignments.  

The expected result is that the person who did the least of the chore would be assigned it, with tiebreakers being arbitrarily assigned.  The current result is that the person who is assigned the chore is not the person who did the least of the chore.

Thanks

**Comment by berrnd** [comment]
I can't look behind screenshots, do you?

The issue template explicitly mentions to provide reproducible examples on a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) due to that.

&nbsp;
> This issue can likely be reproduced on a long standing system with chore completions spread out over a very long period of time 

Got it. I made this mistake, so you want me to spend my spare time to turn your screenshots into a hands-on example - you're welcome:

https://test-86z0wyksx2o29h045vkdtf.demo-prerelease.grocy.info/choresoverview

Everything works there.

So please provide a reproducible example (as mentioned on the issue template) and I maybe or maybe not invest some more of my endless spare time to look even deeper into it.

&nbsp;
> In the above screenshots, you can see that while 'N' has done the most of this chore

I can only do guessing and maybe you simply have a filter active and that's simply not the entire journal of that chore.

**Comment by berrnd** [comment]
Code ref where all the `CHORE_ASSIGNMENT_TYPE_WHO_LEAST_DID_FIRST` magic comes from (pretty simple at the end):

https://github.com/grocy/grocy/blob/11ea8f3716b84f23726338d442d4acfef67f7cef/services/ChoresService.php#L89-L96

https://github.com/grocy/grocy/blob/11ea8f3716b84f23726338d442d4acfef67f7cef/migrations/0083.sql#L66-L74
