### ISSUE TITLE
Bug: Unable to change Quantity unit stock once product is created

### ISSUE THREAD

**Issue by aled2305** [grocy/grocy#2618]
Once a product has been added I am unable to update the following fields. The only value showing in teh dropdown is the current value: 

- Quantity unit stock
- Default quantity unit purchase  
- Default quantity unit consume
- Quantity unit for prices

This appears to be the case on my instance and both the release and master branch demos.

<img width="1089" alt="Screenshot 2024-12-12 at 15 36 33" src="https://github.com/user-attachments/assets/bdd63ef0-ff80-492e-bcf1-5f66c600f9f9" />

**Comment by berrnd** [comment]
This is nowhere a Bug, please be so kind and do a little search beforehand and use the [r/grocy subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) for general usage questions.

Once a product is added to stock, you need to tell Grocy how much a Piece is related to your desired other unit, since Grocy needs to convert all existing amounts everywhere - it's impossible to guess that - you can tell Grocy that by creating corresponding unit conversions.

Just mentioning a few recent threads about that, easily discoverable in seconds:
- https://github.com/grocy/grocy/issues/2369
- https://github.com/grocy/grocy/issues/2357
- https://github.com/grocy/grocy/issues/2405
- https://www.reddit.com/r/grocy/comments/16vsvwe

**Comment by aled2305** [comment]
So how would I fix this if the current value was blank?

I should have mentioned this, but when scanning an item via the iOS app (and forgetting to set the value as the app does not stop you submitting even though it's a required field just like location) how do I then change this value as unless I've missunderstood I can't set a conversion from blank?

<img width="1157" alt="Screenshot 2024-12-12 at 16 54 50" src="https://github.com/user-attachments/assets/c2e2398c-815e-42d6-983a-c86379cb4aec" />

**Comment by berrnd** [comment]
> So how would I fix this if the current value was blank?

Then you fucked something up completely, e.g. by deleting an in-use quantity unit which doesn't make any sense at all - Grocy doesn't prevent any possible user error at each and every place. I would restore my backup if that's important for me / a lot to do to fix it otherwise.

&nbsp;
> as the app does not stop you submitting even though it's a required field just like location

Sounds like a way to get that if that's the case. Very personal recommendation: If your smartphone has a web browser like mine does, simply use Grocy's web frontend there - I do this daily, works since years without a single problem.
