### ISSUE TITLE
Feature Request: non-admin users

### ISSUE THREAD

**Issue by Phaeton20** [grocy/grocy#2628]
I would find it useful, if there was a posiiblity to differntiate between admin / non-admin users.

I think a simple 2-role-system would be enough for most households:

1. (normal) user: has the right to access and change most data with following **exclusions**
   - Change Users other than itself
   - Change default settings under the toolbar in the top right toolbar.
   I think it would be imporant, that the user still has the ability to manage his API-Keys by himself
2. Admin: Has all rights (like the standard user right now)

The main goal with this, is to prevent teens from deleting admin users or messing with accounts of other people of the household.

Maybe in a distant future there would be some kind of ability to specifiy more rights on a per  user rate / role rate but that would be 200 % right now.

**Comment by berrnd** [comment]
I would find that useful too and that's why I've built that more than 4 years ago (ref [changelog v3.0.0](https://grocy.info/changelog#v3.0.0)).

Has also been a topic here and on the [r/grocy subreddit](https://www.reddit.com/r/grocy) like a trillion times - please be so kind and do a quick and easy search beforehand, that's also mentioned on the request template.
