### ISSUE TITLE
Feature Request: Android App

### ISSUE THREAD

**Issue by Raverphil** [grocy/grocy#287]
Hello, First of all thanks for the great ERP system for the fridge :) Now to my question. Is an Android app with a synchronization feature planned in the future? I don't want to expose the service to the world, a mobile app with "offlinedata" and synchronization function (local area network) would be super convenient.

Hallo,

Zuerst einmal danke für das tolle ERP für den Kühlschrank :)

Nun zu meiner Frage. Ist in Zukunft eine Android App mit einer  synchronisation geplant?
Ich betreibe grocy aktuell auf einem rpi3 und möchte nur ungerne den Service der Welt präsentieren, deswegen wäre eine mobile App mit "offlinedaten" und synchronisations Funktion (lokales Netz) super praktisch.

**Comment by berrnd** [comment]
Ich belasse es mal bei Englisch, damit jeder einfacher mitlesen kann...

Was already request in #199.

I personally also use grocy on my smartphone, mainly the shopping list, but I rarely have the problem to have no internet connection somewhere and also have no problem to expose my selfhosted service publicly. grocy only exposes something when you are logged in, if you're worried, maybe just put a webserver with HTTP Basic Auth or something in front - that's how I do it with a bunch of other services...

As already said in the mentioned issue, I can think of working on an "companion app" for certain (little) features like the shopping list or tracking chores, but I don't see the benefit to develop a feature-complete app, as the website is responsive (enough). But this will not happen anytime too soon from my side ... because of time ... would love to get all the other feature requests sorted here first... :)

**Comment by berrnd** [comment]
Closing this, please follow #199 for updates on this topic.
