### ISSUE TITLE
Not loading properly

### ISSUE THREAD

**Issue by assasen11** [grocy/grocy#347]
![image](https://user-images.githubusercontent.com/2252890/63804032-393e6580-c8e4-11e9-8fad-06b0444e01db.png)
Ubuntu - 18.04
PHP - 7.2
Sqlite - 3.24
Yarn - 1.17.3
Composer - 1.9.0
Apache2 - 2.4.34

There is a bunch of stuff that are not loading and I am trying to figure out what I am missing. The data folder has write access. All the files have the correct permissions. I have all of the software installed and the versions that were necessary. I am almost wondering if I am missing one slight PHP component or something odd. Any help is much appreciated. I can provide any additional information. I did not see any obvious errors in the apache log.

-Thanks
Chris

**Comment by berrnd** [comment]
Try disable URL rewriting - `data/config.php` -> `Setting('DISABLE_URL_REWRITING', true);`.

Check the browser console and/or the webserver logs, I think you will see a lot 404 errors because of missing (dependency) files...

Or maybe you have installed directly from master and have not installed the Yarn dependencies manually...

**Comment by berrnd** [comment]
Then this did not work I suppose...

After `yarn install` there should be a lot of files and around 38 directories in `<grocy-dir>/public/node_modules`.

Or just use the release ZIP where everyhting is included...

**Comment by berrnd** [comment]
Great that it works now :) - so going to close this...

**Comment by ADIX7** [comment]
I also get 404 for all node_modules path. It's my first time with grocy, currently I try to start with docker-compose, I copied most of the configs from the repo:
```
  grocy:
    image: grocy/grocy-docker:grocy
    container_name: grocy
    restart: unless-stopped
    environment:
      PHP_MEMORY_LIMIT:    512M
      MAX_UPLOAD:          50M
      PHP_MAX_FILE_UPLOAD: 200
      PHP_MAX_POST:        100M
      GROCY_CULTURE: en
    ports:
      - 9000:9000
    networks:
      homemedia:
        aliases:
          - grocy

  grocy-nginx:
    image: grocy/grocy-docker:nginx
    depends_on:
      - grocy
    ports:
      - '4450:80'
    container_name: grocy-nginx
    networks:
      homemedia:
        aliases:
          - grocy-nginx
```

Login loads correctly but that's all. Is there any problem with my config? (Don't mind the ports, they are just temporary)

**Comment by berrnd** [comment]
Is the `<grocy-dir>/public/node_modules` directory there? If not, you've probably not used the release ZIP and need to install dependencies manually, as mentioned in README and above.

There is also a separate [grocy-docker](https://github.com/grocy/grocy-docker) repo, please report Docker related issues there.

**Comment by ADIX7** [comment]
Yes, there is inside the container, I use the docker version.
Okay, I will post there.

**Comment by Pistos** [comment]
I had the same problem and similar screenshot as OP.  The `package.json` is in the root of the git checkout, so that is where I assumed you needed to run `npm install`.  This, of course, puts the `node_modules` dir in the git root.  I saw lots of 404s looking for `node_modules/**/*` files.  If I symlink `node_modules` from the git root to `public/node_modules`, then everything is found (404s turn to 200s).

I got it working this way, but, pardon me for saying, but it seems extremely bizarre to me to have `node_modules` publicly exposed by the webserver to the web.

**Comment by berrnd** [comment]
> The `package.json` is in the root of the git checkout, so that is where I assumed you needed to run `npm install`.  This, of course, puts the `node_modules` dir in the git root.

True and false. We use `yarn`, not `npm` (as [mentioned in README](https://github.com/grocy/grocy#how-to-install)) and there is [`.yarnrc` file](https://github.com/grocy/grocy/blob/master/.yarnrc) where the `node_modules` folder is redirected to `/public`.

> I got it working this way, but, pardon me for saying, but it seems extremely bizarre to me to have `node_modules` publicly exposed by the webserver to the web.

Feel free to suggest a better way, all ideas are always welcome. This is not Node.js application, we only use `yarn` for frontend dependency management, so I don't see the problem about exposing that...
