### ISSUE TITLE
Default to product_group in Edit recipe ingredient Group field

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#398]
When adding an ingredient to a recipe, can the "Group" field be pre-populated with the product's  product_group name?

Or perhaps add a checkbox under the field that says something like
"Default: Use the product's product group" which then renders the Group field uneditable.

**Comment by berrnd** [comment]
> Or perhaps add a checkbox under the field that says something like...

Maybe that.

Product groups were mainly thought to group products on the shopping list and to categorize them.

"Group" for recipe ingredients is a free editable text field because it was thought to just group ingredients together, maybe you have a recipe with two components (dough, filling) and want to not have all ingredients in one mixed list...
