### ISSUE TITLE
Multiple instances on the same server?

### ISSUE THREAD

**Issue by Banbury** [grocy/grocy#399]
I'm trying to create a second installation of Grocy on my server.
I've copied the contents of grocy into a folder grocy2. But every time I  try to log in, I'm rerouted to the main grocy installation. Changing the BASE_URL does nothing.
Is there a way to run multiple instances on the same server?

**Comment by berrnd** [comment]
Sure, everything is based on the `BASE_URL` setting - check if all the URLs for stylesheets or also the visible links point to the correct path. (?)

If you visited the second installation once with `BASE_URL` pointing to the first installation, then I just think your browser remembers that - maybe try another one or clear all caches, etc. - 301 redirects are remembered like forever in most browsers...

**Comment by Banbury** [comment]
I copied the files to a new folder grocy3 and changed the BASE_URL to /grocy3. I'm still rerouted to the main installation.

**Comment by berrnd** [comment]
`BASE_URL` can only be `/` when running directly under a (sub)domain, or a full URL (like mentioned in the comment above the setting) - so please try to enter your full URL path there.

All the links in the sidebar for example, to they point to right path or not?

grocy cannot know the other installation for any reason, so this can only be a problem about `BASE_URL`...

**Comment by Banbury** [comment]
Both installations are directly under the main domain. And I have no idea where the links are pointing to, because I'm rerouted to /grocy immediately. Do I need a virtual host?

**Comment by berrnd** [comment]
> Both installations are directly under the main domain
Then your `BASE URL` setting should just `/` or the FULL URL when you have it in a subdirectory.

Redirections (by grocy) only happen on the main route (`/`) so what about directly checking it by manually visiting for example `https://yoursecondgrocyinstall.com/stockoverview`?

As I said, if the first installation works, the second will in the same way - grocy know nothing about your server, for example no my demo server 24 instances are running (stable/pre-release demo and for each language)...

Otherwise please post your full config, it's hard to guess all the things...

**Comment by Banbury** [comment]
I guess it's a problem on my end then. Thanks for the help.
