### ISSUE TITLE
Unable to edit or add products after 2.5.1 update

### ISSUE THREAD

**Issue by K-Money** [grocy/grocy#401]
After upgrading to 2.5.1, whenever I try to edit or add a product It gives a red error that says 

> "Error while saving, probably this item already exists. Click to shown technical details"

The same behavior happens even when adding a brand new item though that definitely doesn't exist. When the error message is clicked on it gives the below technical details:

> "{\"error_message\":\"SQLSTATE[HY000]: General error: 1 table products has no column named cumulate_min_stock_amount_of_sub_products\"}"

I have tried restarting to no avail.

**Comment by berrnd** [comment]
Seems that migration [0092](https://github.com/grocy/grocy/blob/master/migrations/0092.sql) did not run, as [mentioned in README](https://github.com/grocy/grocy#database-migrations), migrations run when visiting the root route (`/`), please verify that, just click the grocy logo in the left upper corner.

Otherwise I have no idea why the migration was not applied without errors, you can then only run it manually...

**Comment by K-Money** [comment]
Ah! You're totally right! That fixed it! I don't know how I missed that! Sorry and thanks!
