### ISSUE TITLE
Ingredients of a recipe only visible inside edit recipe

### ISSUE THREAD

**Issue by Jeltel** [grocy/grocy#403]
I'm using the Mealplan with the recipes every week. But recently the new recipes are having a problem.

When I add a new recipe with ingredients. The ingredients show up in the edit part of a recipe:
![afbeelding](https://user-images.githubusercontent.com/1732436/65955637-e575ed80-e448-11e9-9d2f-59d245d3d3aa.png)

But in the main recipe list, the ingredients do not show:
![afbeelding](https://user-images.githubusercontent.com/1732436/65955695-00486200-e449-11e9-98cd-2f44772227b9.png)

In this list (and the mealplan) the check if everything is in stock for this meal always says yes, even though the ingredients are clearly not available.

In the API the recipe is there:
```
  {
    "id": "48",
    "name": "Test Recept",
    "description": "<p>test<br></p>",
    "row_created_timestamp": "2019-10-01 12:39:04",
    "picture_file_name": null,
    "base_servings": "2",
    "desired_servings": "2",
    "not_check_shoppinglist": "0",
    "type": "normal"
  }
```

And also the ingrediënt is there:
```
  {
    "id": "132",
    "recipe_id": "48",
    "product_id": "113",
    "amount": "1.0",
    "note": "",
    "qu_id": "3",
    "only_check_single_unit_in_stock": "0",
    "ingredient_group": "",
    "not_check_stock_fulfillment": "0",
    "row_created_timestamp": "2019-10-01 12:39:18",
    "variable_amount": ""
  }
```

I'm note sure how to recreate this bug, because it's happing for all my new recipes since some date. Last recipe to work is this one:
```
  {
    "id": "30",
    "name": "Bloemkool met gehaktbal en kaassaus",
    "description": "",
    "row_created_timestamp": "2019-05-25 19:55:06",
    "picture_file_name": null,
    "base_servings": "3",
    "desired_servings": "3",
    "not_check_shoppinglist": "0",
    "type": "normal"
  }
```
But multiple recipes where added around the same time.

**Comment by berrnd** [comment]
Hm, if you can reproduce this on the demo it would be great...

Does it only happen when all ingredients for that recipe are not in stock?
Tried that on the demo (single ingredient, not in stock) and it displays fine...
https://en.demo.grocy.info/recipes?recipe=9

**Comment by Jeltel** [comment]
Yes that's the problem. I don't know how to reproduce. It might be something in a recipe what causes it.

5 min later:
I had some placeholder recipes. Only titles without any ingredients. I deleted some of them and there where there weren't any ingredients included. I cannot pinpoint it to one recipe. Only if i delete several of them it starts working again.

So maybe it has to do with to much recipes without ingredients?

**Comment by berrnd** [comment]
Tried to create a bunch of empty reccipes on the demo, the "TEST1" recipe displays still fine...

Unfortunately, without being able to reproduce that, I have no real idea what's the problem there...

If it's ok for you, you can send me your database (bernd@berrnd.de) while at least one recipe has this problem, then I will have a deeper look.

**Comment by Jeltel** [comment]
I've joined you, But no I cannot repeat the error.

I'll send the database.

**Comment by berrnd** [comment]
I've found and fixed it:
Because it's not enforced forbidden to include the same recipe into itself as a nested recipe, it would cause infinite loops when resolving recipes. Therefore I've introduced a hard limit of 100 in the SQL view `recipes_nestings_resolved`, which does the recipe resolving part - which was totally stupid, because you can have of course more than 100 recipes. And also since meal plans are internally also nested recipes per day and week, there are much more recipes since then.

Sorry...

If you want to have it now, you can execute the SQL inside [that file](https://github.com/grocy/grocy/blob/901b345714469a892362af4f9e4c4b383935b3ee/migrations/0093.sql) manually against the database for example with [SQLiteDatabaseBrowser](https://sqlitebrowser.org/), it will not hurt/conflict when doing an update later.

**Comment by Jeltel** [comment]
Cool. I've executed the SQL on the database and it works. Thanks!
