### ISSUE TITLE
Feature Request: Nextcloud integration

### ISSUE THREAD

**Issue by Igel18** [grocy/grocy#406]
It would be nice the application could be installed in nextcloud as an app. 

The reason is there is already an calender integraled as well as a FileSystem Access with manuals and receipts from my devices. 
The third thing there is a fully user and right management.

**Comment by berrnd** [comment]
You could just load your grocy instance embedded as an iframe, see: https://docs.nextcloud.com/server/17/admin_manual/configuration_server/external_sites.html

I also use Nextcloud, integrating everything into their ecosystem would be a major effort (grocy has no permission management currently for example)...

**Comment by Igel18** [comment]
Thank you. Thats a good work around. I understand thats a lot of work, but its more easy to eg update grocy.

**Comment by berrnd** [comment]
> but its more easy to eg update grocy

When you run it on Linux, just run `update.sh` and that's it: https://github.com/grocy/grocy#how-to-update

If you use Docker, just pull the image again...

**Comment by Paddy0174** [comment]
Personally I think the integration into HomeAssistant is the better way to go, rather than Nextcloud. :) 
Thematically Grocy is _inside_ the household, like an instance of HomeAssistant. Nextcloud on the other hand is a more _outgoing_ (or exposed) installation. 
I can see the point, but if you open pandoras box of trying to manage your household software-based or automatically, it is just a very small step to home automation. And if you are there, you'll find a lot of things, that are already implemented in HA, like the use of Alexa/Apple Homekit/Google Home or even your own voice recognition software. On the long run, NC will never (and should never) be the software for your "home", HA on the other hand is.
And, the important thing at last, there is already a PlugIn for HomeAssistant available, just two clicks in Hass.io and you can use Grocy. :)

**Comment by ChadOhman** [comment]
I have to disagree with @Paddy0174.
We use Grocy for our shopping list and while I have an L2TP VPN setup, she’d prefer not to use it so I have Grocy spun up on my remote development kubernetes cluster. I’m not poking a hole into my network.
Nextcloud integration would be a nice perk.

**Comment by RubenKelevra** [comment]
> I’m not poking a hole into my network.

I don't think that's the implication here. Instead of using the insecure L2TP VPN, you could just install a permanent VPN via Tailscale on all devices. There's no manual intervention necessary, you can then just connect directly to HA.

**Comment by berrnd** [comment]
Providing grocy as an Nextcloud app is not a specific feature request for grocy. So closing this.
