### ISSUE TITLE
Information about getUserMedia and HTTPS

### ISSUE THREAD

**Issue by jrester** [grocy/grocy#411]
The Barcode Scanner does not work without a site accessible over https because `getUserMedia` requires a [secure-context](https://stackoverflow.com/questions/34197653/getusermedia-in-chrome-47-without-using-https). Maybe there should be a warning in the documentation and a more informative error message instead of the current "getUserMedia is not defined".

**Comment by berrnd** [comment]
This was mentioned in the changelog of v2.5.0: https://grocy.info/changelog#v2.5.0

I will add a note to README - we have not more "documentation" at the moment...

And that's not totally true, because you can configure your Browser to allow the API also on non-secure sites as the example in your linked thread shows for Chrome.
