### ISSUE TITLE
[request] Add minimalist shopping list view for mobile

### ISSUE THREAD

**Issue by ministryofsillywalks** [grocy/grocy#453]
The shopping list packs a lot of features, so on mobile you have to scroll quite a while before actually reaching the list itself
![grafik](https://user-images.githubusercontent.com/10544895/70135397-4a88d200-168a-11ea-8451-6002cce7e652.png)
Would it somehow be possible to hide everything inbetween the red bars and just show the list itself?
It would greatly improve the waf and make it sleeker to use when shopping.
Also see my issue #452 for making the list even more user friendly and more minimalist.

**Comment by gersilex** [comment]
I think the "full-screen" button of the recipes could be used here as well. It even prevents accidental reloading as long as the full-screen view is opened.

**Comment by berrnd** [comment]
This now looks/works like that:

![2020-01-24_22-06-39](https://user-images.githubusercontent.com/2161815/73104119-f49c1200-3ef5-11ea-9bbc-8fafedf004f0.gif)

It automatically switches to that "compact view" on mobile devices (when screen width is < 768 px).

**Comment by gersilex** [comment]
I'd like to re-iterate on this feature and ask if a calendar is really something that belongs on a mobile shopping list. Never seen it before and I can not think of any reason how this could be useful to me.

Also there are some padding oddities I was not able to fix easily. It's also shown on your demo gif.

If I read this correctly, when switching to compact mode, the paddings are not reduced, but instead the whole content is moved to the left by 15px, leaving a big gap on the right side. I'd like to re-open the issue to show that there is still work to be done, instead of opening a bug.

**Comment by gersilex** [comment]
Using `width: calc(100% + 30px)` on `.fullscreen` and removing `width` from `.dataTables_scrollHeadInner` seems to workaround this display issue in the short term,

![image](https://user-images.githubusercontent.com/2018039/73553626-894cc580-444a-11ea-9cee-b8b94dc92dca.png)

Those changes do not break the normal view, too

**Comment by berrnd** [comment]
Thanks, based on your suggestion I tried to improve it, see https://github.com/grocy/grocy/commit/6d4a15d372fec9dc64af702b74859226c7c1eccf. I think in your example the scrollbar was then hidden/overlapped by the table...

What was also missing in compact is the notes field - I also added that again.

Adding an option to hide the calendar is already tracked in #531.

**Comment by gersilex** [comment]
Almost perfect now. There is still an issue with horizontal scrolling:

![GIF 02 02 2020 01-17-26](https://user-images.githubusercontent.com/2018039/73601080-ed5eaf00-455a-11ea-8b29-e1f9bda6f595.gif)

Removing the `overflow` from `.fullscreen` in `grocy.css` seems to mitigate the issue.
