### ISSUE TITLE
No automated Picture downscaling via api file upload

### ISSUE THREAD

**Issue by KenshiHH** [grocy/grocy#464]
hi, i think i found a bug.

when i upload an image via the rest api, the file gets correctly uploaded and correctly displayed if the resolution is under 400pixels

if its higher it should be automatically downscaled when the image is viewed for the first time(__downscaledtoautox400 gets created)

but the automatic downscale only works for files uploaded button via edit products page

files uploaded via the rest-api are not getting downscaled

version info
Linuxserver Docker Container
Version 2.5.2
Released on 2019-10-05 2 months ago

PHP Version 7.3.11
SQLite Version 3.28.0

**Comment by berrnd** [comment]
There is no difference - the product page also uses the API to upload pictures...

I think maybe an error happens when downscaling your example picture. Is it served when you not downscale it (so not with query param `force_serve_as=picture`)?

Downscaling happens here: https://github.com/grocy/grocy/blob/0be1994c029b2dbe9204765dcf5a4d7d804cd5ee/services/FilesService.php#L36-L76
When any error about downscaling occurs, the original image should be served.

Maybe you can upload your example image on any demo, then I will have a look.

**Comment by KenshiHH** [comment]
after a good night of sleep, i found out my file upload gets somehow messed up, fault is completely on my side. thank you :)
