### ISSUE TITLE
Edit Recipe Questions/Bug?

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#473]
Heya,

I can't seem to track down what's happening but maybe you know offhand
My issue is selecting an ingredient to edit in a recipe changes the product picker to a different ingredient with a similar name.

1. Select a recipe
2. Click edit on an ingredient in the Ingredient List
3. The product picker for the Edit Recipe Ingredient, does it
- prefill by name?
If so, I have a few ingredients that have similar names.

If instead it uses the product id, then it seems to be sending the wrong product id?

The other issue I have is the Recipe cost looks to be off.
Why is there a divisor in the recipes_pos_resolved by the purchase factor?
I removed it from the view and it seems to have cleared up my issue.

**Comment by berrnd** [comment]
The recipe ingredient edit page uses "prefill-by-name", which just does a "normal" search and picks the first result, which could be not 100 % accurate if you have similar named products. So you're right, it should be better changed to "prefill-by-id" (for all places where the productpicker is used with a prefilled product).

For the second question:
Prices are always per purchase quantity unit.
See "testproduct1" and "testrecipe1" currently on the english demo: https://en.demo.grocy.info/recipes?recipe=11
1 Pack purchased = 10 Pieces in stock; 1 Pack costs 10 $.
If you remove the division as you proposed in #474, it would result that 1 Piece costs 10 $ (instead of 1 $)...

**Comment by berrnd** [comment]
I created #475 to track the issue about "don't use prefill-by-name for the productpicker".
