### ISSUE TITLE
Desktop version

### ISSUE THREAD

**Issue by dieselman8228** [grocy/grocy#480]
Are there any plans/ way to build grocy to function as a desktop application like it does for windows?

**Comment by berrnd** [comment]
[grocy-desktop](https://github.com/grocy/grocy-desktop) runs grocy in a "just works" manner on Windows (it's not a real desktop application, it's more a wrapper which auto-manages the webserver behind and so on).

If you mean doing that for other platforms than Windows - not from my side, mainly because personally I only use Windows as a desktop OS. But I'm sure it would be possible, PHP runs on every OS.

**Comment by berrnd** [comment]
And just to add that here: grocy also has an API, building a native app based on that should be possible as well: https://demo.grocy.info/api.

**Comment by dieselman8228** [comment]
Thank you very much for the insight and help.
