### ISSUE TITLE
Missing option for GBP currency

### ISSUE THREAD

**Issue by muggahtee** [grocy/grocy#486]
Choosing alternative languages changes the currency, however there is only one option for English which uses USD

**Comment by berrnd** [comment]
> Choosing alternative languages changes the currency

No. There is a separate setting for the currency:
https://github.com/grocy/grocy/blob/d4bec3bd10eebe4585cf33cf4badd9617eb48a7e/config-dist.php#L34-L38

**Comment by muggahtee** [comment]
Ah I see, so it is not configurable in the GUI by the user, but instead in the server settings? Thanks for replying

**Comment by berrnd** [comment]
> Ah I see, so it is not configurable in the GUI by the user, but instead in the server settings?

Yes, the same as for all options in the `config.php` file...

**Comment by jamesgeddes** [comment]
Would be good if the admin could set this and any other settings in the GUI.

**Comment by patrickShaikh** [comment]
> Would be good if the admin could set this and any other settings in the GUI.

Why? it is a server setting not a gui setting.

**Comment by gingerbeardman** [comment]
Took me a while to find this.

It would be great if it was a user setting, `DefaultUserSetting()`, like the many others in `config.php`

**Comment by berrnd** [comment]
> It would be great if it was a user setting, `DefaultUserSetting()`

That would mean different users in your home need to have different currencies and would involve currency conversion. I doubt that's a common need in reality.

In contrast it's not so uncommon to have a config file for "things", once going through it (when installing grocy) is IMHO doable. If you missed that config option, you missed each and every one.

I personally will nothing change about that, everyone can catch up on improving this, if that's the most important missing thing for you.

**Comment by gingerbeardman** [comment]
It's disappointing that you are so set on making using this software more difficult for anybody not usingUSD. That's more than two thirds of the world. 🌍

First things I did:
- change password
- setup users
- change due soon days
- change currency
  - tried ENV (asdirected in another issue) but it not work
  - finally found config info

Out of those only currency had to be done in the config. 😞

**Comment by berrnd** [comment]
At the very first step or so, you've copied `config-dist.php` to `data/config.php`, otherwise grocy won't work at all.

When doing that, having a look at such a config file is no big deal - if all defaults of the other 50+ options fit you, glad for you.

Fun facts:
- My "home currency" is also not USD, making it essentially very hard for myself too
- For at least the same amount of people, the preferred language and therefore grocy localization is not `en`, but that's default in the shipped `config-dist.php` - sorry for making it easy for YOU
- This is Open Source, you can start immediately making it so much easier for the whole world, if that's the most important thing about grocy for yourself, as said above (for me it's more about the things after the once and initial setup, but well, everyone enjoys other parts)

Sorry, but if those initial simple steps are too hard for you, I would so grocy is not the right thing to use - parent/child products, quantity unit conversions - just to name a few other "difficulties". When a software disappoints at the very first steps, I personally don't use it.

**Comment by gingerbeardman** [comment]
> At the very first step or so, you've copied config-dist.php to data/config.php, otherwise grocy won't work at all.

Incorrect, I did not do any such file copy. Why? I am using a docker container of Grocy so I assume that step was already completed.

**Comment by berrnd** [comment]
> I am using a docker container of Grocy so I can only assume that step was already completed.

None of the community contributed Docker images are maintained here. If you want 100 % flexibility over configuration options and more, maybe Docker is also not the way to go in general.

&nbsp;
I'm really not open-minded at all. By only implementing nearly 400 Feature Requests in the last 5 years, that's definitely the case.

Time is limited and so I enjoy to focus on things which are just more important / make grocy more fun. A simple configuration setting, which need to be changed once and for all, is not that. Beside that all, someone needs to define the goals of a project and since this here is mine, I'm the one who decided that having a GUI setting for `CURRENCY` will not be added. Project decisions don't have to please everyone, since nobody is forced to use this software and it's totally fine that someone maybe thinks I'm a not-open-minded asshole. If the developer of a software is an idiot, for me that's also a reason to not use a product.

**Comment by gingerbeardman** [comment]
Hey, no need to resort to name-calling, throwing bad language and abuse at random people. That is not cool.

I think it would be better to have no currency symbol at all rather than the wrong currency symbol.

Take care.

**Comment by Deanmrd** [comment]
where is the file [config-dist.php] cannot seem to find it.

**Comment by berrnd** [comment]
> where is the file [config-dist.php] cannot seem to find it.

In the root directory, on the same level where the `public`, `services` and all the other directories are - content of the latest release ZIP:

![grafik](https://user-images.githubusercontent.com/2161815/202996314-688061d0-5155-4d9a-96a2-c636c3bcd5c4.png)

But that's not the one you should edit, you need to copy that to `data/config.php` and edit that one - exactly that is also mentioned in README: https://github.com/grocy/grocy#how-to-install

> _Copy `config-dist.php` to `data/config.php` + edit to your needs_

**Comment by VNRARA** [comment]
> Choosing alternative languages changes the currency, however there is only one option for English which uses USD

For NLD there's no EUR as currency

**Comment by berrnd** [comment]
> For NLD there's no EUR as currency

To clarify this once more here:

The [`config.php` setting `CURRENCY`](https://github.com/grocy/grocy/blob/df4907f5d43df42167cdceebf0737eaba7311b36/config-dist.php#L38-L42) is completely unrelated to any user language setting. And of course `EUR` or `USD` or any [ISO 4217 currency code](https://en.wikipedia.org/wiki/ISO_4217#List_of_ISO_4217_currency_codes) (as mentioned in the `config.php` setting comment) is valid and can be used there.

**Comment by KoenDG** [comment]
This seems to no longer be possible. The docker-compose.yml file created a docker volume by default, `app-db`. You need to go inside the volume to perform the edit with `vi`, it seems. Not ideal.

Adding it to grocy.env seems to have no effect.

**Comment by berrnd** [comment]
> The docker-compose.yml file created a docker volume by default [...]

Nothing Docker related is maintained here, the `CURRENCY` setting `data/config.php` is the same today as 4 years ago:

https://github.com/grocy/grocy/blob/33d5ec44d23eb8ec37c7a9b633cecd29f8cabadf/config-dist.php#L40-L44

Locking this due to enough off-topic added.
