### ISSUE TITLE
Meal Plan Week Costs off by one day?

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#516]
If I go to the prerelease demo Meal Plan page it currently shows the week as Sun Jan 19 - Sat 25.

Jan 19th is the start of the week however it is not included in the Week Costs. 
Instead Sunday Jan 26 is included in the week costs.

**Comment by berrnd** [comment]
That's because of the problem we currently don't care about timezones, everything date related is supposed to be in local time everywhere. Therefore the client (browser) and server need to have the same timezone configured. The demos run on a server where to local configured timezone is `Europe/Berlin`.
