### ISSUE TITLE
New category: small appliances [idea]

### ISSUE THREAD

**Issue by jose1711** [grocy/grocy#521]
Not sure if `grocy` would be a good match for this but I have many electronic devices scattered all around my home (under the bed, in the closet, in the shelf.. you got the idea) and often it's a challenge to reach to the right place when you need something.

Currently I can enter such things as products, but then many fields does not really make sense - like you do not "consume" a gamepad or put a multimeter or an old mp3-player into a recipe. Those are not really consumables with expiration date etc.

Equipment would probably be more appropriate but there's no way to add location and/or image. Maybe having a separate non-consumables section could fit in and would certainly help me to manage my household better.

**Comment by berrnd** [comment]
That should be already doable by using "Userenttities" (custom objects), see #242 and #176.
Except for having a field which takes a file/image, but that's already tracked in #282.

Because the demo instances get reset at least once a day, I made a short screenvideo to showcase what I mean: https://nc.b7c7.de/s/bq7RXaJ6Enpm6oi

Would that fit for what you thought of? :)

**Comment by jose1711** [comment]
Thank you, the image field type and the ability to reorder menuitems (wonder if this deserves another issue or can be achieved somehow) and I am all set :-)

**Comment by berrnd** [comment]
Ok, I've created #526 to track the ability to reorder userentity fields, so let's close this here.
