### ISSUE TITLE
Hide/archive products instead of deleting 

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#565]
Problem: I bought these awful vegan broccoli balls. I won't ever buy them again, but they come up every time I search for broccoli in purchase/inventory/etc.

Solution #1: Delete the product - but then, I'm worried that a possible future dashboard/analytics would be incorrect and skewed.

Solution #2: Add an option to hide or archive products. The product continues to exist in the master data section, but doesn't show up in searches in other areas. 

This is very low priority.

**Comment by kriddles** [comment]
I second the option 2 so that it doesn't show up in searches too.

There are several items I would want to keep track of whether or not I previously purchased them and liked it. Perhaps even down the line including a 3-5 star rating on a product.

That brought to mind an idea that perhaps the minimum purchased could be set to -1 or include a checkbox next to it that says "Never Buy This EVER again".

**Comment by berrnd** [comment]
I think checkboxes where to show a product would cover all cases, also #564:

Show for/on
- Purchase
- Consume
- Inventory
- (maybe more)

When the product should be hidden everywhere, uncheck all those checkboxes...
