### ISSUE TITLE
Running grocy in a subdirectory does not work since Slim 4 upgrade

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#568]
As mentioned in the discussion here: https://github.com/grocy/grocy/commit/d4fa1a64c2f3021e400cb1b1506f291e20b57bf3#comments.

This needs to be solved before releasing v2.6.1.

**Comment by kriddles** [comment]
I'll see if I can take a look at this over the weekend

**Comment by berrnd** [comment]
Great.

I tried today to setup a test server (nginx), but I even didn't got the current release running in a subdirectory, tried your config mentionend in the commit discussion, nothing worked, don't know what's wrong ... proper subdirectory-path-stuff seems to be overly complicated somehow...

**Comment by kriddles** [comment]
I tried your fixes and couldn't get it to work for my installation. The current only path that I have that works looks to be based off of your commit 5dd78aa19 prior to the slim fix adding the base path middleware.

The only change I have to make at this commit is to add the 
$app->setBasePath('/testGrocy');
to the app.js

A new config variable could be used for this in config.php.

There is already a base_url config variable however I do have to put the entire url into that variable for Grocy to work such as https://www.example.com/testGrocy
Otherwise I see postMessage issues mainly using modals
![image](https://user-images.githubusercontent.com/54413450/75002598-985fdb80-542a-11ea-901c-999fa22da4ff.png)

**Comment by berrnd** [comment]
Thanks for testing this, I still had no luck to set it up, however...

So I removed the "selective/basepath" package again and added a new `config.php` setting to be used for `$app->setBasePath`.

**Comment by kriddles** [comment]
Thanks for reverting this.
I am up and running with your latest release and the new config.php option.

I tried to test this again a few days ago but didn't get a chance to notify you. It looked like the selective basepath just was not set up for nginx. I attempted to make a few changes to it to allow support but couldn't get it up and running.

![image](https://user-images.githubusercontent.com/54413450/76131585-a427d200-5fd4-11ea-9a21-b62a486294d1.png)
