### ISSUE TITLE
[Feature request] Create settings page to manage config

### ISSUE THREAD

**Issue by tjorim** [grocy/grocy#575]
While users can change the `config.php`-file (which is very cumbersome with grocy-desktop) or set environment variables (mostly docker), it's not very intuitive. Settings are all over the place. Maybe add a single page that has tabs for various settings.

Master settings that now can only be set using the config.php option (currency, language...),
UI settings that are in the top navbar on every page (auto-refresh, clock at the top, night mode),
and separate tabs for the other settings under the button with the wrench icon.

**Comment by berrnd** [comment]
There are already per user changeable settings and all those can be adjusted via the UI (top right corner settings menus).

`data/config.php` contains application wide, mostly technical configuration properties, providing a GUI for that makes not so much sense, is IMHO not required ([there are more also more ways to define those options](https://github.com/grocy/grocy/blob/e9421e9102e78eca519fd16d53592b6a57f22f66/config-dist.php#L3-L14)) and partly won't be technically possible (since some options need to be defined before any UI can be served).

If some currently application wide options / `config.php` settings should be rather user settings instead, this would be another topic.

So closing this.
