### ISSUE TITLE
Upgrade QuaggaJS

### ISSUE THREAD

**Issue by adtwomey** [grocy/grocy#579]
I have try and Samsung and HTC but still no luck trying to add a barcode to grocy. Is grocy running the latest QuaggaJS?
https://www.reddit.com/r/grocy/comments/f8onl2/scan_a_barcode/?utm_medium=android_app&utm_source=share

**Comment by berrnd** [comment]
I've used the latest tagged release of QuaggaJS, which is also the latest available version through npm. Seems that they use the master branch directly for the example - I will switch to it.

However, for my daily use of grocy I would still say to using the device camera for barcode scanning is too slow compared to a (cheap wirless) barcode laser scanner which does the job much better regardless of lighting and from all angles...

**Comment by NikitaPuzyryov** [comment]
For me, current scanner pretty much doesnt work at all. Example “master” scanner seems to work very well.

But it seems like that the project has been left unmaintained serratus/quaggaJS#381. Thereʼs a fork mentioned in that issue [ericblade/quagga2](https://github.com/ericblade/quagga2). May be worthwhile to switch.

**Comment by berrnd** [comment]
The switch to use Quagga2 is now done.

And also #713.

Maybe give it a short try on the [pre-release demo](https://demo-prerelease.grocy.info) if this improved something.

**Comment by berrnd** [comment]
Just to note that here: Using [QuaggaJS](https://github.com/serratus/quaggaJS) (master branch) again instead of [Quagga2](https://github.com/ericblade/quagga2) because of #749.

**Comment by ericblade** [comment]
Hi all :) Maintainer of Q2 here. :)  I'm trying hard to not break Quagga in ways that break it for other people, while also significantly upgrading it from years old code.  

My apologies if something is broken on my end -- I try to keep it from breaking with a fairly rigorous test suite, but there are a lot of holes in the coverage of the test suite that I inherited, so it's been a bit prickly there.  Especially when something gets broken in LiveStream mode, since there's not really a way to test that automatically.  

I'd love to have you on a version that is relatively recent, so once I get started in really fixing and improving it, you can come along too :)  so, this weekend, I'll see if I can figure out where the source of the problem you're having is, and get that fixed, and ship something that works for you.

**Comment by berrnd** [comment]
Thanks for your comment, and Quagga2! :)

I don't know if something was broken, maybe it just works different - but I haven't had time to test / debug it...

The noticed problem was that `Quagga.canvas.ctx.overlay` was always `undefined` (used in the `Quagga.onProcessed` event to draw the "barcodescanner lines").

The main "Quagga code" used are those two parts:

https://github.com/grocy/grocy/blob/59650728a2abf126d703cca355b1f869b06f9ed2/public/viewjs/components/barcodescanner.js#L61-L130

https://github.com/grocy/grocy/blob/59650728a2abf126d703cca355b1f869b06f9ed2/public/viewjs/components/barcodescanner.js#L174-L203

**Comment by ericblade** [comment]
That may be a possible accidental change to the interface -- i did some streamlining in that area of the code, and it's possible that some returns there came out differently from the way they used to be -- the test suite tests for success quite well, but doesn't test any failure conditions, or have any hard tests for anything but the end results of success.  So, I'm hoping to improve upon that, and over the next day or two, I'll try to see if I can restore that so canvas.ctx.overlay returns properly, or advise on which way it should be, if I think that interface should change.    I'm trying hard not to change the interface as I work on it, but some of the architecture just doesn't make sense in modern javascript.

**Comment by berrnd** [comment]
Thanks a lot for your work, but no hurry needed at all. :)

I personally don't use camera barcode scanning in grocy (laser scanners just work 1000 % better/faster anyway, but some others said that the barcode recognition quality was better with Quagga2 comparde to QuaggaJS. So would be great to include Quagga2 again in the next grocy release, but that will usually take some weeks or maybe also some months, except bug fixes...

**Comment by ericblade** [comment]
If it's higher quality, that's news to me, for sure :-) I hope to make changes to it in the future that will improve it where I can, but I've spent the first 6-7 months since I called myself maintainer mostly upgrading dependencies and converting to typescript, so that future work will hopefully be a lot easier.

Definitely laser scanners are a better choice than camera scanners, but I don't think most people have a laser scanner around, the one i have is wired, and i can never locate the USB C adapter when I want to use it.
