### ISSUE TITLE
Feature request: db change time for specific object

### ISSUE THREAD

**Issue by smhgit** [grocy/grocy#587]
Currently the API api/system/db-changed-time returns the last change time of the DB. It will be useful to have support for specific object type change time (shopping list, products, chores etc).

One of the reason for that request is because I see slow response querying grocy and it will be helpful to query only changes and not all objects.

**Comment by berrnd** [comment]
Related to #461 and #577.

**Comment by berrnd** [comment]
This will not be added.

If we would have a change time e.g. per product, you would also need to fetch that change time - at the same time/request you could simply fetch the whole corresponding object.

grocy's API is generally not slow, but of course that depends on your server:

Example request which loads 1519 recipes:
```
curl -X 'GET' \
  'https://test-yn582ebblwcl7dvnctq75.demo-prerelease.grocy.info/api/objects/recipes' \
  -H 'accept: application/json'
```

Less than half a second (including network (internet) round trip time), I think that's ok:

![grafik](https://user-images.githubusercontent.com/2161815/209401338-99fd8ee5-0fd6-412e-9587-9357a535d44d.png)

Since v3.0.0 generic filters on most API endpoints are possible, if you don't want to always load everything - changelog excerpt:

>   - There are 4 new (optional) query parameters to utilize that
>     - `order` The field to order by (use the separator `:` to specify the sort order - `asc` or `desc`, defaults to `asc` when omitted)
>     - `limit` The maximum number of objects to return
>     - `offset` The number of objects to skip
>     - `query[]` An array of conditions, each of them is a string in the form of `<field><condition><value>`, where
>       - `<field>` is a field name
>       - `<condition>` is a comparison operator, one of
>         - `=` equal
> 		- `!=` not equal
>         - `~` LIKE
>         - `!~` not LIKE
>         - `<` less
>         - `>` greater
>         - `<=` less or equal
>         - `>=` greater or equal
>         - `§` regular expression
>       - `<value>` is the value to search for
