### ISSUE TITLE
Using Enter to advance in purchase

### ISSUE THREAD

**Issue by Belafestim** [grocy/grocy#611]
When i am putting items in with a USB barcode scanner, it doesnt auto advance to the next feild when the scanner automaticly hits enter at the end of the scan. it currently can only be advanced by using tab

**Comment by berrnd** [comment]
Yes, just configure your barcode scanner to send a `TAB` or `ENTER` after a barcode scan. All scanners I had so far could be configured to do this...

See also: https://github.com/grocy/grocy#barcode-readers--camera-scanning

Otherwise the only way would be to "guess" when the barcode scan is finished. But because the barcode scanner just acts like a keybord, it's not possible to distinguish between manual inputs and the ones from the barcode scanner...
