### ISSUE TITLE
Journal undo creates stock mess

### ISSUE THREAD

**Issue by sgofferj** [grocy/grocy#634]
**What happened**
I consumed 0.09 packs of dog food. Then I used the Journal undo function. In the stock overview I see again 1 pack of dog food but when I go to stock entries, I see 0.91 pack of dog food and 0.09 pack of dog food.

**What should happen**
The 0.09 packs of dog food should have been added back to the pack they were taken from, resulting in 1 pack in the stock entries.

**Comment by berrnd** [comment]
That's intentional.

The "Stock entries" are the "raw stock" rows, it doesn't matter if there are 100 rows with an amount of 0.01 each, or one row with an amount of 1. On consume those rows get maybe splitted, if a partial amount is needed while using the entries in first-in-first-out order. I personally never look into the single stock entries, the page was only recently added to correct maybe wrong best before dates or prices entered during purchase.
