### ISSUE TITLE
Provide consistent URL for github release zipfiles

### ISSUE THREAD

**Issue by jayaddison** [grocy/grocy#640]
Although GitHub's own [release API documentation](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) makes it sound like a unique filename is required across a project's assets, in fact uniqueness is only enforced within each release.

For example, here are two releases ([v0.1](https://github.com/openculinary/api/releases/tag/v0.1),[ v0.2](https://github.com/openculinary/api/releases/tag/v0.2)) under a single project - they both contain a filename `test.txt` with different contents:

```
$ curl -L https://github.com/openculinary/api/releases/download/v0.1/test.txt
v0.1

$ curl -L https://github.com/openculinary/api/releases/download/v0.2/test.txt
v0.2
```

It could simplify scripting and install guides if the `grocy` source bundle could be provided with a static asset name.

This could also provide additional hosting resilience and reduced personal hosting costs (perhaps via server-side HTTP redirect) for installations that currently [download from releases.grocy.info](https://github.com/grocy/grocy/blob/375865d80e54f71ee355bb3bd8f00d04a11cd6f3/README.md#how-to-install).

Your hosting looks good and I have no concerns with it (`servus` to you too!).

**Comment by berrnd** [comment]
Thanks, but I prefer to have the version in the release ZIP/binary. I also think that's more common, when we look across other projects.

Of course when scripting downloads from GitHub two requests would be needed, an example can be found in [linuxserver/docker-grocy](https://github.com/linuxserver/docker-grocy):
https://github.com/linuxserver/docker-grocy/blob/4b22fc0439bc97680efabb2c89f1715e447952a0/Dockerfile#L26-L32

Additionally https://releases.grocy.info/latest always returns the latest released ZIP. I have no problem to provide this "forever". Hosting costs / required resources for that are negligible.

(In fact, because grocy is about _selfhosting_ and _ownyourdata_, I would love to stay away from any centralized service, like GitHub, but that's beyond reality...)

> `servus `to you too!

 😂

**Comment by jayaddison** [comment]
Thanks, understood.  I'll continue on with some installation and documentation updates and hope to provide further feedback.

Could I confirm whether the https://releases.grocy.info/latest Zipfile contains all the required files for a local server installation?  (particularly `composer.json`, `package.json`)

If not I can open an issue to handle that (and potentially a pull request if the infrastructure components are open for contributions).

**Comment by berrnd** [comment]
`composer.json` and `package.json` is not needed in the release ZIP, because the Composer/Yarn dependencies are included (the user does not need to install them manually, just unpack the ZIP).

There is nothing more involved that the [`create_release_package.bat`](https://github.com/grocy/grocy/blob/master/.devtools/create_release_package.bat) (upload happens manually). So if you think something should be included in the release ZIP, feel free to modify that file (like you already did).

**Comment by jayaddison** [comment]
Excellent - I see those bundled dependencies now.

I have a sense it could be beneficial safety-wise to avoid bundling the full Javascript packages (often they have `dist` contents which should be sufficient?).  I'll open issue(s) if & when I find anything that is confirmed problematic or when I've considered the problem a little more.

It may be that you've considered this situation already, so I might be duplicating ideas :)

**Comment by berrnd** [comment]
> often they have `dist` contents which should be sufficient?

Sure, in most packages more than needed is included (for both Yarn and Composer packages), but because there is no standard folder structure for what is needed or not, I don't think it's worth the effort (and common) to hand-pick each package manually...
