### ISSUE TITLE
Feature Request: Multiple Homes

### ISSUE THREAD

**Issue by dshafik** [grocy/grocy#644]
My family shares food between multiple households, and would like to be able to see what's in which house, and to have different default locations per product, per house.

Here's how I see the feature fleshed out:

- Home entity (for my purposes, only needs a Name, custom fields can be used for anything else)
- A default Home should be created (it should be possible to rename it)
- **If only one Home exists, Grocy does nothing behaves differently than today** in terms of UI, everything defaults to the one Home that exists
- Each Location can belong to a Home, needs to allow duplicate names (one per home)
  - Update `locations` schema: `UNIQUE INDEX` on `locations.name + locations.home_id` instead of just `locations.name`
- Each Chore can belong to a Home, need to allow duplicate names (one per home, yes, this means duplicating a lot of chores, but they likely need different schedules anyway)
  - Update `chores` schema: `UNIQUE INDEX` on `chores.name + chores.home_id` instead of just `chores.name`
- Each user would be assigned a default house (but I don't think we need to limit them to specific houses)
- Stock would have a filter for Home (or All Homes)
  - Each user has an account preference as to whether they see stock just in their house, or all houses by default
- When adding products, purchases, transferring, or consuming products, the users home locations would be top of the list.
- Each product can have one default location **per home**
- When tracking a chore, the users homes chores are listed first
- For Meal Plans & Calendar, those should be per Home also, but I'm not sure if we really need to see each others meal plans, so it should default to the users Home, and _might_ have a dropdown to see other homes
- Recipes should be visible by all, but filterable by Home (maybe defaulted to users Home)
- Equipment and Batteries should also be per Home, probably needs schema updates to allow UNIQUE based on name + home_id
- Tasks are assigned per-user, so I think that can be left alone

**Comment by CrushaKRool** [comment]
In addition to the things you've listed, I would actually propose to also use the feature to offer more restrictions. Each user account should need to be explicitly assigned to at least one Home (admins get automatically assigned to all Homes). The user can then only see the items associated with the Homes he is assigned to. You could also only assign tasks to users who share a Home with you.

By assigning a user to multiple Homes, it would still be possible to get the same system as you described. But it would also be possible to make user X see only things from Home A and B while user Y can only see things from Home B.

You could even host a single instance of Grocy and make it available to multiple families and households, without having to worry about whether they can see each other's stock, shopping lists and planned meals.
Later on, there could then be a feature to share selected individual items with users from other Homes. For example if a friend wants to send you a shopping list for the one time where you offered to do his shopping along with your own. (But to be fair, you could probably get the same by simply having him export his shopping list to some other text format.)


One thing to note: Keeping track of the price history of products in different markets could leak some purchase information (who bought what, where, when and for how much) to other Homes, unless you also filter the graph data for the Homes that you have access to. You might also need to have multiple stores of the same brand but at different locations, since prices may vary depending on the city. But that's something that could easily be handled by just including the location in the store's name.

And there might be some disagreements between Homes about things like quantity conversion rates for the same product. Some might prefer to track their tomatoes per piece while others might prefer to track them by weight.

**Comment by avocadio** [comment]
+1 
I was searching this exact feature, so I could share grocy with different member of the family.

**Comment by Kilill** [comment]
+1 
Was looking for this as well, being able to separate into household's would be very nice, as of now one basically needs to run more instances

**Comment by sotiris-bos** [comment]
+1

**Comment by KylesDev** [comment]
+1

**Comment by robocopp3r** [comment]
+1. Is the current workaround running multiple instances?

**Comment by berrnd** [comment]
I'm sorry to say, but also want to communicate the goals about this project clearly and without empty promises:

Grocy has now grown over 6 years into what it is today and based and what that is, it's technically unlikely that this here, splitting everything up into "Homes", will ever happen.

Implementing that would mean kind rewriting and rethinking everything, the backend, frontend and most likely every detail.

Running multiple instances or organizing all that with separate locations and/or Userfields are possible workarounds on that topic.
