### ISSUE TITLE
Adopt TODO.md for task list

### ISSUE THREAD

**Issue by ngduc** [grocy/grocy#666]
Hi,
Thanks for creating this great project!

I have some thoughts about the project task list:
- Today, it's hard to find out what are the current plans, ideas or tasks being worked on.
- Having a source of truth like TODO.md will help users quickly know about them which leads to more engagement.

Please adopt a TODO.md file for task list like the example here - https://github.com/coddx-hq/coddx-alpha

![image](https://user-images.githubusercontent.com/639189/77603370-25380200-6ecd-11ea-92d5-436e2fc3ca55.png)

Thanks.

**Comment by berrnd** [comment]
Thanks for the idea.

However, I hate too much planning for hobby projects. That's because I don't plan anything for grocy. It leads to expections when something should be ready, and I hate those every arrising questions about when it's ready, even when there is no due date planned - but more worse, when the planned due date is already due.

I recently started using Milestones here. And had the exact (for me) bad experience described above.

Maybe this will change over time, but currently more or less everything (thanks for all contributions!) is done by me. So it's ready when it's done. Maybe tomorrow or maybe tomorrow next year. And yes, both already happened for requested features.
