### ISSUE TITLE
Meal plan / recipes performance optimization

### ISSUE THREAD

**Issue by Jeltel** [grocy/grocy#695]
When opening the Mealplan and Recipe sections of grocy it takes about 10 seconds to load the page. Clicking around on the page works fine after that, but after adding or removing a recipe from the mealplan the page reloads, ie you have to wait 10 seconds.
Same when selecting a recipe, the page reloads and loads the clicked recipe, but you have to wait 10 seconds. Also when editing a recipe.

Is it possible to fix this?

**Comment by berrnd** [comment]
Surely depends on the amount of recipes (and server/client speed). How many do you have?

The mealplan currently loads all ever planned meals, this could be improved of course....

**Comment by Jeltel** [comment]
I've got 46 recipes.
And i run it on a NUC(NUC6CAYH Intel Celeron J3455) with 8gb memory. Should be fine. It also runs Home Assistant with several addons.

**Comment by Vader266** [comment]
Here from issue #946. Could a good temporary fix be a database purge function (manual or periodic) to delete history and restore speed?

I don't rely on having historic meal plan data so cleaning off the database would be the best workaround for myself but not too sure of the nuts and bolts required.

**Comment by Jeltel** [comment]
I manually removed old meal plan/recipes entries via the api. This improved the pages and I can still see what I ate before the purge.
After 4 months the issue reappeared. A automatic purge would certainly help.

**Comment by berrnd** [comment]
> Could a good temporary fix be a database purge function (manual or periodic) to delete history and restore speed?

Should work for the meal plan page - either do it via the API as suggested by @Jeltel or here is an example SQL command to delete all meal plan entries older than 30 days:
```sql
DELETE FROM meal_plan
WHERE JULIANDAY(DATE()) - JULIANDAY(day) > 30
```

**Comment by berrnd** [comment]
> here is an example SQL command to delete all meal plan entries older than 30 days

And here an example command to delete the corresponding recipes (the meal plan creates internal recipes per day and week for stock fulfillment checking):
```sql
-- Name of mealplan-day recipes is the ISO8601 date of the day
DELETE FROM recipes
WHERE type IN ('mealplan-day')
	AND JULIANDAY(DATE()) - JULIANDAY(DATE(name)) > 30

-- Name of mealplan-week recipes is in the form <YEAR>-<WEEKNUMBER>
DELETE FROM recipes
WHERE type IN ('mealplan-week')
	AND JULIANDAY(DATE()) - JULIANDAY(DATE(DATE(SUBSTR(name, 1, 4) || '-01-01'), '+' || CAST(CAST(SUBSTR(name, 6, 2) AS INTEGER) * 7 AS TEXT) || ' days')) > 30
```

**Comment by Vader266** [comment]
This is a really helpful workaround, thank you! I would prefer to do it via SQL but I think I'm snookered with my Hassio implementation. Don't think there's ready access to the DB, so will have to work out the API calls.

**Comment by donk7413** [comment]
Possible to have a path in api to get recipe_pos by recipe I'd ?

**Comment by donk7413** [comment]
I fix the issue , I change my php.ini max_execution_time to 300 (default 30). Now the recipe page loads (slow but it does)

**Comment by berrnd** [comment]
> Possible to have a path in api to get recipe_pos by recipe I'd ?

This is about the page, not the API, but yes, as I just mentioned in https://github.com/grocy/grocy/issues/1027#issuecomment-702784176, see #985 (still not yet released).

**Comment by Jeltel** [comment]
@berrnd I'm now deleting recipes with a negative index. And I see no issues in using grocy.
What do these 'recipes' actually do?

You say stock fulfilment. Can I then conclude that after adding the recipes to the stock and consuming the meal. That these recipes with a negative index to not fulfil any use in grocy any more?

**Comment by berrnd** [comment]
The `id` doesn't say anything, it's about the recipe `type` - as mentioned in the example above, the meal plan is based on nested recipes per day and week (so type `mealplan-day` and `mealplan-week`).

And also as mentioned above, if you don't need old meal plans, you can of course delete the meal plan entry (table `meal_plan`) and the corresponding recipes.
If you only delete the recipe behind, not the meal plan entry itself, when accessing/showing that meal plan of course not only stock fulfillment checking will be broken, more probably the whole meal plan page - but why not just try it...

**Comment by Jeltel** [comment]
@berrnd Well the mealplan page keeps working and I can also access the recipe (the original I assume, not the one created for the meal in the mealplan). 
Stock fulfilment is probably broken, but I don't care about that after I've already consumed my meal.

What then does the negative ID mean? Why use negative ID's?

**Comment by berrnd** [comment]
> What then does the negative ID mean? Why use negative ID's?

At first there was no `type` column, so recipes with a negative id were internal ones, all others not. The `id` column is a signed integer, so I don't see problem with that.

**Comment by crazyelectron-io** [comment]
What would be the new SQL command to delete the old daily mealplans? The one mentioned doesn't seen to match the current database structure anymore.
```SQL
sqlite> DELETE FROM meal_plan
   ...> WHERE JULIANDAY(DATE()) - JULIANDAY(day) > 30;
Error: UNIQUE constraint failed: recipes_nestings.recipe_id, recipes_nestings.includes_recipe_id
```
I would like to run this regularly since performance is getting worse over time, even on a 4-core 16 GB Azure VM.

**Comment by berrnd** [comment]
Nothing has changed, the correspoding internal recipes can be deleted by the second command I already posted above: https://github.com/grocy/grocy/issues/695#issuecomment-670003590

**Comment by crazyelectron-io** [comment]
I should have been more precise in my wording. The commands to delete the created internal recipes work just fine, indeed. I meant the first command that deletes old meal plans I created.

**Comment by berrnd** [comment]
Can't reproduce this specific error, must be something wrong with the internal recipes...

On any `DELETE` OR `INSERT` of any `meal_plan` row, the trigger `create_internal_recipe` or `remove_internal_recipe` recreates the corresponding internal recipe, that's most likely the source for this error. Maybe just try to disable that trigger temporarily (not directly possible in SQLite, you would need to drop and then recreate it, the latest version is in [migration 96](https://github.com/grocy/grocy/blob/master/migrations/0096.sql).

**Comment by berrnd** [comment]
Sorry that this took so long, the /recipes and /mealplan page was really unusable when there was a bigger history of meal plan entries - I've finally did something about that:

Technically pretty easy: Only load the meal entries of the shown week (means a page reload on week change, but that's at the end not too bad) and improve some things about the handling of internal recipes.

Test case:
1 recipe, 1 product, 1 note per day for today+60 days and today-440 days on the meal plan (so 500 days with 3 entries per day in total => results in about 2065 internal recipes).

Before:
https://test-iffb6mv9smnejuee4iydh5.demo.grocy.info/recipes takes here about 5 seconds
https://test-iffb6mv9smnejuee4iydh5.demo.grocy.info/mealplan takes here about 8 seconds

After:
https://test-21ltarepa8hh4kmjtlt6i4w.demo-prerelease.grocy.info/recipes takes here about 1 second
https://test-21ltarepa8hh4kmjtlt6i4w.demo-prerelease.grocy.info/mealplan takes here about 1 second

So please don't delete your meal plan entries from now on, we maybe need them for fancy statistics (ref #64) hopefully anytime soon. 😁

I try to get some more things sorted and currently thinking about pushing a new release at about the end of this month.

**Comment by Saturo78** [comment]
I think the  loading times are still very long. I have round about 300 recipes and i have to wait 35 seconds to view a recipe.
Can i expect further improvements here?

**Comment by berrnd** [comment]
> I have round about 300 recipes and i have to wait 35 seconds to view a recipe.

Not the topic here, this here was about that the **meal plan page** was slow when having a lot of recipes/products/notes there (only related to recipes since the meal plan uses internally, on the frontend hidden, recipes to do its thing, which caused also the recipes page to be slow before).

In general a base-design problem/decision (related to #120) which affects any really big table and is caused by how tables are currently loaded (server side / [DOM source DataTable](https://datatables.net/examples/data_sources/dom)).
Changing that in general is more or less a kind of rewrite of the frontend - as always, everything is technically possible.

By-purpose big lists (like the journal pages) have special handling (e.g. sensible default filters) to workaround that and in general each page is optimized to work pretty okayable with common data amounts. I would say I have a pretty big grocy database ([stats from two years ago](https://github.com/grocy/grocy/issues/438#issuecomment-549171486), current size is about twice that) and don't see any real problems by my personal daily use - don't know if 300 recipes are so common, at least I don't have that number by far...

New demo instance to not only guess about speed - the one from above (~2000 internal, not visible, meal plan recipes + ~450 normal recipes): https://test-74ds4woshnkeofwbh6hj15.demo.grocy.info/recipes
Takes here about 9.5 seconds to load, of course not so fancy...

> Can i expect further improvements here?

I [never promise](https://github.com/grocy/grocy#roadmap) anything and so won't do it differently here.

**Comment by Saturo78** [comment]
So maybe i have to wait until the grocy android app provides access to the recipes. Syncing the date could be much faster than showing it online.

Thanks a lot, but in this state grocy is not usable in my case.

**Comment by renarena** [comment]
I think it would help if we had some ajax. F.e. while adding new entries to mealplan, only add recipes, rather then loading entire mealplan page every time.

**Comment by berrnd** [comment]
Again: This was about that the meal plan page was slow. Due to how the meal plan works, that also caused the recipes page to be slow. That's solved, that's why this is closed, That the recipes page is slow in general when having a couple of hundred recipes is not tracked here.

If you can add something useful, please add that to the corresponding existing request or open a new one if no one exists. Off-topic extra-long discussions/requests in old threads are untrackable.

That was some call "ajax" is already used to add or edit objects everywhere ([code ref](https://github.com/grocy/grocy/blob/8876c6cf95df5030d0fc4d8e1ea6dd9ed0b794e8/public/viewjs/mealplan.js#L489-L514) of the meal plan recipe add/edit action). Maybe that is the solution (not only for the recipes page) to make it faster, of course that's already known. However, it's not "ajax" (since the amount of data is not less when loading it in a different way), it's more about paging - also known, not yet done (for the recipes page).

**Comment by berrnd** [comment]
Just to note that also here:
The /recipes page should be now also reasonable faster:

Quote of https://github.com/grocy/grocy/issues/1750#issuecomment-1013878388:
> New demo instance with a bigger number of recipes:
> => https://test-y8p74fcapkzc171wmxy4i.demo.grocy.info/recipes
>  - 441 normal recipes
>  - 1509 meal plan entries (meal plan entries also generate internal not visible recipes per day and week)
>  - => 1520 total recipes
>  - ==> /recipes loads here currently in about 12.5 seconds

Quote of https://github.com/grocy/grocy/issues/1750#issuecomment-1013894998:
> I've optimized some things, comparison pre-relase demo instance (same data):
> => https://test-yn582ebblwcl7dvnctq75.demo-prerelease.grocy.info/recipes
> 
> ==> /recipes loads here about 10 times faster

**Comment by dannycb1987** [comment]
> 
I'm deleting older meal_plan objects by using the API, but is it true you have to do it for each object ID? (I have 244) Can't I do it on multiple OBJECT ID's at the same time?

**Comment by berrnd** [comment]
> Can't I do it on multiple OBJECT ID's at the same time?

Yes, there is not API endpoint to do add/edit/delete multiple objects at once (related to #1987).

Since the last optimizations done for that here in 7ee15946c765f77e1c874b1b5ccf9feb4e079aa1, the meal plan page loads exactly only what's needed to be shown (so one week of data). SQLite is generally fast, unless something else (especially storage access) is really slow. So I doubt that having 244 meal plan entries slows down anything practically.

**Comment by dannycb1987** [comment]
> > Can't I do it on multiple OBJECT ID's at the same time?
> 
> Yes, there is not API endpoint to do add/edit/delete multiple objects at once (related to #1987).
> 
> Since the last optimizations done for that here in [7ee1594](https://github.com/grocy/grocy/commit/7ee15946c765f77e1c874b1b5ccf9feb4e079aa1), the meal plan page loads exactly only what's needed to be shown (so one week of data). SQLite is generally fast, unless something else (especially storage access) is really slow. So I doubt that having 244 meal plan entries slows down anything practically.

Ok thanks! I'll let this go and try to find another cause of the addon running really slow lately.
