### ISSUE TITLE
Release 2.6.2 hasn't upgraded the version

### ISSUE THREAD

**Issue by lyz-code** [grocy/grocy#698]
After using the 2.6.2 release, I still keep on seeing version 2.6.1 in the `About Grocy` part of the settings.

Check the [linuxserver bug](https://github.com/linuxserver/docker-grocy/issues/19) for more information.

Also I don't see how to use the new shopping locations.

Thanks

**Comment by berrnd** [comment]
Yes.

v2.6.2 was a hotfix because of the security fix.
The release ZIP contains a proper `version.json` which is responsible for the about dialog, I don't know what the Docker image does. When it's checking out the repo, the `version.json` still contains the old versions string at the git tag v2.6.2 (I don't know how it should be possible to update that, we only have a single master branch as of now...).

However, doesn't matter, the tagged and and released v2.6.2 versions contains the hotfix.

> Also I don't see how to use the new shopping locations.

That's not mentionend in the v2.6.2 changelog and therefore not included. Again: v2.6.2 was all and only about the small but important security fix mentionend in the changelog.

**Comment by berrnd** [comment]
I have created a new branch `release` which from now on will always reference/contain the latest released version. The tag for v2.6.2 was also recreated, so should now be fixed / `version.json` properly contains the correct version info.

So maybe consider using the `release` branch from now on when directly installing from the repo.
