### ISSUE TITLE
[question] tare weight handling with subproducts

### ISSUE THREAD

**Issue by luclu** [grocy/grocy#728]
While setting up a highly automated workflow I stumbled upon one issue I cannot resolve:
Consider the following example:

1. One Product with several Subproducts
(ex. one kind of pasta "Fussili" and several different sized packages from different brands)
2. minimum stock requirement for the (parent) product
3. tare weight handling for easily accesible jar of the product

Thus
- for the tare weight handling to work I set up the products unit in gramm
- the subproducts have "Quantity unit purchase" set to "Pack" and "Quantity unit stock" set to "Gramm" (because of different sizes)

---

Is there any way to (open and) transfer the full or partial content of one pack to the parent product in order for the tare weight handling to work?

Thanks a lot for any input and this great piece of software :)
Best Luca

**Comment by luclu** [comment]
Basically the transfer action could be extended to allow for a transfer to the parent product, right?

**Comment by berrnd** [comment]
Currently that's not possible...

So alllowing to consume a parent product, even if it is not in stock, and then using (any?) of the subproducts would maybe work (including tare weight handling on parent product level and only if the stock quantity unit of the parent product and all subproducts is the same).

Or your idea about transfering amounts between products instead of locations.

Or maybe just a product option on the parent product which would make that when purchasing any of the subproducts, the amount always gets added to the parent product (if necessary including unit conversions). So the only sense then to have the subproducts at all, would be to have a way to cover the different pack sizes - related and/or maybe a solution for #204.

So just say what would fit best for you in that case and let's track that then in this issue... :)

**Comment by berrnd** [comment]
Closing this for now.

Feel free to reopen it if you have any further specific ideas for this which is not possible with the current possibilities.
