### ISSUE TITLE
Retry camera barcode scanning from produktpicker workflow dialog

### ISSUE THREAD

**Issue by ghost** [grocy/grocy#736]
Can we get a retry button on the barcode scanner for the times it picks up the wrong number?

**Comment by berrnd** [comment]
The camera popup stays until it recognizes a barcode, then it closes. Depending on where you scan into, for example on the purchase page, the "worklfow" popup will show up and asking what to do with this unknown barcode, because maybe you scanned a new product. If that's not the case, I think you just use the scanner button again to do a new scan.

So what do you want to behave differently?

**Comment by Belafestim** [comment]
Sometimes when putting in purchases, the barcode scanned sent completely off, if possible could we add a red “Rescan” button to the “create or assign” pop up page?

**Comment by berrnd** [comment]
> if possible could we add a red “Rescan” button to the “create or assign” pop up page

Ok...

**Comment by berrnd** [comment]
There is now a camera button on the product picker workflow dialog for that (shortcut `C`):

![grafik](https://user-images.githubusercontent.com/2161815/101394454-d601f800-38c8-11eb-9ba5-e3ddca2e6976.png)
