### ISSUE TITLE
Slim\Exception\HttpNotFoundException

### ISSUE THREAD

**Issue by movvamrocks** [grocy/grocy#768]
Getting a 404 Not Found error. 

404 Not Found
The application could not run because of the following error:

Details
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /var/www/html/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93

Any suggestions please. 

Running on CentOS 8.1 / Php 7.4.5 

Regards, Mohan.

**Comment by movvamrocks** [comment]
Trace
#0 /var/www/html/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting()
#1 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process()
#2 /var/www/html/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
#3 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process()
#4 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#5 /var/www/html/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#6 /var/www/html/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#7 /var/www/html/grocy/app.php(68): Slim\App->run()
#8 /var/www/html/grocy/public/index.php(27): require_once('/var/www/html/g...')
#9 {main}

**Comment by berrnd** [comment]
Seems like you run grocy in a subdirectory, so please use search existing issues first because there is the solution.

https://github.com/grocy/grocy/issues/694#issuecomment-609079721

https://github.com/grocy/grocy/issues/694#issue-592850273

https://github.com/grocy/grocy/issues/650

General questions about setup problems also fit better on the [subbredit](https://www.reddit.com/r/grocy/), thanks.
