### ISSUE TITLE
Recipe costs: Use last price for out of stock ingredients

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#779]
The recipe costs currently displayed are based on the last price for a product however the consume would be based on "First expiring first, then first in first out" which maybe a different price.

When I initially made the view products_oldest_price it only took into account the current stock information, however if there is no current stock then it should pull the last purchased price.

**Comment by Bonerserk** [comment]
I Often need to know how much a recipe will cost before cooking it and then I'll buy missing ingredients.
Now the default price rule is "the default consume rule which is Opened first, then first due first, then first in first out".
If an ingredient is out of stock, its price isn't added to the total receipe price.
It would be great to use the last ingredient price or the average price for the not in stock ingredients so the rule will be "Opened first, then first due first, then first in first out, then average price".

**Comment by berrnd** [comment]
Out of stock items are not included in recipes costs since v3.0.0.

Before the change that recipes costs are based on the default consume rule, all prices were based on the corresponding products last price.

Let's change again that for _out of stock ingredients_, the _last price_ is used again. I think that reflects current recipe costs best - will be done for the next release.
