### ISSUE TITLE
First time user, getting extremely fustrated (Can't edit inventory)

### ISSUE THREAD

**Issue by Ryonez** [grocy/grocy#847]
So, I got this set up because I would like to track my food and inventory. But by damn is this absolutely frustrating me.

Documentation is lacking. I have to use the subreddit and search there to try and understand things.

I have tried to add my first product, and have been at it for over an hour!

The website is up, I can access it, sorted out an api key for [PantryParty](https://pantryparty.app/) (This has some docs, but they are out of date).

The first product is a 5 pack of instant noodles. There's two barcodes, one on the pack, and another on the single packets. I've figured out I should use the single packet barcode as a parent product. Okay, think I have purchase factor right.

But, I can't use barcodes for the site using my phone. It's an Note 10 Plus, and firefox, vivaldi, chrome, all don't work. Used PartyPantry, and noticed the expiry dates for the product aren't right. That's fine, I'll fix that...

![image](https://user-images.githubusercontent.com/16157130/81874700-88433c80-95d2-11ea-9463-d1ce6a710d3e.png)

For some reason, I can't correct that, without changing the amount?

How do I fix this, without having to redo it all again for like the 6th time?

**Comment by kriddles** [comment]
> So, I got this set up because I would like to track my food and inventory. But by damn is this absolutely frustrating me.
> 
> Documentation is lacking. I have to use the subreddit and search there to try and understand things.
> 
> I have tried to add my first product, and have been at it for over an hour!
> 
> The website is up, I can access it, sorted out an api key for [PantryParty](https://pantryparty.app/) (This has some docs, but they are out of date).
> 
> The first product is a 5 pack of instant noodles. There's two barcodes, one on the pack, and another on the single packets. I've figured out I should use the single packet barcode as a parent product. Okay, think I have purchase factor right.
> 
> But, I can't use barcodes for the site using my phone. It's an Note 10 Plus, and firefox, vivaldi, chrome, all don't work. Used PartyPantry, and noticed the expiry dates for the product aren't right. That's fine, I'll fix that...
> 
> ![image](https://user-images.githubusercontent.com/16157130/81874700-88433c80-95d2-11ea-9463-d1ce6a710d3e.png)
> 
> For some reason, I can't correct that, without changing the amount?
> 
> How do I fix this, without having to redo it all again for like the 6th time?

Hi, you can fix this using the Stock Entries edit which can be found at the top of the Stock Overview page the can be filtered by product.

The inventory tab does not change current stock best before dates.

**Comment by Ryonez** [comment]
Thank you, I was able to fix it there. Any chance you'd know how I could scan a single packet and have it remove the item from the 5 pack?

**Comment by kriddles** [comment]
> Thank you, I was able to fix it there. Any chance you'd know how I could scan a single packet and have it remove the item from the 5 pack?

If you're using party pantry you'll have to ask @arjes but I have not delved into scanning much yet with using parent products in the main grocy app.

**Comment by arjes** [comment]
@Ryonez Parent products are for when you have many different things that are the same ingredient . For example multiple different brands of canned tomatoes.

What you want here is more than one barcode for the _same_ item. This can't be done via the PantryParty quick create workflow (yellow bar on the top). I have an open issue here https://github.com/PantryParty/pantry_party/issues/50 to add support for additional barcodes if you select a different consume and purchase unit.

So what you ideally are doing is adding both the single and the back barcode to the Grocy Product. When you "Purchase" each 1 item you scan will turn into 5x items in your inventory. I have unreleased changes to PantryParty which will make that more clear (screenshot available https://pantryparty.app/release_log.html).

So how do you do this now? Assuming you scanned the bulk-package in PantryParty already and created the product in Grocy to purcahse you should now head to the consume page. On the consume page go ahead and scan the barcode of the single item. It won't be found since that barcode isn't associated to the Grocy Product yet. 

So in order to associated this new barcode tap the line on the screen, then tap line item to select a product. You will be presented with a list of all the known products you can tap to select it, save the product (top right) and you should be back on the Consume screen. After 20s your scan should save and you will have one less item in your stock and the new barcode will be associated.

**Comment by arjes** [comment]
As an addendum. Once you get both barcodes associated to the product, either one can be used to purchase or consume, no matter what barcode you consume with it will always consume 1 and always purchase based on your purchase factor

**Comment by Ryonez** [comment]
So are we at a point where it might be worthwhile adding a issue here to request separate bulk barcodes for products?
Because this product does have two, and it does represent two different things.

**Comment by kriddles** [comment]
> So are we at a point where it might be worthwhile adding a issue here to request separate bulk barcodes for products?
> Because this product does have two, and it does represent two different things.

Please read through #204 to identify if this is a different issue, but it addresses what you have described which is in current development for an upcoming yet to be scheduled release so this is not a new issue.

@arjes can address it in the party pantry app as well using the current api consume endpoints as he mentioned in his open issue.

**Comment by berrnd** [comment]
Closing this for now.

Feel free to reopen it if something is still unclear or please open separate issues if something does not work.
