### ISSUE TITLE
Feature Request: Chore Enhancements

### ISSUE THREAD

**Issue by bmcclure** [grocy/grocy#860]
Hello! I'm just starting to learn Grocy. I am a software engineer so I may end up working on some or all of these enhancements myself when I find some free time. But for now, I just wanted to document these features and see if these are things that would fit well within Grocy or that other users would be interested in.

I have been a Tody user on Android for a while, and I really like the way it handles chores. However, I don't like that it's a self-contained Android app with no web service backing it and no way to access it from other devices or automate it via API integrations, so I am attempting to move over to Grocy as an alternative.

Some features that I would love to see incorporated into the Chores functionality in Grocy:
1. Allow each chore to reference a Location, and allow viewing chores based on location so that they can be completed one area at a time.
2. Allow a chore to always be assigned to the same person. Currently, it seems you can only have rotating assignments or no assignment at all unless I'm missing something. If I always take out the garbage, it would be nice to have that chore auto-assigned to me at all times.
3. Add support for seasonal chores that essentially disable that chore when it's off-season (Tody does this by allowing you to set active months). Mowing the lawn in climates where the grass doesn't grow during the winter would be an example of where this would be useful.
4. For Dynamic Regular chores, allow other period types besides days. Weeks can be simulated by using increments of 7 days, but there currently isn't an easy way to make a dynamic regular chore due after N months since there are varying numbers of days in different months. Tody lets you specify the dynamic schedule in days, weeks, months, or years, which might be overkill, but it does make it very easy to specify exactly what you want.
5. Add historical data to each chore so you can easily see the frequency it has been completed in the past (and how far overdue it's been or how early it was done) to inform future scheduling decisions. Tody accomplishes this with a History tab which both shows a graph of previous completions as well as a list of dates/times previously completed.
6. Add support for chores consuming multiple different types of products
7. Add support for chores referencing equipment (as mentioned by @mascot4hire)

It's possible some of this is already possible and I just haven't discovered it yet. I realize a few of these items are larger and might deserve their own separate feature request, and I can break them out if so.

Thank you for all your hard work on this platform!

**Comment by mascot4hire** [comment]
I really like suggestions 2 and 5 and would use them. For 4 isn't daily, weekly, monthly,yearly already there? and you can change it so that monthly is every 2,3, or 4 months...

Another thing I've like to see is chore's referencing equipment.

I have already used the user fields in the Equipment section to add more details to more things (purchase date, receipts, warranty info, serial numbers, tips for use) It would be good if they were connected.

I'll give an example. I have a recurring Chore to clean the filters on my split-system air conditioner. It would be good for that Chore to tag the Air-con so I know which air con is due for cleaning(yes i know this can just be in the text) but also then on the equipment section it will show a record of cleaning.

**Comment by bmcclure** [comment]
For 4, those options only exist for fixed dates. But what I'm looking for is, for example, 3 months after I complete the chore, rather than every 3 months regardless of when I actually complete it. Although it's possible I'm just misunderstanding that option.

**Comment by bmcclure** [comment]
Chores referencing equipment would be great too! Chores able to consume several different products would be helpful as well IMO.

**Comment by berrnd** [comment]
Great ideas, thanks! :)

> 2. Allow a chore to always be assigned to the same person.

Regardless of the assignment type, if only one person is selected in the "Assign to" list, it will always assign the same person again...

> 5. Add historical data to each chore so you can easily see the frequency

Tracked executions are already saved in the database and currently only visible on the `/choresjournal` page. There is also #65 for this.

**Comment by bmcclure** [comment]
@berrnd Regarding #2, it seems that the "Assign to" field is disabled if the "Assignment type" isn't selected. Or are you saying I should select any random assignment type so that I can choose a person to assign to? The description makes it seem like that won't keep the same person each time if I do that so just want to clarify. Thanks!

**Comment by berrnd** [comment]
> I just realized that I can select a random "Assignment type," choose myself in the list, and then unselect the "Assignment type" which disables the "Assigned to"

Not needed, just keep it to "Random" for example and only select you - there is a (very) special handling implement if only one person is assigned for "Random":
https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/services/ChoresService.php#L152-L156

**Comment by karifritsch** [comment]
I have a [workaround for 1](https://karifritsch.com/wp-content/uploads/2021/09/grocy-chore-locations.png) putting location in the chore name. It works somewhat well, but I would really love to separate it via location categories.

**Comment by berrnd** [comment]
> I have a [workaround for 1](https://karifritsch.com/wp-content/uploads/2021/09/grocy-chore-locations.png) putting location in the chore name. It works somewhat well, but I would really love to separate it via location categories.

That's also already possible by using Userfields:

![grafik](https://user-images.githubusercontent.com/2161815/132997021-8b17c4ff-7de1-4897-98c5-ab7c28b60eff.png)

Example demo instance:

https://test-ilkhg049duyk2bofqusk.demo.grocy.info/choresoverview

https://test-ilkhg049duyk2bofqusk.demo.grocy.info/userfields?entity=chores

**Comment by karifritsch** [comment]
Ah, that's right. grocy is definitely built for programmers. Lots of things are possible, but it still feels like the user has to work for grocy rather than grocy working for the user. But I know you have a big update you've been working on for a while and I'm looking forward to it.

My version of grocy did not have the eye icon so I think the windows store version is quite outdated (and I hadn't updated it yet).

**Comment by berrnd** [comment]
It's off-topic here, but:

> Ah, that's right. grocy is definitely built for programmers.

I prefer pragmatic approaches for most things over a fluffy UI. Of course advanced features requires (not only here) some testing, or investigation, or reading, or asking on the forum, or a little bit of all if you can't figure it out yourself.

> But I know you have a big update you've been working on for a while

Then you know more than I do, since [I don't plan anything](https://github.com/grocy/grocy#roadmap), but do any work on grocy in public - the [master](https://github.com/grocy/grocy/tree/master) branch [is (kind of) even](https://github.com/grocy/grocy/compare/release...master) with the [release](https://github.com/grocy/grocy/tree/release) branch, only [2 little bug fixes are currently already done, but not released yet](https://github.com/grocy/grocy/milestone/9?closed=1).

The last bigger feature release was [v3.1.0](https://grocy.info/changelog#v3.1.0), released about 2 months ago.

> I think the windows store version is quite outdated

I don't think so (at least if you're referring to [grocy-desktop](https://github.com/grocy/grocy-desktop):
- The latest release is [v1.11.0](https://github.com/grocy/grocy-desktop/releases/tag/v1.11.0) which was released about 3 weeks ago and contains [grocy v3.1.1](https://grocy.info/changelog#v3.1.1)
- That's exactly the same release which is currently (as always) [published on the Microsoft Store](https://www.microsoft.com/de-de/p/grocy/9nwb1trnnksf)

That's all nothing new, just publicly available information...

**Comment by karifritsch** [comment]
Ah, maybe that was it. I thought there was more UI work and possibly
packing common quantity units into grocy natively. I know I only installed
grocy a few days ago... I uninstalled and reinstalled it and it is 1.11.0.
I found another grocy-desktop from January, so perhaps there was some
issues there. grocy was originally on the HD that failed/windows
deinitialized and I lost all my data there. Sounds like I need a clean
install.

**Comment by berrnd** [comment]
Multi-topic requests are more than hard to track and it has been quite a while since this was opened.

A lot was changed/improved around chores since then / by the last 8 releases and most, or probably all, of the mentioned things are already possible or otherwise tracked in topic specific other requests.

If something is not already possible and not already tracked, feel free to open separate requests per specific topic.

**Comment by albarreto** [comment]
Item 6 (multiple products) is very interesting too.

> I really like suggestions 2 and 5 and would use them. For 4 isn't daily, weekly, monthly,yearly already there? and you can change it so that monthly is every 2,3, or 4 months...
> 
> Another thing I've like to see is chore's referencing equipment.
> 
> I have already used the user fields in the Equipment section to add more details to more things (purchase date, receipts, warranty info, serial numbers, tips for use) It would be good if they were connected.
> 
> I'll give an example. I have a recurring Chore to clean the filters on my split-system air conditioner. It would be good for that Chore to tag the Air-con so I know which air con is due for cleaning(yes i know this can just be in the text) but also then on the equipment section it will show a record of cleaning.

BTW, how to create user fields on Equipment Section? There's no equipment section on master data.
