### ISSUE TITLE
Enable BAT Tips

### ISSUE THREAD

**Issue by LukeStaszewski** [grocy/grocy#874]
Hi guys

I just tipped the Grocy github 10 BAT, you'll need to verify your account to receive it tho.

If you don't know what BAT is, it's a currency you can earn from a variety of decentralised applications, most commonly the Brave browser. 

10 BAT is like $2 now so not much but I've got you guys on my auto-contribute so you'll get a percentage of my BAT each month :)

If you need any help setting it up let me know

p.s BAT enabled projects sometimes get promotion from Brave etc so maybe something worth looking into to get the word out a bit more? Not sure how it works though! You can also enable it on the Reddit subreddit etc

**Comment by TheBird956** [comment]
I second this. Brave is also gaining in popularity and is an easy way to donate to a projet.

**Comment by berrnd** [comment]
Thanks for the hint, haven't heard about that before.

I created such an account and added/verified the GitHub account + [grocy.info](https://grocy.info/).
The "current balance" is 0.00 BAT.

If this helps spreading the word about grocy - great. 🙂
For the rest I'm absolutely not interested in any financial things, I (and hopefully all others) work on grocy because it makes fun, that's it (see https://grocy.info/#say-thanks).
