### ISSUE TITLE
Wrong Day and Week Cost in Meal Plan with recipes that include other recipes with servings > 1

### ISSUE THREAD

**Issue by garrapato** [grocy/grocy#897]
When I include a recipe that include servings greater than 1 of another recipes, the Total of day and week in the Meal Plan are wrong. 
For example:

I have a Recipe named Menú 1.1, that include several ingredients and 2 servings of a recipe "Ensalada de Atún" that cost $11.03

The cost in the recipe is correct $53.22, but in the column show only $42.18, in consequence the total cost of week is $42.18, the difference is just $11.03, the cost of one serving of Ensalada de Atún.

Attach some screenshots

<img width="811" alt="Captura de Pantalla 2020-06-23 a la(s) 18 28 08" src="https://user-images.githubusercontent.com/1179567/85478505-fa1f8600-b581-11ea-9a44-867e6f93df9c.png">

<img width="831" alt="Captura de Pantalla 2020-06-23 a la(s) 18 19 56" src="https://user-images.githubusercontent.com/1179567/85478541-0efc1980-b582-11ea-809b-491a768e3af9.png">

<img width="847" alt="Captura de Pantalla 2020-06-23 a la(s) 18 23 23" src="https://user-images.githubusercontent.com/1179567/85478559-16232780-b582-11ea-991f-6131b1ac5fc0.png">

**Comment by berrnd** [comment]
Sorry for coming back so late on this.

I just tried to reproduce this and it currently works on both the latest release and the master branch.

According to the screenshots above you used the master branch at that time, a lot has change since the last release according to price handling - the master branch is not considered stable, so things can be broken there.
