### ISSUE TITLE
CS localization - missing file -> error

### ISSUE THREAD

**Issue by Melvidor** [grocy/grocy#901]
Hello All,

czech localization folder is not complete. Its missing 1 file - stock_transaction_types.po. I've just copied that file from Slovak and it works. Do you have original from translator team?

` /var/www/html/grocy/services/../localization/cs/stock_transaction_types.po' is not a valid file`

_BTW: thank you for this project, really awesome!_ 

M.

**Comment by berrnd** [comment]
That's true, currently missing because only files with 80 % complete translations get added ([transifex ref](https://www.transifex.com/grocy/grocy/translate/#cs/stock_transaction_types), [code ref](https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/.devtools/transifex_download.bat#L2)).

But since v2.7.0 / https://github.com/grocy/grocy/commit/4072dfd26f2ea02cde6bec2d2e74e0cfa54d4bb0 missing translation files are just ignored (default strings are used), so maybe you use an old version?

**Comment by Melvidor** [comment]
Yep.. followed your guide and downloaded old version.. heh.. Atleast I can test my skills while doing upgrade :-P

Thanks and sorry :-S

**Comment by berrnd** [comment]
No problem! :)
