### ISSUE TITLE
Feature Request: Integration with grocery delivery (Amazon Fresh, Instacart, etc.)

### ISSUE THREAD

**Issue by catern** [grocy/grocy#905]
Grocy should have integration with grocery delivery sites such as Amazon Fresh, Instacart, or other grocery delivery services.

1. Grocy could automatically export a grocery list to a grocery delivery service, which would allow the user to then place an order for those groceries
2. Grocy could look at the information about what was delivered from the service, and import that information back into Grocy, removing the need for some manual data entry.

Prior art: https://www.eatthismuch.com/ which maintains a grocery list and pantry, does part 1, but not part 2.

The Amazon Fresh API even (appears to) support specifying amounts in grams or liters and automatically calculating what quantity of product to buy. Instacart doesn't seem to support this.

At least for Amazon Fresh and Instacart, these APIs don't have (afaik) publicly accessible documentation. Amazon Fresh at least seems to require some kind of onboarding to use their API: https://forums.developer.amazon.com/questions/60471/amazon-fresh-api.html However, it might be possible to reverse-engineer the APIs. On the plus side, these APIs provide affiliate revenue. This could be a nice bonus to fund Grocy development.

**Comment by berrnd** [comment]
Similar to #194.

**Comment by Mattrazol** [comment]
This should be something to really look forward two. Both points are extremely valid and can take this application to a whole new level.
Imagine: this kind of integration will allow to make automatic purchases based off your meal schedule (if you have set that up) and have your orders placed on auto-pilot. Or, along with that, you could also even set the minimum amounts for some items that you always want at home and have them plut in the order along with the produces required by the meal schedule. Wouldn't that be great?

**Comment by berrnd** [comment]
This is generally more something for an external add-on / tool / companion app - also because services to be integrated will be highly depended on where you're located on this planet.

General import/export is tracked in #129.

&nbsp;
> Imagine: this kind of integration will allow to make automatic purchases based off your meal schedule (if you have set that up) and have your orders placed on auto-pilot.

Is something like that really practically used by someone for _everything_ (I mean everything, including fresh products and so on) you need for food and other household needs while also having somehow acceptable prices or is this just a dream? I personally don't know anyone.

I also like and do online shopping a lot, but food and everything related to that is commonly bought at the local stores.
