### ISSUE TITLE
Display "Track date only"-chores as all-day-events on the calendar instead of fixed at 12am

### ISSUE THREAD

**Issue by jlo88** [grocy/grocy#941]
Is it possible to set a due time for a chore? I currently see this configuration: 

![image](https://user-images.githubusercontent.com/10574850/89120395-53020880-d4b6-11ea-92cd-6628d699c926.png)

What does the checkbox "Track date only When enabled only the day of an execution is tracked, not the time" do? It suggests that a due time is usually set up and you can ignore this and use only a due date but this time is not settable? 

When i look in my calender I also see different times: 

![image](https://user-images.githubusercontent.com/10574850/89120451-c0159e00-d4b6-11ea-96c3-fe4a23da5abd.png)

What is the logic behind this? Am I missing something?

**Comment by berrnd** [comment]
`Track date only` tracks only a date, not the time of the execution.

The next execution time is just based on the last execution time.

"Track date only"-chores seem to be displayed always at 12am on the calendar, this is of course a bug - should better be displayed as a all-day-event I would say. I'll change the title of this issue to track this problem here.

**Comment by moverperfect** [comment]
@berrnd Does 95ca6f6 fix this issue for the calendar api ical as well? This looks like it would only change it on the /calendar screen. I think changing line 30 in controllers/CalendarApiController.php from 
`->setNoTime($event['date_format'] === 'date')` 
to
`->setNoTime($event['date_format'] === 'date' || $event['allDay'])`
would fix this for the ical as well

**Comment by berrnd** [comment]
Thanks @moverperfect, I added your suggestion in https://github.com/grocy/grocy/commit/60f3d900e806dad1be0978f2839c14cacecb5feb.

**Comment by moverperfect** [comment]
Looks like it's still not working and I think it's because the $date has a time value associated with it still. When looking at the ical on the demo pre release site, we have these 2 entries
uid - 5f4e8db9ce790
dtstart - 2020-09-05T00:00:00
tzid: Europe/Berlin
sequence - 0
transp - OPAQUE
dtend - 2020-09-05T00:00:00
tzid: Europe/Berlin
summary - Chore due: The thing which happens on the 5th of every month
class - PUBLIC
dtstamp - 2020-09-01T18:06:49Z

uid - 5f4e8db9ce878
dtstart - 2020-09-01
sequence - 0
transp - OPAQUE
dtend - 2020-09-02
summary - Meal plan recipe: Spaghetti bolognese
class - PUBLIC
description - https://demo-prerelease.grocy.info/mealplan?week=2020-09-01
x-microsoft-cdo-alldayevent - TRUE
dtstamp - 2020-09-01T18:06:49Z

One of the main differences apart from the x-ms value is that dtstart doesn't have a time. I'm assuming that the issue is with the CalendarService.php line 82 `'start' => $currentChoreEntry->next_estimated_execution_time,` this looks like it is grabbing a time value as well as a date, is there a way maybe that we can strip the time value if track_date_only is 1, not hot on php so not sure how to strip it myself.

**Comment by berrnd** [comment]
> is there a way maybe that we can strip the time value if track_date_only is 1

Not directly, that's not a string, but a datetime object, all the iCal output stuff is handle by [that library](https://github.com/markuspoerschke/iCal).

The demo chore `Chore due: The thing which happens on the 5th of every month` doesn't have `Track date only` set, I changed that, then the iCal output is
```
BEGIN:VEVENT
UID:5f4e95208dfed
DTSTART;VALUE=DATE:20200905
SEQUENCE:0
TRANSP:OPAQUE
DTEND;VALUE=DATE:20200906
SUMMARY:Chore due: The thing which happens on the 5th of every month
CLASS:PUBLIC
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
DTSTAMP:20200901T183824Z
END:VEVENT
```

I'm not familiar with the format, but `DTSTART` and `DTEND` looks good to me...
