### ISSUE TITLE
Feature request: prepared/ frozen meals

### ISSUE THREAD

**Issue by MaartenSiersema** [grocy/grocy#942]
It would be nice if you're able to track your prepared meals. Whenever you got any leftovers you can freeze them. What would be nice to track is the recipe, the amount of servings, preparation date and an expiration date.

**Comment by berrnd** [comment]
Recipes can on consume add a product to stock (see #374 and #501) - do you meant that?

**Comment by MaartenSiersema** [comment]
No what I mean is that when you've got meal leftovers from a prepared meal you can put it in your freezer to eat it on another day. It would be nice if you're able to track these leftovers and eventually use them in your meal plan.

**Comment by berrnd** [comment]
Ok, would need more details how that should work / look like...
- A button on the meal plan per recipe to add `x` of an (before somehow to the recipe attached) product?
- Or somehow automatically, so you kind of plan before how much will be left over?

Spontaneously currently have no idea how that should work.
But you can of course also add and use those products manually...

**Comment by MaartenSiersema** [comment]
There are a few use cases in which this feature could be useful.

1. In my case, I have a family consisting out of 2 adults and 2 little children. One son of the age 6 and a daughter of 1.5 years old. When I prepare a meal it is usually between 3 or 4 servings. Both my son and daughter don't eat a full serving and in most cases they both eat about 1 serving together. However sometimes they're more hungry and 1 serving is not enough. So sometimes I have 1 full serving as a leftover which I put in my fridge or freezer. Once per 2 weeks we have a a leftover day and combine some servings to make a full diner for the evening. 

2. A few of my colleagues live on their own and cook multiple servings at once. This is easier because they don't have to cook every day. Besides that most of the recipes are for multiple servings, so they don't have to be adjusted for just one person.

**How should it work.**
In my opinion I think that we should keep the impact small. The ingredients needed for preparing the meal are already consumed and should be taken out of stack just as normal when you consume a meal. So that we need no modifications for that. However, we have a prepared meal as leftover which can either be placed in de fridge or freezer. Typically a serving of a prepared meal expires within a few days in the fridge. In the freezer however it expires after a few weeks of even months. 

I think we should have a new "leftover" or "prepared meal" overview page in which we can track the prepared recipes. A prepared meal consists out of a serving amount, the recipe, an expire date and a location (fridge or freezer). As said before a prepared meal has no impact on your stock as the ingredients are already used and can not be used for any other purpose anymore.

**Nice to have**
Eventually it would be nice if we're able to use the prepared meals in you meal plan instead of selecting a recipe. In that case we should have a button in the meal plan overview with which you can select 1 or more prepared meals and determine the amount of servings needed.

**Comment by kriddles** [comment]
Thank you for using Grocy and making suggestions! 

I don't see anything new in this request that is not available in the producing products from recipes feature. This was the purpose for allowing recipes to create products as Bernd mentioned. Products were also at the same time allowed to be used in the meal plans when this feature was introduced.

I have some products that are my meals created from recipes which I then can consume on the meal plan or put in the freezer which uses the frozen date feature of Grocy. For me, I put the recipes on the meal plan for the day that I do meal prep. Then on the meal plan I consume the 'products' created for those recipes that created the products on that meal prep day.

One other note, I use product groups and set these products that were created as "meals" so that I can filter for them.

Will you give this feature a shot for your purpose? I'm sure there are ways to make it better.

![image](https://user-images.githubusercontent.com/54413450/91172647-1fc02d00-e6a2-11ea-9bda-7ffbe3a42f2b.png)

![image](https://user-images.githubusercontent.com/54413450/91172580-0c14c680-e6a2-11ea-9b95-838bb99354b2.png)

**Comment by MaartenSiersema** [comment]
@kriddles Great explanation! This is indeed the feature that I proposed, even more extensive. I didn't noticed the feature before. Thanks again, I think this issue can now be closed.
