### ISSUE TITLE
Customized fork to manage Iventory/Stock

### ISSUE THREAD

**Issue by Nasreddine** [grocy/grocy#967]
I'm looking for fork of this project to manage inventory or small business, since there are a lot things in common such as products, stock, etc.

Kind regards.

**Comment by berrnd** [comment]
Please use the [subreddit](https://www.reddit.com/r/grocy/) for general questions as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), this here is the issue tracker - thanks.

I'm sure there are a lot more professional food/gastronomy/catering management systems, but nothing that fits for home usage - that's why I created grocy.
