### ISSUE TITLE
Stores additional info

### ISSUE THREAD

**Issue by yarons** [grocy/grocy#982]
I think it could be a nice idea to include the actual location of the store (using OSM etc.) but it's quite niche.

Other important details that I think can really improve the listing is working hours (can be parsed from OSM or allow manual entry) and possibly a phone number for deliveries.

I was also thinking about maybe adding some scraping function to fetch the hours externally if the grocery store is not so open data friendly.

**Comment by berrnd** [comment]
To any entity any custom field, called Userfields, can be attached. See #176.

Of course this not includes data scraping, but I think a link to the stores website in a custom field would be enough.

**Comment by yarons** [comment]
I know about the custom fields yet there is something missing.
Using a custom field will not create an automatic `tel:` link when I enter a telephone number.
Furthermore, if I enter an address or coordinates it will not be used for mapping (displaying the location from OSM, creating a Waze/Google Maps link) and filling the working hour as text won't allow me to see whether this branch is open or not by some indication, I need to go and look at the text.

I know these can all be text fields but they don't serve the purpose I'm after.

**Comment by berrnd** [comment]
There is a Userfield Type "Link" which renders the text as links...

**Comment by yarons** [comment]
OK so we've covered the `tel:` link part, what about the map and the working hours indication?

**Comment by berrnd** [comment]
Feel free to suggest how to do this generic (Userfield types).

If I would need this, a link to the website of the store would be enough.
In reality, I personally go to the maybe same 5 stores all the time and they all have the same opening hours, because that's how it is, at least here...

So I prefer not making things overly complex when not really needed (and yes, meanwhile grocy got a lot of already too complex features)...
